In [2]:
!pip install -q kagglehub

In [3]:
import kagglehub

game_path = kagglehub.dataset_download(
    "wyattowalsh/basketball/versions/237",
    path="csv/game.csv"
)

print(game_path)

Downloading to /root/.cache/kagglehub/datasets/wyattowalsh/basketball/versions/237/csv/game.csv...

100%|██████████| 19.4M/19.4M [00:00<00:00, 68.5MB/s]

/root/.cache/kagglehub/datasets/wyattowalsh/basketball/versions/237/csv/game.csv

In [4]:
import os

print("Fichier :", game_path)
print("Existe :", os.path.exists(game_path))
print("Taille :", os.path.getsize(game_path) / 1024 / 1024, "Mo")

Fichier : /root/.cache/kagglehub/datasets/wyattowalsh/basketball/versions/237/csv/game.csv
Existe : True
Taille : 19.373666763305664 Mo

In [5]:
import pandas as pd

df_game = pd.read_csv(game_path)

print(df_game.shape)
df_game.head()

(65698, 55)

,season_id,team_id_home,team_abbreviation_home,team_name_home,game_id,game_date,matchup_home,wl_home,min,fgm_home,...,reb_away,ast_away,stl_away,blk_away,tov_away,pf_away,pts_away,plus_minus_away,video_available_away,season_type
0,21946,1610610035,HUS,Toronto Huskies,24600001,1946-11-01 00:00:00,HUS vs. NYK,L,0,25.0,...,NaN,NaN,NaN,NaN,NaN,NaN,68.0,2,0,Regular Season
1,21946,1610610034,BOM,St. Louis Bombers,24600003,1946-11-02 00:00:00,BOM vs. PIT,W,0,20.0,...,NaN,NaN,NaN,NaN,NaN,25.0,51.0,-5,0,Regular Season
2,21946,1610610032,PRO,Providence Steamrollers,24600002,1946-11-02 00:00:00,PRO vs. BOS,W,0,21.0,...,NaN,NaN,NaN,NaN,NaN,NaN,53.0,-6,0,Regular Season
3,21946,1610610025,CHS,Chicago Stags,24600004,1946-11-02 00:00:00,CHS vs. NYK,W,0,21.0,...,NaN,NaN,NaN,NaN,NaN,22.0,47.0,-16,0,Regular Season
4,21946,1610610028,DEF,Detroit Falcons,24600005,1946-11-02 00:00:00,DEF vs. WAS,L,0,10.0,...,NaN,NaN,NaN,NaN,NaN,NaN,50.0,17,0,Regular Season

In [6]:
df_game.columns.tolist()

['season_id',
 'team_id_home',
 'team_abbreviation_home',
 'team_name_home',
 'game_id',
 'game_date',
 'matchup_home',
 'wl_home',
 'min',
 'fgm_home',
 'fga_home',
 'fg_pct_home',
 'fg3m_home',
 'fg3a_home',
 'fg3_pct_home',
 'ftm_home',
 'fta_home',
 'ft_pct_home',
 'oreb_home',
 'dreb_home',
 'reb_home',
 'ast_home',
 'stl_home',
 'blk_home',
 'tov_home',
 'pf_home',
 'pts_home',
 'plus_minus_home',
 'video_available_home',
 'team_id_away',
 'team_abbreviation_away',
 'team_name_away',
 'matchup_away',
 'wl_away',
 'fgm_away',
 'fga_away',
 'fg_pct_away',
 'fg3m_away',
 'fg3a_away',
 'fg3_pct_away',
 'ftm_away',
 'fta_away',
 'ft_pct_away',
 'oreb_away',
 'dreb_away',
 'reb_away',
 'ast_away',
 'stl_away',
 'blk_away',
 'tov_away',
 'pf_away',
 'pts_away',
 'plus_minus_away',
 'video_available_away',
 'season_type']

In [7]:
df_game.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 65698 entries, 0 to 65697
Data columns (total 55 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   season_id               65698 non-null  int64
 1   team_id_home            65698 non-null  int64
 2   team_abbreviation_home  65698 non-null  object
 3   team_name_home          65698 non-null  object
 4   game_id                 65698 non-null  int64
 5   game_date               65698 non-null  object
 6   matchup_home            65698 non-null  object
 7   wl_home                 65696 non-null  object
 8   min                     65698 non-null  int64
 9   fgm_home                65685 non-null  float64
 10  fga_home                50251 non-null  float64
 11  fg_pct_home             50208 non-null  float64
 12  fg3m_home               52480 non-null  float64
 13  fg3a_home               47015 non-null  float64
 14  fg3_pct_home            46624 non-null  float64
 15  ftm_home                65682 non-null  float64
 16  fta_home                62694 non-null  float64
 17  ft_pct_home             62689 non-null  float64
 18  oreb_home               46762 non-null  float64
 19  dreb_home               46699 non-null  float64
 20  reb_home                49969 non-null  float64
 21  ast_home                49893 non-null  float64
 22  stl_home                46849 non-null  float64
 23  blk_home                47072 non-null  float64
 24  tov_home                47014 non-null  float64
 25  pf_home                 62842 non-null  float64
 26  pts_home                65698 non-null  float64
 27  plus_minus_home         65698 non-null  int64
 28  video_available_home    65698 non-null  int64
 29  team_id_away            65698 non-null  int64
 30  team_abbreviation_away  65698 non-null  object
 31  team_name_away          65698 non-null  object
 32  matchup_away            65698 non-null  object
 33  wl_away                 65696 non-null  object
 34  fgm_away                65685 non-null  float64
 35  fga_away                50251 non-null  float64
 36  fg_pct_away             50209 non-null  float64
 37  fg3m_away               52480 non-null  float64
 38  fg3a_away               47015 non-null  float64
 39  fg3_pct_away            46736 non-null  float64
 40  ftm_away                65685 non-null  float64
 41  fta_away                62694 non-null  float64
 42  ft_pct_away             62692 non-null  float64
 43  oreb_away               46762 non-null  float64
 44  dreb_away               46700 non-null  float64
 45  reb_away                49973 non-null  float64
 46  ast_away                49897 non-null  float64
 47  stl_away                46849 non-null  float64
 48  blk_away                47073 non-null  float64
 49  tov_away                47013 non-null  float64
 50  pf_away                 62847 non-null  float64
 51  pts_away                65698 non-null  float64
 52  plus_minus_away         65698 non-null  int64
 53  video_available_away    65698 non-null  int64
 54  season_type             65698 non-null  object
dtypes: float64(36), int64(9), object(10)
memory usage: 27.6+ MB

In [8]:
df_game.head(3).T

,0,1,2
season_id,21946,21946,21946
team_id_home,1610610035,1610610034,1610610032
team_abbreviation_home,HUS,BOM,PRO
team_name_home,Toronto Huskies,St. Louis Bombers,Providence Steamrollers
game_id,24600001,24600003,24600002
game_date,1946-11-01 00:00:00,1946-11-02 00:00:00,1946-11-02 00:00:00
matchup_home,HUS vs. NYK,BOM vs. PIT,PRO vs. BOS
wl_home,L,W,W
min,0,0,0
fgm_home,25.0,20.0,21.0
fga_home,NaN,59.0,NaN
fg_pct_home,NaN,0.339,NaN
fg3m_home,NaN,NaN,NaN
fg3a_home,NaN,NaN,NaN
fg3_pct_home,NaN,NaN,NaN
ftm_home,16.0,16.0,17.0
fta_home,29.0,NaN,NaN
ft_pct_home,0.552,NaN,NaN
oreb_home,NaN,NaN,NaN
dreb_home,NaN,NaN,NaN
reb_home,NaN,NaN,NaN
ast_home,NaN,NaN,NaN
stl_home,NaN,NaN,NaN
blk_home,NaN,NaN,NaN
tov_home,NaN,NaN,NaN
pf_home,NaN,21.0,NaN
pts_home,66.0,56.0,59.0
plus_minus_home,-2,5,6
video_available_home,0,0,0
team_id_away,1610612752,1610610031,1610612738
team_abbreviation_away,NYK,PIT,BOS
team_name_away,New York Knicks,Pittsburgh Ironmen,Boston Celtics
matchup_away,NYK @ HUS,PIT @ BOM,BOS @ PRO
wl_away,W,L,L
fgm_away,24.0,16.0,21.0
fga_away,NaN,72.0,NaN
fg_pct_away,NaN,0.222,NaN
fg3m_away,NaN,NaN,NaN
fg3a_away,NaN,NaN,NaN
fg3_pct_away,NaN,NaN,NaN
ftm_away,20.0,19.0,11.0
fta_away,26.0,NaN,NaN
ft_pct_away,0.769,NaN,NaN
oreb_away,NaN,NaN,NaN
dreb_away,NaN,NaN,NaN
reb_away,NaN,NaN,NaN
ast_away,NaN,NaN,NaN
stl_away,NaN,NaN,NaN
blk_away,NaN,NaN,NaN
tov_away,NaN,NaN,NaN
pf_away,NaN,25.0,NaN
pts_away,68.0,51.0,53.0
plus_minus_away,2,-5,-6
video_available_away,0,0,0
season_type,Regular Season,Regular Season,Regular Season

In [9]:
df_game.shape

(65698, 55)

In [10]:
df_game.shape

(65698, 55)

In [11]:
df_game.columns.tolist()

['season_id',
 'team_id_home',
 'team_abbreviation_home',
 'team_name_home',
 'game_id',
 'game_date',
 'matchup_home',
 'wl_home',
 'min',
 'fgm_home',
 'fga_home',
 'fg_pct_home',
 'fg3m_home',
 'fg3a_home',
 'fg3_pct_home',
 'ftm_home',
 'fta_home',
 'ft_pct_home',
 'oreb_home',
 'dreb_home',
 'reb_home',
 'ast_home',
 'stl_home',
 'blk_home',
 'tov_home',
 'pf_home',
 'pts_home',
 'plus_minus_home',
 'video_available_home',
 'team_id_away',
 'team_abbreviation_away',
 'team_name_away',
 'matchup_away',
 'wl_away',
 'fgm_away',
 'fga_away',
 'fg_pct_away',
 'fg3m_away',
 'fg3a_away',
 'fg3_pct_away',
 'ftm_away',
 'fta_away',
 'ft_pct_away',
 'oreb_away',
 'dreb_away',
 'reb_away',
 'ast_away',
 'stl_away',
 'blk_away',
 'tov_away',
 'pf_away',
 'pts_away',
 'plus_minus_away',
 'video_available_away',
 'season_type']

In [12]:
print("Dimensions :", df_game.shape)

print("\nTypes de saison :")
print(df_game["season_type"].value_counts(dropna=False))

print("\nExemples de season_id :")
print(df_game["season_id"].dropna().unique()[:20])

print("\nPériode :")
print(df_game["game_date"].min(), "→", df_game["game_date"].max())

Dimensions : (65698, 55)

Types de saison :
season_type
Regular Season    60192
Playoffs           3842
Pre Season         1536
All Star             65
All-Star             63
Name: count, dtype: int64

Exemples de season_id :
[21946 41946 21947 41947 21948 41948 21949 41949 21950 41950 31950 21951
 41951 31951 21952 41952 31952 21953 41953 31953]

Période :
1946-11-01 00:00:00 → 2023-06-12 00:00:00

In [13]:
home = df_game[
    [
        "season_id",
        "game_id",
        "game_date",
        "season_type",
        "team_id_home",
        "team_abbreviation_home",
        "team_name_home",
        "wl_home",
        "pts_home",
        "fg_pct_home",
        "fg3_pct_home",
        "ft_pct_home",
        "reb_home",
        "ast_home",
        "stl_home",
        "blk_home",
        "tov_home"
    ]
].copy()

In [14]:
home.columns = [
    "season_id",
    "game_id",
    "game_date",
    "season_type",
    "team_id",
    "team",
    "team_name",
    "result",
    "points",
    "fg_pct",
    "fg3_pct",
    "ft_pct",
    "rebounds",
    "assists",
    "steals",
    "blocks",
    "turnovers"
]

home["location"] = "Home"

In [15]:
home.head()

,season_id,game_id,game_date,season_type,team_id,team,team_name,result,points,fg_pct,fg3_pct,ft_pct,rebounds,assists,steals,blocks,turnovers,location
0,21946,24600001,1946-11-01 00:00:00,Regular Season,1610610035,HUS,Toronto Huskies,L,66.0,NaN,NaN,0.552,NaN,NaN,NaN,NaN,NaN,Home
1,21946,24600003,1946-11-02 00:00:00,Regular Season,1610610034,BOM,St. Louis Bombers,W,56.0,0.339,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Home
2,21946,24600002,1946-11-02 00:00:00,Regular Season,1610610032,PRO,Providence Steamrollers,W,59.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Home
3,21946,24600004,1946-11-02 00:00:00,Regular Season,1610610025,CHS,Chicago Stags,W,63.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Home
4,21946,24600005,1946-11-02 00:00:00,Regular Season,1610610028,DEF,Detroit Falcons,L,33.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Home

In [16]:
away = df_game[
    [
        "season_id",
        "game_id",
        "game_date",
        "season_type",
        "team_id_away",
        "team_abbreviation_away",
        "team_name_away",
        "wl_away",
        "pts_away",
        "fg_pct_away",
        "fg3_pct_away",
        "ft_pct_away",
        "reb_away",
        "ast_away",
        "stl_away",
        "blk_away",
        "tov_away"
    ]
].copy()

In [17]:
away.columns = [
    "season_id",
    "game_id",
    "game_date",
    "season_type",
    "team_id",
    "team",
    "team_name",
    "result",
    "points",
    "fg_pct",
    "fg3_pct",
    "ft_pct",
    "rebounds",
    "assists",
    "steals",
    "blocks",
    "turnovers"
]

away["location"] = "Away"

In [18]:
away.head()

,season_id,game_id,game_date,season_type,team_id,team,team_name,result,points,fg_pct,fg3_pct,ft_pct,rebounds,assists,steals,blocks,turnovers,location
0,21946,24600001,1946-11-01 00:00:00,Regular Season,1610612752,NYK,New York Knicks,W,68.0,NaN,NaN,0.769,NaN,NaN,NaN,NaN,NaN,Away
1,21946,24600003,1946-11-02 00:00:00,Regular Season,1610610031,PIT,Pittsburgh Ironmen,L,51.0,0.222,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Away
2,21946,24600002,1946-11-02 00:00:00,Regular Season,1610612738,BOS,Boston Celtics,L,53.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Away
3,21946,24600004,1946-11-02 00:00:00,Regular Season,1610612752,NYK,New York Knicks,L,47.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Away
4,21946,24600005,1946-11-02 00:00:00,Regular Season,1610610036,WAS,Washington Capitols,W,50.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Away

In [19]:
df_team_games = pd.concat(
    [home, away],
    ignore_index=True
)

df_team_games.head()

,season_id,game_id,game_date,season_type,team_id,team,team_name,result,points,fg_pct,fg3_pct,ft_pct,rebounds,assists,steals,blocks,turnovers,location
0,21946,24600001,1946-11-01 00:00:00,Regular Season,1610610035,HUS,Toronto Huskies,L,66.0,NaN,NaN,0.552,NaN,NaN,NaN,NaN,NaN,Home
1,21946,24600003,1946-11-02 00:00:00,Regular Season,1610610034,BOM,St. Louis Bombers,W,56.0,0.339,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Home
2,21946,24600002,1946-11-02 00:00:00,Regular Season,1610610032,PRO,Providence Steamrollers,W,59.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Home
3,21946,24600004,1946-11-02 00:00:00,Regular Season,1610610025,CHS,Chicago Stags,W,63.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Home
4,21946,24600005,1946-11-02 00:00:00,Regular Season,1610610028,DEF,Detroit Falcons,L,33.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Home

In [20]:
df_team_games.shape

(131396, 18)

In [21]:
df_team_games.shape

(131396, 18)

In [22]:
print("Matchs :", df_game["game_id"].nunique())
print("Lignes équipe/match :", len(df_team_games))

Matchs : 65642
Lignes équipe/match : 131396

In [23]:
df_team_games["win"] = (
    df_team_games["result"] == "W"
).astype(int)

In [24]:
df_team_games[
    ["team", "result", "win"]
].head(10)

  team result  win
0  HUS      L    0
1  BOM      W    1
2  PRO      W    1
3  CHS      W    1
4  DEF      L    0
5  CLR      W    1
6  PIT      L    0
7  BOS      L    0
8  DEF      L    0
9  PRO      W    1

In [25]:
df_team_games["win"].value_counts()

win
0    65700
1    65696
Name: count, dtype: int64

In [26]:
teams_test = [
    "GSW",
    "BOS",
    "LAL"
]

In [27]:
df_test = df_team_games[
    df_team_games["team"].isin(teams_test)
].copy()

In [28]:
df_test["team"].value_counts()

team
BOS    6207
LAL    5203
GSW    2325
Name: count, dtype: int64

In [29]:
df_test[
    ["season_id", "game_date", "team"]
].sort_values("game_date").tail(20)

        season_id            game_date team
131367      42022  2023-05-08 00:00:00  GSW
65669       42022  2023-05-08 00:00:00  LAL
65671       42022  2023-05-09 00:00:00  BOS
65674       42022  2023-05-10 00:00:00  GSW
131372      42022  2023-05-10 00:00:00  LAL
131373      42022  2023-05-11 00:00:00  BOS
65677       42022  2023-05-12 00:00:00  LAL
131375      42022  2023-05-12 00:00:00  GSW
65679       42022  2023-05-14 00:00:00  BOS
131378      42022  2023-05-16 00:00:00  LAL
65681       42022  2023-05-17 00:00:00  BOS
131380      42022  2023-05-18 00:00:00  LAL
65683       42022  2023-05-19 00:00:00  BOS
65684       42022  2023-05-20 00:00:00  LAL
131383      42022  2023-05-21 00:00:00  BOS
65686       42022  2023-05-22 00:00:00  LAL
131385      42022  2023-05-23 00:00:00  BOS
65688       42022  2023-05-25 00:00:00  BOS
131387      42022  2023-05-27 00:00:00  BOS
65690       42022  2023-05-29 00:00:00  BOS

In [30]:
df_test["game_date"] = pd.to_datetime(
    df_test["game_date"]
)

In [31]:
df_test["season"] = df_test["game_date"].apply(
    lambda x: (
        f"{x.year}-{str(x.year + 1)[-2:]}"
        if x.month >= 7
        else f"{x.year - 1}-{str(x.year)[-2:]}"
    )
)

In [32]:
df_test[
    ["game_date", "season"]
].drop_duplicates().tail(10)

        game_date   season
131349 2023-04-27  2022-23
131354 2023-04-30  2022-23
131362 2023-05-05  2022-23
131365 2023-05-07  2022-23
131373 2023-05-11  2022-23
131378 2023-05-16  2022-23
131380 2023-05-18  2022-23
131383 2023-05-21  2022-23
131385 2023-05-23  2022-23
131387 2023-05-27  2022-23

In [33]:
seasons_test = [
    "2020-21",
    "2021-22",
    "2022-23",
    "2023-24",
    "2024-25"
]

df_test = df_test[
    df_test["season"].isin(seasons_test)
].copy()

In [34]:
df_test = df_test[
    df_test["season_type"] == "Regular Season"
].copy()

In [35]:
df_test.shape

(724, 20)

In [36]:
df_animation = (
    df_test
    .groupby(
        ["season", "team", "team_name"],
        as_index=False
    )
    .agg(
        games=("game_id", "nunique"),
        win_rate=("win", "mean"),
        points_per_game=("points", "mean"),
        fg_pct=("fg_pct", "mean"),
        three_pct=("fg3_pct", "mean"),
        rebounds=("rebounds", "mean"),
        assists=("assists", "mean"),
        turnovers=("turnovers", "mean")
    )
)

In [37]:
df_animation["win_rate"] = (
    df_animation["win_rate"] * 100
)

In [38]:
df_animation.round(2)

,season,team,team_name,games,win_rate,points_per_game,fg_pct,three_pct,rebounds,assists,turnovers
0,2020-21,BOS,Boston Celtics,80,51.25,113.25,0.47,0.38,44.51,23.56,14.18
1,2020-21,GSW,Golden State Warriors,72,54.17,113.71,0.47,0.37,43.03,27.65,15.00
2,2020-21,LAL,Los Angeles Lakers,80,56.25,109.22,0.47,0.35,44.06,24.35,15.26
3,2021-22,BOS,Boston Celtics,82,62.20,111.76,0.47,0.35,46.07,24.83,13.63
4,2021-22,GSW,Golden State Warriors,82,64.63,111.00,0.47,0.36,45.49,27.11,14.89
5,2021-22,LAL,Los Angeles Lakers,82,40.24,112.10,0.47,0.35,44.00,24.00,14.52
6,2022-23,BOS,Boston Celtics,82,69.51,117.94,0.48,0.38,45.33,26.66,13.35
7,2022-23,GSW,Golden State Warriors,82,53.66,118.94,0.48,0.38,44.60,29.83,16.29
8,2022-23,LAL,Los Angeles Lakers,82,52.44,117.17,0.48,0.35,45.71,25.27,14.07

In [39]:
!pip install -q plotly

In [40]:
import plotly.express as px

In [41]:
import plotly.express as px

fig = px.scatter(
    df_animation,
    x="points_per_game",
    y="win_rate",
    size="rebounds",
    color="team",
    hover_name="team_name",
    animation_frame="season",
    animation_group="team",
    size_max=50,
    labels={
        "points_per_game": "Points per Game",
        "win_rate": "Win Rate",
        "rebounds": "Rebounds",
        "team": "Team"
    },
    title="NBA Team Performance Evolution"
)

# Axe Y : toujours de 0 à 100 %
fig.update_yaxes(
    range=[0, 100],
    title="Win Rate (%)",
    ticksuffix="%"
)

# Axe X fixe pour éviter qu'il bouge pendant l'animation
fig.update_xaxes(
    range=[
        df_animation["points_per_game"].min() - 3,
        df_animation["points_per_game"].max() + 3
    ],
    title="Points per Game"
)

# Animation plus lente
fig.layout.updatemenus[0].buttons[0].args[1]["frame"]["duration"] = 4000
fig.layout.updatemenus[0].buttons[0].args[1]["transition"]["duration"] = 2000

fig.add_hline(
    y=50,
    line_dash="dash",
    annotation_text="50% Win Rate"


)
fig.show()

In [42]:
# Export du graphique Plotly interactif
fig.write_html(
    "nba_team_performance_animation.html",
    include_plotlyjs="cdn"
)

print("Fichier HTML créé")

Fichier HTML créé

In [43]:
from google.colab import files

files.download("nba_team_performance_animation.html")

In [44]:
df_animation.to_csv(
    "nba_team_performance_animation_data.csv",
    index=False
)

files.download("nba_team_performance_animation_data.csv")

In [45]:
print(df_animation.shape)
display(df_animation)

(9, 11)

,season,team,team_name,games,win_rate,points_per_game,fg_pct,three_pct,rebounds,assists,turnovers
0,2020-21,BOS,Boston Celtics,80,51.250000,113.250000,0.468075,0.375700,44.512500,23.562500,14.175000
1,2020-21,GSW,Golden State Warriors,72,54.166667,113.708333,0.469167,0.374194,43.027778,27.652778,15.000000
2,2020-21,LAL,Los Angeles Lakers,80,56.250000,109.225000,0.468687,0.347925,44.062500,24.350000,15.262500
3,2021-22,BOS,Boston Celtics,82,62.195122,111.756098,0.467085,0.352439,46.073171,24.829268,13.634146
4,2021-22,GSW,Golden State Warriors,82,64.634146,111.000000,0.469183,0.364524,45.487805,27.109756,14.890244
5,2021-22,LAL,Los Angeles Lakers,82,40.243902,112.097561,0.469146,0.346817,44.000000,24.000000,14.524390
6,2022-23,BOS,Boston Celtics,82,69.512195,117.939024,0.476305,0.375402,45.329268,26.658537,13.353659
7,2022-23,GSW,Golden State Warriors,82,53.658537,118.939024,0.479793,0.384634,44.597561,29.829268,16.292683
8,2022-23,LAL,Los Angeles Lakers,82,52.439024,117.170732,0.483098,0.348037,45.707317,25.268293,14.073171

In [46]:
df_animation.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   season           9 non-null      object
 1   team             9 non-null      object
 2   team_name        9 non-null      object
 3   games            9 non-null      int64
 4   win_rate         9 non-null      float64
 5   points_per_game  9 non-null      float64
 6   fg_pct           9 non-null      float64
 7   three_pct        9 non-null      float64
 8   rebounds         9 non-null      float64
 9   assists          9 non-null      float64
 10  turnovers        9 non-null      float64
dtypes: float64(7), int64(1), object(3)
memory usage: 924.0+ bytes

In [47]:
!pip install -q google-cloud-bigquery pandas-gbq

In [48]:
from google.colab import auth

auth.authenticate_user()

print("Authentification réussie")

Authentification réussie

In [49]:
PROJECT_ID = "bootcamp-data-analytics-amadou"

In [50]:
df_animation.columns.tolist()

['season',
 'team',
 'team_name',
 'games',
 'win_rate',
 'points_per_game',
 'fg_pct',
 'three_pct',
 'rebounds',
 'assists',
 'turnovers']

In [51]:
from google.cloud import bigquery

client = bigquery.Client(project=PROJECT_ID)

In [52]:
table_id = f"{PROJECT_ID}.nba_analytics.team_season_animation"

job = client.load_table_from_dataframe(
    df_animation,
    table_id
)

job.result()

print("Table envoyée dans BigQuery !")

Table envoyée dans BigQuery !

In [53]:
import plotly.express as px

fig = px.scatter(
    df_animation,
    x="points_per_game",
    y="win_rate",
    size="rebounds",
    color="team",
    hover_name="team_name",
    animation_frame="season",
    animation_group="team",
    size_max=50,
    labels={
        "points_per_game": "Points per Game",
        "win_rate": "Win Rate",
        "rebounds": "Rebounds",
        "team": "Team"
    },
    title="NBA Team Performance Evolution"
)

fig.update_yaxes(
    range=[0, 100],
    ticksuffix="%"
)

fig.update_xaxes(
    range=[
        df_animation["points_per_game"].min() - 3,
        df_animation["points_per_game"].max() + 3
    ]
)

fig.layout.updatemenus[0].buttons[0].args[1]["frame"]["duration"] = 4000
fig.layout.updatemenus[0].buttons[0].args[1]["transition"]["duration"] = 2000

fig.show()

In [54]:
import plotly.express as px

fig = px.scatter(
    df_animation,
    x="points_per_game",
    y="win_rate",
    size="rebounds",
    color="team",
    hover_name="team_name",
    animation_frame="season",
    animation_group="team",
    size_max=50,
    labels={
        "points_per_game": "Points per Game",
        "win_rate": "Win Rate",
        "rebounds": "Rebounds",
        "team": "Team"
    },
    title="NBA Team Performance Evolution"
)

fig.update_yaxes(
    range=[0, 100],
    ticksuffix="%"
)

fig.update_xaxes(
    range=[
        df_animation["points_per_game"].min() - 3,
        df_animation["points_per_game"].max() + 3
    ]
)

fig.layout.updatemenus[0].buttons[0].args[1]["frame"]["duration"] = 3000
fig.layout.updatemenus[0].buttons[0].args[1]["transition"]["duration"] = 1000

fig.show()

In [55]:
import plotly.express as px

fig = px.scatter(
    df_animation,
    x="points_per_game",
    y="win_rate",
    size="rebounds",
    color="team",
    hover_name="team_name",
    animation_frame="season",
    animation_group="team",
    size_max=50,
    labels={
        "points_per_game": "Points per Game",
        "win_rate": "Win Rate",
        "rebounds": "Rebounds",
        "team": "Team"
    },
    title="NBA Team Performance Evolution"
)

fig.update_yaxes(
    range=[0, 100],
    ticksuffix="%"
)

fig.update_xaxes(
    range=[
        df_animation["points_per_game"].min() - 3,
        df_animation["points_per_game"].max() + 3
    ]
)

fig.layout.updatemenus[0].buttons[0].args[1]["frame"]["duration"] = 4000
fig.layout.updatemenus[0].buttons[0].args[1]["transition"]["duration"] = 2000

fig.show()

In [56]:
fig.write_html(
    "nba_team_performance_animation.html",
    include_plotlyjs=True,
    full_html=True
)

In [57]:
import os

print(
    round(
        os.path.getsize("nba_team_performance_animation.html") / 1024 / 1024,
        2
    ),
    "MB"
)

4.36 MB

In [58]:
from google.colab import files

files.download("nba_team_performance_animation.html")

In [59]:
import kagglehub

player_path = kagglehub.dataset_download(
    "wyattowalsh/basketball/versions/237",
    path="csv/player.csv"
)

common_info_path = kagglehub.dataset_download(
    "wyattowalsh/basketball/versions/237",
    path="csv/common_player_info.csv"
)

print(player_path)
print(common_info_path)

Using Colab cache for faster access to the 'basketball' dataset.
Using Colab cache for faster access to the 'basketball' dataset.
/kaggle/input/basketball/csv/player.csv
/kaggle/input/basketball/csv/common_player_info.csv

In [60]:
import pandas as pd

df_player = pd.read_csv(player_path)
df_common = pd.read_csv(common_info_path)

print(df_player.shape)
print(df_common.shape)

display(df_player.head())
display(df_common.head())

(4831, 5)
(4171, 33)

      id            full_name first_name     last_name  is_active
0  76001       Alaa Abdelnaby       Alaa     Abdelnaby          0
1  76002      Zaid Abdul-Aziz       Zaid    Abdul-Aziz          0
2  76003  Kareem Abdul-Jabbar     Kareem  Abdul-Jabbar          0
3     51   Mahmoud Abdul-Rauf    Mahmoud    Abdul-Rauf          0
4   1505    Tariq Abdul-Wahad      Tariq   Abdul-Wahad          0

,person_id,first_name,last_name,display_first_last,display_last_comma_first,display_fi_last,player_slug,birthdate,school,country,...,playercode,from_year,to_year,dleague_flag,nba_flag,games_played_flag,draft_year,draft_round,draft_number,greatest_75_flag
0,76001,Alaa,Abdelnaby,Alaa Abdelnaby,"Abdelnaby, Alaa",A. Abdelnaby,alaa-abdelnaby,1968-06-24 00:00:00,Duke,USA,...,HISTADD_alaa_abdelnaby,1990.0,1994.0,N,Y,Y,1990,1,25,N
1,76003,Kareem,Abdul-Jabbar,Kareem Abdul-Jabbar,"Abdul-Jabbar, Kareem",K. Abdul-Jabbar,kareem-abdul-jabbar,1947-04-16 00:00:00,UCLA,USA,...,HISTADD_kareem_abdul-jabbar,1969.0,1988.0,N,Y,Y,1969,1,1,Y
2,1505,Tariq,Abdul-Wahad,Tariq Abdul-Wahad,"Abdul-Wahad, Tariq",T. Abdul-Wahad,tariq-abdul-wahad,1974-11-03 00:00:00,San Jose State,France,...,tariq_abdul-wahad,1997.0,2003.0,N,Y,Y,1997,1,11,N
3,949,Shareef,Abdur-Rahim,Shareef Abdur-Rahim,"Abdur-Rahim, Shareef",S. Abdur-Rahim,shareef-abdur-rahim,1976-12-11 00:00:00,California,USA,...,shareef_abdur-rahim,1996.0,2007.0,N,Y,Y,1996,1,3,N
4,76005,Tom,Abernethy,Tom Abernethy,"Abernethy, Tom",T. Abernethy,tom-abernethy,1954-05-06 00:00:00,Indiana,USA,...,HISTADD_tom_abernethy,1976.0,1980.0,N,Y,Y,1976,3,43,N

In [61]:
print(df_player.columns.tolist())
print(df_common.columns.tolist())

['id', 'full_name', 'first_name', 'last_name', 'is_active']
['person_id', 'first_name', 'last_name', 'display_first_last', 'display_last_comma_first', 'display_fi_last', 'player_slug', 'birthdate', 'school', 'country', 'last_affiliation', 'height', 'weight', 'season_exp', 'jersey', 'position', 'rosterstatus', 'games_played_current_season_flag', 'team_id', 'team_name', 'team_abbreviation', 'team_code', 'team_city', 'playercode', 'from_year', 'to_year', 'dleague_flag', 'nba_flag', 'games_played_flag', 'draft_year', 'draft_round', 'draft_number', 'greatest_75_flag']

In [62]:
import kagglehub

duckdb_path = kagglehub.dataset_download(
    "wyattowalsh/basketball/versions/237",
    path="nba.duckdb"
)

print(duckdb_path)

Using Colab cache for faster access to the 'basketball' dataset.
/kaggle/input/basketball/nba.duckdb

In [63]:
!pip install -q duckdb

In [64]:
import duckdb

con = duckdb.connect(duckdb_path, read_only=True)

In [65]:
tables = con.execute("SHOW TABLES").df()

print(tables.shape)
display(tables.head(50))

(0, 1)

Empty DataFrame
Columns: [name]
Index: []

In [66]:
tables[
    tables.iloc[:, 0].str.contains(
        "player|season|career|award|traditional|advanced",
        case=False,
        regex=True
    )
]

Empty DataFrame
Columns: [name]
Index: []

In [67]:
import os

print("duckdb_path :", duckdb_path)
print("Existe :", os.path.exists(duckdb_path))
print("Est un fichier :", os.path.isfile(duckdb_path))
print("Est un dossier :", os.path.isdir(duckdb_path))

if os.path.isfile(duckdb_path):
    print("Taille :", round(os.path.getsize(duckdb_path) / 1024**2, 2), "Mo")

duckdb_path : /kaggle/input/basketball/nba.duckdb
Existe : True
Est un fichier : True
Est un dossier : False
Taille : 0.01 Mo

In [68]:
import kagglehub
import os

dataset_path = kagglehub.dataset_download(
    "wyattowalsh/basketball/versions/237"
)

print("Dataset :", dataset_path)

for root, dirs, files in os.walk(dataset_path):
    for file in files:
        if file.endswith((".duckdb", ".sqlite", ".csv")):
            full_path = os.path.join(root, file)
            size_mb = os.path.getsize(full_path) / 1024**2

            print(f"{file:40} {size_mb:10.2f} MB")

Using Colab cache for faster access to the 'basketball' dataset.
Dataset : /kaggle/input/basketball
nba.sqlite                                  2240.74 MB
nba.duckdb                                     0.01 MB
other_stats.csv                                3.34 MB
draft_history.csv                              0.79 MB
team_details.csv                               0.01 MB
player.csv                                     0.16 MB
draft_combine_stats.csv                        0.19 MB
team_info_common.csv                           0.00 MB
common_player_info.csv                         0.98 MB
team_history.csv                               0.00 MB
game.csv                                      19.37 MB
game_summary.csv                               5.36 MB
officials.csv                                  2.23 MB
game_info.csv                                  2.28 MB
line_score.csv                                10.20 MB
play_by_play.csv                            2151.94 MB
team.csv                                       0.00 MB
inactive_players.csv                           7.04 MB

In [69]:
import kagglehub

sqlite_path = kagglehub.dataset_download(
    "wyattowalsh/basketball/versions/237",
    path="nba.sqlite"
)

print(sqlite_path)

Using Colab cache for faster access to the 'basketball' dataset.
/kaggle/input/basketball/nba.sqlite

In [70]:
import os

print("Existe :", os.path.exists(sqlite_path))
print("Taille :", round(os.path.getsize(sqlite_path) / 1024**2, 2), "Mo")

Existe : True
Taille : 2240.74 Mo

In [71]:
import sqlite3

conn = sqlite3.connect(sqlite_path)

tables_sqlite = pd.read_sql("""
SELECT name
FROM sqlite_master
WHERE type='table'
ORDER BY name
""", conn)

print(tables_sqlite.shape)
display(tables_sqlite.head(100))

(16, 1)

                   name
0    common_player_info
1   draft_combine_stats
2         draft_history
3                  game
4             game_info
5          game_summary
6      inactive_players
7            line_score
8             officials
9           other_stats
10         play_by_play
11               player
12                 team
13         team_details
14         team_history
15     team_info_common

In [72]:
goat_tables = tables_sqlite[
    tables_sqlite["name"].str.contains(
        "player|season|career|award|traditional|advanced|box|stats",
        case=False,
        regex=True,
        na=False
    )
]

display(goat_tables)

                   name
0    common_player_info
1   draft_combine_stats
6      inactive_players
9           other_stats
11               player

In [73]:
tables_to_check = [
    "player",
    "common_player_info",
    "game",
    "other_stats",
    "draft_combine_stats"
]

for table in tables_to_check:
    print("\n" + "=" * 80)
    print(f"TABLE : {table}")
    print("=" * 80)

    info = pd.read_sql(
        f"PRAGMA table_info({table})",
        conn
    )

    display(info[["name", "type"]])

================================================================================
TABLE : player
================================================================================

         name     type
0          id     TEXT
1   full_name     TEXT
2  first_name     TEXT
3   last_name     TEXT
4   is_active  INTEGER

================================================================================
TABLE : common_player_info
================================================================================

                                name       type
0                          person_id       TEXT
1                         first_name       TEXT
2                          last_name       TEXT
3                 display_first_last       TEXT
4           display_last_comma_first       TEXT
5                    display_fi_last       TEXT
6                        player_slug       TEXT
7                          birthdate  TIMESTAMP
8                             school       TEXT
9                            country       TEXT
10                  last_affiliation       TEXT
11                            height       TEXT
12                            weight       TEXT
13                        season_exp       REAL
14                            jersey       TEXT
15                          position       TEXT
16                      rosterstatus       TEXT
17  games_played_current_season_flag       TEXT
18                           team_id    INTEGER
19                         team_name       TEXT
20                 team_abbreviation       TEXT
21                         team_code       TEXT
22                         team_city       TEXT
23                        playercode       TEXT
24                         from_year       REAL
25                           to_year       REAL
26                      dleague_flag       TEXT
27                          nba_flag       TEXT
28                 games_played_flag       TEXT
29                        draft_year       TEXT
30                       draft_round       TEXT
31                      draft_number       TEXT
32                  greatest_75_flag       TEXT

================================================================================
TABLE : game
================================================================================

                      name       type
0                season_id       TEXT
1             team_id_home       TEXT
2   team_abbreviation_home       TEXT
3           team_name_home       TEXT
4                  game_id       TEXT
5                game_date  TIMESTAMP
6             matchup_home       TEXT
7                  wl_home       TEXT
8                      min    INTEGER
9                 fgm_home       REAL
10                fga_home       REAL
11             fg_pct_home       REAL
12               fg3m_home       REAL
13               fg3a_home       REAL
14            fg3_pct_home       REAL
15                ftm_home       REAL
16                fta_home       REAL
17             ft_pct_home       REAL
18               oreb_home       REAL
19               dreb_home       REAL
20                reb_home       REAL
21                ast_home       REAL
22                stl_home       REAL
23                blk_home       REAL
24                tov_home       REAL
25                 pf_home       REAL
26                pts_home       REAL
27         plus_minus_home    INTEGER
28    video_available_home    INTEGER
29            team_id_away       TEXT
30  team_abbreviation_away       TEXT
31          team_name_away       TEXT
32            matchup_away       TEXT
33                 wl_away       TEXT
34                fgm_away       REAL
35                fga_away       REAL
36             fg_pct_away       REAL
37               fg3m_away       REAL
38               fg3a_away       REAL
39            fg3_pct_away       REAL
40                ftm_away       REAL
41                fta_away       REAL
42             ft_pct_away       REAL
43               oreb_away       REAL
44               dreb_away       REAL
45                reb_away       REAL
46                ast_away       REAL
47                stl_away       REAL
48                blk_away       REAL
49                tov_away       REAL
50                 pf_away       REAL
51                pts_away       REAL
52         plus_minus_away    INTEGER
53    video_available_away    INTEGER
54             season_type       TEXT

================================================================================
TABLE : other_stats
================================================================================

                      name     type
0                  game_id     TEXT
1                league_id     TEXT
2             team_id_home     TEXT
3   team_abbreviation_home     TEXT
4           team_city_home     TEXT
5           pts_paint_home  INTEGER
6      pts_2nd_chance_home  INTEGER
7              pts_fb_home  INTEGER
8        largest_lead_home  INTEGER
9             lead_changes  INTEGER
10              times_tied  INTEGER
11     team_turnovers_home  INTEGER
12    total_turnovers_home  INTEGER
13      team_rebounds_home  INTEGER
14         pts_off_to_home  INTEGER
15            team_id_away     TEXT
16  team_abbreviation_away     TEXT
17          team_city_away     TEXT
18          pts_paint_away  INTEGER
19     pts_2nd_chance_away  INTEGER
20             pts_fb_away  INTEGER
21       largest_lead_away  INTEGER
22     team_turnovers_away  INTEGER
23    total_turnovers_away  INTEGER
24      team_rebounds_away  INTEGER
25         pts_off_to_away  INTEGER

================================================================================
TABLE : draft_combine_stats
================================================================================

                            name  type
0                         season  TEXT
1                      player_id  TEXT
2                     first_name  TEXT
3                      last_name  TEXT
4                    player_name  TEXT
5                       position  TEXT
6                height_wo_shoes  REAL
7          height_wo_shoes_ft_in  TEXT
8                 height_w_shoes  REAL
9           height_w_shoes_ft_in  TEXT
10                        weight  TEXT
11                      wingspan  REAL
12                wingspan_ft_in  TEXT
13                standing_reach  REAL
14          standing_reach_ft_in  TEXT
15                  body_fat_pct  TEXT
16                   hand_length  TEXT
17                    hand_width  TEXT
18        standing_vertical_leap  REAL
19             max_vertical_leap  REAL
20             lane_agility_time  REAL
21    modified_lane_agility_time  REAL
22          three_quarter_sprint  REAL
23                   bench_press  REAL
24      spot_fifteen_corner_left  TEXT
25       spot_fifteen_break_left  TEXT
26          spot_fifteen_top_key  TEXT
27      spot_fifteen_break_right  TEXT
28     spot_fifteen_corner_right  TEXT
29      spot_college_corner_left  TEXT
30       spot_college_break_left  TEXT
31          spot_college_top_key  TEXT
32      spot_college_break_right  TEXT
33     spot_college_corner_right  TEXT
34          spot_nba_corner_left  TEXT
35           spot_nba_break_left  TEXT
36              spot_nba_top_key  TEXT
37          spot_nba_break_right  TEXT
38         spot_nba_corner_right  TEXT
39   off_drib_fifteen_break_left  TEXT
40      off_drib_fifteen_top_key  TEXT
41  off_drib_fifteen_break_right  TEXT
42   off_drib_college_break_left  TEXT
43      off_drib_college_top_key  TEXT
44  off_drib_college_break_right  TEXT
45               on_move_fifteen  TEXT
46               on_move_college  TEXT

In [74]:
df_other_sample = pd.read_sql("""
SELECT *
FROM other_stats
LIMIT 5
""", conn)

display(df_other_sample)

,game_id,league_id,team_id_home,team_abbreviation_home,team_city_home,pts_paint_home,pts_2nd_chance_home,pts_fb_home,largest_lead_home,lead_changes,...,team_abbreviation_away,team_city_away,pts_paint_away,pts_2nd_chance_away,pts_fb_away,largest_lead_away,team_turnovers_away,total_turnovers_away,team_rebounds_away,pts_off_to_away
0,0029600012,00,1610612756,PHX,Phoenix,44,18,2,1,4,...,LAL,Los Angeles,42,10,13,19,0,23,11,None
1,0029600005,00,1610612737,ATL,Atlanta,32,9,6,0,0,...,MIA,Miami,32,15,14,16,1,19,6,None
2,0029600002,00,1610612739,CLE,Cleveland,36,14,6,20,1,...,NJN,New Jersey,26,16,4,2,1,22,12,None
3,0029600007,00,1610612754,IND,Indiana,34,11,4,10,7,...,DET,Detroit,30,14,7,9,2,19,10,None
4,0029600013,00,1610612746,LAC,Los Angeles,40,19,2,12,5,...,GSW,Golden State,30,9,2,6,0,20,7,None

In [75]:
df_game_sample = pd.read_sql("""
SELECT *
FROM game
LIMIT 5
""", conn)

display(df_game_sample)

,season_id,team_id_home,team_abbreviation_home,team_name_home,game_id,game_date,matchup_home,wl_home,min,fgm_home,...,reb_away,ast_away,stl_away,blk_away,tov_away,pf_away,pts_away,plus_minus_away,video_available_away,season_type
0,21946,1610610035,HUS,Toronto Huskies,0024600001,1946-11-01 00:00:00,HUS vs. NYK,L,0,25.0,...,None,None,None,None,None,NaN,68.0,2,0,Regular Season
1,21946,1610610034,BOM,St. Louis Bombers,0024600003,1946-11-02 00:00:00,BOM vs. PIT,W,0,20.0,...,None,None,None,None,None,25.0,51.0,-5,0,Regular Season
2,21946,1610610032,PRO,Providence Steamrollers,0024600002,1946-11-02 00:00:00,PRO vs. BOS,W,0,21.0,...,None,None,None,None,None,NaN,53.0,-6,0,Regular Season
3,21946,1610610025,CHS,Chicago Stags,0024600004,1946-11-02 00:00:00,CHS vs. NYK,W,0,21.0,...,None,None,None,None,None,22.0,47.0,-16,0,Regular Season
4,21946,1610610028,DEF,Detroit Falcons,0024600005,1946-11-02 00:00:00,DEF vs. WAS,L,0,10.0,...,None,None,None,None,None,NaN,50.0,17,0,Regular Season

In [76]:
pbp_info = pd.read_sql("""
PRAGMA table_info(play_by_play)
""", conn)

print("Nombre de colonnes :", len(pbp_info))

display(
    pbp_info[["name", "type"]]
)

Nombre de colonnes : 34

                         name     type
0                     game_id     TEXT
1                    eventnum  INTEGER
2                eventmsgtype  INTEGER
3          eventmsgactiontype  INTEGER
4                      period  INTEGER
5                wctimestring     TEXT
6                pctimestring     TEXT
7             homedescription     TEXT
8          neutraldescription     TEXT
9          visitordescription     TEXT
10                      score     TEXT
11                scoremargin     TEXT
12                person1type     REAL
13                 player1_id     TEXT
14               player1_name     TEXT
15            player1_team_id     TEXT
16          player1_team_city     TEXT
17      player1_team_nickname     TEXT
18  player1_team_abbreviation     TEXT
19                person2type     REAL
20                 player2_id     TEXT
21               player2_name     TEXT
22            player2_team_id     TEXT
23          player2_team_city     TEXT
24      player2_team_nickname     TEXT
25  player2_team_abbreviation     TEXT
26                person3type     REAL
27                 player3_id     TEXT
28               player3_name     TEXT
29            player3_team_id     TEXT
30          player3_team_city     TEXT
31      player3_team_nickname     TEXT
32  player3_team_abbreviation     TEXT
33       video_available_flag     TEXT

In [77]:
player_columns = pbp_info[
    pbp_info["name"].str.contains(
        "player|person|assist|rebound|score|shot",
        case=False,
        regex=True,
        na=False
    )
]

display(player_columns[["name", "type"]])

                         name  type
10                      score  TEXT
11                scoremargin  TEXT
12                person1type  REAL
13                 player1_id  TEXT
14               player1_name  TEXT
15            player1_team_id  TEXT
16          player1_team_city  TEXT
17      player1_team_nickname  TEXT
18  player1_team_abbreviation  TEXT
19                person2type  REAL
20                 player2_id  TEXT
21               player2_name  TEXT
22            player2_team_id  TEXT
23          player2_team_city  TEXT
24      player2_team_nickname  TEXT
25  player2_team_abbreviation  TEXT
26                person3type  REAL
27                 player3_id  TEXT
28               player3_name  TEXT
29            player3_team_id  TEXT
30          player3_team_city  TEXT
31      player3_team_nickname  TEXT
32  player3_team_abbreviation  TEXT

In [78]:
common_info = pd.read_sql("""
PRAGMA table_info(common_player_info)
""", conn)

display(common_info[["name", "type"]])

                                name       type
0                          person_id       TEXT
1                         first_name       TEXT
2                          last_name       TEXT
3                 display_first_last       TEXT
4           display_last_comma_first       TEXT
5                    display_fi_last       TEXT
6                        player_slug       TEXT
7                          birthdate  TIMESTAMP
8                             school       TEXT
9                            country       TEXT
10                  last_affiliation       TEXT
11                            height       TEXT
12                            weight       TEXT
13                        season_exp       REAL
14                            jersey       TEXT
15                          position       TEXT
16                      rosterstatus       TEXT
17  games_played_current_season_flag       TEXT
18                           team_id    INTEGER
19                         team_name       TEXT
20                 team_abbreviation       TEXT
21                         team_code       TEXT
22                         team_city       TEXT
23                        playercode       TEXT
24                         from_year       REAL
25                           to_year       REAL
26                      dleague_flag       TEXT
27                          nba_flag       TEXT
28                 games_played_flag       TEXT
29                        draft_year       TEXT
30                       draft_round       TEXT
31                      draft_number       TEXT
32                  greatest_75_flag       TEXT

In [79]:
lebron = pd.read_sql("""
SELECT *
FROM common_player_info
WHERE display_first_last LIKE '%LeBron James%'
LIMIT 5
""", conn)

display(lebron.T)

Empty DataFrame
Columns: []
Index: [person_id, first_name, last_name, display_first_last, display_last_comma_first, display_fi_last, player_slug, birthdate, school, country, last_affiliation, height, weight, season_exp, jersey, position, rosterstatus, games_played_current_season_flag, team_id, team_name, team_abbreviation, team_code, team_city, playercode, from_year, to_year, dleague_flag, nba_flag, games_played_flag, draft_year, draft_round, draft_number, greatest_75_flag]

In [80]:
import kagglehub
import os

dataset_path = kagglehub.dataset_download(
    "wyattowalsh/basketball"
)

print("Dataset :", dataset_path)

Downloading to /root/.cache/kagglehub/datasets/wyattowalsh/basketball/238.archive...

100%|██████████| 697M/697M [00:08<00:00, 87.4MB/s]

Extracting files...

Dataset : /root/.cache/kagglehub/datasets/wyattowalsh/basketball/versions/238

In [81]:
targets = [
    "analytics_player_season_complete",
    "agg_player_season",
    "player_season"
]

matches = []

for root, dirs, files in os.walk(dataset_path):
    for file in files:
        if any(target.lower() in file.lower() for target in targets):
            full_path = os.path.join(root, file)

            matches.append({
                "file": file,
                "path": full_path,
                "size_mb": round(os.path.getsize(full_path) / 1024**2, 2)
            })

matches

[]

In [82]:
import pandas as pd

df_matches = pd.DataFrame(matches)

display(df_matches)

Empty DataFrame
Columns: []
Index: []

In [83]:
import os
import pandas as pd

files_info = []

for root, dirs, files in os.walk(dataset_path):
    for file in files:
        full_path = os.path.join(root, file)

        files_info.append({
            "file": file,
            "extension": os.path.splitext(file)[1],
            "size_mb": round(os.path.getsize(full_path) / 1024**2, 2),
            "path": full_path
        })

df_files = pd.DataFrame(files_info)

print("Nombre de fichiers :", len(df_files))

display(
    df_files
    .sort_values("size_mb", ascending=False)
    .reset_index(drop=True)
)

Nombre de fichiers : 20

,file,extension,size_mb,path
0,nba.sqlite,.sqlite,2240.74,/root/.cache/kagglehub/datasets/wyattowalsh/ba...
1,play_by_play.csv,.csv,2151.94,/root/.cache/kagglehub/datasets/wyattowalsh/ba...
2,game.csv,.csv,19.37,/root/.cache/kagglehub/datasets/wyattowalsh/ba...
3,line_score.csv,.csv,10.20,/root/.cache/kagglehub/datasets/wyattowalsh/ba...
4,inactive_players.csv,.csv,7.04,/root/.cache/kagglehub/datasets/wyattowalsh/ba...
5,game_summary.csv,.csv,5.36,/root/.cache/kagglehub/datasets/wyattowalsh/ba...
6,other_stats.csv,.csv,3.34,/root/.cache/kagglehub/datasets/wyattowalsh/ba...
7,game_info.csv,.csv,2.28,/root/.cache/kagglehub/datasets/wyattowalsh/ba...
8,officials.csv,.csv,2.23,/root/.cache/kagglehub/datasets/wyattowalsh/ba...
9,common_player_info.csv,.csv,0.98,/root/.cache/kagglehub/datasets/wyattowalsh/ba...
10,draft_history.csv,.csv,0.79,/root/.cache/kagglehub/datasets/wyattowalsh/ba...
11,draft_combine_stats.csv,.csv,0.19,/root/.cache/kagglehub/datasets/wyattowalsh/ba...
12,player.csv,.csv,0.16,/root/.cache/kagglehub/datasets/wyattowalsh/ba...
13,dataset-metadata.json,.json,0.03,/root/.cache/kagglehub/datasets/wyattowalsh/ba...
14,team_details.csv,.csv,0.01,/root/.cache/kagglehub/datasets/wyattowalsh/ba...
15,nba.duckdb,.duckdb,0.01,/root/.cache/kagglehub/datasets/wyattowalsh/ba...
16,run_summary.json,.json,0.00,/root/.cache/kagglehub/datasets/wyattowalsh/ba...
17,team_history.csv,.csv,0.00,/root/.cache/kagglehub/datasets/wyattowalsh/ba...
18,team_info_common.csv,.csv,0.00,/root/.cache/kagglehub/datasets/wyattowalsh/ba...
19,team.csv,.csv,0.00,/root/.cache/kagglehub/datasets/wyattowalsh/ba...

In [84]:
player_files = df_files[
    df_files["file"].str.contains(
        "player|career|season|stats|award|box",
        case=False,
        regex=True,
        na=False
    )
]

display(
    player_files
    .sort_values("size_mb", ascending=False)
    .reset_index(drop=True)
)

,file,extension,size_mb,path
0,inactive_players.csv,.csv,7.04,/root/.cache/kagglehub/datasets/wyattowalsh/ba...
1,other_stats.csv,.csv,3.34,/root/.cache/kagglehub/datasets/wyattowalsh/ba...
2,common_player_info.csv,.csv,0.98,/root/.cache/kagglehub/datasets/wyattowalsh/ba...
3,draft_combine_stats.csv,.csv,0.19,/root/.cache/kagglehub/datasets/wyattowalsh/ba...
4,player.csv,.csv,0.16,/root/.cache/kagglehub/datasets/wyattowalsh/ba...

In [85]:
!pip install -q nba_api

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 322.6/322.6 kB 14.9 MB/s eta 0:00:00

In [86]:
from nba_api.stats.endpoints import leaguedashplayerstats
import pandas as pd

In [87]:
import kagglehub

goat_path = kagglehub.dataset_download(
    "flynn28/historical-nba-player-stats-database"
)

print(goat_path)

Downloading to /root/.cache/kagglehub/datasets/flynn28/historical-nba-player-stats-database/1.archive...

100%|██████████| 1.27M/1.27M [00:00<00:00, 44.7MB/s]

Extracting files...
/root/.cache/kagglehub/datasets/flynn28/historical-nba-player-stats-database/versions/1

In [88]:
import os

for root, dirs, files in os.walk(goat_path):
    for file in files:
        print(file)

NBA_PLAYER_DATASET.csv

In [89]:
import pandas as pd
import os

csv_path = os.path.join(goat_path, "NBA_PLAYER_DATASET.csv")

df_goat = pd.read_csv(csv_path)

print("Dimensions :", df_goat.shape)
display(df_goat.head())

Dimensions : (29916, 27)

,PLAYER_ID,Name,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,PLAYER_AGE,GP,GS,MIN,FGM,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS
0,76001,Alaa Abdelnaby,1990-91,1610612757,POR,23.0,43,0.0,290.0,55,...,0.568,27.0,62.0,89.0,12,4.0,12.0,22.0,39,135
1,76001,Alaa Abdelnaby,1991-92,1610612757,POR,24.0,71,1.0,934.0,178,...,0.752,81.0,179.0,260.0,30,25.0,16.0,66.0,132,432
2,76001,Alaa Abdelnaby,1992-93,1610612749,MIL,25.0,12,0.0,159.0,26,...,0.750,12.0,25.0,37.0,10,6.0,4.0,13.0,24,64
3,76001,Alaa Abdelnaby,1992-93,1610612738,BOS,25.0,63,52.0,1152.0,219,...,0.760,114.0,186.0,300.0,17,19.0,22.0,84.0,165,514
4,76001,Alaa Abdelnaby,1992-93,0,TOT,25.0,75,52.0,1311.0,245,...,0.759,126.0,211.0,337.0,27,25.0,26.0,97.0,189,578

In [90]:
print(df_goat.columns.tolist())

['PLAYER_ID', 'Name', 'SEASON_ID', 'TEAM_ID', 'TEAM_ABBREVIATION', 'PLAYER_AGE', 'GP', 'GS', 'MIN', 'FGM', 'FGA', 'FG_PCT', 'FG3M', 'FG3A', 'FG3_PCT', 'FTM', 'FTA', 'FT_PCT', 'OREB', 'DREB', 'REB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS']

In [91]:
df_goat.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29916 entries, 0 to 29915
Data columns (total 27 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   PLAYER_ID          29916 non-null  int64
 1   Name               29916 non-null  object
 2   SEASON_ID          29916 non-null  object
 3   TEAM_ID            29916 non-null  int64
 4   TEAM_ABBREVIATION  29908 non-null  object
 5   PLAYER_AGE         29916 non-null  float64
 6   GP                 29916 non-null  int64
 7   GS                 23434 non-null  float64
 8   MIN                29147 non-null  float64
 9   FGM                29916 non-null  int64
 10  FGA                29916 non-null  int64
 11  FG_PCT             29902 non-null  float64
 12  FG3M               23883 non-null  float64
 13  FG3A               23883 non-null  float64
 14  FG3_PCT            23661 non-null  float64
 15  FTM                29916 non-null  int64
 16  FTA                29916 non-null  int64
 17  FT_PCT             29797 non-null  float64
 18  OREB               25753 non-null  float64
 19  DREB               25753 non-null  float64
 20  REB                29259 non-null  float64
 21  AST                29916 non-null  int64
 22  STL                25753 non-null  float64
 23  BLK                25753 non-null  float64
 24  TOV                24601 non-null  float64
 25  PF                 29916 non-null  int64
 26  PTS                29916 non-null  int64
dtypes: float64(14), int64(10), object(3)
memory usage: 6.2+ MB

In [92]:
print("Première saison :", df_goat["SEASON_ID"].min())
print("Dernière saison :", df_goat["SEASON_ID"].max())
print("Nombre de saisons :", df_goat["SEASON_ID"].nunique())
print("Nombre de joueurs :", df_goat["PLAYER_ID"].nunique())

Première saison : 1946-47
Dernière saison : 2023-24
Nombre de saisons : 78
Nombre de joueurs : 4897

In [93]:
goat_players = [
    "Michael Jordan",
    "LeBron James",
    "Kareem Abdul-Jabbar",
    "Magic Johnson",
    "Larry Bird"
]

df_test_goat = df_goat[
    df_goat["Name"].isin(goat_players)
].copy()

print("Nombre de lignes :", len(df_test_goat))

display(
    df_test_goat[
        [
            "PLAYER_ID",
            "Name",
            "SEASON_ID",
            "TEAM_ABBREVIATION",
            "PLAYER_AGE",
            "GP",
            "MIN",
            "PTS",
            "REB",
            "AST"
        ]
    ].sort_values(["Name", "SEASON_ID"])
)

Nombre de lignes : 82

,PLAYER_ID,Name,SEASON_ID,TEAM_ABBREVIATION,PLAYER_AGE,GP,MIN,PTS,REB,AST
23,76003,Kareem Abdul-Jabbar,1969-70,MIL,23.0,82,3534.0,2361,1190.0,337
24,76003,Kareem Abdul-Jabbar,1970-71,MIL,24.0,82,3288.0,2596,1311.0,272
25,76003,Kareem Abdul-Jabbar,1971-72,MIL,25.0,81,3583.0,2822,1346.0,370
26,76003,Kareem Abdul-Jabbar,1972-73,MIL,26.0,76,3254.0,2292,1224.0,379
27,76003,Kareem Abdul-Jabbar,1973-74,MIL,27.0,81,3548.0,2191,1178.0,386
...,...,...,...,...,...,...,...,...,...,...
14339,893,Michael Jordan,1995-96,CHI,33.0,82,3090.0,2491,543.0,352
14340,893,Michael Jordan,1996-97,CHI,34.0,82,3109.0,2431,482.0,352
14341,893,Michael Jordan,1997-98,CHI,35.0,82,3181.0,2357,475.0,283
14342,893,Michael Jordan,2001-02,WAS,39.0,60,2089.0,1375,339.0,310
14343,893,Michael Jordan,2002-03,WAS,40.0,82,3029.0,1640,497.0,311

In [94]:
df_goat.columns.tolist()

['PLAYER_ID',
 'Name',
 'SEASON_ID',
 'TEAM_ID',
 'TEAM_ABBREVIATION',
 'PLAYER_AGE',
 'GP',
 'GS',
 'MIN',
 'FGM',
 'FGA',
 'FG_PCT',
 'FG3M',
 'FG3A',
 'FG3_PCT',
 'FTM',
 'FTA',
 'FT_PCT',
 'OREB',
 'DREB',
 'REB',
 'AST',
 'STL',
 'BLK',
 'TOV',
 'PF',
 'PTS']

In [95]:
duplicates = (
    df_goat
    .groupby(["PLAYER_ID", "SEASON_ID"])
    .size()
    .reset_index(name="nb_rows")
)

duplicates = duplicates[
    duplicates["nb_rows"] > 1
]

print("Joueur-saisons avec plusieurs lignes :", len(duplicates))

display(
    duplicates
    .sort_values("nb_rows", ascending=False)
    .head(20)
)

Joueur-saisons avec plusieurs lignes : 2572

       PLAYER_ID SEASON_ID  nb_rows
18183     200784   2007-08        6
21510     203930   2017-18        5
12153      77019   1985-86        5
16070      78261   1992-93        5
19735     202328   2021-22        5
3523         763   1991-92        5
23783    1629685   2023-24        4
23658    1629649   2020-21        4
23544    1629620   2021-22        4
23418    1629117   2021-22        4
23392    1629066   2020-21        4
23410    1629109   2020-21        4
23195    1628993   2021-22        4
23306    1629021   2020-21        4
23233    1629003   2023-24        4
23028    1628502   2017-18        4
22624    1627863   2021-22        4
22971    1628436   2021-22        4
22554    1627823   2021-22        4
22352    1627745   2020-21        4

In [96]:
tot_rows = df_goat[
    df_goat["TEAM_ABBREVIATION"] == "TOT"
]

print("Nombre de lignes TOT :", len(tot_rows))
print("Nombre de joueurs concernés :", tot_rows["PLAYER_ID"].nunique())

display(tot_rows.head())

Nombre de lignes TOT : 2572
Nombre de joueurs concernés : 1783

,PLAYER_ID,Name,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,PLAYER_AGE,GP,GS,MIN,FGM,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS
4,76001,Alaa Abdelnaby,1992-93,0,TOT,25.0,75,52.0,1311.0,245,...,0.759,126.0,211.0,337.0,27,25.0,26.0,97.0,189,578
8,76001,Alaa Abdelnaby,1994-95,0,TOT,27.0,54,0.0,506.0,118,...,0.571,37.0,77.0,114.0,13,15.0,12.0,45.0,104,256
11,76002,Zaid Abdul-Aziz,1968-69,0,TOT,23.0,49,NaN,945.0,144,...,0.619,NaN,NaN,409.0,37,NaN,NaN,NaN,115,358
22,76002,Zaid Abdul-Aziz,1977-78,0,TOT,32.0,16,NaN,158.0,23,...,0.739,19.0,31.0,50.0,10,3.0,3.0,11.0,29,63
56,1505,Tariq Abdul-Wahad,1999-00,0,TOT,25.0,61,56.0,1578.0,274,...,0.756,101.0,190.0,291.0,98,59.0,28.0,106.0,147,697

In [97]:
def keep_season_total(group):

    # Plusieurs lignes + présence de TOT
    if "TOT" in group["TEAM_ABBREVIATION"].values:
        return group[
            group["TEAM_ABBREVIATION"] == "TOT"
        ].iloc[0]

    # Une seule ligne
    return group.iloc[0]


df_player_season = (
    df_goat
    .groupby(
        ["PLAYER_ID", "SEASON_ID"],
        group_keys=False
    )
    .apply(keep_season_total)
    .reset_index(drop=True)
)

print("Avant :", df_goat.shape)
print("Après :", df_player_season.shape)

Avant : (29916, 27)
Après : (24599, 27)

/tmp/ipykernel_1080/3920032869.py:19: DeprecationWarning:

DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.

In [98]:
check = (
    df_player_season
    .groupby(["PLAYER_ID", "SEASON_ID"])
    .size()
)

print(
    "Nombre de doublons restants :",
    (check > 1).sum()
)

Nombre de doublons restants : 0

In [99]:
goat_players = [
    "Michael Jordan",
    "LeBron James",
    "Kareem Abdul-Jabbar",
    "Magic Johnson",
    "Larry Bird"
]

career_check = (
    df_player_season[
        df_player_season["Name"].isin(goat_players)
    ]
    .groupby("Name")
    .agg(
        first_season=("SEASON_ID", "min"),
        last_season=("SEASON_ID", "max"),
        seasons=("SEASON_ID", "nunique"),
        games=("GP", "sum"),
        points=("PTS", "sum"),
        rebounds=("REB", "sum"),
        assists=("AST", "sum")
    )
    .sort_values("points", ascending=False)
)

display(career_check)

,first_season,last_season,seasons,games,points,rebounds,assists
Name,,,,,,,
LeBron James,2003-04,2023-24,21,1492,40474,11185.0,11009
Kareem Abdul-Jabbar,1969-70,1988-89,20,1560,38387,17440.0,5660
Michael Jordan,1984-85,2002-03,15,1072,32292,6672.0,5633
Larry Bird,1979-80,1991-92,13,897,21791,8974.0,5695
Magic Johnson,1979-80,1995-96,13,906,17707,6559.0,10141

In [100]:
df_player_season["PPG"] = (
    df_player_season["PTS"] / df_player_season["GP"]
)

df_player_season["RPG"] = (
    df_player_season["REB"] / df_player_season["GP"]
)

df_player_season["APG"] = (
    df_player_season["AST"] / df_player_season["GP"]
)

df_player_season["SPG"] = (
    df_player_season["STL"] / df_player_season["GP"]
)

df_player_season["BPG"] = (
    df_player_season["BLK"] / df_player_season["GP"]
)

df_player_season["MPG"] = (
    df_player_season["MIN"] / df_player_season["GP"]
)

In [101]:
stats_per_game = [
    "PPG",
    "RPG",
    "APG",
    "SPG",
    "BPG",
    "MPG"
]

df_player_season[stats_per_game] = (
    df_player_season[stats_per_game]
    .round(2)
)

In [102]:
goat_seasons = df_player_season[
    df_player_season["Name"].isin(goat_players)
].copy()

display(
    goat_seasons[
        [
            "Name",
            "SEASON_ID",
            "PLAYER_AGE",
            "GP",
            "PPG",
            "RPG",
            "APG",
            "SPG",
            "BPG",
            "FG_PCT",
            "FG3_PCT",
            "FT_PCT"
        ]
    ]
    .sort_values(["Name", "SEASON_ID"])
)

,Name,SEASON_ID,PLAYER_AGE,GP,PPG,RPG,APG,SPG,BPG,FG_PCT,FG3_PCT,FT_PCT
8905,Kareem Abdul-Jabbar,1969-70,23.0,82,28.79,14.51,4.11,NaN,NaN,0.518,NaN,0.653
8906,Kareem Abdul-Jabbar,1970-71,24.0,82,31.66,15.99,3.32,NaN,NaN,0.577,NaN,0.690
8907,Kareem Abdul-Jabbar,1971-72,25.0,81,34.84,16.62,4.57,NaN,NaN,0.574,NaN,0.689
8908,Kareem Abdul-Jabbar,1972-73,26.0,76,30.16,16.11,4.99,NaN,NaN,0.554,NaN,0.713
8909,Kareem Abdul-Jabbar,1973-74,27.0,81,27.05,14.54,4.77,1.38,3.49,0.539,NaN,0.702
...,...,...,...,...,...,...,...,...,...,...,...,...
3787,Michael Jordan,1995-96,33.0,82,30.38,6.62,4.29,2.20,0.51,0.495,0.427,0.834
3788,Michael Jordan,1996-97,34.0,82,29.65,5.88,4.29,1.71,0.54,0.486,0.374,0.833
3789,Michael Jordan,1997-98,35.0,82,28.74,5.79,3.45,1.72,0.55,0.465,0.238,0.784
3790,Michael Jordan,2001-02,39.0,60,22.92,5.65,5.17,1.42,0.43,0.416,0.189,0.790
3791,Michael Jordan,2002-03,40.0,82,20.00,6.06,3.79,1.50,0.48,0.445,0.291,0.821

In [103]:
peak_ppg = (
    goat_seasons
    .sort_values(
        ["Name", "PPG"],
        ascending=[True, False]
    )
    .groupby("Name")
    .head(5)
)

display(
    peak_ppg[
        [
            "Name",
            "SEASON_ID",
            "PLAYER_AGE",
            "GP",
            "PPG",
            "RPG",
            "APG",
            "FG_PCT"
        ]
    ]
    .sort_values(
        ["Name", "PPG"],
        ascending=[True, False]
    )
)

,Name,SEASON_ID,PLAYER_AGE,GP,PPG,RPG,APG,FG_PCT
8907,Kareem Abdul-Jabbar,1971-72,25.0,81,34.84,16.62,4.57,0.574
8906,Kareem Abdul-Jabbar,1970-71,24.0,82,31.66,15.99,3.32,0.577
8908,Kareem Abdul-Jabbar,1972-73,26.0,76,30.16,16.11,4.99,0.554
8910,Kareem Abdul-Jabbar,1974-75,28.0,65,29.98,14.03,4.06,0.513
8905,Kareem Abdul-Jabbar,1969-70,23.0,82,28.79,14.51,4.11,0.518
5040,Larry Bird,1987-88,31.0,76,29.93,9.25,6.14,0.527
5037,Larry Bird,1984-85,28.0,80,28.69,10.52,6.64,0.522
5039,Larry Bird,1986-87,30.0,74,28.05,9.22,7.65,0.525
5038,Larry Bird,1985-86,29.0,82,25.79,9.82,6.79,0.496
5042,Larry Bird,1989-90,33.0,75,24.27,9.49,7.49,0.473
7931,LeBron James,2005-06,21.0,79,31.37,7.04,6.59,0.480
7947,LeBron James,2021-22,37.0,56,30.27,8.20,6.23,0.524
7933,LeBron James,2007-08,23.0,75,30.00,7.89,7.19,0.484
7935,LeBron James,2009-10,25.0,76,29.71,7.29,8.57,0.503
7948,LeBron James,2022-23,38.0,55,28.91,8.31,6.82,0.500
12574,Magic Johnson,1986-87,27.0,80,23.86,6.30,12.21,0.522
12576,Magic Johnson,1988-89,29.0,77,22.47,7.88,12.83,0.509
12577,Magic Johnson,1989-90,30.0,79,22.34,6.61,11.48,0.480
12568,Magic Johnson,1980-81,21.0,37,21.57,8.65,8.57,0.532
12575,Magic Johnson,1987-88,28.0,72,19.56,6.24,11.92,0.492
3779,Michael Jordan,1986-87,24.0,82,37.09,5.24,4.60,0.482
3780,Michael Jordan,1987-88,25.0,82,34.98,5.48,5.91,0.535
3782,Michael Jordan,1989-90,27.0,82,33.57,6.89,6.33,0.526
3785,Michael Jordan,1992-93,30.0,78,32.58,6.69,5.49,0.495
3781,Michael Jordan,1988-89,26.0,81,32.51,8.05,8.02,0.538

In [104]:
peak_5 = (
    peak_ppg
    .groupby("Name")
    .agg(
        peak_5_ppg=("PPG", "mean"),
        peak_5_rpg=("RPG", "mean"),
        peak_5_apg=("APG", "mean")
    )
    .round(2)
    .sort_values("peak_5_ppg", ascending=False)
)

display(peak_5)

                     peak_5_ppg  peak_5_rpg  peak_5_apg
Name
Michael Jordan            34.15        6.47        6.07
Kareem Abdul-Jabbar       31.09       15.45        4.21
LeBron James              30.05        7.75        7.08
Larry Bird                27.35        9.66        6.94
Magic Johnson             21.96        7.14       11.40

In [105]:
career_stats = (
    df_player_season[
        df_player_season["Name"].isin(goat_players)
    ]
    .groupby("Name")
    .agg(
        seasons=("SEASON_ID", "nunique"),
        games=("GP", "sum"),
        minutes=("MIN", "sum"),
        points=("PTS", "sum"),
        rebounds=("REB", "sum"),
        assists=("AST", "sum"),
        steals=("STL", "sum"),
        blocks=("BLK", "sum")
    )
)

In [106]:
career_stats["career_ppg"] = (
    career_stats["points"] / career_stats["games"]
)

career_stats["career_rpg"] = (
    career_stats["rebounds"] / career_stats["games"]
)

career_stats["career_apg"] = (
    career_stats["assists"] / career_stats["games"]
)

career_stats["career_spg"] = (
    career_stats["steals"] / career_stats["games"]
)

career_stats["career_bpg"] = (
    career_stats["blocks"] / career_stats["games"]
)

career_stats["career_mpg"] = (
    career_stats["minutes"] / career_stats["games"]
)

In [107]:
career_stats = career_stats.round(2)

display(
    career_stats[
        [
            "seasons",
            "games",
            "career_ppg",
            "career_rpg",
            "career_apg",
            "career_spg",
            "career_bpg",
            "career_mpg"
        ]
    ]
    .sort_values("career_ppg", ascending=False)
)

,seasons,games,career_ppg,career_rpg,career_apg,career_spg,career_bpg,career_mpg
Name,,,,,,,,
Michael Jordan,15,1072,30.12,6.22,5.25,2.35,0.83,38.25
LeBron James,21,1492,27.13,7.50,7.38,1.52,0.74,37.93
Kareem Abdul-Jabbar,20,1560,24.61,11.18,3.63,0.74,2.04,36.82
Larry Bird,13,897,24.29,10.00,6.35,1.73,0.84,38.40
Magic Johnson,13,906,19.54,7.24,11.19,1.90,0.41,36.69

In [108]:
availability = (
    df_player_season[
        df_player_season["Name"].isin(goat_players)
    ]
    .groupby("Name")
    .agg(
        seasons=("SEASON_ID", "nunique"),
        seasons_with_stl=("STL", "count"),
        seasons_with_blk=("BLK", "count"),
        seasons_with_fg3=("FG3_PCT", "count")
    )
)

availability["stl_coverage"] = (
    availability["seasons_with_stl"] /
    availability["seasons"] * 100
)

availability["blk_coverage"] = (
    availability["seasons_with_blk"] /
    availability["seasons"] * 100
)

availability["fg3_coverage"] = (
    availability["seasons_with_fg3"] /
    availability["seasons"] * 100
)

display(availability.round(1))

,seasons,seasons_with_stl,seasons_with_blk,seasons_with_fg3,stl_coverage,blk_coverage,fg3_coverage
Name,,,,,,,
Kareem Abdul-Jabbar,20,16,16,10,80.0,80.0,50.0
Larry Bird,13,13,13,13,100.0,100.0,100.0
LeBron James,21,21,21,21,100.0,100.0,100.0
Magic Johnson,13,13,13,13,100.0,100.0,100.0
Michael Jordan,15,15,15,15,100.0,100.0,100.0

In [109]:
df_era = df_player_season[
    df_player_season["GP"] >= 20
].copy()

In [110]:
df_era["PPG"] = df_era["PTS"] / df_era["GP"]
df_era["RPG"] = df_era["REB"] / df_era["GP"]
df_era["APG"] = df_era["AST"] / df_era["GP"]

In [111]:
for stat in ["PPG", "RPG", "APG"]:

    season_mean = df_era.groupby("SEASON_ID")[stat].transform("mean")
    season_std = df_era.groupby("SEASON_ID")[stat].transform("std")

    df_era[f"{stat}_Z"] = (
        (df_era[stat] - season_mean) /
        season_std
    )

In [112]:
goat_era = df_era[
    df_era["Name"].isin(goat_players)
].copy()

display(
    goat_era[
        [
            "Name",
            "SEASON_ID",
            "PPG",
            "PPG_Z",
            "RPG",
            "RPG_Z",
            "APG",
            "APG_Z"
        ]
    ]
    .sort_values(
        "PPG_Z",
        ascending=False
    )
    .head(20)
    .round(2)
)

                     Name SEASON_ID    PPG  PPG_Z    RPG  RPG_Z   APG  APG_Z
3779       Michael Jordan   1986-87  37.09   4.15   5.24   0.42  4.60   1.02
3780       Michael Jordan   1987-88  34.98   3.94   5.48   0.54  5.91   1.63
3785       Michael Jordan   1992-93  32.58   3.75   6.69   0.99  5.49   1.58
3782       Michael Jordan   1989-90  33.57   3.62   6.89   1.08  6.33   1.82
3787       Michael Jordan   1995-96  30.38   3.61   6.62   1.04  4.29   1.09
7931         LeBron James   2005-06  31.37   3.60   7.04   1.36  6.59   2.63
7935         LeBron James   2009-10  29.71   3.52   7.29   1.36  8.57   3.59
3789       Michael Jordan   1997-98  28.74   3.50   5.79   0.72  3.45   0.77
3781       Michael Jordan   1988-89  32.51   3.50   8.05   1.55  8.02   2.52
7933         LeBron James   2007-08  30.00   3.45   7.89   1.57  7.19   2.72
3788       Michael Jordan   1996-97  29.65   3.44   5.88   0.74  4.29   1.15
8907  Kareem Abdul-Jabbar   1971-72  34.84   3.43  16.62   3.03  4.57   1.18
7937         LeBron James   2011-12  27.15   3.40   7.94   1.73  6.24   2.34
3783       Michael Jordan   1990-91  31.46   3.37   6.00   0.74  5.52   1.48
7938         LeBron James   2012-13  26.79   3.36   8.03   1.72  7.25   2.81
3784       Michael Jordan   1991-92  30.05   3.32   6.39   0.84  6.11   1.89
7947         LeBron James   2021-22  30.27   3.25   8.20   1.76  6.23   2.11
8910  Kareem Abdul-Jabbar   1974-75  29.98   3.18  14.03   2.95  4.06   1.09
7939         LeBron James   2013-14  27.13   3.17   6.92   1.24  6.34   2.37
5040           Larry Bird   1987-88  29.93   3.15   9.25   1.95  6.14   1.74

In [113]:
df_era["PRODUCTION_Z"] = (
    0.40 * df_era["PPG_Z"] +
    0.30 * df_era["RPG_Z"] +
    0.30 * df_era["APG_Z"]
)

goat_era = df_era[
    df_era["Name"].isin(goat_players)
].copy()

In [114]:
best_seasons = (
    goat_era[
        [
            "Name",
            "SEASON_ID",
            "PPG",
            "RPG",
            "APG",
            "PPG_Z",
            "RPG_Z",
            "APG_Z",
            "PRODUCTION_Z"
        ]
    ]
    .sort_values("PRODUCTION_Z", ascending=False)
    .head(20)
    .round(2)
)

display(best_seasons)

,Name,SEASON_ID,PPG,RPG,APG,PPG_Z,RPG_Z,APG_Z,PRODUCTION_Z
7943,LeBron James,2017-18,27.45,8.65,9.11,3.10,1.95,3.94,3.01
8911,Kareem Abdul-Jabbar,1975-76,27.74,16.87,5.04,2.94,3.94,1.78,2.89
7935,LeBron James,2009-10,29.71,7.29,8.57,3.52,1.36,3.59,2.89
7942,LeBron James,2016-17,26.41,8.64,8.73,2.84,1.95,3.71,2.83
7945,LeBron James,2019-20,25.34,7.84,10.21,2.41,1.51,4.37,2.73
7938,LeBron James,2012-13,26.79,8.03,7.25,3.36,1.72,2.81,2.70
7944,LeBron James,2018-19,27.36,8.45,8.25,2.92,1.75,3.30,2.69
7933,LeBron James,2007-08,30.00,7.89,7.19,3.45,1.57,2.72,2.67
7931,LeBron James,2005-06,31.37,7.04,6.59,3.60,1.36,2.63,2.64
8907,Kareem Abdul-Jabbar,1971-72,34.84,16.62,4.57,3.43,3.03,1.18,2.64
12576,Magic Johnson,1988-89,22.47,7.88,12.83,1.95,1.49,4.64,2.62
3781,Michael Jordan,1988-89,32.51,8.05,8.02,3.50,1.55,2.52,2.62
7937,LeBron James,2011-12,27.15,7.94,6.24,3.40,1.73,2.34,2.58
7934,LeBron James,2008-09,28.44,7.57,7.25,3.14,1.47,2.87,2.56
7936,LeBron James,2010-11,26.72,7.47,7.01,3.14,1.48,2.69,2.50
7930,LeBron James,2004-05,27.19,7.35,7.21,3.03,1.39,2.89,2.50
8910,Kareem Abdul-Jabbar,1974-75,29.98,14.03,4.06,3.18,2.95,1.09,2.48
7947,LeBron James,2021-22,30.27,8.20,6.23,3.25,1.76,2.11,2.46
12574,Magic Johnson,1986-87,23.86,6.30,12.21,2.12,0.80,4.56,2.45
5037,Larry Bird,1984-85,28.69,10.52,6.64,2.78,2.42,1.98,2.43

In [115]:
top5_seasons = (
    goat_era
    .sort_values(
        ["Name", "PRODUCTION_Z"],
        ascending=[True, False]
    )
    .groupby("Name")
    .head(5)
)

peak_score = (
    top5_seasons
    .groupby("Name")
    .agg(
        peak_score=("PRODUCTION_Z", "mean"),
        peak_ppg_z=("PPG_Z", "mean"),
        peak_rpg_z=("RPG_Z", "mean"),
        peak_apg_z=("APG_Z", "mean")
    )
    .round(2)
    .sort_values("peak_score", ascending=False)
)

display(peak_score)

                     peak_score  peak_ppg_z  peak_rpg_z  peak_apg_z
Name
LeBron James               2.83        3.05        1.70        3.68
Kareem Abdul-Jabbar        2.55        3.03        3.17        1.28
Magic Johnson              2.43        1.63        1.35        4.59
Larry Bird                 2.33        2.68        2.08        2.11
Michael Jordan             2.32        3.63        1.00        1.89

In [116]:
import numpy as np

df_era["TS_PCT"] = np.where(
    (df_era["FGA"] + 0.44 * df_era["FTA"]) > 0,
    df_era["PTS"] /
    (2 * (df_era["FGA"] + 0.44 * df_era["FTA"])),
    np.nan
)

In [117]:
display(
    df_era[
        [
            "Name",
            "SEASON_ID",
            "PTS",
            "FGA",
            "FTA",
            "FG_PCT",
            "TS_PCT"
        ]
    ].head(10)
)

          Name SEASON_ID   PTS   FGA  FTA  FG_PCT    TS_PCT
0  Byron Scott   1983-84   788   690  139   0.484  0.524522
1  Byron Scott   1984-85  1295  1003  228   0.539  0.586865
2  Byron Scott   1985-86  1174   989  176   0.513  0.550429
3  Byron Scott   1986-87  1397  1134  251   0.489  0.561297
4  Byron Scott   1987-88  1754  1348  317   0.527  0.589588
5  Byron Scott   1988-89  1448  1198  226   0.491  0.558022
6  Byron Scott   1989-90  1197  1005  209   0.470  0.545599
7  Byron Scott   1990-91  1191  1051  148   0.477  0.533545
8  Byron Scott   1991-92  1218  1005  291   0.458  0.537492
9  Byron Scott   1992-93   792   659  184   0.449  0.535164

In [118]:
df_era["LEAGUE_TS"] = (
    df_era
    .groupby("SEASON_ID")["TS_PCT"]
    .transform("mean")
)

In [119]:
df_era["TS_PLUS"] = (
    df_era["TS_PCT"] /
    df_era["LEAGUE_TS"] * 100
)

In [120]:
ts_mean = (
    df_era
    .groupby("SEASON_ID")["TS_PCT"]
    .transform("mean")
)

ts_std = (
    df_era
    .groupby("SEASON_ID")["TS_PCT"]
    .transform("std")
)

df_era["TS_Z"] = (
    (df_era["TS_PCT"] - ts_mean) /
    ts_std
)

In [121]:
goat_era = df_era[
    df_era["Name"].isin(goat_players)
].copy()

display(
    goat_era[
        [
            "Name",
            "SEASON_ID",
            "PPG",
            "FG_PCT",
            "TS_PCT",
            "LEAGUE_TS",
            "TS_PLUS",
            "TS_Z"
        ]
    ]
    .sort_values("TS_PLUS", ascending=False)
    .head(25)
    .round(3)
)

,Name,SEASON_ID,PPG,FG_PCT,TS_PCT,LEAGUE_TS,TS_PLUS,TS_Z
8906,Kareem Abdul-Jabbar,1970-71,31.659,0.577,0.606,0.480,126.187,2.391
8907,Kareem Abdul-Jabbar,1971-72,34.840,0.574,0.603,0.483,124.773,2.140
8915,Kareem Abdul-Jabbar,1979-80,24.805,0.604,0.639,0.517,123.445,2.465
7939,LeBron James,2013-14,27.130,0.567,0.649,0.527,123.089,2.102
7938,LeBron James,2012-13,26.789,0.565,0.640,0.522,122.687,2.029
8912,Kareem Abdul-Jabbar,1976-77,26.244,0.579,0.608,0.500,121.630,2.223
12572,Magic Johnson,1984-85,18.260,0.561,0.637,0.529,120.436,1.948
12577,Magic Johnson,1989-90,22.342,0.480,0.622,0.517,120.424,1.816
12576,Magic Johnson,1988-89,22.468,0.509,0.625,0.519,120.375,2.105
8908,Kareem Abdul-Jabbar,1972-73,30.158,0.554,0.580,0.483,120.068,1.850
8918,Kareem Abdul-Jabbar,1982-83,21.797,0.588,0.619,0.516,120.041,1.986
12578,Magic Johnson,1990-91,19.380,0.477,0.623,0.520,119.957,1.931
8916,Kareem Abdul-Jabbar,1980-81,26.188,0.574,0.616,0.517,119.141,1.781
12571,Magic Johnson,1983-84,17.582,0.565,0.628,0.528,119.044,1.920
8914,Kareem Abdul-Jabbar,1978-79,23.788,0.577,0.612,0.515,118.871,1.998
8920,Kareem Abdul-Jabbar,1984-85,21.962,0.599,0.628,0.529,118.734,1.786
3781,Michael Jordan,1988-89,32.506,0.538,0.614,0.519,118.330,1.893
7937,LeBron James,2011-12,27.145,0.531,0.605,0.513,117.913,1.592
5039,Larry Bird,1986-87,28.054,0.525,0.612,0.521,117.351,1.730
3782,Michael Jordan,1989-90,33.573,0.526,0.606,0.517,117.277,1.536
8913,Kareem Abdul-Jabbar,1977-78,25.806,0.550,0.589,0.503,116.971,1.820
12570,Magic Johnson,1982-83,16.785,0.548,0.603,0.516,116.888,1.673
3783,Michael Jordan,1990-91,31.463,0.539,0.605,0.520,116.432,1.590
12567,Magic Johnson,1979-80,18.013,0.530,0.602,0.517,116.333,1.718
5040,Larry Bird,1987-88,29.934,0.527,0.608,0.523,116.172,1.641

In [122]:
top5_efficiency = (
    goat_era
    .dropna(subset=["TS_PLUS"])
    .sort_values(
        ["Name", "TS_PLUS"],
        ascending=[True, False]
    )
    .groupby("Name")
    .head(5)
)

In [123]:
peak_efficiency = (
    top5_efficiency
    .groupby("Name")
    .agg(
        peak_ts=("TS_PCT", "mean"),
        peak_ts_plus=("TS_PLUS", "mean"),
        peak_ts_z=("TS_Z", "mean")
    )
    .round(3)
    .sort_values("peak_ts_plus", ascending=False)
)

display(peak_efficiency)

                     peak_ts  peak_ts_plus  peak_ts_z
Name
Kareem Abdul-Jabbar    0.607       123.221      2.214
Magic Johnson          0.627       120.047      1.944
LeBron James           0.624       118.385      1.704
Michael Jordan         0.601       115.921      1.559
Larry Bird             0.589       112.526      1.247

In [124]:
import os
import pandas as pd

game_path = os.path.join(
    dataset_path,
    "csv",
    "game.csv"
)

print(game_path)
print(os.path.exists(game_path))

/root/.cache/kagglehub/datasets/wyattowalsh/basketball/versions/238/csv/game.csv
True

In [125]:
import pandas as pd

game_path = "/root/.cache/kagglehub/datasets/wyattowalsh/basketball/versions/238/csv/game.csv"

df_games = pd.read_csv(game_path)

print("Dimensions :", df_games.shape)
display(df_games.head())

Dimensions : (65698, 55)

,season_id,team_id_home,team_abbreviation_home,team_name_home,game_id,game_date,matchup_home,wl_home,min,fgm_home,...,reb_away,ast_away,stl_away,blk_away,tov_away,pf_away,pts_away,plus_minus_away,video_available_away,season_type
0,21946,1610610035,HUS,Toronto Huskies,24600001,1946-11-01 00:00:00,HUS vs. NYK,L,0,25.0,...,NaN,NaN,NaN,NaN,NaN,NaN,68.0,2,0,Regular Season
1,21946,1610610034,BOM,St. Louis Bombers,24600003,1946-11-02 00:00:00,BOM vs. PIT,W,0,20.0,...,NaN,NaN,NaN,NaN,NaN,25.0,51.0,-5,0,Regular Season
2,21946,1610610032,PRO,Providence Steamrollers,24600002,1946-11-02 00:00:00,PRO vs. BOS,W,0,21.0,...,NaN,NaN,NaN,NaN,NaN,NaN,53.0,-6,0,Regular Season
3,21946,1610610025,CHS,Chicago Stags,24600004,1946-11-02 00:00:00,CHS vs. NYK,W,0,21.0,...,NaN,NaN,NaN,NaN,NaN,22.0,47.0,-16,0,Regular Season
4,21946,1610610028,DEF,Detroit Falcons,24600005,1946-11-02 00:00:00,DEF vs. WAS,L,0,10.0,...,NaN,NaN,NaN,NaN,NaN,NaN,50.0,17,0,Regular Season

In [126]:
print("Types de matchs :")
print(df_games["season_type"].value_counts(dropna=False))

Types de matchs :
season_type
Regular Season    60192
Playoffs           3842
Pre Season         1536
All Star             65
All-Star             63
Name: count, dtype: int64

In [127]:
print("Nombre de saisons :", df_games["season_id"].nunique())

print("\nPremières saisons :")
print(sorted(df_games["season_id"].dropna().unique())[:10])

print("\nDernières saisons :")
print(sorted(df_games["season_id"].dropna().unique())[-10:])

Nombre de saisons : 225

Premières saisons :
[np.int64(12005), np.int64(12006), np.int64(12007), np.int64(12008), np.int64(12009), np.int64(12010), np.int64(12011), np.int64(12012), np.int64(12013), np.int64(12014)]

Dernières saisons :
[np.int64(42013), np.int64(42014), np.int64(42015), np.int64(42016), np.int64(42017), np.int64(42018), np.int64(42019), np.int64(42020), np.int64(42021), np.int64(42022)]

In [128]:
season_check = (
    df_games
    .groupby(["season_id", "season_type"])
    .size()
    .reset_index(name="games")
)

display(season_check.tail(30))

     season_id season_type  games
251      41988    Playoffs     62
252      41989    Playoffs     72
253      41990    Playoffs     68
254      41991    Playoffs     73
255      41992    Playoffs     76
256      41994    Playoffs     73
257      41996    Playoffs     72
258      41997    Playoffs     71
259      41998    Playoffs     66
260      42000    Playoffs     71
261      42002    Playoffs     88
262      42003    Playoffs     82
263      42004    Playoffs     84
264      42006    Playoffs     79
265      42007    Playoffs     86
266      42008    Playoffs     85
267      42009    Playoffs     82
268      42010    Playoffs     81
269      42011    Playoffs     84
270      42012    Playoffs     85
271      42013    Playoffs     89
272      42014    Playoffs     81
273      42015    Playoffs     86
274      42016    Playoffs     79
275      42017    Playoffs     82
276      42018    Playoffs     82
277      42019    Playoffs     83
278      42020    Playoffs     85
279      42021    Playoffs     87
280      42022    Playoffs     84

In [129]:
playoffs = df_games[
    df_games["season_type"] == "Playoffs"
].copy()

playoffs["game_date"] = pd.to_datetime(playoffs["game_date"])

In [130]:
last_playoff_games = (
    playoffs
    .sort_values("game_date")
    .groupby("season_id")
    .tail(1)
    .copy()
)

In [131]:
last_playoff_games["champion"] = last_playoff_games.apply(
    lambda row: row["team_abbreviation_home"]
    if row["wl_home"] == "W"
    else row["team_abbreviation_away"],
    axis=1
)

In [132]:
champions = last_playoff_games[
    [
        "season_id",
        "game_date",
        "team_abbreviation_home",
        "team_abbreviation_away",
        "wl_home",
        "wl_away",
        "champion"
    ]
].sort_values("season_id")

display(champions.tail(20))

,season_id,game_date,team_abbreviation_home,team_abbreviation_away,wl_home,wl_away,champion
39769,42002,2003-06-15,SAS,NJN,W,L,SAS
41042,42003,2004-06-15,DET,LAL,W,L,DET
42358,42004,2005-06-23,SAS,DET,W,L,SAS
45132,42006,2007-06-14,CLE,SAS,L,W,SAS
46556,42007,2008-06-17,BOS,LAL,W,L,BOS
47983,42008,2009-06-14,ORL,LAL,L,W,LAL
49415,42009,2010-06-17,LAL,BOS,W,L,LAL
50847,42010,2011-06-12,MIA,DAL,L,W,DAL
51953,42011,2012-06-21,MIA,OKC,W,L,MIA
52155,42012,2013-06-20,MIA,SAS,W,L,MIA
53591,42013,2014-06-15,SAS,MIA,W,L,SAS
55021,42014,2015-06-16,CLE,GSW,L,W,GSW
56448,42015,2016-06-19,GSW,CLE,L,W,CLE
57860,42016,2017-06-12,GSW,CLE,W,L,GSW
59252,42017,2018-06-08,CLE,GSW,L,W,GSW
60566,42018,2019-06-13,GSW,TOR,L,W,TOR
61710,42019,2020-10-11,MIA,LAL,L,W,LAL
62925,42020,2021-07-20,MIL,PHX,W,L,MIL
64310,42021,2022-06-16,BOS,GSW,L,W,GSW
65695,42022,2023-06-12,DEN,MIA,W,L,DEN

In [133]:
playoffs["season_end_year"] = (
    playoffs["season_id"]
    .astype(str)
    .str[-4:]
    .astype(int)
)

In [134]:
playoffs["SEASON_ID"] = (
    (playoffs["season_end_year"] - 1).astype(str)
    + "-"
    + playoffs["season_end_year"].astype(str).str[-2:]
)

In [135]:
display(
    playoffs[
        ["season_id", "season_end_year", "SEASON_ID"]
    ]
    .drop_duplicates()
    .sort_values("season_end_year")
    .tail(20)
)

       season_id  season_end_year SEASON_ID
39682      42002             2002   2001-02
40961      42003             2003   2002-03
42275      42004             2004   2003-04
45054      42006             2006   2005-06
46471      42007             2007   2006-07
47899      42008             2008   2007-08
49334      42009             2009   2008-09
50767      42010             2010   2009-10
51870      42011             2011   2010-11
52071      42012             2012   2011-12
53503      42013             2013   2012-13
54941      42014             2014   2013-14
56363      42015             2015   2014-15
57782      42016             2016   2015-16
59171      42017             2017   2016-17
60485      42018             2018   2017-18
61628      42019             2019   2018-19
62841      42020             2020   2019-20
64224      42021             2021   2020-21
65612      42022             2022   2021-22

In [136]:
last_playoff_games = (
    playoffs
    .sort_values("game_date")
    .groupby("SEASON_ID")
    .tail(1)
    .copy()
)

In [137]:
last_playoff_games["champion"] = last_playoff_games.apply(
    lambda row:
        row["team_abbreviation_home"]
        if row["wl_home"] == "W"
        else row["team_abbreviation_away"],
    axis=1
)

In [138]:
champions = (
    last_playoff_games[
        [
            "SEASON_ID",
            "game_date",
            "team_abbreviation_home",
            "team_abbreviation_away",
            "wl_home",
            "wl_away",
            "champion"
        ]
    ]
    .sort_values("SEASON_ID")
)

display(champions.tail(20))

,SEASON_ID,game_date,team_abbreviation_home,team_abbreviation_away,wl_home,wl_away,champion
39769,2001-02,2003-06-15,SAS,NJN,W,L,SAS
41042,2002-03,2004-06-15,DET,LAL,W,L,DET
42358,2003-04,2005-06-23,SAS,DET,W,L,SAS
45132,2005-06,2007-06-14,CLE,SAS,L,W,SAS
46556,2006-07,2008-06-17,BOS,LAL,W,L,BOS
47983,2007-08,2009-06-14,ORL,LAL,L,W,LAL
49415,2008-09,2010-06-17,LAL,BOS,W,L,LAL
50847,2009-10,2011-06-12,MIA,DAL,L,W,DAL
51953,2010-11,2012-06-21,MIA,OKC,W,L,MIA
52155,2011-12,2013-06-20,MIA,SAS,W,L,MIA
53591,2012-13,2014-06-15,SAS,MIA,W,L,SAS
55021,2013-14,2015-06-16,CLE,GSW,L,W,GSW
56448,2014-15,2016-06-19,GSW,CLE,L,W,CLE
57860,2015-16,2017-06-12,GSW,CLE,W,L,GSW
59252,2016-17,2018-06-08,CLE,GSW,L,W,GSW
60566,2017-18,2019-06-13,GSW,TOR,L,W,TOR
61710,2018-19,2020-10-11,MIA,LAL,L,W,LAL
62925,2019-20,2021-07-20,MIL,PHX,W,L,MIL
64310,2020-21,2022-06-16,BOS,GSW,L,W,GSW
65695,2021-22,2023-06-12,DEN,MIA,W,L,DEN

In [139]:
check_seasons = [
    "1990-91",
    "1995-96",
    "1999-00",
    "2011-12",
    "2015-16",
    "2019-20",
    "2021-22"
]

display(
    champions[
        champions["SEASON_ID"].isin(check_seasons)
    ]
)

,SEASON_ID,game_date,team_abbreviation_home,team_abbreviation_away,wl_home,wl_away,champion
26866,1990-91,1992-06-14,CHI,POR,W,L,CHI
32795,1995-96,1997-06-13,CHI,UTA,W,L,CHI
37300,1999-00,2001-06-15,PHI,LAL,L,W,LAL
52155,2011-12,2013-06-20,MIA,SAS,W,L,MIA
57860,2015-16,2017-06-12,GSW,CLE,W,L,GSW
62925,2019-20,2021-07-20,MIL,PHX,W,L,MIL
65695,2021-22,2023-06-12,DEN,MIA,W,L,DEN

In [140]:
playoffs = df_games[
    df_games["season_type"] == "Playoffs"
].copy()

playoffs["game_date"] = pd.to_datetime(playoffs["game_date"])

In [141]:
# Année pendant laquelle se terminent les playoffs
playoffs["final_year"] = playoffs["game_date"].dt.year

# Saison NBA = année précédente + année de la finale
playoffs["SEASON_ID"] = (
    (playoffs["final_year"] - 1).astype(str)
    + "-"
    + playoffs["final_year"].astype(str).str[-2:]
)

In [142]:
last_playoff_games = (
    playoffs
    .sort_values("game_date")
    .groupby("SEASON_ID")
    .tail(1)
    .copy()
)

last_playoff_games["champion"] = last_playoff_games.apply(
    lambda row:
        row["team_abbreviation_home"]
        if row["wl_home"] == "W"
        else row["team_abbreviation_away"],
    axis=1
)

In [143]:
champions = (
    last_playoff_games[
        [
            "SEASON_ID",
            "game_date",
            "team_abbreviation_home",
            "team_abbreviation_away",
            "wl_home",
            "wl_away",
            "champion"
        ]
    ]
    .sort_values("SEASON_ID")
)

In [144]:
check_seasons = [
    "1990-91",
    "1995-96",
    "1999-00",
    "2011-12",
    "2015-16",
    "2019-20",
    "2021-22"
]

display(
    champions[
        champions["SEASON_ID"].isin(check_seasons)
    ]
)

,SEASON_ID,game_date,team_abbreviation_home,team_abbreviation_away,wl_home,wl_away,champion
25684,1990-91,1991-06-12,LAL,CHI,L,W,CHI
51953,2011-12,2012-06-21,MIA,OKC,W,L,MIA
56448,2015-16,2016-06-19,GSW,CLE,L,W,CLE
61710,2019-20,2020-10-11,MIA,LAL,L,W,LAL
64310,2021-22,2022-06-16,BOS,GSW,L,W,GSW

In [145]:
champions_clean = champions[
    ["SEASON_ID", "champion"]
].copy()

champions_clean = champions_clean.rename(
    columns={"champion": "CHAMPION_TEAM"}
)

display(champions_clean.tail(20))

      SEASON_ID CHAMPION_TEAM
39769   2002-03           SAS
41042   2003-04           DET
42358   2004-05           SAS
45132   2006-07           SAS
46556   2007-08           BOS
47983   2008-09           LAL
49415   2009-10           LAL
50847   2010-11           DAL
51953   2011-12           MIA
52155   2012-13           MIA
53591   2013-14           SAS
55021   2014-15           GSW
56448   2015-16           CLE
57860   2016-17           GSW
59252   2017-18           GSW
60566   2018-19           TOR
61710   2019-20           LAL
62925   2020-21           MIL
64310   2021-22           GSW
65695   2022-23           DEN

In [146]:
df_goat_titles = df_goat.merge(
    champions_clean,
    on="SEASON_ID",
    how="left"
)

In [147]:
df_goat_titles["CHAMPIONSHIP"] = (
    df_goat_titles["TEAM_ABBREVIATION"]
    == df_goat_titles["CHAMPION_TEAM"]
).astype(int)

In [148]:
goat_titles_check = df_goat_titles[
    df_goat_titles["Name"].isin(goat_players)
][
    [
        "Name",
        "SEASON_ID",
        "TEAM_ABBREVIATION",
        "CHAMPION_TEAM",
        "CHAMPIONSHIP"
    ]
]

display(
    goat_titles_check[
        goat_titles_check["CHAMPIONSHIP"] == 1
    ].sort_values(["Name", "SEASON_ID"])
)

,Name,SEASON_ID,TEAM_ABBREVIATION,CHAMPION_TEAM,CHAMPIONSHIP
24,Kareem Abdul-Jabbar,1970-71,MIL,MIL,1
33,Kareem Abdul-Jabbar,1979-80,LAL,LAL,1
35,Kareem Abdul-Jabbar,1981-82,LAL,LAL,1
38,Kareem Abdul-Jabbar,1984-85,LAL,LAL,1
40,Kareem Abdul-Jabbar,1986-87,LAL,LAL,1
41,Kareem Abdul-Jabbar,1987-88,LAL,LAL,1
2305,Larry Bird,1980-81,BOS,BOS,1
2308,Larry Bird,1983-84,BOS,BOS,1
2310,Larry Bird,1985-86,BOS,BOS,1
13158,LeBron James,2011-12,MIA,MIA,1
13159,LeBron James,2012-13,MIA,MIA,1
13162,LeBron James,2015-16,CLE,CLE,1
13166,LeBron James,2019-20,LAL,LAL,1
13773,Magic Johnson,1979-80,LAL,LAL,1
13775,Magic Johnson,1981-82,LAL,LAL,1
13778,Magic Johnson,1984-85,LAL,LAL,1
13780,Magic Johnson,1986-87,LAL,LAL,1
13781,Magic Johnson,1987-88,LAL,LAL,1
14335,Michael Jordan,1990-91,CHI,CHI,1
14336,Michael Jordan,1991-92,CHI,CHI,1
14337,Michael Jordan,1992-93,CHI,CHI,1
14340,Michael Jordan,1996-97,CHI,CHI,1
14341,Michael Jordan,1997-98,CHI,CHI,1

In [149]:
championship_summary = (
    goat_titles_check
    .groupby("Name")
    .agg(
        championships=("CHAMPIONSHIP", "sum")
    )
    .sort_values("championships", ascending=False)
)

display(championship_summary)

                     championships
Name
Kareem Abdul-Jabbar              6
Michael Jordan                   5
Magic Johnson                    5
LeBron James                     4
Larry Bird                       3

In [150]:
jordan_titles_check = goat_titles_check[
    goat_titles_check["Name"] == "Michael Jordan"
].sort_values("SEASON_ID")

display(jordan_titles_check)

                 Name SEASON_ID TEAM_ABBREVIATION CHAMPION_TEAM  CHAMPIONSHIP
14329  Michael Jordan   1984-85               CHI           LAL             0
14330  Michael Jordan   1985-86               CHI           BOS             0
14331  Michael Jordan   1986-87               CHI           LAL             0
14332  Michael Jordan   1987-88               CHI           LAL             0
14333  Michael Jordan   1988-89               CHI           DET             0
14334  Michael Jordan   1989-90               CHI           DET             0
14335  Michael Jordan   1990-91               CHI           CHI             1
14336  Michael Jordan   1991-92               CHI           CHI             1
14337  Michael Jordan   1992-93               CHI           CHI             1
14338  Michael Jordan   1994-95               CHI           HOU             0
14339  Michael Jordan   1995-96               CHI           NaN             0
14340  Michael Jordan   1996-97               CHI           CHI             1
14341  Michael Jordan   1997-98               CHI           CHI             1
14342  Michael Jordan   2001-02               WAS           NaN             0
14343  Michael Jordan   2002-03               WAS           SAS             0

In [151]:
jordan_championship_seasons = [
    "1990-91",
    "1991-92",
    "1992-93",
    "1995-96",
    "1996-97",
    "1997-98"
]

display(
    jordan_titles_check[
        jordan_titles_check["SEASON_ID"].isin(
            jordan_championship_seasons
        )
    ]
)

                 Name SEASON_ID TEAM_ABBREVIATION CHAMPION_TEAM  CHAMPIONSHIP
14335  Michael Jordan   1990-91               CHI           CHI             1
14336  Michael Jordan   1991-92               CHI           CHI             1
14337  Michael Jordan   1992-93               CHI           CHI             1
14339  Michael Jordan   1995-96               CHI           NaN             0
14340  Michael Jordan   1996-97               CHI           CHI             1
14341  Michael Jordan   1997-98               CHI           CHI             1

In [152]:
display(
    champions[
        champions["SEASON_ID"].isin(
            jordan_championship_seasons
        )
    ].sort_values("SEASON_ID")
)

,SEASON_ID,game_date,team_abbreviation_home,team_abbreviation_away,wl_home,wl_away,champion
25684,1990-91,1991-06-12,LAL,CHI,L,W,CHI
26866,1991-92,1992-06-14,CHI,POR,W,L,CHI
28051,1992-93,1993-06-20,PHX,CHI,L,W,CHI
32795,1996-97,1997-06-13,CHI,UTA,W,L,CHI
34057,1997-98,1998-06-14,UTA,CHI,L,W,CHI

In [153]:
playoffs_1996 = df_games[
    (df_games["season_type"] == "Playoffs") &
    (pd.to_datetime(df_games["game_date"]).dt.year == 1996)
].copy()

playoffs_1996["game_date"] = pd.to_datetime(
    playoffs_1996["game_date"]
)

print("Nombre de matchs :", len(playoffs_1996))

display(
    playoffs_1996[
        [
            "season_id",
            "game_date",
            "team_abbreviation_home",
            "team_abbreviation_away",
            "wl_home",
            "wl_away"
        ]
    ]
    .sort_values("game_date")
    .tail(15)
)

Nombre de matchs : 0

Empty DataFrame
Columns: [season_id, game_date, team_abbreviation_home, team_abbreviation_away, wl_home, wl_away]
Index: []

In [154]:
jordan_championships = 6

In [155]:
available_playoff_seasons = sorted(
    playoffs["SEASON_ID"]
    .dropna()
    .unique()
)

print("Nombre de saisons avec playoffs :", len(available_playoff_seasons))
print(available_playoff_seasons)

Nombre de saisons avec playoffs : 67
['1946-47', '1947-48', '1948-49', '1949-50', '1950-51', '1951-52', '1952-53', '1953-54', '1954-55', '1955-56', '1956-57', '1959-60', '1961-62', '1962-63', '1963-64', '1965-66', '1966-67', '1967-68', '1969-70', '1970-71', '1971-72', '1972-73', '1973-74', '1974-75', '1975-76', '1976-77', '1977-78', '1978-79', '1979-80', '1980-81', '1981-82', '1982-83', '1983-84', '1984-85', '1985-86', '1986-87', '1987-88', '1988-89', '1989-90', '1990-91', '1991-92', '1992-93', '1994-95', '1996-97', '1997-98', '1998-99', '2000-01', '2002-03', '2003-04', '2004-05', '2006-07', '2007-08', '2008-09', '2009-10', '2010-11', '2011-12', '2012-13', '2013-14', '2014-15', '2015-16', '2016-17', '2017-18', '2018-19', '2019-20', '2020-21', '2021-22', '2022-23']

In [156]:
expected_seasons = [
    f"{year}-{str(year + 1)[-2:]}"
    for year in range(1946, 2023)
]

missing_playoff_seasons = [
    season
    for season in expected_seasons
    if season not in available_playoff_seasons
]

print(
    "Nombre de saisons manquantes :",
    len(missing_playoff_seasons)
)

print(missing_playoff_seasons)

Nombre de saisons manquantes : 10
['1957-58', '1958-59', '1960-61', '1964-65', '1968-69', '1993-94', '1995-96', '1999-00', '2001-02', '2005-06']

In [157]:
available_playoff_seasons = sorted(
    playoffs["SEASON_ID"]
    .dropna()
    .unique()
)

print("Nombre de saisons avec playoffs :", len(available_playoff_seasons))
print("Première saison :", available_playoff_seasons[0])
print("Dernière saison :", available_playoff_seasons[-1])

Nombre de saisons avec playoffs : 67
Première saison : 1946-47
Dernière saison : 2022-23

In [158]:
expected_seasons = [
    f"{year}-{str(year + 1)[-2:]}"
    for year in range(1946, 2023)
]

missing_playoff_seasons = [
    season
    for season in expected_seasons
    if season not in available_playoff_seasons
]

print("Nombre de saisons théoriques :", len(expected_seasons))
print("Nombre de saisons disponibles :", len(available_playoff_seasons))
print("Nombre de saisons manquantes :", len(missing_playoff_seasons))

print("\nSaisons manquantes :")
print(missing_playoff_seasons)

Nombre de saisons théoriques : 77
Nombre de saisons disponibles : 67
Nombre de saisons manquantes : 10

Saisons manquantes :
['1957-58', '1958-59', '1960-61', '1964-65', '1968-69', '1993-94', '1995-96', '1999-00', '2001-02', '2005-06']

In [159]:
coverage_rate = (
    len(available_playoff_seasons)
    / len(expected_seasons)
    * 100
)

print(f"Couverture des playoffs : {coverage_rate:.1f} %")

Couverture des playoffs : 87.0 %

In [160]:
print("Saisons manquantes :")
for season in missing_playoff_seasons:
    print(season)

Saisons manquantes :
1957-58
1958-59
1960-61
1964-65
1968-69
1993-94
1995-96
1999-00
2001-02
2005-06

In [161]:
playoff_quality = pd.DataFrame({
    "metric": [
        "Expected seasons",
        "Available seasons",
        "Missing seasons",
        "Coverage rate"
    ],
    "value": [
        len(expected_seasons),
        len(available_playoff_seasons),
        len(missing_playoff_seasons),
        f"{coverage_rate:.1f}%"
    ]
})

display(playoff_quality)

              metric  value
0   Expected seasons     77
1  Available seasons     67
2    Missing seasons     10
3      Coverage rate  87.0%

In [162]:
missing_champions = pd.DataFrame({
    "SEASON_ID": [
        "1957-58",
        "1958-59",
        "1960-61",
        "1964-65",
        "1968-69",
        "1993-94",
        "1995-96",
        "1999-00",
        "2001-02",
        "2005-06"
    ],

    "champion": [
        "STL",
        "BOS",
        "BOS",
        "BOS",
        "BOS",
        "HOU",
        "CHI",
        "LAL",
        "LAL",
        "MIA"
    ],

    "source": "historical_reference"
})

display(missing_champions)

  SEASON_ID champion                source
0   1957-58      STL  historical_reference
1   1958-59      BOS  historical_reference
2   1960-61      BOS  historical_reference
3   1964-65      BOS  historical_reference
4   1968-69      BOS  historical_reference
5   1993-94      HOU  historical_reference
6   1995-96      CHI  historical_reference
7   1999-00      LAL  historical_reference
8   2001-02      LAL  historical_reference
9   2005-06      MIA  historical_reference

In [163]:
champions_kaggle = champions[
    ["SEASON_ID", "champion"]
].copy()

champions_kaggle["source"] = "kaggle_game"

In [164]:
champions_complete = pd.concat(
    [
        champions_kaggle,
        missing_champions
    ],
    ignore_index=True
)

In [165]:
print(
    "Nombre de saisons :",
    champions_complete["SEASON_ID"].nunique()
)

print(
    "Doublons :",
    champions_complete["SEASON_ID"].duplicated().sum()
)

display(
    champions_complete.sort_values("SEASON_ID").tail(20)
)

Nombre de saisons : 77
Doublons : 0

   SEASON_ID champion                source
48   2003-04      DET           kaggle_game
49   2004-05      SAS           kaggle_game
76   2005-06      MIA  historical_reference
50   2006-07      SAS           kaggle_game
51   2007-08      BOS           kaggle_game
52   2008-09      LAL           kaggle_game
53   2009-10      LAL           kaggle_game
54   2010-11      DAL           kaggle_game
55   2011-12      MIA           kaggle_game
56   2012-13      MIA           kaggle_game
57   2013-14      SAS           kaggle_game
58   2014-15      GSW           kaggle_game
59   2015-16      CLE           kaggle_game
60   2016-17      GSW           kaggle_game
61   2017-18      GSW           kaggle_game
62   2018-19      TOR           kaggle_game
63   2019-20      LAL           kaggle_game
64   2020-21      MIL           kaggle_game
65   2021-22      GSW           kaggle_game
66   2022-23      DEN           kaggle_game

In [166]:
remaining_missing = [
    season
    for season in expected_seasons
    if season not in champions_complete["SEASON_ID"].values
]

print("Saisons encore manquantes :", remaining_missing)

Saisons encore manquantes : []

In [167]:
df_player_season_titles = df_player_season.merge(
    champions_complete.rename(
        columns={
            "champion": "CHAMPION_TEAM",
            "source": "CHAMPION_SOURCE"
        }
    ),
    on="SEASON_ID",
    how="left"
)

In [168]:
df_player_season_titles["CHAMPIONSHIP"] = (
    df_player_season_titles["TEAM_ABBREVIATION"]
    ==
    df_player_season_titles["CHAMPION_TEAM"]
).astype(int)

In [169]:
championship_summary = (
    df_player_season_titles[
        df_player_season_titles["Name"].isin(goat_players)
    ]
    .groupby("Name")
    .agg(
        championships=("CHAMPIONSHIP", "sum")
    )
    .sort_values(
        "championships",
        ascending=False
    )
)

display(championship_summary)

                     championships
Name
Kareem Abdul-Jabbar              6
Michael Jordan                   6
Magic Johnson                    5
LeBron James                     4
Larry Bird                       3

In [170]:
print(df_goat.columns.tolist())

['PLAYER_ID', 'Name', 'SEASON_ID', 'TEAM_ID', 'TEAM_ABBREVIATION', 'PLAYER_AGE', 'GP', 'GS', 'MIN', 'FGM', 'FGA', 'FG_PCT', 'FG3M', 'FG3A', 'FG3_PCT', 'FTM', 'FTA', 'FT_PCT', 'OREB', 'DREB', 'REB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS']

In [171]:
possible_playoff_cols = [
    col for col in df_goat.columns
    if any(
        keyword in col.lower()
        for keyword in [
            "season_type",
            "playoff",
            "postseason",
            "season type"
        ]
    )
]

print("Colonnes potentielles :", possible_playoff_cols)

Colonnes potentielles : []

In [172]:
possible_playoff_cols

[]

In [173]:
import kagglehub

playoffs_path = kagglehub.dataset_download(
    "sumitrodatta/nba-aba-baa-stats"
)

print("Chemin :", playoffs_path)

Downloading to /root/.cache/kagglehub/datasets/sumitrodatta/nba-aba-baa-stats/56.archive...

100%|██████████| 10.6M/10.6M [00:00<00:00, 204MB/s]

Extracting files...

Chemin : /root/.cache/kagglehub/datasets/sumitrodatta/nba-aba-baa-stats/versions/56

In [174]:
import os

for root, dirs, files in os.walk(playoffs_path):
    for file in files:
        full_path = os.path.join(root, file)
        size_mb = os.path.getsize(full_path) / 1024**2

        print(f"{file:<50} {size_mb:.2f} MB")

Team Stats Per 100 Poss.csv                        0.21 MB
End of Season Teams (Voting).csv                   0.31 MB
Team Abbrev.csv                                    0.06 MB
End of Season Teams.csv                            0.10 MB
Opponent Stats Per 100 Poss.csv                    0.21 MB
Per 100 Poss.csv                                   4.03 MB
Per 36 Minutes.csv                                 4.38 MB
Player Award Shares.csv                            0.20 MB
Advanced.csv                                       4.41 MB
Team Stats Per Game.csv                            0.26 MB
Opponent Totals.csv                                0.26 MB
Player Per Game.csv                                4.47 MB
Player Shooting.csv                                2.73 MB
All-Star Selections.csv                            0.09 MB
Opponent Stats Per Game.csv                        0.26 MB
Team Summaries.csv                                 0.32 MB
Player Play By Play.csv                            1.69 MB
Player Career Info.csv                             0.49 MB
Team Totals.csv                                    0.27 MB
Player Totals.csv                                  4.28 MB
Player Season Info.csv                             1.41 MB
Draft Pick History.csv                             0.43 MB

In [175]:
import os
import pandas as pd

season_info_path = os.path.join(
    playoffs_path,
    "Player Season Info.csv"
)

df_season_info = pd.read_csv(season_info_path)

print("Dimensions :", df_season_info.shape)
print("\nColonnes :")
print(df_season_info.columns.tolist())

display(df_season_info.head())

Dimensions : (33339, 8)

Colonnes :
['season', 'lg', 'player', 'player_id', 'age', 'team', 'pos', 'experience']

   season   lg              player  player_id   age team  pos  experience
0    1947  BAA      John Abramovic  abramjo01  27.0  PIT  NaN           1
1    1947  BAA       Chet Aubuchon  aubucch01  30.0  DTF  NaN           1
2    1947  BAA          Norm Baker  bakerno01  23.0  CHS  NaN           1
3    1947  BAA  Herschel Baltimore  baltihe01  25.0  STB  NaN           1
4    1947  BAA           John Barr   barrjo01  28.0  STB  NaN           1

In [176]:
per_game_path = os.path.join(
    playoffs_path,
    "Player Per Game.csv"
)

df_per_game = pd.read_csv(per_game_path)

print("Dimensions :", df_per_game.shape)
print("\nColonnes :")
print(df_per_game.columns.tolist())

display(df_per_game.head())

Dimensions : (33339, 32)

Colonnes :
['season', 'lg', 'player', 'player_id', 'age', 'team', 'pos', 'g', 'gs', 'mp_per_game', 'fg_per_game', 'fga_per_game', 'fg_percent', 'x3p_per_game', 'x3pa_per_game', 'x3p_percent', 'x2p_per_game', 'x2pa_per_game', 'x2p_percent', 'e_fg_percent', 'ft_per_game', 'fta_per_game', 'ft_percent', 'orb_per_game', 'drb_per_game', 'trb_per_game', 'ast_per_game', 'stl_per_game', 'blk_per_game', 'tov_per_game', 'pf_per_game', 'pts_per_game']

,season,lg,player,player_id,age,team,pos,g,gs,mp_per_game,...,ft_percent,orb_per_game,drb_per_game,trb_per_game,ast_per_game,stl_per_game,blk_per_game,tov_per_game,pf_per_game,pts_per_game
0,2026,NBA,Precious Achiuwa,achiupr01,26.0,SAC,C,73,57.0,23.9,...,0.554,2.4,4.3,6.7,1.4,0.9,0.7,0.9,1.7,10.1
1,2026,NBA,Steven Adams,adamsst01,32.0,HOU,C,32,11.0,22.8,...,0.580,4.5,4.1,8.6,1.5,0.7,0.6,1.1,1.7,5.8
2,2026,NBA,Bam Adebayo,adebaba01,28.0,MIA,C,73,73.0,32.4,...,0.778,2.0,8.0,10.0,3.2,1.2,0.7,1.6,1.7,20.1
3,2026,NBA,Ochai Agbaji,agbajoc01,25.0,2TM,SG,62,13.0,15.7,...,0.837,0.7,1.5,2.3,0.8,0.4,0.3,0.5,1.5,5.1
4,2026,NBA,Ochai Agbaji,agbajoc01,25.0,TOR,SG,42,13.0,15.5,...,0.862,0.8,1.5,2.3,0.7,0.4,0.3,0.5,1.8,4.3

In [177]:
for name, df in {
    "Player Season Info": df_season_info,
    "Player Per Game": df_per_game
}.items():

    print("\n", name)

    print([
        col for col in df.columns
        if any(
            keyword in col.lower()
            for keyword in [
                "playoff",
                "post",
                "season_type",
                "type"
            ]
        )
    ])

 Player Season Info
[]

 Player Per Game
[]

In [178]:
awards_path = os.path.join(
    playoffs_path,
    "Player Award Shares.csv"
)

df_awards = pd.read_csv(awards_path)

print("Dimensions :", df_awards.shape)

print("\nColonnes :")
print(df_awards.columns.tolist())

display(df_awards.head(10))

Dimensions : (3465, 10)

Colonnes :
['season', 'award', 'player', 'player_id', 'age', 'first', 'pts_won', 'pts_max', 'share', 'winner']

,season,award,player,player_id,age,first,pts_won,pts_max,share,winner
0,2025,nba clutch_poy,Jalen Brunson,brunsja01,28,70.0,426.0,500.0,0.852,True
1,2025,nba clutch_poy,Nikola Jokić,jokicni01,29,26.0,312.0,500.0,0.624,False
2,2025,nba clutch_poy,Anthony Edwards,edwaran01,23,2.0,47.0,500.0,0.094,False
3,2025,nba clutch_poy,Trae Young,youngtr01,26,0.0,44.0,500.0,0.088,False
4,2025,nba clutch_poy,Stephen Curry,curryst01,36,1.0,27.0,500.0,0.054,False
5,2025,nba clutch_poy,Darius Garland,garlada01,25,0.0,16.0,500.0,0.032,False
6,2025,nba clutch_poy,LeBron James,jamesle01,40,1.0,14.0,500.0,0.028,False
7,2025,nba clutch_poy,Shai Gilgeous-Alexander,gilgesh01,26,0.0,8.0,500.0,0.016,False
8,2025,nba clutch_poy,Donovan Mitchell,mitchdo01,28,0.0,3.0,500.0,0.006,False
9,2025,nba clutch_poy,Kyrie Irving,irvinky01,32,0.0,1.0,500.0,0.002,False

In [179]:
print("Récompenses disponibles :")

print(
    df_awards["award"]
    .value_counts(dropna=False)
)

Récompenses disponibles :
award
nba mvp           1057
nba mip            836
nba dpoy           601
nba smoy           488
nba roy            339
aba mvp             79
nba clutch_poy      41
aba roy             22
baa roy              2
Name: count, dtype: int64

In [180]:
goat_awards = df_awards[
    df_awards["player"].isin([
        "Michael Jordan",
        "LeBron James",
        "Kareem Abdul-Jabbar",
        "Magic Johnson",
        "Larry Bird"
    ])
].copy()

display(goat_awards)

,season,award,player,player_id,age,first,pts_won,pts_max,share,winner
6,2025,nba clutch_poy,LeBron James,jamesle01,40,1.0,14.0,500.0,0.028,False
44,2025,nba mvp,LeBron James,jamesle01,40,0.0,16.0,1000.0,0.016,False
76,2024,nba clutch_poy,LeBron James,jamesle01,39,0.0,3.0,495.0,0.006,False
238,2022,nba mvp,LeBron James,jamesle01,37,0.0,1.0,1000.0,0.001,False
308,2021,nba mvp,LeBron James,jamesle01,36,0.0,1.0,1010.0,0.001,False
...,...,...,...,...,...,...,...,...,...,...
3128,1973,nba mvp,Kareem Abdul-Jabbar,abdulka01,25,33.0,339.0,875.0,0.387,False
3160,1972,nba mvp,Kareem Abdul-Jabbar,abdulka01,24,81.0,581.0,900.0,0.646,True
3211,1971,nba mvp,Kareem Abdul-Jabbar,abdulka01,23,133.0,698.0,780.0,0.895,True
3248,1970,nba mvp,Kareem Abdul-Jabbar,abdulka01,22,30.0,335.0,775.0,0.432,False
3265,1970,nba roy,Kareem Abdul-Jabbar,abdulka01,22,78.0,78.0,78.0,1.000,True

In [181]:
teams_path = os.path.join(
    playoffs_path,
    "End of Season Teams.csv"
)

df_eos_teams = pd.read_csv(teams_path)

print("Dimensions :", df_eos_teams.shape)

print("\nColonnes :")
print(df_eos_teams.columns.tolist())

display(df_eos_teams.head(10))

Dimensions : (2222, 7)

Colonnes :
['season', 'lg', 'type', 'number_tm', 'player', 'player_id', 'position']

   season   lg         type number_tm             player  player_id position
0    2025  NBA  All-Defense       1st      Dyson Daniels  daniedy01      NaN
1    2025  NBA  All-Defense       1st      Luguentz Dort   dortlu01      NaN
2    2025  NBA  All-Defense       1st     Draymond Green  greendr01      NaN
3    2025  NBA  All-Defense       1st        Evan Mobley  mobleev01      NaN
4    2025  NBA  All-Defense       1st      Amen Thompson  thompam01      NaN
5    2025  NBA  All-Defense       2nd     Toumani Camara  camarto01      NaN
6    2025  NBA  All-Defense       2nd        Rudy Gobert  goberru01      NaN
7    2025  NBA  All-Defense       2nd  Jaren Jackson Jr.  jacksja02      NaN
8    2025  NBA  All-Defense       2nd     Jalen Williams  willija06      NaN
9    2025  NBA  All-Defense       2nd        Ivica Zubac  zubaciv01      NaN

In [182]:
df_mvp = df_awards[
    df_awards["award"].str.lower() == "nba mvp"
].copy()

print("Dimensions MVP :", df_mvp.shape)
print("\nColonnes :")
print(df_mvp.columns.tolist())

display(df_mvp.head(10))

Dimensions MVP : (1057, 10)

Colonnes :
['season', 'award', 'player', 'player_id', 'age', 'first', 'pts_won', 'pts_max', 'share', 'winner']

,season,award,player,player_id,age,first,pts_won,pts_max,share,winner
39,2025,nba mvp,Shai Gilgeous-Alexander,gilgesh01,26,71.0,913.0,1000.0,0.913,True
40,2025,nba mvp,Nikola Jokić,jokicni01,29,29.0,787.0,1000.0,0.787,False
41,2025,nba mvp,Giannis Antetokounmpo,antetgi01,30,0.0,470.0,1000.0,0.470,False
42,2025,nba mvp,Jayson Tatum,tatumja01,26,0.0,311.0,1000.0,0.311,False
43,2025,nba mvp,Donovan Mitchell,mitchdo01,28,0.0,74.0,1000.0,0.074,False
44,2025,nba mvp,LeBron James,jamesle01,40,0.0,16.0,1000.0,0.016,False
45,2025,nba mvp,Cade Cunningham,cunnica01,23,0.0,12.0,1000.0,0.012,False
46,2025,nba mvp,Anthony Edwards,edwaran01,23,0.0,12.0,1000.0,0.012,False
47,2025,nba mvp,Stephen Curry,curryst01,36,0.0,2.0,1000.0,0.002,False
48,2025,nba mvp,Jalen Brunson,brunsja01,28,0.0,1.0,1000.0,0.001,False

In [183]:
df_mvp.info()

display(
    df_mvp.isna()
    .sum()
    .sort_values(ascending=False)
)

<class 'pandas.core.frame.DataFrame'>
Index: 1057 entries, 39 to 3454
Data columns (total 10 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   season     1057 non-null   int64
 1   award      1057 non-null   object
 2   player     1057 non-null   object
 3   player_id  1057 non-null   object
 4   age        1057 non-null   int64
 5   first      1057 non-null   float64
 6   pts_won    1057 non-null   float64
 7   pts_max    1057 non-null   float64
 8   share      1057 non-null   float64
 9   winner     1057 non-null   bool
dtypes: bool(1), float64(4), int64(2), object(3)
memory usage: 83.6+ KB

season       0
award        0
player       0
player_id    0
age          0
first        0
pts_won      0
pts_max      0
share        0
winner       0
dtype: int64

In [184]:
goat_names = [
    "Michael Jordan",
    "LeBron James",
    "Kareem Abdul-Jabbar",
    "Magic Johnson",
    "Larry Bird"
]

goat_mvp = df_mvp[
    df_mvp["player"].isin(goat_names)
].copy()

display(goat_mvp)

,season,award,player,player_id,age,first,pts_won,pts_max,share,winner
44,2025,nba mvp,LeBron James,jamesle01,40,0.0,16.0,1000.0,0.016,False
238,2022,nba mvp,LeBron James,jamesle01,37,0.0,1.0,1000.0,0.001,False
308,2021,nba mvp,LeBron James,jamesle01,36,0.0,1.0,1010.0,0.001,False
357,2020,nba mvp,LeBron James,jamesle01,35,16.0,753.0,1010.0,0.746,False
428,2019,nba mvp,LeBron James,jamesle01,34,0.0,1.0,1010.0,0.001,False
...,...,...,...,...,...,...,...,...,...,...
3091,1974,nba mvp,Kareem Abdul-Jabbar,abdulka01,26,74.0,528.0,905.0,0.583,True
3128,1973,nba mvp,Kareem Abdul-Jabbar,abdulka01,25,33.0,339.0,875.0,0.387,False
3160,1972,nba mvp,Kareem Abdul-Jabbar,abdulka01,24,81.0,581.0,900.0,0.646,True
3211,1971,nba mvp,Kareem Abdul-Jabbar,abdulka01,23,133.0,698.0,780.0,0.895,True
3248,1970,nba mvp,Kareem Abdul-Jabbar,abdulka01,22,30.0,335.0,775.0,0.432,False

In [185]:
df_mvp.columns.tolist()

['season',
 'award',
 'player',
 'player_id',
 'age',
 'first',
 'pts_won',
 'pts_max',
 'share',
 'winner']

In [186]:
goat_names = [
    "Michael Jordan",
    "LeBron James",
    "Kareem Abdul-Jabbar",
    "Magic Johnson",
    "Larry Bird"
]

goat_mvp = df_mvp[
    df_mvp["player"].isin(goat_names)
].copy()

display(
    goat_mvp[
        [
            "season",
            "player",
            "age",
            "first",
            "pts_won",
            "pts_max",
            "share",
            "winner"
        ]
    ]
    .sort_values(
        ["player", "season"]
    )
)

      season               player  age  first  pts_won  pts_max  share  winner
3248    1970  Kareem Abdul-Jabbar   22   30.0    335.0    775.0  0.432   False
3211    1971  Kareem Abdul-Jabbar   23  133.0    698.0    780.0  0.895    True
3160    1972  Kareem Abdul-Jabbar   24   81.0    581.0    900.0  0.646    True
3128    1973  Kareem Abdul-Jabbar   25   33.0    339.0    875.0  0.387   False
3091    1974  Kareem Abdul-Jabbar   26   74.0    528.0    905.0  0.583    True
...      ...                  ...  ...    ...      ...      ...    ...     ...
2323    1995       Michael Jordan   31    0.0     12.0   1050.0  0.011   False
2256    1996       Michael Jordan   32  109.0   1114.0   1130.0  0.986    True
2193    1997       Michael Jordan   33   52.0    957.0   1150.0  0.832   False
2139    1998       Michael Jordan   34   92.0   1084.0   1160.0  0.934    True
1910    2002       Michael Jordan   38    0.0     16.0   1260.0  0.013   False

[74 rows x 8 columns]

In [187]:
print(df_mvp["winner"].value_counts(dropna=False))
print(df_mvp["winner"].dtype)

winner
False    987
True      70
Name: count, dtype: int64
bool

In [188]:
mvp_wins = (
    goat_mvp
    .groupby("player")
    .agg(
        mvp_wins=("winner", "sum")
    )
    .sort_values(
        "mvp_wins",
        ascending=False
    )
)

display(mvp_wins)

                     mvp_wins
player
Kareem Abdul-Jabbar         6
Michael Jordan              5
LeBron James                4
Larry Bird                  3
Magic Johnson               3

In [189]:
mvp_summary = (
    goat_mvp
    .groupby("player")
    .agg(
        mvp_wins=("winner", "sum"),
        mvp_total_share=("share", "sum"),
        mvp_best_share=("share", "max"),
        mvp_seasons=("season", "nunique")
    )
    .round(3)
    .sort_values(
        "mvp_total_share",
        ascending=False
    )
)

display(mvp_summary)

                     mvp_wins  mvp_total_share  mvp_best_share  mvp_seasons
player
LeBron James                4            8.834           0.998           20
Michael Jordan              5            8.115           0.986           13
Kareem Abdul-Jabbar         6            6.104           0.895           17
Larry Bird                  3            5.611           0.981           12
Magic Johnson               3            5.104           0.940           12

In [190]:
df_mvp["mvp_rank"] = (
    df_mvp
    .groupby("season")["share"]
    .rank(
        method="min",
        ascending=False
    )
)

In [191]:
goat_mvp = df_mvp[
    df_mvp["player"].isin(goat_names)
].copy()

In [192]:
display(
    goat_mvp[
        [
            "season",
            "player",
            "share",
            "mvp_rank",
            "winner"
        ]
    ]
    .sort_values(
        ["player", "season"]
    )
)

      season               player  share  mvp_rank  winner
3248    1970  Kareem Abdul-Jabbar  0.432       3.0   False
3211    1971  Kareem Abdul-Jabbar  0.895       1.0    True
3160    1972  Kareem Abdul-Jabbar  0.646       1.0    True
3128    1973  Kareem Abdul-Jabbar  0.387       2.0   False
3091    1974  Kareem Abdul-Jabbar  0.583       1.0    True
...      ...                  ...    ...       ...     ...
2323    1995       Michael Jordan  0.011      11.0   False
2256    1996       Michael Jordan  0.986       1.0    True
2193    1997       Michael Jordan  0.832       2.0   False
2139    1998       Michael Jordan  0.934       1.0    True
1910    2002       Michael Jordan  0.013      12.0   False

[74 rows x 5 columns]

In [193]:
goat_mvp["MVP_TOP3"] = (
    goat_mvp["mvp_rank"] <= 3
).astype(int)

goat_mvp["MVP_TOP5"] = (
    goat_mvp["mvp_rank"] <= 5
).astype(int)

In [194]:
mvp_complete = (
    goat_mvp
    .groupby("player")
    .agg(
        mvp_wins=("winner", "sum"),
        mvp_top3=("MVP_TOP3", "sum"),
        mvp_top5=("MVP_TOP5", "sum"),
        total_mvp_share=("share", "sum"),
        best_mvp_share=("share", "max"),
        first_place_votes=("first", "sum")
    )
    .round(3)
    .sort_values(
        ["mvp_wins", "total_mvp_share"],
        ascending=False
    )
)

display(mvp_complete)

,mvp_wins,mvp_top3,mvp_top5,total_mvp_share,best_mvp_share,first_place_votes
player,,,,,,
Kareem Abdul-Jabbar,6,9,15,6.104,0.895,762.0
Michael Jordan,5,10,10,8.115,0.986,530.5
LeBron James,4,11,14,8.834,0.998,494.0
Larry Bird,3,8,9,5.611,0.981,271.0
Magic Johnson,3,9,9,5.104,0.940,168.5

In [195]:
eos_path = os.path.join(
    playoffs_path,
    "End of Season Teams.csv"
)

df_eos = pd.read_csv(eos_path)

print("Dimensions :", df_eos.shape)

print("\nColonnes :")
print(df_eos.columns.tolist())

display(df_eos.head(10))

Dimensions : (2222, 7)

Colonnes :
['season', 'lg', 'type', 'number_tm', 'player', 'player_id', 'position']

   season   lg         type number_tm             player  player_id position
0    2025  NBA  All-Defense       1st      Dyson Daniels  daniedy01      NaN
1    2025  NBA  All-Defense       1st      Luguentz Dort   dortlu01      NaN
2    2025  NBA  All-Defense       1st     Draymond Green  greendr01      NaN
3    2025  NBA  All-Defense       1st        Evan Mobley  mobleev01      NaN
4    2025  NBA  All-Defense       1st      Amen Thompson  thompam01      NaN
5    2025  NBA  All-Defense       2nd     Toumani Camara  camarto01      NaN
6    2025  NBA  All-Defense       2nd        Rudy Gobert  goberru01      NaN
7    2025  NBA  All-Defense       2nd  Jaren Jackson Jr.  jacksja02      NaN
8    2025  NBA  All-Defense       2nd     Jalen Williams  willija06      NaN
9    2025  NBA  All-Defense       2nd        Ivica Zubac  zubaciv01      NaN

In [196]:
for col in df_eos.select_dtypes(include="object").columns:
    print(f"\n--- {col} ---")
    print(df_eos[col].value_counts(dropna=False).head(30))

--- lg ---
lg
NBA    2034
ABA     158
BAA      30
Name: count, dtype: int64

--- type ---
type
All-NBA        946
All-Defense    604
All-Rookie     551
All-ABA         91
All-BAA         30
Name: count, dtype: int64

--- number_tm ---
number_tm
1st    1121
2nd     916
3rd     185
Name: count, dtype: int64

--- player ---
player
Tim Duncan               31
Kobe Bryant              28
LeBron James             28
Kareem Abdul-Jabbar      27
Kevin Garnett            22
Hakeem Olajuwon          22
Michael Jordan           21
Chris Paul               21
John Havlicek            20
David Robinson           19
Karl Malone              19
Gary Payton              19
Shaquille O'Neal         18
Jerry West               17
Scottie Pippen           17
Jason Kidd               16
John Stockton            16
Giannis Antetokounmpo    15
Walt Frazier             14
Kawhi Leonard            14
Dwight Howard            14
Julius Erving            14
Larry Bird               14
Bobby Jones              13
Bill Russell             12
Wilt Chamberlain         12
Dwyane Wade              12
Kevin Durant             12
Stephen Curry            12
Bob Cousy                12
Name: count, dtype: int64

--- player_id ---
player_id
duncati01    31
bryanko01    28
jamesle01    28
abdulka01    27
garneke01    22
olajuha01    22
jordami01    21
paulch01     21
havlijo01    20
robinda01    19
malonka01    19
paytoga01    19
onealsh01    18
westje01     17
pippesc01    17
kiddja01     16
stockjo01    16
antetgi01    15
fraziwa01    14
leonaka01    14
howardw01    14
ervinju01    14
birdla01     14
jonesbo01    13
russebi01    12
chambwi01    12
wadedw01     12
duranke01    12
curryst01    12
cousybo01    12
Name: count, dtype: int64

--- position ---
position
NaN    1246
G       393
F       387
C       196
Name: count, dtype: int64

In [197]:
print(df_eos.columns.tolist())

['season', 'lg', 'type', 'number_tm', 'player', 'player_id', 'position']

In [198]:
print("Dimensions :", df_eos.shape)

for col in df_eos.columns:
    print(f"\n{col}:")

    if df_eos[col].nunique() <= 30:
        print(df_eos[col].value_counts(dropna=False))
    else:
        print(
            f"{df_eos[col].nunique()} valeurs uniques"
        )

Dimensions : (2222, 7)

season:
79 valeurs uniques

lg:
lg
NBA    2034
ABA     158
BAA      30
Name: count, dtype: int64

type:
type
All-NBA        946
All-Defense    604
All-Rookie     551
All-ABA         91
All-BAA         30
Name: count, dtype: int64

number_tm:
number_tm
1st    1121
2nd     916
3rd     185
Name: count, dtype: int64

player:
775 valeurs uniques

player_id:
775 valeurs uniques

position:
position
NaN    1246
G       393
F       387
C       196
Name: count, dtype: int64

In [199]:
df_eos_nba = df_eos[
    df_eos["lg"] == "NBA"
].copy()

print(df_eos_nba["type"].value_counts())

type
All-NBA        946
All-Defense    582
All-Rookie     506
Name: count, dtype: int64

In [200]:
goat_eos = df_eos_nba[
    df_eos_nba["player"].isin(goat_names)
].copy()

display(
    goat_eos[
        [
            "season",
            "type",
            "number_tm",
            "player"
        ]
    ].sort_values(
        ["player", "season", "type"]
    )
)

      season         type number_tm               player
1890    1970  All-Defense       2nd  Kareem Abdul-Jabbar
1900    1970      All-NBA       2nd  Kareem Abdul-Jabbar
1910    1970   All-Rookie       1st  Kareem Abdul-Jabbar
1850    1971  All-Defense       2nd  Kareem Abdul-Jabbar
1855    1971      All-NBA       1st  Kareem Abdul-Jabbar
...      ...          ...       ...                  ...
1040    1996      All-NBA       1st       Michael Jordan
991     1997  All-Defense       1st       Michael Jordan
1005    1997      All-NBA       1st       Michael Jordan
956     1998  All-Defense       1st       Michael Jordan
969     1998      All-NBA       1st       Michael Jordan

[101 rows x 4 columns]

In [201]:
goat_eos["ALL_NBA_1ST"] = (
    (goat_eos["type"] == "All-NBA") &
    (goat_eos["number_tm"] == "1st")
).astype(int)

goat_eos["ALL_NBA_2ND"] = (
    (goat_eos["type"] == "All-NBA") &
    (goat_eos["number_tm"] == "2nd")
).astype(int)

goat_eos["ALL_NBA_3RD"] = (
    (goat_eos["type"] == "All-NBA") &
    (goat_eos["number_tm"] == "3rd")
).astype(int)

In [202]:
goat_eos["ALL_NBA"] = (
    goat_eos["type"] == "All-NBA"
).astype(int)

In [203]:
goat_eos["ALL_DEF_1ST"] = (
    (goat_eos["type"] == "All-Defense") &
    (goat_eos["number_tm"] == "1st")
).astype(int)

goat_eos["ALL_DEF_2ND"] = (
    (goat_eos["type"] == "All-Defense") &
    (goat_eos["number_tm"] == "2nd")
).astype(int)

goat_eos["ALL_DEF"] = (
    goat_eos["type"] == "All-Defense"
).astype(int)

In [204]:
eos_summary = (
    goat_eos
    .groupby("player")
    .agg(
        all_nba_1st=("ALL_NBA_1ST", "sum"),
        all_nba_2nd=("ALL_NBA_2ND", "sum"),
        all_nba_3rd=("ALL_NBA_3RD", "sum"),
        all_nba_total=("ALL_NBA", "sum"),

        all_def_1st=("ALL_DEF_1ST", "sum"),
        all_def_2nd=("ALL_DEF_2ND", "sum"),
        all_def_total=("ALL_DEF", "sum")
    )
    .sort_values(
        "all_nba_1st",
        ascending=False
    )
)

display(eos_summary)

,all_nba_1st,all_nba_2nd,all_nba_3rd,all_nba_total,all_def_1st,all_def_2nd,all_def_total
player,,,,,,,
LeBron James,13,4,4,21,5,1,6
Kareem Abdul-Jabbar,10,5,0,15,5,6,11
Michael Jordan,10,1,0,11,9,0,9
Larry Bird,9,1,0,10,0,3,3
Magic Johnson,9,1,0,10,0,0,0

In [205]:
individual_success = (
    mvp_complete
    .join(
        eos_summary,
        how="outer"
    )
    .fillna(0)
)

display(individual_success)

,mvp_wins,mvp_top3,mvp_top5,total_mvp_share,best_mvp_share,first_place_votes,all_nba_1st,all_nba_2nd,all_nba_3rd,all_nba_total,all_def_1st,all_def_2nd,all_def_total
player,,,,,,,,,,,,,
Kareem Abdul-Jabbar,6,9,15,6.104,0.895,762.0,10,5,0,15,5,6,11
Larry Bird,3,8,9,5.611,0.981,271.0,9,1,0,10,0,3,3
LeBron James,4,11,14,8.834,0.998,494.0,13,4,4,21,5,1,6
Magic Johnson,3,9,9,5.104,0.940,168.5,9,1,0,10,0,0,0
Michael Jordan,5,10,10,8.115,0.986,530.5,10,1,0,11,9,0,9

In [206]:
individual_display = individual_success[
    [
        "mvp_wins",
        "mvp_top3",
        "total_mvp_share",
        "all_nba_1st",
        "all_nba_total",
        "all_def_1st",
        "all_def_total"
    ]
].copy()

individual_display.columns = [
    "MVP",
    "MVP Top 3",
    "MVP Share",
    "All-NBA 1st",
    "All-NBA Total",
    "All-Defense 1st",
    "All-Defense Total"
]

display(individual_display)

,MVP,MVP Top 3,MVP Share,All-NBA 1st,All-NBA Total,All-Defense 1st,All-Defense Total
player,,,,,,,
Kareem Abdul-Jabbar,6,9,6.104,10,15,5,11
Larry Bird,3,8,5.611,9,10,0,3
LeBron James,4,11,8.834,13,21,5,6
Magic Johnson,3,9,5.104,9,10,0,0
Michael Jordan,5,10,8.115,10,11,9,9

In [207]:
goat_longevity = df_player_season[
    df_player_season["Name"].isin(goat_players)
].copy()

In [208]:
longevity_basic = (
    goat_longevity
    .groupby("Name")
    .agg(
        career_seasons=("SEASON_ID", "nunique"),
        career_games=("GP", "sum"),
        career_minutes=("MIN", "sum"),
        career_points=("PTS", "sum")
    )
)

display(
    longevity_basic
    .sort_values("career_games", ascending=False)
)

,career_seasons,career_games,career_minutes,career_points
Name,,,,
Kareem Abdul-Jabbar,20,1560,57446.0,38387
LeBron James,21,1492,56596.0,40474
Michael Jordan,15,1072,41008.0,32292
Magic Johnson,13,906,33245.0,17707
Larry Bird,13,897,34443.0,21791

In [209]:
goat_longevity["PPG"] = (
    goat_longevity["PTS"] /
    goat_longevity["GP"]
)

In [210]:
goat_longevity["SEASON_20_PPG"] = (
    goat_longevity["PPG"] >= 20
).astype(int)

goat_longevity["SEASON_25_PPG"] = (
    goat_longevity["PPG"] >= 25
).astype(int)

goat_longevity["SEASON_30_PPG"] = (
    goat_longevity["PPG"] >= 30
).astype(int)

In [211]:
scoring_longevity = (
    goat_longevity
    .groupby("Name")
    .agg(
        seasons_20_ppg=("SEASON_20_PPG", "sum"),
        seasons_25_ppg=("SEASON_25_PPG", "sum"),
        seasons_30_ppg=("SEASON_30_PPG", "sum")
    )
)

display(
    scoring_longevity
    .sort_values("seasons_25_ppg", ascending=False)
)

                     seasons_20_ppg  seasons_25_ppg  seasons_30_ppg
Name
LeBron James                     21              20               3
Michael Jordan                   15              12               8
Kareem Abdul-Jabbar              17              10               3
Larry Bird                       11               4               0
Magic Johnson                     4               0               0

In [212]:
goat_elite = df_era[
    df_era["Name"].isin(goat_players)
].copy()

In [213]:
goat_elite["ELITE_SEASON"] = (
    goat_elite["PRODUCTION_Z"] >= 1
).astype(int)

goat_elite["SUPER_ELITE_SEASON"] = (
    goat_elite["PRODUCTION_Z"] >= 1.5
).astype(int)

goat_elite["DOMINANT_SEASON"] = (
    goat_elite["PRODUCTION_Z"] >= 2
).astype(int)

In [214]:
elite_longevity = (
    goat_elite
    .groupby("Name")
    .agg(
        elite_seasons=("ELITE_SEASON", "sum"),
        super_elite_seasons=("SUPER_ELITE_SEASON", "sum"),
        dominant_seasons=("DOMINANT_SEASON", "sum")
    )
)

display(
    elite_longevity
    .sort_values("elite_seasons", ascending=False)
)

                     elite_seasons  super_elite_seasons  dominant_seasons
Name
LeBron James                    21                   21                20
Kareem Abdul-Jabbar             17                   13                10
Magic Johnson                   13                   12                11
Michael Jordan                  13                   12                 8
Larry Bird                      12                   12                 8

In [215]:
longevity_complete = (
    longevity_basic
    .join(scoring_longevity)
    .join(elite_longevity)
    .join(
        individual_success[
            [
                "mvp_top5",
                "all_nba_total"
            ]
        ]
    )
)

display(longevity_complete)

,career_seasons,career_games,career_minutes,career_points,seasons_20_ppg,seasons_25_ppg,seasons_30_ppg,elite_seasons,super_elite_seasons,dominant_seasons,mvp_top5,all_nba_total
Name,,,,,,,,,,,,
Kareem Abdul-Jabbar,20,1560,57446.0,38387,17,10,3,17,13,10,15,15
Larry Bird,13,897,34443.0,21791,11,4,0,12,12,8,9,10
LeBron James,21,1492,56596.0,40474,21,20,3,21,21,20,14,21
Magic Johnson,13,906,33245.0,17707,4,0,0,13,12,11,9,10
Michael Jordan,15,1072,41008.0,32292,15,12,8,13,12,8,10,11

In [216]:
longevity_display = longevity_complete[
    [
        "career_seasons",
        "career_games",
        "seasons_25_ppg",
        "elite_seasons",
        "super_elite_seasons",
        "dominant_seasons",
        "mvp_top5",
        "all_nba_total"
    ]
].copy()

display(
    longevity_display
    .sort_values("elite_seasons", ascending=False)
)

,career_seasons,career_games,seasons_25_ppg,elite_seasons,super_elite_seasons,dominant_seasons,mvp_top5,all_nba_total
Name,,,,,,,,
LeBron James,21,1492,20,21,21,20,14,21
Kareem Abdul-Jabbar,20,1560,10,17,13,10,15,15
Magic Johnson,13,906,0,13,12,11,9,10
Michael Jordan,15,1072,12,13,12,8,10,11
Larry Bird,13,897,4,12,12,8,9,10

In [217]:
import pandas as pd

url = "https://raw.githubusercontent.com/fivethirtyeight/nba-player-advanced-metrics/master/nba-data-historical.csv"

df_hist = pd.read_csv(url)

print(df_hist.shape)
print(df_hist.columns.tolist())

display(df_hist.head())

(28179, 42)
['player_id', 'name_common', 'year_id', 'type', 'age', 'team_id', 'pos', 'tmRtg', 'franch_id', 'G', 'Min', 'MP%', 'MPG', 'P/36', 'TS%', 'A/36', 'R/36', 'SB/36', 'TO/36', 'Raptor O', 'Raptor D', 'Raptor+/-', 'Raptor WAR', 'PIE%', 'AWS%', 'USG%', 'AST%', 'TOV%', 'ORB%', 'DRB%', 'TRB%', 'STL%', 'BLK%', 'ORtg', '%Pos', 'DRtg', '2P%', '3P%', 'FT%', '3PAr', 'FTAr', 'Pace +/-']

,player_id,name_common,year_id,type,age,team_id,pos,tmRtg,franch_id,G,...,BLK%,ORtg,%Pos,DRtg,2P%,3P%,FT%,3PAr,FTAr,Pace +/-
0,youngtr01,Trae Young,2020,RS,21,ATL,PG,NaN,ATL,60,...,0.3,NaN,NaN,NaN,NaN,NaN,NaN,45.5,44.8,2.9
1,huntede01,De'Andre Hunter,2020,RS,22,ATL,SF,NaN,ATL,63,...,0.7,NaN,NaN,NaN,NaN,NaN,NaN,44.5,21.1,0.0
2,huertke01,Kevin Huerter,2020,RS,21,ATL,SG,NaN,ATL,56,...,1.3,NaN,NaN,NaN,NaN,NaN,NaN,54.8,10.5,0.1
3,reddica01,Cam Reddish,2020,RS,20,ATL,SF,NaN,ATL,58,...,1.5,NaN,NaN,NaN,NaN,NaN,NaN,45.1,22.7,0.9
4,collijo01,John Collins,2020,RS,22,ATL,PF,NaN,ATL,41,...,4.1,NaN,NaN,NaN,NaN,NaN,NaN,24.3,24.8,0.1

In [218]:
print(df_hist["type"].value_counts(dropna=False))

type
RS    20080
PO     8099
Name: count, dtype: int64

In [219]:
goat_hist = df_hist[
    df_hist["name_common"].isin([
        "Michael Jordan",
        "LeBron James",
        "Kareem Abdul-Jabbar",
        "Magic Johnson",
        "Larry Bird"
    ])
].copy()

display(
    goat_hist[
        [
            "name_common",
            "year_id",
            "type",
            "G",
            "Min",
            "MPG"
        ]
    ].sort_values(
        ["name_common", "year_id", "type"]
    )
)

               name_common  year_id type   G   Min   MPG
27974  Kareem Abdul-Jabbar     1977   PO  11   467  42.5
27959  Kareem Abdul-Jabbar     1977   RS  82  3016  36.8
27482  Kareem Abdul-Jabbar     1978   PO   3   134  44.7
27468  Kareem Abdul-Jabbar     1978   RS  62  2265  36.5
27021  Kareem Abdul-Jabbar     1979   PO   8   367  45.9
...                    ...      ...  ...  ..   ...   ...
16689       Michael Jordan     1997   RS  82  3106  37.9
16022       Michael Jordan     1998   PO  21   872  41.5
16005       Michael Jordan     1998   RS  82  3181  38.8
13925       Michael Jordan     2002   RS  60  2093  34.9
13265       Michael Jordan     2003   RS  82  3031  37.0

[136 rows x 6 columns]

In [220]:
df_hist.columns.tolist()

['player_id',
 'name_common',
 'year_id',
 'type',
 'age',
 'team_id',
 'pos',
 'tmRtg',
 'franch_id',
 'G',
 'Min',
 'MP%',
 'MPG',
 'P/36',
 'TS%',
 'A/36',
 'R/36',
 'SB/36',
 'TO/36',
 'Raptor O',
 'Raptor D',
 'Raptor+/-',
 'Raptor WAR',
 'PIE%',
 'AWS%',
 'USG%',
 'AST%',
 'TOV%',
 'ORB%',
 'DRB%',
 'TRB%',
 'STL%',
 'BLK%',
 'ORtg',
 '%Pos',
 'DRtg',
 '2P%',
 '3P%',
 'FT%',
 '3PAr',
 'FTAr',
 'Pace +/-']

In [221]:
df_hist["type"].value_counts()

type
RS    20080
PO     8099
Name: count, dtype: int64

In [222]:
print(df_hist["type"].value_counts(dropna=False))

type
RS    20080
PO     8099
Name: count, dtype: int64

In [223]:
print(
    df_hist.groupby("type")["year_id"]
    .agg(["min", "max", "nunique"])
)

       min   max  nunique
type
PO    1977  2020       44
RS    1977  2020       44

In [224]:
goat_names = [
    "Michael Jordan",
    "LeBron James",
    "Kareem Abdul-Jabbar",
    "Magic Johnson",
    "Larry Bird"
]

goat_playoffs = df_hist[
    (df_hist["name_common"].isin(goat_names)) &
    (df_hist["type"] == "PO")
].copy()

In [225]:
playoff_coverage = (
    goat_playoffs
    .groupby("name_common")
    .agg(
        playoff_seasons=("year_id", "nunique"),
        playoff_games=("G", "sum"),
        playoff_minutes=("Min", "sum"),
        first_playoffs=("year_id", "min"),
        last_playoffs=("year_id", "max")
    )
    .sort_values("playoff_games", ascending=False)
)

display(playoff_coverage)

,playoff_seasons,playoff_games,playoff_minutes,first_playoffs,last_playoffs
name_common,,,,,
LeBron James,14,260,10811,2006,2020
Magic Johnson,13,190,7538,1980,1996
Kareem Abdul-Jabbar,13,180,6295,1977,1989
Michael Jordan,13,179,7474,1985,1998
Larry Bird,12,164,6886,1980,1992

In [226]:
display(
    goat_playoffs[
        [
            "name_common",
            "year_id",
            "team_id",
            "G",
            "Min",
            "MPG",
            "P/36",
            "R/36",
            "A/36",
            "TS%",
            "Raptor+/-",
            "Raptor WAR"
        ]
    ]
    .sort_values(["name_common", "year_id"])
)

,name_common,year_id,team_id,G,Min,MPG,P/36,R/36,A/36,TS%,Raptor+/-,Raptor WAR
27974,Kareem Abdul-Jabbar,1977,LAL,11,467,42.5,NaN,NaN,NaN,64.6,9.6,3.03
27482,Kareem Abdul-Jabbar,1978,LAL,3,134,44.7,NaN,NaN,NaN,52.6,0.2,0.21
27021,Kareem Abdul-Jabbar,1979,LAL,8,367,45.9,NaN,NaN,NaN,63.6,5.3,1.54
26577,Kareem Abdul-Jabbar,1980,LAL,15,618,41.2,NaN,NaN,NaN,61.1,6.8,3.07
26142,Kareem Abdul-Jabbar,1981,LAL,3,134,44.7,NaN,NaN,NaN,51.7,1.9,0.33
...,...,...,...,...,...,...,...,...,...,...,...,...
19336,Michael Jordan,1993,CHI,19,783,41.2,NaN,NaN,NaN,55.3,11.1,5.72
18089,Michael Jordan,1995,CHI,10,420,42.0,NaN,NaN,NaN,55.7,6.3,2.00
17397,Michael Jordan,1996,CHI,18,733,40.7,NaN,NaN,NaN,56.4,9.0,4.50
16704,Michael Jordan,1997,CHI,19,804,42.3,NaN,NaN,NaN,52.4,7.9,4.50
16022,Michael Jordan,1998,CHI,21,872,41.5,NaN,NaN,NaN,54.5,7.5,4.67

In [227]:
playoff_summary = (
    goat_playoffs
    .groupby("name_common")
    .apply(
        lambda x: pd.Series({
            "PO_seasons": x["year_id"].nunique(),
            "PO_games": x["G"].sum(),

            "PO_P36": (
                (x["P/36"] * x["Min"]).sum()
                / x["Min"].sum()
            ),

            "PO_R36": (
                (x["R/36"] * x["Min"]).sum()
                / x["Min"].sum()
            ),

            "PO_A36": (
                (x["A/36"] * x["Min"]).sum()
                / x["Min"].sum()
            ),

            "PO_TS": (
                (x["TS%"] * x["Min"]).sum()
                / x["Min"].sum()
            ),

            "PO_RAPTOR": (
                (x["Raptor+/-"] * x["Min"]).sum()
                / x["Min"].sum()
            ),

            "PO_RAPTOR_WAR": x["Raptor WAR"].sum()
        })
    )
    .round(3)
)

display(playoff_summary)

/tmp/ipykernel_1080/4165737493.py:4: DeprecationWarning:

DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.

,PO_seasons,PO_games,PO_P36,PO_R36,PO_A36,PO_TS,PO_RAPTOR,PO_RAPTOR_WAR
name_common,,,,,,,,
Kareem Abdul-Jabbar,13.0,180.0,0.0,0.0,0.0,58.185,3.429,20.39
Larry Bird,12.0,164.0,0.0,0.0,0.0,54.989,6.164,32.17
LeBron James,14.0,260.0,0.0,0.0,0.0,58.457,8.820,65.45
Magic Johnson,13.0,190.0,0.0,0.0,0.0,59.451,8.192,43.17
Michael Jordan,13.0,179.0,0.0,0.0,0.0,56.802,9.394,47.69

In [228]:
display(
    goat_playoffs[
        [
            "name_common",
            "year_id",
            "P/36",
            "R/36",
            "A/36",
            "Min",
            "TS%"
        ]
    ].head(30)
)

          name_common  year_id  P/36  R/36  A/36  Min   TS%
378      LeBron James     2020   NaN   NaN   NaN  762  64.7
1778     LeBron James     2018   NaN   NaN   NaN  922  61.9
2613     LeBron James     2017   NaN   NaN   NaN  744  64.9
3357     LeBron James     2016   NaN   NaN   NaN  822  58.5
4117     LeBron James     2015   NaN   NaN   NaN  844  48.7
5152     LeBron James     2014   NaN   NaN   NaN  763  66.8
5915     LeBron James     2013   NaN   NaN   NaN  960  58.5
6591     LeBron James     2012   NaN   NaN   NaN  983  57.6
7304     LeBron James     2011   NaN   NaN   NaN  922  56.3
7817     LeBron James     2010   NaN   NaN   NaN  460  60.7
8521     LeBron James     2009   NaN   NaN   NaN  580  61.8
9216     LeBron James     2008   NaN   NaN   NaN  552  52.5
9927     LeBron James     2007   NaN   NaN   NaN  893  51.6
10608    LeBron James     2006   NaN   NaN   NaN  604  55.7
16022  Michael Jordan     1998   NaN   NaN   NaN  872  54.5
16704  Michael Jordan     1997   NaN   NaN   NaN  804  52.4
17397  Michael Jordan     1996   NaN   NaN   NaN  733  56.4
17597   Magic Johnson     1996   NaN   NaN   NaN  135  57.0
18089  Michael Jordan     1995   NaN   NaN   NaN  420  55.7
19336  Michael Jordan     1993   NaN   NaN   NaN  783  55.3
19882      Larry Bird     1992   NaN   NaN   NaN  107  51.4
19921  Michael Jordan     1992   NaN   NaN   NaN  920  57.1
20494      Larry Bird     1991   NaN   NaN   NaN  396  49.0
20535  Michael Jordan     1991   NaN   NaN   NaN  689  60.0
20731   Magic Johnson     1991   NaN   NaN   NaN  823  59.8
21086      Larry Bird     1990   NaN   NaN   NaN  207  53.9
21132  Michael Jordan     1990   NaN   NaN   NaN  674  59.2
21352   Magic Johnson     1990   NaN   NaN   NaN  376  59.8
21744  Michael Jordan     1989   NaN   NaN   NaN  718  60.2
21958   Magic Johnson     1989   NaN   NaN   NaN  518  60.9

In [229]:
print("P/36")
print(goat_playoffs["P/36"].describe())

print("\nR/36")
print(goat_playoffs["R/36"].describe())

print("\nA/36")
print(goat_playoffs["A/36"].describe())

P/36
count    0.0
mean     NaN
std      NaN
min      NaN
25%      NaN
50%      NaN
75%      NaN
max      NaN
Name: P/36, dtype: float64

R/36
count    0.0
mean     NaN
std      NaN
min      NaN
25%      NaN
50%      NaN
75%      NaN
max      NaN
Name: R/36, dtype: float64

A/36
count    0.0
mean     NaN
std      NaN
min      NaN
25%      NaN
50%      NaN
75%      NaN
max      NaN
Name: A/36, dtype: float64

In [230]:
print(
    goat_playoffs[
        ["P/36", "R/36", "A/36"]
    ].dtypes
)

P/36    float64
R/36    float64
A/36    float64
dtype: object

In [231]:
display(
    goat_playoffs[
        goat_playoffs["name_common"] == "Michael Jordan"
    ][
        [
            "year_id",
            "G",
            "Min",
            "MPG",
            "P/36",
            "R/36",
            "A/36",
            "TS%",
            "Raptor+/-",
            "Raptor WAR"
        ]
    ]
)

       year_id   G  Min   MPG  P/36  R/36  A/36   TS%  Raptor+/-  Raptor WAR
16022     1998  21  872  41.5   NaN   NaN   NaN  54.5        7.5        4.67
16704     1997  19  804  42.3   NaN   NaN   NaN  52.4        7.9        4.50
17397     1996  18  733  40.7   NaN   NaN   NaN  56.4        9.0        4.50
18089     1995  10  420  42.0   NaN   NaN   NaN  55.7        6.3        2.00
19336     1993  19  783  41.2   NaN   NaN   NaN  55.3       11.1        5.72
19921     1992  22  920  41.8   NaN   NaN   NaN  57.1        8.4        5.38
20535     1991  17  689  40.5   NaN   NaN   NaN  60.0       13.9        6.01
21132     1990  16  674  42.1   NaN   NaN   NaN  59.2       12.1        5.28
21744     1989  17  718  42.2   NaN   NaN   NaN  60.2       10.3        4.94
22311     1988  10  427  42.7   NaN   NaN   NaN  59.8        7.4        2.28
22882     1987   3  128  42.7   NaN   NaN   NaN  52.9        8.0        0.72
23420     1986   3  135  45.0   NaN   NaN   NaN  58.4        7.0        0.70
23945     1985   4  171  42.8   NaN   NaN   NaN  56.5        8.2        0.99

In [232]:
goat_hist_all = df_hist[
    df_hist["name_common"].isin(goat_names)
].copy()

print(
    goat_hist_all["type"]
    .value_counts(dropna=False)
)

type
RS    71
PO    65
Name: count, dtype: int64

In [233]:
metrics = [
    "TS%",
    "Raptor O",
    "Raptor D",
    "Raptor+/-",
    "ORtg",
    "DRtg"
]

print(
    goat_hist_all[metrics]
    .notna()
    .sum()
)

TS%          136
Raptor O     136
Raptor D     136
Raptor+/-    136
ORtg          70
DRtg          70
dtype: int64

In [234]:
goat_hist_all = df_hist[
    df_hist["name_common"].isin(goat_names)
].copy()

print(
    goat_hist_all["type"]
    .value_counts(dropna=False)
)

type
RS    71
PO    65
Name: count, dtype: int64

In [235]:
metrics = [
    "TS%",
    "Raptor O",
    "Raptor D",
    "Raptor+/-",
    "ORtg",
    "DRtg"
]

print(
    goat_hist_all[metrics]
    .notna()
    .sum()
)

TS%          136
Raptor O     136
Raptor D     136
Raptor+/-    136
ORtg          70
DRtg          70
dtype: int64

In [236]:
rs = goat_hist_all[
    goat_hist_all["type"] == "RS"
][
    [
        "name_common",
        "year_id",
        "G",
        "Min",
        "TS%",
        "Raptor O",
        "Raptor D",
        "Raptor+/-",
        "ORtg",
        "DRtg"
    ]
].copy()

In [237]:
rs = rs.rename(columns={
    "G": "RS_G",
    "Min": "RS_Min",
    "TS%": "RS_TS",
    "Raptor O": "RS_RAPTOR_O",
    "Raptor D": "RS_RAPTOR_D",
    "Raptor+/-": "RS_RAPTOR",
    "ORtg": "RS_ORtg",
    "DRtg": "RS_DRtg"
})

In [238]:
po = goat_hist_all[
    goat_hist_all["type"] == "PO"
][
    [
        "name_common",
        "year_id",
        "G",
        "Min",
        "TS%",
        "Raptor O",
        "Raptor D",
        "Raptor+/-",
        "ORtg",
        "DRtg"
    ]
].copy()

In [239]:
po = po.rename(columns={
    "G": "PO_G",
    "Min": "PO_Min",
    "TS%": "PO_TS",
    "Raptor O": "PO_RAPTOR_O",
    "Raptor D": "PO_RAPTOR_D",
    "Raptor+/-": "PO_RAPTOR",
    "ORtg": "PO_ORtg",
    "DRtg": "PO_DRtg"
})

In [240]:
rs_po = rs.merge(
    po,
    on=["name_common", "year_id"],
    how="inner"
)

In [241]:
coverage_rs_po = (
    rs_po
    .groupby("name_common")
    .agg(
        comparable_seasons=("year_id", "nunique"),
        playoff_games=("PO_G", "sum")
    )
    .sort_values(
        "comparable_seasons",
        ascending=False
    )
)

display(coverage_rs_po)

                     comparable_seasons  playoff_games
name_common
LeBron James                         14            260
Kareem Abdul-Jabbar                  13            180
Magic Johnson                        13            190
Michael Jordan                       13            179
Larry Bird                           12            164

In [242]:
rs_po["TS_UPLIFT"] = (
    rs_po["PO_TS"] -
    rs_po["RS_TS"]
)

In [243]:
rs_po["RAPTOR_UPLIFT"] = (
    rs_po["PO_RAPTOR"] -
    rs_po["RS_RAPTOR"]
)

In [244]:
rs_po["RAPTOR_O_UPLIFT"] = (
    rs_po["PO_RAPTOR_O"] -
    rs_po["RS_RAPTOR_O"]
)

rs_po["RAPTOR_D_UPLIFT"] = (
    rs_po["PO_RAPTOR_D"] -
    rs_po["RS_RAPTOR_D"]
)

In [245]:
import numpy as np

playoff_uplift = (
    rs_po
    .groupby("name_common")
    .apply(
        lambda x: pd.Series({

            "seasons": x["year_id"].nunique(),

            "PO_games": x["PO_G"].sum(),

            "RS_TS": np.average(
                x["RS_TS"],
                weights=x["PO_Min"]
            ),

            "PO_TS": np.average(
                x["PO_TS"],
                weights=x["PO_Min"]
            ),

            "TS_uplift": np.average(
                x["TS_UPLIFT"],
                weights=x["PO_Min"]
            ),

            "RS_RAPTOR": np.average(
                x["RS_RAPTOR"],
                weights=x["PO_Min"]
            ),

            "PO_RAPTOR": np.average(
                x["PO_RAPTOR"],
                weights=x["PO_Min"]
            ),

            "RAPTOR_uplift": np.average(
                x["RAPTOR_UPLIFT"],
                weights=x["PO_Min"]
            )
        }),
        include_groups=False
    )
    .round(3)
)

display(playoff_uplift)

,seasons,PO_games,RS_TS,PO_TS,TS_uplift,RS_RAPTOR,PO_RAPTOR,RAPTOR_uplift
name_common,,,,,,,,
Kareem Abdul-Jabbar,13.0,180.0,60.290,58.185,-2.105,2.814,3.429,0.615
Larry Bird,12.0,164.0,56.986,54.989,-1.997,6.932,6.164,-0.768
LeBron James,14.0,260.0,59.802,58.457,-1.346,7.706,8.820,1.114
Magic Johnson,13.0,190.0,60.987,59.451,-1.536,7.369,8.192,0.823
Michael Jordan,13.0,179.0,57.497,56.802,-0.696,9.381,9.394,0.013

In [246]:
tables_to_check = [
    "individual_success",
    "longevity_complete",
    "playoff_uplift",
    "championship_summary"
]

for table in tables_to_check:
    print(
        table,
        "→",
        table in globals()
    )

individual_success → True
longevity_complete → True
playoff_uplift → True
championship_summary → True

In [247]:
print(df_era.columns.tolist())

['PLAYER_ID', 'Name', 'SEASON_ID', 'TEAM_ID', 'TEAM_ABBREVIATION', 'PLAYER_AGE', 'GP', 'GS', 'MIN', 'FGM', 'FGA', 'FG_PCT', 'FG3M', 'FG3A', 'FG3_PCT', 'FTM', 'FTA', 'FT_PCT', 'OREB', 'DREB', 'REB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS', 'PPG', 'RPG', 'APG', 'SPG', 'BPG', 'MPG', 'PPG_Z', 'RPG_Z', 'APG_Z', 'PRODUCTION_Z', 'TS_PCT', 'LEAGUE_TS', 'TS_PLUS', 'TS_Z']

In [248]:
production_summary = (
    df_era[
        df_era["Name"].isin(goat_players)
    ]
    .groupby("Name")
    .agg(
        career_production_z=("PRODUCTION_Z", "mean"),
        peak_production_z=("PRODUCTION_Z", "max"),
        career_ts_plus=("TS_PLUS", "mean"),
        peak_ts_plus=("TS_PLUS", "max")
    )
    .round(3)
)

display(production_summary)

,career_production_z,peak_production_z,career_ts_plus,peak_ts_plus
Name,,,,
Kareem Abdul-Jabbar,1.740,2.892,116.515,126.187
Larry Bird,2.129,2.435,107.788,117.351
LeBron James,2.509,3.009,110.377,123.089
Magic Johnson,2.186,2.619,116.639,120.436
Michael Jordan,2.030,2.619,109.238,118.330

In [249]:
display(championship_summary)

                     championships
Name
Kareem Abdul-Jabbar              6
Michael Jordan                   6
Magic Johnson                    5
LeBron James                     4
Larry Bird                       3

In [250]:
championships_master = (
    championship_summary[
        ["championships"]
    ]
    .copy()
)

In [251]:
playoffs_master = playoff_uplift[
    [
        "PO_RAPTOR",
        "RAPTOR_uplift",
        "TS_uplift"
    ]
].copy()

In [252]:
playoffs_master.index.name = "Name"

In [253]:
individual_master = individual_success[
    [
        "mvp_wins",
        "total_mvp_share",
        "all_nba_1st",
        "all_nba_total",
        "all_def_1st",
        "all_def_total"
    ]
].copy()

In [254]:
longevity_master = longevity_complete[
    [
        "career_seasons",
        "career_games",
        "seasons_25_ppg",
        "elite_seasons",
        "mvp_top5",
        "all_nba_total"
    ]
].copy()

In [255]:
longevity_master = longevity_complete[
    [
        "career_seasons",
        "career_games",
        "seasons_25_ppg",
        "elite_seasons"
    ]
].copy()

In [256]:
goat_master = (
    production_summary
    .join(individual_master, how="outer")
    .join(championships_master, how="outer")
    .join(longevity_master, how="outer")
    .join(playoffs_master, how="outer")
)

display(goat_master)

,career_production_z,peak_production_z,career_ts_plus,peak_ts_plus,mvp_wins,total_mvp_share,all_nba_1st,all_nba_total,all_def_1st,all_def_total,championships,career_seasons,career_games,seasons_25_ppg,elite_seasons,PO_RAPTOR,RAPTOR_uplift,TS_uplift
Name,,,,,,,,,,,,,,,,,,
Kareem Abdul-Jabbar,1.740,2.892,116.515,126.187,6,6.104,10,15,5,11,6,20,1560,10,17,3.429,0.615,-2.105
Larry Bird,2.129,2.435,107.788,117.351,3,5.611,9,10,0,3,3,13,897,4,12,6.164,-0.768,-1.997
LeBron James,2.509,3.009,110.377,123.089,4,8.834,13,21,5,6,4,21,1492,20,21,8.820,1.114,-1.346
Magic Johnson,2.186,2.619,116.639,120.436,3,5.104,9,10,0,0,5,13,906,0,13,8.192,0.823,-1.536
Michael Jordan,2.030,2.619,109.238,118.330,5,8.115,10,11,9,9,6,15,1072,12,13,9.394,0.013,-0.696

In [257]:
print("Dimensions :", goat_master.shape)

Dimensions : (5, 18)

In [258]:
display(
    goat_master
    .isna()
    .sum()
    .sort_values(ascending=False)
)

career_production_z    0
peak_production_z      0
career_ts_plus         0
peak_ts_plus           0
mvp_wins               0
total_mvp_share        0
all_nba_1st            0
all_nba_total          0
all_def_1st            0
all_def_total          0
championships          0
career_seasons         0
career_games           0
seasons_25_ppg         0
elite_seasons          0
PO_RAPTOR              0
RAPTOR_uplift          0
TS_uplift              0
dtype: int64

In [259]:
print(
    "Nombre total de valeurs manquantes :",
    goat_master.isna().sum().sum()
)

Nombre total de valeurs manquantes : 0

In [260]:
display(
    goat_master.round(3)
)

,career_production_z,peak_production_z,career_ts_plus,peak_ts_plus,mvp_wins,total_mvp_share,all_nba_1st,all_nba_total,all_def_1st,all_def_total,championships,career_seasons,career_games,seasons_25_ppg,elite_seasons,PO_RAPTOR,RAPTOR_uplift,TS_uplift
Name,,,,,,,,,,,,,,,,,,
Kareem Abdul-Jabbar,1.740,2.892,116.515,126.187,6,6.104,10,15,5,11,6,20,1560,10,17,3.429,0.615,-2.105
Larry Bird,2.129,2.435,107.788,117.351,3,5.611,9,10,0,3,3,13,897,4,12,6.164,-0.768,-1.997
LeBron James,2.509,3.009,110.377,123.089,4,8.834,13,21,5,6,4,21,1492,20,21,8.820,1.114,-1.346
Magic Johnson,2.186,2.619,116.639,120.436,3,5.104,9,10,0,0,5,13,906,0,13,8.192,0.823,-1.536
Michael Jordan,2.030,2.619,109.238,118.330,5,8.115,10,11,9,9,6,15,1072,12,13,9.394,0.013,-0.696

In [261]:
display(goat_master.round(3))

,career_production_z,peak_production_z,career_ts_plus,peak_ts_plus,mvp_wins,total_mvp_share,all_nba_1st,all_nba_total,all_def_1st,all_def_total,championships,career_seasons,career_games,seasons_25_ppg,elite_seasons,PO_RAPTOR,RAPTOR_uplift,TS_uplift
Name,,,,,,,,,,,,,,,,,,
Kareem Abdul-Jabbar,1.740,2.892,116.515,126.187,6,6.104,10,15,5,11,6,20,1560,10,17,3.429,0.615,-2.105
Larry Bird,2.129,2.435,107.788,117.351,3,5.611,9,10,0,3,3,13,897,4,12,6.164,-0.768,-1.997
LeBron James,2.509,3.009,110.377,123.089,4,8.834,13,21,5,6,4,21,1492,20,21,8.820,1.114,-1.346
Magic Johnson,2.186,2.619,116.639,120.436,3,5.104,9,10,0,0,5,13,906,0,13,8.192,0.823,-1.536
Michael Jordan,2.030,2.619,109.238,118.330,5,8.115,10,11,9,9,6,15,1072,12,13,9.394,0.013,-0.696

In [262]:
goat_scores = goat_master.copy()

In [263]:
def minmax_100(series):
    min_val = series.min()
    max_val = series.max()

    if max_val == min_val:
        return pd.Series(
            50,
            index=series.index
        )

    return (
        (series - min_val)
        / (max_val - min_val)
        * 100
    )

In [264]:
metrics_to_normalize = [
    "career_production_z",
    "peak_production_z",

    "career_ts_plus",
    "peak_ts_plus",

    "PO_RAPTOR",
    "RAPTOR_uplift",
    "TS_uplift",

    "mvp_wins",
    "total_mvp_share",
    "all_nba_1st",
    "all_nba_total",
    "all_def_1st",
    "all_def_total",

    "championships",

    "career_seasons",
    "career_games",
    "elite_seasons"
]

goat_norm = pd.DataFrame(
    index=goat_master.index
)

for metric in metrics_to_normalize:
    goat_norm[metric] = minmax_100(
        goat_master[metric]
    )

display(goat_norm.round(1))

,career_production_z,peak_production_z,career_ts_plus,peak_ts_plus,PO_RAPTOR,RAPTOR_uplift,TS_uplift,mvp_wins,total_mvp_share,all_nba_1st,all_nba_total,all_def_1st,all_def_total,championships,career_seasons,career_games,elite_seasons
Name,,,,,,,,,,,,,,,,,
Kareem Abdul-Jabbar,0.0,79.6,98.6,100.0,0.0,73.5,0.0,100.0,26.8,25.0,45.5,55.6,100.0,100.0,87.5,100.0,55.6
Larry Bird,50.6,0.0,0.0,0.0,45.9,0.0,7.7,0.0,13.6,0.0,0.0,0.0,27.3,0.0,0.0,0.0,0.0
LeBron James,100.0,100.0,29.3,64.9,90.4,100.0,53.9,33.3,100.0,100.0,100.0,55.6,54.5,33.3,100.0,89.7,100.0
Magic Johnson,58.0,32.1,100.0,34.9,79.8,84.5,40.4,0.0,0.0,0.0,0.0,0.0,0.0,66.7,0.0,1.4,11.1
Michael Jordan,37.7,32.1,16.4,11.1,100.0,41.5,100.0,66.7,80.7,25.0,9.1,100.0,81.8,100.0,25.0,26.4,11.1

In [265]:
goat_norm["Production_Score"] = (
    0.60 * goat_norm["career_production_z"]
    +
    0.40 * goat_norm["peak_production_z"]
)

In [266]:
goat_norm["Efficiency_Score"] = (
    0.60 * goat_norm["career_ts_plus"]
    +
    0.40 * goat_norm["peak_ts_plus"]
)

In [267]:
goat_norm["Playoffs_Score"] = (
    0.50 * goat_norm["PO_RAPTOR"]
    +
    0.30 * goat_norm["RAPTOR_uplift"]
    +
    0.20 * goat_norm["TS_uplift"]
)

In [268]:
goat_norm["Individual_Score"] = (
    0.30 * goat_norm["mvp_wins"]
    +
    0.20 * goat_norm["total_mvp_share"]
    +
    0.20 * goat_norm["all_nba_1st"]
    +
    0.10 * goat_norm["all_nba_total"]
    +
    0.10 * goat_norm["all_def_1st"]
    +
    0.10 * goat_norm["all_def_total"]
)

In [269]:
goat_norm["Team_Score"] = (
    goat_norm["championships"]
)

In [270]:
goat_norm["Longevity_Score"] = (
    0.25 * goat_norm["career_seasons"]
    +
    0.25 * goat_norm["career_games"]
    +
    0.50 * goat_norm["elite_seasons"]
)

In [271]:
dimension_scores = goat_norm[
    [
        "Production_Score",
        "Efficiency_Score",
        "Playoffs_Score",
        "Individual_Score",
        "Team_Score",
        "Longevity_Score"
    ]
].copy()

display(
    dimension_scores.round(1)
)

,Production_Score,Efficiency_Score,Playoffs_Score,Individual_Score,Team_Score,Longevity_Score
Name,,,,,,
Kareem Abdul-Jabbar,31.8,99.2,22.0,60.5,100.0,74.7
Larry Bird,30.4,0.0,24.5,5.4,0.0,0.0
LeBron James,100.0,43.5,86.0,71.0,33.3,97.4
Magic Johnson,47.6,74.0,73.4,0.0,66.7,5.9
Michael Jordan,35.4,14.3,82.4,60.2,100.0,18.4

In [272]:
from scipy.stats import norm

In [273]:
production_percentile = pd.DataFrame(
    index=goat_master.index
)

production_percentile["career_prod_score"] = (
    norm.cdf(
        goat_master["career_production_z"]
    ) * 100
)

production_percentile["peak_prod_score"] = (
    norm.cdf(
        goat_master["peak_production_z"]
    ) * 100
)

production_percentile["Production_Score_v2"] = (
    0.60 * production_percentile["career_prod_score"]
    +
    0.40 * production_percentile["peak_prod_score"]
)

display(
    production_percentile.round(1)
)

                     career_prod_score  peak_prod_score  Production_Score_v2
Name
Kareem Abdul-Jabbar               95.9             99.8                 97.5
Larry Bird                        98.3             99.3                 98.7
LeBron James                      99.4             99.9                 99.6
Magic Johnson                     98.6             99.6                 99.0
Michael Jordan                    97.9             99.6                 98.6

In [274]:
def ts_plus_score(series):
    return (
        ((series - 90) / 30) * 100
    ).clip(0, 100)

In [275]:
efficiency_v2 = pd.DataFrame(
    index=goat_master.index
)

efficiency_v2["career_ts_score"] = (
    ts_plus_score(
        goat_master["career_ts_plus"]
    )
)

efficiency_v2["peak_ts_score"] = (
    ts_plus_score(
        goat_master["peak_ts_plus"]
    )
)

efficiency_v2["Efficiency_Score_v2"] = (
    0.60 * efficiency_v2["career_ts_score"]
    +
    0.40 * efficiency_v2["peak_ts_score"]
)

display(
    efficiency_v2.round(1)
)

                     career_ts_score  peak_ts_score  Efficiency_Score_v2
Name
Kareem Abdul-Jabbar             88.4          100.0                 93.0
Larry Bird                      59.3           91.2                 72.0
LeBron James                    67.9          100.0                 80.8
Magic Johnson                   88.8          100.0                 93.3
Michael Jordan                  64.1           94.4                 76.2

In [276]:
def benchmark_score(series, benchmark):
    return (
        series / benchmark * 100
    ).clip(0, 100)

In [277]:
team_score_v2 = (
    goat_master["championships"]
    / 6
    * 100
).clip(0, 100)

display(
    team_score_v2
    .round(1)
    .sort_values(ascending=False)
)

Name
Kareem Abdul-Jabbar    100.0
Michael Jordan         100.0
Magic Johnson           83.3
LeBron James            66.7
Larry Bird              50.0
Name: championships, dtype: float64

In [278]:
longevity_v2 = pd.DataFrame(
    index=goat_master.index
)

longevity_v2["seasons_score"] = (
    goat_master["career_seasons"] / 20 * 100
).clip(0, 100)

longevity_v2["games_score"] = (
    goat_master["career_games"] / 1500 * 100
).clip(0, 100)

longevity_v2["elite_score"] = (
    goat_master["elite_seasons"] / 20 * 100
).clip(0, 100)

longevity_v2["Longevity_Score_v2"] = (
    0.25 * longevity_v2["seasons_score"]
    +
    0.25 * longevity_v2["games_score"]
    +
    0.50 * longevity_v2["elite_score"]
)

display(
    longevity_v2.round(1)
)

,seasons_score,games_score,elite_score,Longevity_Score_v2
Name,,,,
Kareem Abdul-Jabbar,100.0,100.0,85.0,92.5
Larry Bird,65.0,59.8,60.0,61.2
LeBron James,100.0,99.5,100.0,99.9
Magic Johnson,65.0,60.4,65.0,63.8
Michael Jordan,75.0,71.5,65.0,69.1

In [279]:
production_percentile
efficiency_v2
team_score_v2
longevity_v2

,seasons_score,games_score,elite_score,Longevity_Score_v2
Name,,,,
Kareem Abdul-Jabbar,100.0,100.000000,85.0,92.500000
Larry Bird,65.0,59.800000,60.0,61.200000
LeBron James,100.0,99.466667,100.0,99.866667
Magic Johnson,65.0,60.400000,65.0,63.850000
Michael Jordan,75.0,71.466667,65.0,69.116667

In [280]:
scores_v2_check = pd.DataFrame({
    "Production": production_percentile["Production_Score_v2"],
    "Efficiency": efficiency_v2["Efficiency_Score_v2"],
    "Team Success": team_score_v2,
    "Longevity": longevity_v2["Longevity_Score_v2"]
})

display(
    scores_v2_check
    .round(1)
)

                     Production  Efficiency  Team Success  Longevity
Name
Kareem Abdul-Jabbar        97.5        93.0         100.0       92.5
Larry Bird                 98.7        72.0          50.0       61.2
LeBron James               99.6        80.8          66.7       99.9
Magic Johnson              99.0        93.3          83.3       63.8
Michael Jordan             98.6        76.2         100.0       69.1

In [281]:
def playoff_raptor_score(series):
    return (
        series / 10 * 100
    ).clip(0, 100)


def raptor_uplift_score(series):
    return (
        (series + 2) / 4 * 100
    ).clip(0, 100)


def ts_uplift_score(series):
    return (
        (series + 5) / 5 * 100
    ).clip(0, 100)

In [282]:
playoffs_v2 = pd.DataFrame(
    index=goat_master.index
)

playoffs_v2["raptor_score"] = playoff_raptor_score(
    goat_master["PO_RAPTOR"]
)

playoffs_v2["raptor_uplift_score"] = raptor_uplift_score(
    goat_master["RAPTOR_uplift"]
)

playoffs_v2["ts_uplift_score"] = ts_uplift_score(
    goat_master["TS_uplift"]
)

In [283]:
playoffs_v2["Playoffs_Score_v2"] = (
    0.50 * playoffs_v2["raptor_score"]
    +
    0.30 * playoffs_v2["raptor_uplift_score"]
    +
    0.20 * playoffs_v2["ts_uplift_score"]
)

display(
    playoffs_v2.round(1)
)

,raptor_score,raptor_uplift_score,ts_uplift_score,Playoffs_Score_v2
Name,,,,
Kareem Abdul-Jabbar,34.3,65.4,57.9,48.3
Larry Bird,61.6,30.8,60.1,52.1
LeBron James,88.2,77.8,73.1,82.1
Magic Johnson,81.9,70.6,69.3,76.0
Michael Jordan,93.9,50.3,86.1,79.3

In [284]:
individual_v2 = pd.DataFrame(
    index=goat_master.index
)

individual_v2["mvp_score"] = (
    goat_master["mvp_wins"] / 6 * 100
).clip(0, 100)

individual_v2["mvp_share_score"] = (
    goat_master["total_mvp_share"] / 9 * 100
).clip(0, 100)

individual_v2["all_nba_1st_score"] = (
    goat_master["all_nba_1st"] / 13 * 100
).clip(0, 100)

individual_v2["all_nba_total_score"] = (
    goat_master["all_nba_total"] / 21 * 100
).clip(0, 100)

individual_v2["all_def_1st_score"] = (
    goat_master["all_def_1st"] / 9 * 100
).clip(0, 100)

individual_v2["all_def_total_score"] = (
    goat_master["all_def_total"] / 11 * 100
).clip(0, 100)

In [285]:
individual_v2["Individual_Score_v2"] = (
    0.30 * individual_v2["mvp_score"]
    +
    0.20 * individual_v2["mvp_share_score"]
    +
    0.20 * individual_v2["all_nba_1st_score"]
    +
    0.10 * individual_v2["all_nba_total_score"]
    +
    0.10 * individual_v2["all_def_1st_score"]
    +
    0.10 * individual_v2["all_def_total_score"]
)

display(
    individual_v2.round(1)
)

,mvp_score,mvp_share_score,all_nba_1st_score,all_nba_total_score,all_def_1st_score,all_def_total_score,Individual_Score_v2
Name,,,,,,,
Kareem Abdul-Jabbar,100.0,67.8,76.9,71.4,55.6,100.0,81.6
Larry Bird,50.0,62.3,69.2,47.6,0.0,27.3,48.8
LeBron James,66.7,98.2,100.0,100.0,55.6,54.5,80.6
Magic Johnson,50.0,56.7,69.2,47.6,0.0,0.0,45.0
Michael Jordan,83.3,90.2,76.9,52.4,100.0,81.8,81.8

In [286]:
dimension_scores_v2 = pd.DataFrame({
    "Production": production_percentile["Production_Score_v2"],
    "Efficiency": efficiency_v2["Efficiency_Score_v2"],
    "Playoffs": playoffs_v2["Playoffs_Score_v2"],
    "Individual": individual_v2["Individual_Score_v2"],
    "Team Success": team_score_v2,
    "Longevity": longevity_v2["Longevity_Score_v2"]
})

display(
    dimension_scores_v2.round(1)
)

,Production,Efficiency,Playoffs,Individual,Team Success,Longevity
Name,,,,,,
Kareem Abdul-Jabbar,97.5,93.0,48.3,81.6,100.0,92.5
Larry Bird,98.7,72.0,52.1,48.8,50.0,61.2
LeBron James,99.6,80.8,82.1,80.6,66.7,99.9
Magic Johnson,99.0,93.3,76.0,45.0,83.3,63.8
Michael Jordan,98.6,76.2,79.3,81.8,100.0,69.1

In [287]:
display(dimension_scores_v2.round(1))

,Production,Efficiency,Playoffs,Individual,Team Success,Longevity
Name,,,,,,
Kareem Abdul-Jabbar,97.5,93.0,48.3,81.6,100.0,92.5
Larry Bird,98.7,72.0,52.1,48.8,50.0,61.2
LeBron James,99.6,80.8,82.1,80.6,66.7,99.9
Magic Johnson,99.0,93.3,76.0,45.0,83.3,63.8
Michael Jordan,98.6,76.2,79.3,81.8,100.0,69.1

In [288]:
goat_final = dimension_scores_v2.copy()

goat_final["GOAT_Score"] = (
    0.20 * goat_final["Production"]
    + 0.15 * goat_final["Efficiency"]
    + 0.20 * goat_final["Playoffs"]
    + 0.20 * goat_final["Individual"]
    + 0.10 * goat_final["Team Success"]
    + 0.15 * goat_final["Longevity"]
)

goat_final["GOAT_Score"] = goat_final["GOAT_Score"].round(1)

goat_final = goat_final.sort_values(
    "GOAT_Score",
    ascending=False
)

goat_final["Rank"] = range(
    1,
    len(goat_final) + 1
)

display(goat_final)

,Production,Efficiency,Playoffs,Individual,Team Success,Longevity,GOAT_Score,Rank
Name,,,,,,,,
LeBron James,99.584358,80.754000,82.0710,80.641212,66.666667,99.866667,86.2,1
Michael Jordan,98.552928,76.249333,79.2835,81.837862,100.000000,69.116667,83.7,2
Kareem Abdul-Jabbar,97.467670,93.030000,48.3375,81.647473,100.000000,92.500000,83.3,3
Magic Johnson,98.959156,93.278000,75.9885,44.950281,83.333333,63.850000,75.9,4
Larry Bird,98.704536,72.044000,52.0720,48.804220,50.000000,61.200000,64.9,5

In [289]:
scenarios = {

    "Balanced": {
        "Production": 0.20,
        "Efficiency": 0.15,
        "Playoffs": 0.20,
        "Individual": 0.20,
        "Team Success": 0.10,
        "Longevity": 0.15
    },

    "Peak": {
        "Production": 0.30,
        "Efficiency": 0.15,
        "Playoffs": 0.30,
        "Individual": 0.15,
        "Team Success": 0.05,
        "Longevity": 0.05
    },

    "Longevity": {
        "Production": 0.15,
        "Efficiency": 0.10,
        "Playoffs": 0.15,
        "Individual": 0.15,
        "Team Success": 0.05,
        "Longevity": 0.40
    },

    "Winning": {
        "Production": 0.10,
        "Efficiency": 0.10,
        "Playoffs": 0.30,
        "Individual": 0.15,
        "Team Success": 0.25,
        "Longevity": 0.10
    },

    "Individual Dominance": {
        "Production": 0.25,
        "Efficiency": 0.10,
        "Playoffs": 0.15,
        "Individual": 0.35,
        "Team Success": 0.05,
        "Longevity": 0.10
    }
}

In [290]:
for scenario, weights in scenarios.items():
    print(
        scenario,
        "→",
        round(sum(weights.values()), 2)
    )

Balanced → 1.0
Peak → 1.0
Longevity → 1.0
Winning → 1.0
Individual Dominance → 1.0

In [291]:
scenario_scores = pd.DataFrame(
    index=dimension_scores_v2.index
)

for scenario, weights in scenarios.items():

    scenario_scores[scenario] = sum(
        dimension_scores_v2[dimension] * weight
        for dimension, weight in weights.items()
    )

scenario_scores = scenario_scores.round(1)

display(scenario_scores)

                     Balanced  Peak  Longevity  Winning  Individual Dominance
Name
Kareem Abdul-Jabbar      83.3  79.6       85.4     80.0                  83.7
Larry Bird               64.9  68.9       64.1     58.6                  65.4
LeBron James             86.2  87.0       90.7     81.4                  86.8
Magic Johnson            75.9  80.6       72.0     76.0                  71.8
Michael Jordan           83.7  85.5       79.2     85.5                  84.7

In [292]:
scenario_rankings = scenario_scores.rank(
    ascending=False,
    method="min"
).astype(int)

display(scenario_rankings)

                     Balanced  Peak  Longevity  Winning  Individual Dominance
Name
Kareem Abdul-Jabbar         3     4          2        3                     3
Larry Bird                  5     5          5        5                     5
LeBron James                1     1          1        2                     1
Magic Johnson               4     3          4        4                     4
Michael Jordan              2     2          3        1                     2

In [293]:
scenario_winners = pd.DataFrame({
    "Winner": scenario_scores.idxmax(),
    "Score": scenario_scores.max()
})

display(scenario_winners)

                              Winner  Score
Balanced                LeBron James   86.2
Peak                    LeBron James   87.0
Longevity               LeBron James   90.7
Winning               Michael Jordan   85.5
Individual Dominance    LeBron James   86.8

In [294]:
final_dashboard = dimension_scores_v2.copy()

final_dashboard["GOAT Score"] = (
    0.20 * final_dashboard["Production"]
    + 0.15 * final_dashboard["Efficiency"]
    + 0.20 * final_dashboard["Playoffs"]
    + 0.20 * final_dashboard["Individual"]
    + 0.10 * final_dashboard["Team Success"]
    + 0.15 * final_dashboard["Longevity"]
)

final_dashboard["GOAT Score"] = (
    final_dashboard["GOAT Score"].round(1)
)

final_dashboard["Rank"] = (
    final_dashboard["GOAT Score"]
    .rank(
        ascending=False,
        method="min"
    )
    .astype(int)
)

final_dashboard = (
    final_dashboard
    .sort_values("GOAT Score", ascending=False)
)

display(final_dashboard)

,Production,Efficiency,Playoffs,Individual,Team Success,Longevity,GOAT Score,Rank
Name,,,,,,,,
LeBron James,99.584358,80.754000,82.0710,80.641212,66.666667,99.866667,86.2,1
Michael Jordan,98.552928,76.249333,79.2835,81.837862,100.000000,69.116667,83.7,2
Kareem Abdul-Jabbar,97.467670,93.030000,48.3375,81.647473,100.000000,92.500000,83.3,3
Magic Johnson,98.959156,93.278000,75.9885,44.950281,83.333333,63.850000,75.9,4
Larry Bird,98.704536,72.044000,52.0720,48.804220,50.000000,61.200000,64.9,5

In [295]:
for scenario in scenario_scores.columns:
    final_dashboard[scenario] = (
        scenario_scores[scenario]
    )

display(final_dashboard.round(1))

,Production,Efficiency,Playoffs,Individual,Team Success,Longevity,GOAT Score,Rank,Balanced,Peak,Winning,Individual Dominance
Name,,,,,,,,,,,,
LeBron James,99.6,80.8,82.1,80.6,66.7,90.7,86.2,1,86.2,87.0,81.4,86.8
Michael Jordan,98.6,76.2,79.3,81.8,100.0,79.2,83.7,2,83.7,85.5,85.5,84.7
Kareem Abdul-Jabbar,97.5,93.0,48.3,81.6,100.0,85.4,83.3,3,83.3,79.6,80.0,83.7
Magic Johnson,99.0,93.3,76.0,45.0,83.3,72.0,75.9,4,75.9,80.6,76.0,71.8
Larry Bird,98.7,72.0,52.1,48.8,50.0,64.1,64.9,5,64.9,68.9,58.6,65.4

In [296]:
dashboard_long = (
    dimension_scores_v2
    .reset_index()
    .melt(
        id_vars="Name",
        var_name="Dimension",
        value_name="Score"
    )
)

display(dashboard_long.head(20))

                   Name   Dimension      Score
0   Kareem Abdul-Jabbar  Production  97.467670
1            Larry Bird  Production  98.704536
2          LeBron James  Production  99.584358
3         Magic Johnson  Production  98.959156
4        Michael Jordan  Production  98.552928
5   Kareem Abdul-Jabbar  Efficiency  93.030000
6            Larry Bird  Efficiency  72.044000
7          LeBron James  Efficiency  80.754000
8         Magic Johnson  Efficiency  93.278000
9        Michael Jordan  Efficiency  76.249333
10  Kareem Abdul-Jabbar    Playoffs  48.337500
11           Larry Bird    Playoffs  52.072000
12         LeBron James    Playoffs  82.071000
13        Magic Johnson    Playoffs  75.988500
14       Michael Jordan    Playoffs  79.283500
15  Kareem Abdul-Jabbar  Individual  81.647473
16           Larry Bird  Individual  48.804220
17         LeBron James  Individual  80.641212
18        Magic Johnson  Individual  44.950281
19       Michael Jordan  Individual  81.837862

In [297]:
print("Dimensions :", dashboard_long.shape)
print("\nNombre de joueurs :", dashboard_long["Name"].nunique())
print("Nombre de dimensions :", dashboard_long["Dimension"].nunique())

print("\nDimensions :")
print(dashboard_long["Dimension"].unique())

Dimensions : (30, 3)

Nombre de joueurs : 5
Nombre de dimensions : 6

Dimensions :
['Production' 'Efficiency' 'Playoffs' 'Individual' 'Team Success'
 'Longevity']

In [298]:
goat_master["peak_production_z"]

Name
Kareem Abdul-Jabbar    2.892
Larry Bird             2.435
LeBron James           3.009
Magic Johnson          2.619
Michael Jordan         2.619
Name: peak_production_z, dtype: float64

In [299]:
peak_production_score = (
    norm.cdf(
        goat_master["peak_production_z"]
    ) * 100
)

In [300]:
peak_efficiency_score = ts_plus_score(
    goat_master["peak_ts_plus"]
)

In [301]:
goat_master["best_mvp_share"] = (
    individual_success["best_mvp_share"]
)

In [302]:
peak_mvp_score = (
    goat_master["best_mvp_share"] * 100
).clip(0, 100)

In [303]:
true_peak = pd.DataFrame(
    index=goat_master.index
)

true_peak["Peak Production"] = peak_production_score

true_peak["Peak Efficiency"] = peak_efficiency_score

true_peak["Playoffs"] = (
    playoffs_v2["Playoffs_Score_v2"]
)

true_peak["Peak MVP"] = peak_mvp_score

In [304]:
true_peak["True Peak Score"] = (
    0.30 * true_peak["Peak Production"]
    + 0.20 * true_peak["Peak Efficiency"]
    + 0.30 * true_peak["Playoffs"]
    + 0.20 * true_peak["Peak MVP"]
)

true_peak = (
    true_peak
    .sort_values(
        "True Peak Score",
        ascending=False
    )
)

true_peak["Peak Rank"] = range(
    1,
    len(true_peak) + 1
)

display(
    true_peak.round(1)
)

,Peak Production,Peak Efficiency,Playoffs,Peak MVP,True Peak Score,Peak Rank
Name,,,,,,
LeBron James,99.9,100.0,82.1,99.8,94.5,1
Michael Jordan,99.6,94.4,79.3,98.6,92.3,2
Magic Johnson,99.6,100.0,76.0,94.0,91.5,3
Larry Bird,99.3,91.2,52.1,98.1,83.3,4
Kareem Abdul-Jabbar,99.8,100.0,48.3,89.5,82.3,5

In [305]:
# 03 — GOAT MASTER
goat_master.reset_index().to_csv(
    "03_goat_master.csv",
    index=False
)

# 04 — DIMENSIONS
dimension_scores_v2.reset_index().to_csv(
    "04_goat_dimensions.csv",
    index=False
)

# 05 — SCENARIOS
scenario_scores.reset_index().to_csv(
    "05_goat_scenarios.csv",
    index=False
)

# 06 — TRUE PEAK
true_peak.reset_index().to_csv(
    "06_goat_peak.csv",
    index=False
)

In [306]:
import os

for file in [
    "03_goat_master.csv",
    "04_goat_dimensions.csv",
    "05_goat_scenarios.csv",
    "06_goat_peak.csv"
]:
    print(
        file,
        "→",
        os.path.exists(file),
        "|",
        round(os.path.getsize(file) / 1024, 2),
        "KB"
    )

03_goat_master.csv → True | 0.75 KB
04_goat_dimensions.csv → True | 0.53 KB
05_goat_scenarios.csv → True | 0.25 KB
06_goat_peak.csv → True | 0.45 KB

In [307]:
goat_player_seasons_export = df_era[
    df_era["Name"].isin(goat_players)
][
    [
        "Name",
        "PLAYER_ID",
        "SEASON_ID",
        "TEAM_ABBREVIATION",
        "PLAYER_AGE",
        "GP",
        "MIN",
        "PTS",
        "REB",
        "AST",
        "PPG",
        "RPG",
        "APG",
        "PPG_Z",
        "RPG_Z",
        "APG_Z",
        "PRODUCTION_Z",
        "TS_PCT",
        "TS_PLUS",
        "TS_Z"
    ]
].copy()

goat_player_seasons_export.to_csv(
    "07_goat_player_seasons.csv",
    index=False
)

print(
    "07_goat_player_seasons.csv →",
    os.path.exists("07_goat_player_seasons.csv"),
    "|",
    round(
        os.path.getsize("07_goat_player_seasons.csv") / 1024,
        2
    ),
    "KB"
)

07_goat_player_seasons.csv → True | 18.88 KB

In [308]:
methodology = pd.DataFrame([
    {
        "dimension": "Production",
        "weight_balanced": 0.20,
        "metrics": "Career Production Z; Peak Production Z",
        "method": "Era-adjusted Z-scores",
        "purpose": "Measure statistical dominance relative to each NBA era"
    },
    {
        "dimension": "Efficiency",
        "weight_balanced": 0.15,
        "metrics": "Career TS+; Peak TS+",
        "method": "True Shooting relative to league environment",
        "purpose": "Measure scoring efficiency adjusted for era"
    },
    {
        "dimension": "Playoffs",
        "weight_balanced": 0.20,
        "metrics": "PO RAPTOR; RAPTOR Uplift; TS Uplift",
        "method": "Regular Season vs Playoffs comparison",
        "purpose": "Measure postseason level and ability to maintain or improve performance"
    },
    {
        "dimension": "Individual Success",
        "weight_balanced": 0.20,
        "metrics": "MVP; MVP Share; All-NBA; All-Defense",
        "method": "Benchmark normalization",
        "purpose": "Measure individual recognition and sustained elite status"
    },
    {
        "dimension": "Team Success",
        "weight_balanced": 0.10,
        "metrics": "NBA Championships",
        "method": "Historical championships benchmark",
        "purpose": "Measure contribution within successful team contexts"
    },
    {
        "dimension": "Longevity",
        "weight_balanced": 0.15,
        "metrics": "Career Seasons; Career Games; Elite Seasons",
        "method": "Career and elite longevity benchmarks",
        "purpose": "Measure duration of sustained elite performance"
    }
])

methodology.to_csv(
    "08_methodology.csv",
    index=False
)

display(methodology)

,dimension,weight_balanced,metrics,method,purpose
0,Production,0.20,Career Production Z; Peak Production Z,Era-adjusted Z-scores,Measure statistical dominance relative to each...
1,Efficiency,0.15,Career TS+; Peak TS+,True Shooting relative to league environment,Measure scoring efficiency adjusted for era
2,Playoffs,0.20,PO RAPTOR; RAPTOR Uplift; TS Uplift,Regular Season vs Playoffs comparison,Measure postseason level and ability to mainta...
3,Individual Success,0.20,MVP; MVP Share; All-NBA; All-Defense,Benchmark normalization,Measure individual recognition and sustained e...
4,Team Success,0.10,NBA Championships,Historical championships benchmark,Measure contribution within successful team co...
5,Longevity,0.15,Career Seasons; Career Games; Elite Seasons,Career and elite longevity benchmarks,Measure duration of sustained elite performance

In [309]:
for file in [
    "07_goat_player_seasons.csv",
    "08_methodology.csv"
]:
    print(
        file,
        "→",
        os.path.exists(file),
        "|",
        round(os.path.getsize(file) / 1024, 2),
        "KB"
    )

07_goat_player_seasons.csv → True | 18.88 KB
08_methodology.csv → True | 0.85 KB

In [310]:
import pandas as pd
import os

game_path = "/root/.cache/kagglehub/datasets/wyattowalsh/basketball/versions/238/csv/game.csv"

df_game = pd.read_csv(
    game_path,
    low_memory=False
)

print("Dimensions :", df_game.shape)

print(
    "\nTypes de matchs :\n",
    df_game["season_type"].value_counts()
)

print(
    "\nPériode :",
    df_game["game_date"].min(),
    "→",
    df_game["game_date"].max()
)

Dimensions : (65698, 55)

Types de matchs :
 season_type
Regular Season    60192
Playoffs           3842
Pre Season         1536
All Star             65
All-Star             63
Name: count, dtype: int64

Période : 1946-11-01 00:00:00 → 2023-06-12 00:00:00

In [311]:
games_rs = df_game[
    df_game["season_type"] == "Regular Season"
].copy()

print("Matchs Regular Season :", len(games_rs))

Matchs Regular Season : 60192

In [312]:
home = pd.DataFrame({
    "season_id": games_rs["season_id"],
    "game_id": games_rs["game_id"],
    "game_date": games_rs["game_date"],

    "team_id": games_rs["team_id_home"],
    "team": games_rs["team_abbreviation_home"],
    "team_name": games_rs["team_name_home"],

    "win": (games_rs["wl_home"] == "W").astype(int),

    "PTS": games_rs["pts_home"],
    "FG_PCT": games_rs["fg_pct_home"],
    "FG3_PCT": games_rs["fg3_pct_home"],
    "FT_PCT": games_rs["ft_pct_home"],

    "REB": games_rs["reb_home"],
    "OREB": games_rs["oreb_home"],
    "DREB": games_rs["dreb_home"],

    "AST": games_rs["ast_home"],
    "STL": games_rs["stl_home"],
    "BLK": games_rs["blk_home"],
    "TOV": games_rs["tov_home"],
    "PF": games_rs["pf_home"]
})

In [313]:
away = pd.DataFrame({
    "season_id": games_rs["season_id"],
    "game_id": games_rs["game_id"],
    "game_date": games_rs["game_date"],

    "team_id": games_rs["team_id_away"],
    "team": games_rs["team_abbreviation_away"],
    "team_name": games_rs["team_name_away"],

    "win": (games_rs["wl_away"] == "W").astype(int),

    "PTS": games_rs["pts_away"],
    "FG_PCT": games_rs["fg_pct_away"],
    "FG3_PCT": games_rs["fg3_pct_away"],
    "FT_PCT": games_rs["ft_pct_away"],

    "REB": games_rs["reb_away"],
    "OREB": games_rs["oreb_away"],
    "DREB": games_rs["dreb_away"],

    "AST": games_rs["ast_away"],
    "STL": games_rs["stl_away"],
    "BLK": games_rs["blk_away"],
    "TOV": games_rs["tov_away"],
    "PF": games_rs["pf_away"]
})

In [314]:
team_games = pd.concat(
    [home, away],
    ignore_index=True
)

print("Dimensions team_games :", team_games.shape)

display(team_games.head())

Dimensions team_games : (120384, 19)

,season_id,game_id,game_date,team_id,team,team_name,win,PTS,FG_PCT,FG3_PCT,FT_PCT,REB,OREB,DREB,AST,STL,BLK,TOV,PF
0,21946,24600001,1946-11-01 00:00:00,1610610035,HUS,Toronto Huskies,0,66.0,NaN,NaN,0.552,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,21946,24600003,1946-11-02 00:00:00,1610610034,BOM,St. Louis Bombers,1,56.0,0.339,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21.0
2,21946,24600002,1946-11-02 00:00:00,1610610032,PRO,Providence Steamrollers,1,59.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,21946,24600004,1946-11-02 00:00:00,1610610025,CHS,Chicago Stags,1,63.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20.0
4,21946,24600005,1946-11-02 00:00:00,1610610028,DEF,Detroit Falcons,0,33.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [315]:
team_season = (
    team_games
    .groupby(
        ["season_id", "team_id", "team", "team_name"],
        as_index=False
    )
    .agg(
        games=("game_id", "nunique"),
        wins=("win", "sum"),

        avg_pts=("PTS", "mean"),
        avg_fg_pct=("FG_PCT", "mean"),
        avg_fg3_pct=("FG3_PCT", "mean"),
        avg_ft_pct=("FT_PCT", "mean"),

        avg_reb=("REB", "mean"),
        avg_oreb=("OREB", "mean"),
        avg_dreb=("DREB", "mean"),

        avg_ast=("AST", "mean"),
        avg_stl=("STL", "mean"),
        avg_blk=("BLK", "mean"),
        avg_tov=("TOV", "mean"),
        avg_pf=("PF", "mean")
    )
)

In [316]:
team_season["losses"] = (
    team_season["games"]
    - team_season["wins"]
)

team_season["win_rate"] = (
    team_season["wins"]
    / team_season["games"]
)

In [317]:
display(
    team_season
    .sort_values(
        "win_rate",
        ascending=False
    )
    .head(20)
)

,season_id,team_id,team,team_name,games,wins,avg_pts,avg_fg_pct,avg_fg3_pct,avg_ft_pct,avg_reb,avg_oreb,avg_dreb,avg_ast,avg_stl,avg_blk,avg_tov,avg_pf,losses,win_rate
1286,22015,1610612744,GSW,Golden State Warriors,82,73,114.890244,0.488476,0.414232,0.767841,46.195122,9.951220,36.243902,28.939024,8.402439,6.073171,15.182927,20.743902,9,0.890244
721,21995,1610612741,CHI,Chicago Bulls,82,72,105.182927,0.478524,0.399366,0.746927,44.609756,15.207317,29.402439,24.792683,9.085366,4.207317,13.829268,22.036585,10,0.878049
219,21971,1610612747,LAL,Los Angeles Lakers,82,69,120.975610,0.519000,NaN,0.735695,51.000000,NaN,NaN,28.000000,NaN,NaN,NaN,19.939024,13,0.841463
750,21996,1610612741,CHI,Chicago Bulls,82,69,103.146341,0.473817,0.372061,0.745951,45.073171,15.060976,30.012195,26.121951,8.731707,4.048780,13.524390,19.719512,13,0.841463
230,21972,1610612738,BOS,Boston Celtics,82,68,112.658537,NaN,NaN,0.777476,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22.024390,14,0.829268
843,21999,1610612747,LAL,Los Angeles Lakers,82,67,100.817073,0.459793,0.322793,0.695183,47.012195,13.621951,33.390244,23.426829,7.475610,6.512195,13.939024,22.451220,15,0.817073
1316,22016,1610612744,GSW,Golden State Warriors,82,67,115.890244,0.495963,0.385951,0.784232,44.426829,9.390244,35.036585,30.378049,9.573171,6.768293,14.768293,19.329268,15,0.817073
1256,22014,1610612744,GSW,Golden State Warriors,82,67,109.951220,0.479232,0.397878,0.767378,44.719512,10.402439,34.317073,27.414634,9.292683,6.048780,14.451220,19.853659,15,0.817073
1301,22015,1610612759,SAS,San Antonio Spurs,82,67,103.536585,0.484744,0.379695,0.807793,43.914634,9.390244,34.524390,24.512195,8.256098,5.914634,13.060976,17.475610,15,0.817073
463,21985,1610612738,BOS,Boston Celtics,82,67,114.134146,0.509817,0.323073,0.790268,46.426829,12.890244,33.536585,28.987805,7.780488,6.231707,16.268293,21.439024,15,0.817073
613,21991,1610612741,CHI,Chicago Bulls,82,67,109.890244,0.509280,0.297111,0.742110,44.048780,14.304878,29.743902,27.792683,8.195122,5.853659,12.804878,20.646341,15,0.817073
1044,22006,1610612742,DAL,Dallas Mavericks,82,67,100.012195,0.468951,0.381829,0.807610,41.890244,11.219512,30.670732,19.902439,6.829268,4.975610,13.902439,22.402439,15,0.817073
7,21946,1610610036,WAS,Washington Capitols,60,49,73.800000,NaN,NaN,0.732235,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18.720930,11,0.816667
1070,22007,1610612738,BOS,Boston Celtics,82,66,100.548780,0.475902,0.376768,0.769500,42.012195,10.121951,31.890244,22.353659,8.487805,4.621951,15.195122,22.731707,16,0.804878
1101,22008,1610612739,CLE,Cleveland Cavaliers,82,66,100.280488,0.469220,0.394268,0.756134,42.195122,10.804878,31.390244,20.280488,7.231707,5.304878,12.743902,20.280488,16,0.804878
45,21949,1610612755,SYR,Syracuse Nationals,64,51,84.859375,0.413000,NaN,0.718885,NaN,NaN,NaN,NaN,NaN,NaN,NaN,29.500000,13,0.796875
494,21986,1610612747,LAL,Los Angeles Lakers,82,65,117.756098,0.516354,0.392646,0.787427,44.414634,13.743902,30.670732,29.621951,8.878049,5.841463,16.378049,22.597561,17,0.792683
407,21982,1610612755,PHL,Philadelphia 76ers,82,65,112.085366,0.499317,0.193300,0.737963,47.926829,15.187500,NaN,24.573171,10.043478,7.037037,19.600000,24.902439,17,0.792683
1109,22008,1610612747,LAL,Los Angeles Lakers,82,65,106.926829,0.474854,0.365341,0.767927,43.926829,12.378049,31.548780,23.268293,8.756098,5.121951,13.451220,20.707317,17,0.792683
1347,22017,1610612745,HOU,Houston Rockets,82,65,112.353659,0.460305,0.363829,0.780232,43.463415,9.012195,34.451220,21.548780,8.524390,4.780488,13.841463,19.475610,17,0.792683

In [318]:
print("Dimensions :", team_season.shape)

print(
    "\nSaisons :",
    team_season["season_id"].nunique()
)

print(
    "\nÉquipes :",
    team_season["team"].nunique()
)

print(
    "\nWin rate :"
)

print(
    team_season["win_rate"].describe()
)

Dimensions : (1519, 20)

Saisons : 70

Équipes : 72

Win rate :
count    1519.000000
mean        0.499789
std         0.150576
min         0.106061
25%         0.390244
50%         0.512195
75%         0.609756
max         0.890244
Name: win_rate, dtype: float64

In [319]:
display(
    team_season[
        [
            "season_id",
            "team",
            "games",
            "wins",
            "losses",
            "win_rate",
            "avg_pts",
            "avg_fg_pct",
            "avg_fg3_pct",
            "avg_reb",
            "avg_ast",
            "avg_stl",
            "avg_blk",
            "avg_tov"
        ]
    ]
    .sort_values(
        ["season_id", "win_rate"],
        ascending=[False, False]
    )
    .head(20)
)

,season_id,team,games,wins,losses,win_rate,avg_pts,avg_fg_pct,avg_fg3_pct,avg_reb,avg_ast,avg_stl,avg_blk,avg_tov
1501,22022,MIL,82,58,24,0.707317,116.939024,0.474098,0.367915,48.634146,25.792683,6.353659,4.914634,14.621951
1490,22022,BOS,82,57,25,0.695122,117.939024,0.476305,0.375402,45.329268,26.658537,6.353659,5.243902,13.353659
1507,22022,PHI,82,54,28,0.658537,115.219512,0.487695,0.385012,40.926829,25.158537,7.743902,4.743902,13.670732
1495,22022,DEN,82,53,29,0.646341,115.792683,0.505366,0.376012,43.012195,28.878049,7.536585,4.487805,14.536585
1491,22022,CLE,82,51,31,0.621951,112.256098,0.489512,0.366317,41.085366,24.939024,7.146341,4.682927,13.341463
1515,22022,MEM,82,51,31,0.621951,116.914634,0.475232,0.349780,46.621951,26.036585,8.292683,5.768293,13.609756
1510,22022,SAC,82,48,34,0.585366,120.707317,0.494573,0.367720,42.451220,27.280488,7.000000,3.353659,13.487805
1504,22022,NYK,82,47,35,0.573171,116.024390,0.471073,0.353841,46.597561,22.926829,6.426829,4.146341,12.987805
1503,22022,BKN,82,45,37,0.548780,113.353659,0.488488,0.380134,40.512195,25.524390,7.134146,6.170732,13.743902
1508,22022,PHX,82,45,37,0.548780,113.646341,0.468098,0.371317,44.243902,27.256098,7.134146,5.268293,13.536585
1496,22022,GSW,82,44,38,0.536585,118.939024,0.479793,0.384634,44.597561,29.829268,7.170732,3.939024,16.292683
1498,22022,LAC,82,44,38,0.536585,113.585366,0.479122,0.376829,43.231707,23.890244,7.073171,4.439024,14.231707
1500,22022,MIA,82,44,38,0.536585,109.475610,0.460451,0.344317,40.597561,23.841463,7.987805,2.963415,13.487805
1499,22022,LAL,82,43,39,0.524390,117.170732,0.483098,0.348037,45.707317,25.268293,6.414634,4.609756,14.073171
1492,22022,NOP,82,42,40,0.512195,114.365854,0.481354,0.361561,43.695122,25.878049,8.304878,4.109756,14.585366
1502,22022,MIN,82,42,40,0.512195,115.780488,0.492037,0.363512,41.890244,26.158537,8.012195,5.414634,15.341463
1489,22022,ATL,82,41,41,0.500000,118.426829,0.484329,0.353390,44.378049,24.987805,7.073171,4.890244,12.926829
1513,22022,TOR,82,41,41,0.500000,112.853659,0.459561,0.336159,43.024390,23.914634,9.414634,5.170732,11.658537
1493,22022,CHI,82,40,42,0.487805,113.121951,0.491451,0.357000,42.353659,24.463415,7.853659,4.524390,13.378049
1512,22022,OKC,82,40,42,0.487805,117.475610,0.466585,0.356890,43.646341,24.414634,8.243902,4.158537,13.036585

In [320]:
home = pd.DataFrame({
    "season_id": games_rs["season_id"],
    "game_id": games_rs["game_id"],
    "game_date": games_rs["game_date"],

    "team_id": games_rs["team_id_home"],
    "team": games_rs["team_abbreviation_home"],
    "team_name": games_rs["team_name_home"],

    "win": (games_rs["wl_home"] == "W").astype(int),

    # TEAM
    "PTS": games_rs["pts_home"],
    "FG_PCT": games_rs["fg_pct_home"],
    "FG3_PCT": games_rs["fg3_pct_home"],
    "FT_PCT": games_rs["ft_pct_home"],
    "REB": games_rs["reb_home"],
    "OREB": games_rs["oreb_home"],
    "DREB": games_rs["dreb_home"],
    "AST": games_rs["ast_home"],
    "STL": games_rs["stl_home"],
    "BLK": games_rs["blk_home"],
    "TOV": games_rs["tov_home"],
    "PF": games_rs["pf_home"],

    # OPPONENT
    "OPP_PTS": games_rs["pts_away"],
    "OPP_FG_PCT": games_rs["fg_pct_away"],
    "OPP_FG3_PCT": games_rs["fg3_pct_away"],
    "OPP_REB": games_rs["reb_away"],
    "OPP_AST": games_rs["ast_away"],
    "OPP_TOV": games_rs["tov_away"]
})

In [321]:
away = pd.DataFrame({
    "season_id": games_rs["season_id"],
    "game_id": games_rs["game_id"],
    "game_date": games_rs["game_date"],

    "team_id": games_rs["team_id_away"],
    "team": games_rs["team_abbreviation_away"],
    "team_name": games_rs["team_name_away"],

    "win": (games_rs["wl_away"] == "W").astype(int),

    # TEAM
    "PTS": games_rs["pts_away"],
    "FG_PCT": games_rs["fg_pct_away"],
    "FG3_PCT": games_rs["fg3_pct_away"],
    "FT_PCT": games_rs["ft_pct_away"],
    "REB": games_rs["reb_away"],
    "OREB": games_rs["oreb_away"],
    "DREB": games_rs["dreb_away"],
    "AST": games_rs["ast_away"],
    "STL": games_rs["stl_away"],
    "BLK": games_rs["blk_away"],
    "TOV": games_rs["tov_away"],
    "PF": games_rs["pf_away"],

    # OPPONENT
    "OPP_PTS": games_rs["pts_home"],
    "OPP_FG_PCT": games_rs["fg_pct_home"],
    "OPP_FG3_PCT": games_rs["fg3_pct_home"],
    "OPP_REB": games_rs["reb_home"],
    "OPP_AST": games_rs["ast_home"],
    "OPP_TOV": games_rs["tov_home"]
})

In [322]:
team_games = pd.concat(
    [home, away],
    ignore_index=True
)

team_games["POINT_DIFF"] = (
    team_games["PTS"] -
    team_games["OPP_PTS"]
)

display(team_games.head())

,season_id,game_id,game_date,team_id,team,team_name,win,PTS,FG_PCT,FG3_PCT,...,BLK,TOV,PF,OPP_PTS,OPP_FG_PCT,OPP_FG3_PCT,OPP_REB,OPP_AST,OPP_TOV,POINT_DIFF
0,21946,24600001,1946-11-01 00:00:00,1610610035,HUS,Toronto Huskies,0,66.0,NaN,NaN,...,NaN,NaN,NaN,68.0,NaN,NaN,NaN,NaN,NaN,-2.0
1,21946,24600003,1946-11-02 00:00:00,1610610034,BOM,St. Louis Bombers,1,56.0,0.339,NaN,...,NaN,NaN,21.0,51.0,0.222,NaN,NaN,NaN,NaN,5.0
2,21946,24600002,1946-11-02 00:00:00,1610610032,PRO,Providence Steamrollers,1,59.0,NaN,NaN,...,NaN,NaN,NaN,53.0,NaN,NaN,NaN,NaN,NaN,6.0
3,21946,24600004,1946-11-02 00:00:00,1610610025,CHS,Chicago Stags,1,63.0,NaN,NaN,...,NaN,NaN,20.0,47.0,NaN,NaN,NaN,NaN,NaN,16.0
4,21946,24600005,1946-11-02 00:00:00,1610610028,DEF,Detroit Falcons,0,33.0,NaN,NaN,...,NaN,NaN,NaN,50.0,NaN,NaN,NaN,NaN,NaN,-17.0

In [323]:
team_season = (
    team_games
    .groupby(
        ["season_id", "team_id", "team", "team_name"],
        as_index=False
    )
    .agg(
        games=("game_id", "nunique"),
        wins=("win", "sum"),

        avg_pts=("PTS", "mean"),
        avg_opp_pts=("OPP_PTS", "mean"),
        point_diff=("POINT_DIFF", "mean"),

        avg_fg_pct=("FG_PCT", "mean"),
        avg_fg3_pct=("FG3_PCT", "mean"),
        avg_ft_pct=("FT_PCT", "mean"),

        avg_reb=("REB", "mean"),
        avg_oreb=("OREB", "mean"),
        avg_dreb=("DREB", "mean"),
        avg_ast=("AST", "mean"),
        avg_stl=("STL", "mean"),
        avg_blk=("BLK", "mean"),
        avg_tov=("TOV", "mean"),

        opp_fg_pct=("OPP_FG_PCT", "mean"),
        opp_fg3_pct=("OPP_FG3_PCT", "mean"),
        opp_reb=("OPP_REB", "mean"),
        opp_ast=("OPP_AST", "mean"),
        opp_tov=("OPP_TOV", "mean")
    )
)

team_season["losses"] = (
    team_season["games"] -
    team_season["wins"]
)

team_season["win_rate"] = (
    team_season["wins"] /
    team_season["games"]
)

In [324]:
display(
    team_season[
        team_season["season_id"] == 22022
    ][
        [
            "team",
            "games",
            "wins",
            "losses",
            "win_rate",
            "avg_pts",
            "avg_opp_pts",
            "point_diff",
            "avg_fg_pct",
            "avg_fg3_pct",
            "avg_ast",
            "avg_reb",
            "avg_tov"
        ]
    ]
    .sort_values(
        "win_rate",
        ascending=False
    )
    .head(15)
    .round(3)
)

,team,games,wins,losses,win_rate,avg_pts,avg_opp_pts,point_diff,avg_fg_pct,avg_fg3_pct,avg_ast,avg_reb,avg_tov
1501,MIL,82,58,24,0.707,116.939,113.305,3.634,0.474,0.368,25.793,48.634,14.622
1490,BOS,82,57,25,0.695,117.939,111.415,6.524,0.476,0.375,26.659,45.329,13.354
1507,PHI,82,54,28,0.659,115.220,110.902,4.317,0.488,0.385,25.159,40.927,13.671
1495,DEN,82,53,29,0.646,115.793,112.463,3.329,0.505,0.376,28.878,43.012,14.537
1515,MEM,82,51,31,0.622,116.915,112.976,3.939,0.475,0.350,26.037,46.622,13.610
1491,CLE,82,51,31,0.622,112.256,106.878,5.378,0.490,0.366,24.939,41.085,13.341
1510,SAC,82,48,34,0.585,120.707,118.061,2.646,0.495,0.368,27.280,42.451,13.488
1504,NYK,82,47,35,0.573,116.024,113.098,2.927,0.471,0.354,22.927,46.598,12.988
1503,BKN,82,45,37,0.549,113.354,112.500,0.854,0.488,0.380,25.524,40.512,13.744
1508,PHX,82,45,37,0.549,113.646,111.573,2.073,0.468,0.371,27.256,44.244,13.537
1500,MIA,82,44,38,0.537,109.476,109.793,-0.317,0.460,0.344,23.841,40.598,13.488
1498,LAC,82,44,38,0.537,113.585,113.085,0.500,0.479,0.377,23.890,43.232,14.232
1496,GSW,82,44,38,0.537,118.939,117.134,1.805,0.480,0.385,29.829,44.598,16.293
1499,LAL,82,43,39,0.524,117.171,116.598,0.573,0.483,0.348,25.268,45.707,14.073
1492,NOP,82,42,40,0.512,114.366,112.476,1.890,0.481,0.362,25.878,43.695,14.585

In [325]:
winning_metrics = [
    "avg_pts",
    "avg_opp_pts",
    "point_diff",
    "avg_fg_pct",
    "avg_fg3_pct",
    "avg_ft_pct",
    "avg_reb",
    "avg_oreb",
    "avg_dreb",
    "avg_ast",
    "avg_stl",
    "avg_blk",
    "avg_tov",
    "opp_fg_pct",
    "opp_fg3_pct",
    "opp_reb",
    "opp_ast",
    "opp_tov"
]

winning_corr = (
    team_season[
        ["win_rate"] + winning_metrics
    ]
    .corr(numeric_only=True)["win_rate"]
    .drop("win_rate")
    .sort_values(ascending=False)
)

display(
    winning_corr
    .to_frame("correlation_with_win_rate")
    .round(3)
)

             correlation_with_win_rate
point_diff                       0.966
avg_dreb                         0.296
avg_fg_pct                       0.247
avg_ast                          0.243
avg_pts                          0.223
avg_blk                          0.195
avg_fg3_pct                      0.167
avg_reb                          0.131
avg_ft_pct                       0.087
avg_stl                          0.081
opp_tov                         -0.020
opp_fg3_pct                     -0.079
avg_oreb                        -0.090
opp_reb                         -0.149
avg_tov                         -0.219
opp_ast                         -0.235
avg_opp_pts                     -0.235
opp_fg_pct                      -0.242

In [326]:
features = [
    "avg_fg_pct",      # efficacité au tir
    "avg_fg3_pct",     # efficacité à 3 pts
    "avg_ft_pct",      # lancers francs
    "avg_dreb",        # rebond défensif
    "avg_ast",         # création / circulation
    "avg_stl",         # interceptions
    "avg_blk",         # protection du cercle
    "avg_tov",         # pertes de balle
]

X = team_season[features].copy()
y = team_season["win_rate"].copy()

In [327]:
model_data = pd.concat(
    [X, y],
    axis=1
).dropna()

X = model_data[features]
y = model_data["win_rate"]

print("Observations :", len(model_data))

Observations : 1079

In [328]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_scaled = scaler.fit_transform(X)

X_scaled = pd.DataFrame(
    X_scaled,
    columns=features,
    index=X.index
)

In [329]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()

model.fit(
    X_scaled,
    y
)

LinearRegression()

In [330]:
r2 = model.score(
    X_scaled,
    y
)

print(
    "R² :",
    round(r2, 3)
)

R² : 0.495

In [331]:
winning_factors = pd.DataFrame({
    "factor": features,
    "coefficient": model.coef_
})

winning_factors["abs_coefficient"] = (
    winning_factors["coefficient"].abs()
)

winning_factors = winning_factors.sort_values(
    "abs_coefficient",
    ascending=False
)

display(
    winning_factors.round(4)
)

        factor  coefficient  abs_coefficient
0   avg_fg_pct       0.0941           0.0941
7      avg_tov      -0.0541           0.0541
5      avg_stl       0.0390           0.0390
3     avg_dreb       0.0316           0.0316
4      avg_ast      -0.0268           0.0268
6      avg_blk       0.0255           0.0255
1  avg_fg3_pct       0.0236           0.0236
2   avg_ft_pct      -0.0036           0.0036

In [332]:
print(
    sorted(
        team_season["season_id"]
        .dropna()
        .unique()
    )[-20:]
)

[np.int64(22002), np.int64(22003), np.int64(22004), np.int64(22005), np.int64(22006), np.int64(22007), np.int64(22008), np.int64(22009), np.int64(22010), np.int64(22011), np.int64(22013), np.int64(22014), np.int64(22015), np.int64(22016), np.int64(22017), np.int64(22018), np.int64(22019), np.int64(22020), np.int64(22021), np.int64(22022)]

In [333]:
team_season["season_year"] = (
    team_season["season_id"]
    .astype(str)
    .str[-4:]
    .astype(int)
)

print(
    team_season["season_year"].min(),
    "→",
    team_season["season_year"].max()
)

1946 → 2022

In [334]:
train = team_season[
    team_season["season_year"] <= 2017
].copy()

test = team_season[
    team_season["season_year"] >= 2018
].copy()

print("TRAIN :", train.shape)
print("TEST  :", test.shape)

print(
    "Train :",
    train["season_year"].min(),
    "→",
    train["season_year"].max()
)

print(
    "Test :",
    test["season_year"].min(),
    "→",
    test["season_year"].max()
)

TRAIN : (1369, 27)
TEST  : (150, 27)
Train : 1946 → 2017
Test : 2018 → 2022

In [335]:
features = [
    "avg_fg_pct",
    "avg_fg3_pct",
    "avg_ft_pct",
    "avg_dreb",
    "avg_ast",
    "avg_stl",
    "avg_blk",
    "avg_tov"
]

train_model = train[
    features + ["win_rate"]
].dropna()

test_model = test[
    features + ["win_rate"]
].dropna()

In [336]:
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_absolute_error

scaler = StandardScaler()

X_train = scaler.fit_transform(
    train_model[features]
)

X_test = scaler.transform(
    test_model[features]
)

y_train = train_model["win_rate"]
y_test = test_model["win_rate"]

model_time = LinearRegression()

model_time.fit(
    X_train,
    y_train
)

y_pred = model_time.predict(X_test)

In [337]:
train_pred = model_time.predict(X_train)

train_r2 = r2_score(
    y_train,
    train_pred
)

test_r2 = r2_score(
    y_test,
    y_pred
)

mae = mean_absolute_error(
    y_test,
    y_pred
)

print("Train R² :", round(train_r2, 3))
print("Test R²  :", round(test_r2, 3))
print("Test MAE :", round(mae, 3))

Train R² : 0.54
Test R²  : -0.179
Test MAE : 0.129

In [338]:
print(
    "Erreur approximative en victoires :",
    round(mae * 82, 1)
)

Erreur approximative en victoires : 10.6

In [339]:
winning_factors_time = pd.DataFrame({
    "factor": features,
    "coefficient": model_time.coef_
})

winning_factors_time["abs_coefficient"] = (
    winning_factors_time["coefficient"].abs()
)

winning_factors_time = (
    winning_factors_time
    .sort_values(
        "abs_coefficient",
        ascending=False
    )
)

display(
    winning_factors_time.round(4)
)

        factor  coefficient  abs_coefficient
0   avg_fg_pct       0.0903           0.0903
7      avg_tov      -0.0583           0.0583
3     avg_dreb       0.0421           0.0421
5      avg_stl       0.0391           0.0391
1  avg_fg3_pct       0.0246           0.0246
6      avg_blk       0.0223           0.0223
4      avg_ast      -0.0128           0.0128
2   avg_ft_pct      -0.0030           0.0030

In [340]:
print("Train R² :", round(train_r2, 3))
print("Test R²  :", round(test_r2, 3))
print("Test MAE :", round(mae, 3))
print(
    "Erreur approximative en victoires :",
    round(mae * 82, 1)
)

Train R² : 0.54
Test R²  : -0.179
Test MAE : 0.129
Erreur approximative en victoires : 10.6

In [341]:
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_absolute_error
import pandas as pd

features = [
    "avg_fg_pct",
    "avg_fg3_pct",
    "avg_ft_pct",
    "avg_dreb",
    "avg_ast",
    "avg_stl",
    "avg_blk",
    "avg_tov"
]

def temporal_model(start_year):

    train = team_season[
        (team_season["season_year"] >= start_year)
        &
        (team_season["season_year"] <= 2017)
    ].copy()

    test = team_season[
        team_season["season_year"] >= 2018
    ].copy()

    train_data = train[
        features + ["win_rate"]
    ].dropna()

    test_data = test[
        features + ["win_rate"]
    ].dropna()

    scaler = StandardScaler()

    X_train = scaler.fit_transform(
        train_data[features]
    )

    X_test = scaler.transform(
        test_data[features]
    )

    y_train = train_data["win_rate"]
    y_test = test_data["win_rate"]

    model = LinearRegression()

    model.fit(
        X_train,
        y_train
    )

    train_pred = model.predict(X_train)
    test_pred = model.predict(X_test)

    return {
        "start_year": start_year,
        "train_obs": len(train_data),

        "train_r2": r2_score(
            y_train,
            train_pred
        ),

        "test_r2": r2_score(
            y_test,
            test_pred
        ),

        "test_mae": mean_absolute_error(
            y_test,
            test_pred
        )
    }

In [342]:
results = []

for start_year in [
    team_season["season_year"].min(),
    1990,
    2000,
    2010
]:
    results.append(
        temporal_model(start_year)
    )

window_results = pd.DataFrame(results)

window_results["approx_win_error"] = (
    window_results["test_mae"] * 82
)

display(
    window_results.round(3)
)

   start_year  train_obs  train_r2  test_r2  test_mae  approx_win_error
0        1946        929     0.540   -0.179     0.129            10.607
1        1990        786     0.559   -0.209     0.132            10.783
2        2000        506     0.559    0.106     0.110             9.049
3        2010        210     0.602    0.376     0.092             7.514

In [343]:
test = team_season[
    team_season["season_year"] >= 2018
].dropna(
    subset=["win_rate"]
)

train = team_season[
    team_season["season_year"] <= 2017
].dropna(
    subset=["win_rate"]
)

baseline_prediction = (
    train["win_rate"].mean()
)

baseline_pred = [
    baseline_prediction
] * len(test)

baseline_mae = mean_absolute_error(
    test["win_rate"],
    baseline_pred
)

print(
    "Baseline Win Rate :",
    round(baseline_prediction, 3)
)

print(
    "Baseline MAE :",
    round(baseline_mae, 3)
)

print(
    "Baseline ≈ erreur victoires :",
    round(baseline_mae * 82, 1)
)

Baseline Win Rate : 0.5
Baseline MAE : 0.116
Baseline ≈ erreur victoires : 9.5

In [344]:
import os

matches = []

for root, dirs, files in os.walk("/"):
    # évite quelques dossiers système inutiles
    if root.startswith(("/proc", "/sys", "/dev")):
        continue

    for file in files:
        if file in [
            "Team Stats Per 100 Poss.csv",
            "Opponent Stats Per 100 Poss.csv",
            "Team Summaries.csv"
        ]:
            matches.append(
                os.path.join(root, file)
            )

matches

['/root/.cache/kagglehub/datasets/sumitrodatta/nba-aba-baa-stats/versions/56/Team Stats Per 100 Poss.csv',
 '/root/.cache/kagglehub/datasets/sumitrodatta/nba-aba-baa-stats/versions/56/Opponent Stats Per 100 Poss.csv',
 '/root/.cache/kagglehub/datasets/sumitrodatta/nba-aba-baa-stats/versions/56/Team Summaries.csv']

In [345]:
team100_path = [
    p for p in matches
    if p.endswith("Team Stats Per 100 Poss.csv")
][0]

opp100_path = [
    p for p in matches
    if p.endswith("Opponent Stats Per 100 Poss.csv")
][0]

summary_path = [
    p for p in matches
    if p.endswith("Team Summaries.csv")
][0]

In [346]:
team100 = pd.read_csv(team100_path)
opp100 = pd.read_csv(opp100_path)
team_summary = pd.read_csv(summary_path)

print("TEAM PER 100 :", team100.shape)
print("OPP PER 100  :", opp100.shape)
print("SUMMARIES    :", team_summary.shape)

TEAM PER 100 : (1462, 28)
OPP PER 100  : (1462, 28)
SUMMARIES    : (1907, 31)

In [347]:
print("\n--- TEAM PER 100 ---")
print(team100.columns.tolist())

print("\n--- OPPONENT PER 100 ---")
print(opp100.columns.tolist())

print("\n--- TEAM SUMMARIES ---")
print(team_summary.columns.tolist())

--- TEAM PER 100 ---
['season', 'lg', 'team', 'abbreviation', 'playoffs', 'g', 'mp', 'fg_per_100_poss', 'fga_per_100_poss', 'fg_percent', 'x3p_per_100_poss', 'x3pa_per_100_poss', 'x3p_percent', 'x2p_per_100_poss', 'x2pa_per_100_poss', 'x2p_percent', 'ft_per_100_poss', 'fta_per_100_poss', 'ft_percent', 'orb_per_100_poss', 'drb_per_100_poss', 'trb_per_100_poss', 'ast_per_100_poss', 'stl_per_100_poss', 'blk_per_100_poss', 'tov_per_100_poss', 'pf_per_100_poss', 'pts_per_100_poss']

--- OPPONENT PER 100 ---
['season', 'lg', 'team', 'abbreviation', 'playoffs', 'g', 'mp', 'opp_fg_per_100_poss', 'opp_fga_per_100_poss', 'opp_fg_percent', 'opp_x3p_per_100_poss', 'opp_x3pa_per_100_poss', 'opp_x3p_percent', 'opp_x2p_per_100_poss', 'opp_x2pa_per_100_poss', 'opp_x2p_percent', 'opp_ft_per_100_poss', 'opp_fta_per_100_poss', 'opp_ft_percent', 'opp_orb_per_100_poss', 'opp_drb_per_100_poss', 'opp_trb_per_100_poss', 'opp_ast_per_100_poss', 'opp_stl_per_100_poss', 'opp_blk_per_100_poss', 'opp_tov_per_100_poss', 'opp_pf_per_100_poss', 'opp_pts_per_100_poss']

--- TEAM SUMMARIES ---
['season', 'lg', 'team', 'abbreviation', 'playoffs', 'age', 'w', 'l', 'pw', 'pl', 'mov', 'sos', 'srs', 'o_rtg', 'd_rtg', 'n_rtg', 'pace', 'f_tr', 'x3p_ar', 'ts_percent', 'e_fg_percent', 'tov_percent', 'orb_percent', 'ft_fga', 'opp_e_fg_percent', 'opp_tov_percent', 'drb_percent', 'opp_ft_fga', 'arena', 'attend', 'attend_g']

In [348]:
display(team100.head())
display(opp100.head())
display(team_summary.head())

,season,lg,team,abbreviation,playoffs,g,mp,fg_per_100_poss,fga_per_100_poss,fg_percent,...,ft_percent,orb_per_100_poss,drb_per_100_poss,trb_per_100_poss,ast_per_100_poss,stl_per_100_poss,blk_per_100_poss,tov_per_100_poss,pf_per_100_poss,pts_per_100_poss
0,2026,NBA,Atlanta Hawks,ATL,False,82,19755,42.7,90.1,0.474,...,0.774,10.8,31.9,42.7,29.5,9.2,4.6,13.9,19.3,116.1
1,2026,NBA,Boston Celtics,BOS,False,82,19730,44.3,94.9,0.467,...,0.807,13.1,35.6,48.8,25.9,7.5,5.3,13.0,20.0,120.8
2,2026,NBA,Brooklyn Nets,BRK,False,82,19755,38.4,86.8,0.443,...,0.780,10.6,29.8,40.4,25.7,8.2,4.4,16.2,21.6,108.7
3,2026,NBA,Chicago Bulls,CHI,False,82,19755,41.2,87.9,0.469,...,0.776,10.1,33.7,43.8,27.7,7.4,4.9,14.9,18.5,113.0
4,2026,NBA,Charlotte Hornets,CHO,False,82,19755,42.1,91.5,0.460,...,0.818,13.2,34.3,47.4,27.1,7.2,4.6,15.9,19.6,119.4

,season,lg,team,abbreviation,playoffs,g,mp,opp_fg_per_100_poss,opp_fga_per_100_poss,opp_fg_percent,...,opp_ft_percent,opp_orb_per_100_poss,opp_drb_per_100_poss,opp_trb_per_100_poss,opp_ast_per_100_poss,opp_stl_per_100_poss,opp_blk_per_100_poss,opp_tov_per_100_poss,opp_pf_per_100_poss,opp_pts_per_100_poss
0,2026,NBA,Atlanta Hawks,ATL,False,82,19755,41.5,87.7,0.474,...,0.794,10.9,33.4,44.3,26.1,8.3,4.8,15.7,18.1,113.7
1,2026,NBA,Boston Celtics,BOS,False,82,19730,40.3,91.3,0.442,...,0.775,11.4,31.9,43.3,26.0,6.5,4.3,13.1,19.3,112.7
2,2026,NBA,Brooklyn Nets,BRK,False,82,19755,43.3,87.0,0.497,...,0.775,10.4,34.3,44.7,28.2,9.4,5.5,14.9,20.0,119.0
3,2026,NBA,Chicago Bulls,CHI,False,82,19755,43.6,91.1,0.478,...,0.774,11.0,33.5,44.4,27.9,8.9,5.4,12.6,18.3,118.1
4,2026,NBA,Charlotte Hornets,CHO,False,82,19755,42.2,90.4,0.467,...,0.801,10.5,29.9,40.4,26.7,8.4,4.6,13.1,20.4,114.4

,season,lg,team,abbreviation,playoffs,age,w,l,pw,pl,...,tov_percent,orb_percent,ft_fga,opp_e_fg_percent,opp_tov_percent,drb_percent,opp_ft_fga,arena,attend,attend_g
0,2026,NBA,Atlanta Hawks,ATL,False,25.2,46.0,36.0,47.0,35.0,...,12.3,24.4,0.181,0.546,13.9,74.5,0.206,State Farm Arena,670581.0,16356.0
1,2026,NBA,Boston Celtics,BOS,False,26.9,56.0,26.0,59.0,23.0,...,11.2,29.2,0.167,0.523,11.4,75.7,0.189,TD Garden,785396.0,19156.0
2,2026,NBA,Brooklyn Nets,BRK,False,23.5,20.0,62.0,18.0,64.0,...,14.3,23.6,0.212,0.571,13.2,74.0,0.225,Barclays Center,713896.0,17412.0
3,2026,NBA,Chicago Bulls,CHI,False,25.3,31.0,51.0,29.0,53.0,...,13.3,23.1,0.191,0.553,11.1,75.5,0.190,United Center,829997.0,20244.0
4,2026,NBA,Charlotte Hornets,CHO,False,24.0,44.0,38.0,53.0,29.0,...,13.5,30.5,0.200,0.540,11.6,76.6,0.186,Spectrum Center,767319.0,18715.0

In [349]:
for name, df in {
    "TEAM100": team100,
    "OPP100": opp100,
    "SUMMARY": team_summary
}.items():

    print("\n" + "=" * 80)
    print(name)
    print("=" * 80)

    for col in df.columns:
        print(col)

================================================================================
TEAM100
================================================================================
season
lg
team
abbreviation
playoffs
g
mp
fg_per_100_poss
fga_per_100_poss
fg_percent
x3p_per_100_poss
x3pa_per_100_poss
x3p_percent
x2p_per_100_poss
x2pa_per_100_poss
x2p_percent
ft_per_100_poss
fta_per_100_poss
ft_percent
orb_per_100_poss
drb_per_100_poss
trb_per_100_poss
ast_per_100_poss
stl_per_100_poss
blk_per_100_poss
tov_per_100_poss
pf_per_100_poss
pts_per_100_poss

================================================================================
OPP100
================================================================================
season
lg
team
abbreviation
playoffs
g
mp
opp_fg_per_100_poss
opp_fga_per_100_poss
opp_fg_percent
opp_x3p_per_100_poss
opp_x3pa_per_100_poss
opp_x3p_percent
opp_x2p_per_100_poss
opp_x2pa_per_100_poss
opp_x2p_percent
opp_ft_per_100_poss
opp_fta_per_100_poss
opp_ft_percent
opp_orb_per_100_poss
opp_drb_per_100_poss
opp_trb_per_100_poss
opp_ast_per_100_poss
opp_stl_per_100_poss
opp_blk_per_100_poss
opp_tov_per_100_poss
opp_pf_per_100_poss
opp_pts_per_100_poss

================================================================================
SUMMARY
================================================================================
season
lg
team
abbreviation
playoffs
age
w
l
pw
pl
mov
sos
srs
o_rtg
d_rtg
n_rtg
pace
f_tr
x3p_ar
ts_percent
e_fg_percent
tov_percent
orb_percent
ft_fga
opp_e_fg_percent
opp_tov_percent
drb_percent
opp_ft_fga
arena
attend
attend_g

In [350]:
keys = [
    "season",
    "lg",
    "abbreviation"
]

for name, df in {
    "team100": team100,
    "opp100": opp100,
    "team_summary": team_summary
}.items():

    duplicates = df.duplicated(
        subset=keys
    ).sum()

    print(
        name,
        "→",
        duplicates,
        "doublons"
    )

team100 → 0 doublons
opp100 → 0 doublons
team_summary → 0 doublons

In [351]:
for name, df in {
    "team100": team100,
    "opp100": opp100,
    "team_summary": team_summary
}.items():

    print(
        name,
        "→",
        df["season"].min(),
        "-",
        df["season"].max(),
        "|",
        df["season"].nunique(),
        "saisons"
    )

team100 → 1974 - 2026 | 53 saisons
opp100 → 1974 - 2026 | 53 saisons
team_summary → 1947 - 2026 | 80 saisons

In [352]:
team100_nba = team100[
    team100["lg"] == "NBA"
].copy()

opp100_nba = opp100[
    opp100["lg"] == "NBA"
].copy()

summary_nba = team_summary[
    team_summary["lg"] == "NBA"
].copy()

print(team100_nba.shape)
print(opp100_nba.shape)
print(summary_nba.shape)

(1433, 28)
(1433, 28)
(1770, 31)

In [353]:
team_advanced = (
    summary_nba
    .merge(
        team100_nba,
        on=["season", "lg", "team", "abbreviation"],
        how="inner",
        suffixes=("_summary", "_team100"),
        validate="one_to_one"
    )
    .merge(
        opp100_nba,
        on=["season", "lg", "team", "abbreviation"],
        how="inner",
        suffixes=("", "_opp100"),
        validate="one_to_one"
    )
)

print(
    "Dimensions :",
    team_advanced.shape
)

display(
    team_advanced.head()
)

Dimensions : (1433, 79)

,season,lg,team,abbreviation,playoffs_summary,age,w,l,pw,pl,...,opp_ft_percent,opp_orb_per_100_poss,opp_drb_per_100_poss,opp_trb_per_100_poss,opp_ast_per_100_poss,opp_stl_per_100_poss,opp_blk_per_100_poss,opp_tov_per_100_poss,opp_pf_per_100_poss,opp_pts_per_100_poss
0,2026,NBA,Atlanta Hawks,ATL,False,25.2,46.0,36.0,47.0,35.0,...,0.794,10.9,33.4,44.3,26.1,8.3,4.8,15.7,18.1,113.7
1,2026,NBA,Boston Celtics,BOS,False,26.9,56.0,26.0,59.0,23.0,...,0.775,11.4,31.9,43.3,26.0,6.5,4.3,13.1,19.3,112.7
2,2026,NBA,Brooklyn Nets,BRK,False,23.5,20.0,62.0,18.0,64.0,...,0.775,10.4,34.3,44.7,28.2,9.4,5.5,14.9,20.0,119.0
3,2026,NBA,Chicago Bulls,CHI,False,25.3,31.0,51.0,29.0,53.0,...,0.774,11.0,33.5,44.4,27.9,8.9,5.4,12.6,18.3,118.1
4,2026,NBA,Charlotte Hornets,CHO,False,24.0,44.0,38.0,53.0,29.0,...,0.801,10.5,29.9,40.4,26.7,8.4,4.6,13.1,20.4,114.4

In [354]:
team_advanced["games"] = (
    team_advanced["w"]
    + team_advanced["l"]
)

team_advanced["win_rate"] = (
    team_advanced["w"]
    / team_advanced["games"]
)

In [355]:
display(
    team_advanced[
        [
            "season",
            "team",
            "abbreviation",
            "w",
            "l",
            "games",
            "win_rate"
        ]
    ]
    .sort_values(
        ["season", "win_rate"],
        ascending=[False, False]
    )
    .head(20)
)

    season                    team abbreviation     w     l  games  win_rate
20    2026   Oklahoma City Thunder          OKC  64.0  18.0   82.0  0.780488
26    2026       San Antonio Spurs          SAS  62.0  20.0   82.0  0.756098
8     2026         Detroit Pistons          DET  60.0  22.0   82.0  0.731707
1     2026          Boston Celtics          BOS  56.0  26.0   82.0  0.682927
7     2026          Denver Nuggets          DEN  54.0  28.0   82.0  0.658537
13    2026      Los Angeles Lakers          LAL  53.0  29.0   82.0  0.646341
19    2026         New York Knicks          NYK  53.0  29.0   82.0  0.646341
5     2026     Cleveland Cavaliers          CLE  52.0  30.0   82.0  0.634146
10    2026         Houston Rockets          HOU  52.0  30.0   82.0  0.634146
17    2026  Minnesota Timberwolves          MIN  49.0  33.0   82.0  0.597561
0     2026           Atlanta Hawks          ATL  46.0  36.0   82.0  0.560976
27    2026         Toronto Raptors          TOR  46.0  36.0   82.0  0.560976
21    2026           Orlando Magic          ORL  45.0  37.0   82.0  0.548780
22    2026      Philadelphia 76ers          PHI  45.0  37.0   82.0  0.548780
23    2026            Phoenix Suns          PHO  45.0  37.0   82.0  0.548780
4     2026       Charlotte Hornets          CHO  44.0  38.0   82.0  0.536585
15    2026              Miami Heat          MIA  43.0  39.0   82.0  0.524390
12    2026    Los Angeles Clippers          LAC  42.0  40.0   82.0  0.512195
24    2026  Portland Trail Blazers          POR  42.0  40.0   82.0  0.512195
9     2026   Golden State Warriors          GSW  37.0  45.0   82.0  0.451220

In [356]:
team_advanced["net_rating_proxy"] = (
    team_advanced["pts_per_100_poss"]
    - team_advanced["opp_pts_per_100_poss"]
)

In [357]:
print(
    team_advanced[
        ["win_rate", "net_rating_proxy"]
    ]
    .corr()
    .round(3)
)

                  win_rate  net_rating_proxy
win_rate             1.000             0.966
net_rating_proxy     0.966             1.000

In [358]:
# 1
print(team100.columns.tolist())

# 2
print(opp100.columns.tolist())

# 3
print(team_summary.columns.tolist())

['season', 'lg', 'team', 'abbreviation', 'playoffs', 'g', 'mp', 'fg_per_100_poss', 'fga_per_100_poss', 'fg_percent', 'x3p_per_100_poss', 'x3pa_per_100_poss', 'x3p_percent', 'x2p_per_100_poss', 'x2pa_per_100_poss', 'x2p_percent', 'ft_per_100_poss', 'fta_per_100_poss', 'ft_percent', 'orb_per_100_poss', 'drb_per_100_poss', 'trb_per_100_poss', 'ast_per_100_poss', 'stl_per_100_poss', 'blk_per_100_poss', 'tov_per_100_poss', 'pf_per_100_poss', 'pts_per_100_poss']
['season', 'lg', 'team', 'abbreviation', 'playoffs', 'g', 'mp', 'opp_fg_per_100_poss', 'opp_fga_per_100_poss', 'opp_fg_percent', 'opp_x3p_per_100_poss', 'opp_x3pa_per_100_poss', 'opp_x3p_percent', 'opp_x2p_per_100_poss', 'opp_x2pa_per_100_poss', 'opp_x2p_percent', 'opp_ft_per_100_poss', 'opp_fta_per_100_poss', 'opp_ft_percent', 'opp_orb_per_100_poss', 'opp_drb_per_100_poss', 'opp_trb_per_100_poss', 'opp_ast_per_100_poss', 'opp_stl_per_100_poss', 'opp_blk_per_100_poss', 'opp_tov_per_100_poss', 'opp_pf_per_100_poss', 'opp_pts_per_100_poss']
['season', 'lg', 'team', 'abbreviation', 'playoffs', 'age', 'w', 'l', 'pw', 'pl', 'mov', 'sos', 'srs', 'o_rtg', 'd_rtg', 'n_rtg', 'pace', 'f_tr', 'x3p_ar', 'ts_percent', 'e_fg_percent', 'tov_percent', 'orb_percent', 'ft_fga', 'opp_e_fg_percent', 'opp_tov_percent', 'drb_percent', 'opp_ft_fga', 'arena', 'attend', 'attend_g']

In [359]:
# 1
print(team100.columns.tolist())

# 2
print(opp100.columns.tolist())

# 3
print(team_summary.columns.tolist())

['season', 'lg', 'team', 'abbreviation', 'playoffs', 'g', 'mp', 'fg_per_100_poss', 'fga_per_100_poss', 'fg_percent', 'x3p_per_100_poss', 'x3pa_per_100_poss', 'x3p_percent', 'x2p_per_100_poss', 'x2pa_per_100_poss', 'x2p_percent', 'ft_per_100_poss', 'fta_per_100_poss', 'ft_percent', 'orb_per_100_poss', 'drb_per_100_poss', 'trb_per_100_poss', 'ast_per_100_poss', 'stl_per_100_poss', 'blk_per_100_poss', 'tov_per_100_poss', 'pf_per_100_poss', 'pts_per_100_poss']
['season', 'lg', 'team', 'abbreviation', 'playoffs', 'g', 'mp', 'opp_fg_per_100_poss', 'opp_fga_per_100_poss', 'opp_fg_percent', 'opp_x3p_per_100_poss', 'opp_x3pa_per_100_poss', 'opp_x3p_percent', 'opp_x2p_per_100_poss', 'opp_x2pa_per_100_poss', 'opp_x2p_percent', 'opp_ft_per_100_poss', 'opp_fta_per_100_poss', 'opp_ft_percent', 'opp_orb_per_100_poss', 'opp_drb_per_100_poss', 'opp_trb_per_100_poss', 'opp_ast_per_100_poss', 'opp_stl_per_100_poss', 'opp_blk_per_100_poss', 'opp_tov_per_100_poss', 'opp_pf_per_100_poss', 'opp_pts_per_100_poss']
['season', 'lg', 'team', 'abbreviation', 'playoffs', 'age', 'w', 'l', 'pw', 'pl', 'mov', 'sos', 'srs', 'o_rtg', 'd_rtg', 'n_rtg', 'pace', 'f_tr', 'x3p_ar', 'ts_percent', 'e_fg_percent', 'tov_percent', 'orb_percent', 'ft_fga', 'opp_e_fg_percent', 'opp_tov_percent', 'drb_percent', 'opp_ft_fga', 'arena', 'attend', 'attend_g']

In [360]:
# 4 — doublons
keys = ["season", "lg", "abbreviation"]

for name, df in {
    "team100": team100,
    "opp100": opp100,
    "team_summary": team_summary
}.items():

    print(
        name,
        df.duplicated(keys).sum()
    )

team100 0
opp100 0
team_summary 0

In [361]:
for name, df in {
    "team100": team100,
    "opp100": opp100,
    "team_summary": team_summary
}.items():

    print(
        name,
        df["season"].min(),
        "→",
        df["season"].max()
    )

team100 1974 → 2026
opp100 1974 → 2026
team_summary 1947 → 2026

In [362]:
# ============================================================
# CONTRÔLE FINAL AVANT JOINTURE
# ============================================================

datasets = {
    "TEAM100": team100,
    "OPP100": opp100,
    "TEAM_SUMMARY": team_summary
}

for name, df in datasets.items():

    print("\n" + "=" * 80)
    print(name)
    print("=" * 80)

    print(
        "Période :",
        df["season"].min(),
        "→",
        df["season"].max()
    )

    print("Nombre de saisons :", df["season"].nunique())
    print("Nombre de lignes :", len(df))

    print("\nColonnes :")

    for col in df.columns:
        print(" -", col)

================================================================================
TEAM100
================================================================================
Période : 1974 → 2026
Nombre de saisons : 53
Nombre de lignes : 1462

Colonnes :
 - season
 - lg
 - team
 - abbreviation
 - playoffs
 - g
 - mp
 - fg_per_100_poss
 - fga_per_100_poss
 - fg_percent
 - x3p_per_100_poss
 - x3pa_per_100_poss
 - x3p_percent
 - x2p_per_100_poss
 - x2pa_per_100_poss
 - x2p_percent
 - ft_per_100_poss
 - fta_per_100_poss
 - ft_percent
 - orb_per_100_poss
 - drb_per_100_poss
 - trb_per_100_poss
 - ast_per_100_poss
 - stl_per_100_poss
 - blk_per_100_poss
 - tov_per_100_poss
 - pf_per_100_poss
 - pts_per_100_poss

================================================================================
OPP100
================================================================================
Période : 1974 → 2026
Nombre de saisons : 53
Nombre de lignes : 1462

Colonnes :
 - season
 - lg
 - team
 - abbreviation
 - playoffs
 - g
 - mp
 - opp_fg_per_100_poss
 - opp_fga_per_100_poss
 - opp_fg_percent
 - opp_x3p_per_100_poss
 - opp_x3pa_per_100_poss
 - opp_x3p_percent
 - opp_x2p_per_100_poss
 - opp_x2pa_per_100_poss
 - opp_x2p_percent
 - opp_ft_per_100_poss
 - opp_fta_per_100_poss
 - opp_ft_percent
 - opp_orb_per_100_poss
 - opp_drb_per_100_poss
 - opp_trb_per_100_poss
 - opp_ast_per_100_poss
 - opp_stl_per_100_poss
 - opp_blk_per_100_poss
 - opp_tov_per_100_poss
 - opp_pf_per_100_poss
 - opp_pts_per_100_poss

================================================================================
TEAM_SUMMARY
================================================================================
Période : 1947 → 2026
Nombre de saisons : 80
Nombre de lignes : 1907

Colonnes :
 - season
 - lg
 - team
 - abbreviation
 - playoffs
 - age
 - w
 - l
 - pw
 - pl
 - mov
 - sos
 - srs
 - o_rtg
 - d_rtg
 - n_rtg
 - pace
 - f_tr
 - x3p_ar
 - ts_percent
 - e_fg_percent
 - tov_percent
 - orb_percent
 - ft_fga
 - opp_e_fg_percent
 - opp_tov_percent
 - drb_percent
 - opp_ft_fga
 - arena
 - attend
 - attend_g

In [363]:
team100_nba = team100[
    team100["lg"] == "NBA"
].copy()

opp100_nba = opp100[
    opp100["lg"] == "NBA"
].copy()

summary_nba = team_summary[
    team_summary["lg"] == "NBA"
].copy()

print("TEAM100 :", team100_nba.shape)
print("OPP100  :", opp100_nba.shape)
print("SUMMARY :", summary_nba.shape)

TEAM100 : (1433, 28)
OPP100  : (1433, 28)
SUMMARY : (1770, 31)

In [364]:
["season", "lg", "abbreviation"]

['season', 'lg', 'abbreviation']

In [365]:
team_advanced = (
    summary_nba
    .merge(
        team100_nba,
        on=["season", "lg", "abbreviation"],
        how="inner",
        suffixes=("_summary", "_team100"),
        validate="one_to_one"
    )
    .merge(
        opp100_nba,
        on=["season", "lg", "abbreviation"],
        how="inner",
        suffixes=("", "_opp100"),
        validate="one_to_one"
    )
)

print("Dimensions :", team_advanced.shape)
print(
    "Période :",
    team_advanced["season"].min(),
    "→",
    team_advanced["season"].max()
)

Dimensions : (1433, 81)
Période : 1974 → 2026

In [366]:
team_advanced["games"] = (
    team_advanced["w"] +
    team_advanced["l"]
)

team_advanced["win_rate"] = (
    team_advanced["w"] /
    team_advanced["games"]
)

In [367]:
team_advanced["net_rating_calc"] = (
    team_advanced["pts_per_100_poss"]
    -
    team_advanced["opp_pts_per_100_poss"]
)

In [368]:
display(
    team_advanced[
        [
            "season",
            "abbreviation",
            "win_rate",
            "o_rtg",
            "d_rtg",
            "n_rtg",
            "net_rating_calc"
        ]
    ]
    .sort_values(
        ["season", "win_rate"],
        ascending=[False, False]
    )
    .head(20)
    .round(3)
)

    season abbreviation  win_rate  o_rtg  d_rtg  n_rtg  net_rating_calc
20    2026          OKC     0.780  118.9  107.7   11.2             11.2
26    2026          SAS     0.756  119.6  111.3    8.3              8.3
8     2026          DET     0.732  117.9  109.7    8.2              8.2
1     2026          BOS     0.683  120.8  112.7    8.1              8.1
7     2026          DEN     0.659  122.6  117.4    5.2              5.2
13    2026          LAL     0.646  118.2  116.4    1.8              1.8
19    2026          NYK     0.646  119.8  113.3    6.5              6.5
5     2026          CLE     0.634  119.2  115.1    4.1              4.1
10    2026          HOU     0.634  118.6  113.2    5.4              5.4
17    2026          MIN     0.598  116.8  113.5    3.3              3.3
0     2026          ATL     0.561  116.1  113.7    2.4              2.4
27    2026          TOR     0.561  115.9  113.0    2.9              2.9
21    2026          ORL     0.549  114.9  114.3    0.6              0.6
22    2026          PHI     0.549  115.4  115.5   -0.1             -0.1
23    2026          PHO     0.549  115.4  113.9    1.5              1.5
4     2026          CHO     0.537  119.4  114.4    5.0              5.0
15    2026          MIA     0.524  116.7  114.5    2.2              2.2
12    2026          LAC     0.512  117.3  116.1    1.2              1.2
24    2026          POR     0.512  114.4  114.7   -0.3             -0.3
9     2026          GSW     0.451  115.0  115.6   -0.6             -0.6

In [369]:
features_v2 = [
    "e_fg_percent",
    "tov_percent",
    "orb_percent",
    "drb_percent",
    "ft_fga",
    "opp_e_fg_percent",
    "opp_tov_percent",
    "opp_ft_fga"
]

In [370]:
corr_v2 = (
    team_advanced[
        ["win_rate"] + features_v2
    ]
    .corr(numeric_only=True)["win_rate"]
    .drop("win_rate")
    .sort_values(ascending=False)
)

display(
    corr_v2
    .to_frame("correlation_with_win_rate")
    .round(3)
)

                  correlation_with_win_rate
e_fg_percent                          0.419
ft_fga                                0.184
drb_percent                           0.157
orb_percent                           0.054
opp_tov_percent                       0.041
tov_percent                          -0.198
opp_ft_fga                           -0.226
opp_e_fg_percent                     -0.378

In [371]:
kpi_corr = (
    team_advanced[
        [
            "win_rate",
            "o_rtg",
            "d_rtg",
            "n_rtg",
            "net_rating_calc"
        ]
    ]
    .corr(numeric_only=True)["win_rate"]
    .drop("win_rate")
    .sort_values(ascending=False)
)

display(
    kpi_corr
    .to_frame("correlation_with_win_rate")
    .round(3)
)

                 correlation_with_win_rate
net_rating_calc                      0.966
n_rtg                                0.966
o_rtg                                0.502
d_rtg                               -0.441

In [372]:
analysis_v2 = team_advanced[
    team_advanced["season"] <= 2025
].copy()

In [373]:
train_v2 = analysis_v2[
    analysis_v2["season"] <= 2017
].copy()

test_v2 = analysis_v2[
    analysis_v2["season"] >= 2018
].copy()

In [374]:
train_data_v2 = train_v2[
    features_v2 + ["win_rate"]
].dropna()

test_data_v2 = test_v2[
    features_v2 + ["win_rate"]
].dropna()

print(
    "TRAIN :",
    train_data_v2.shape
)

print(
    "TEST :",
    test_data_v2.shape
)

TRAIN : (1163, 9)
TEST : (240, 9)

In [375]:
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_absolute_error

scaler_v2 = StandardScaler()

X_train_v2 = scaler_v2.fit_transform(
    train_data_v2[features_v2]
)

X_test_v2 = scaler_v2.transform(
    test_data_v2[features_v2]
)

y_train_v2 = train_data_v2["win_rate"]
y_test_v2 = test_data_v2["win_rate"]

In [376]:
model_v2 = LinearRegression()

model_v2.fit(
    X_train_v2,
    y_train_v2
)

train_pred_v2 = model_v2.predict(
    X_train_v2
)

test_pred_v2 = model_v2.predict(
    X_test_v2
)

In [377]:
train_r2_v2 = r2_score(
    y_train_v2,
    train_pred_v2
)

test_r2_v2 = r2_score(
    y_test_v2,
    test_pred_v2
)

mae_v2 = mean_absolute_error(
    y_test_v2,
    test_pred_v2
)

print(
    "Train R² V2 :",
    round(train_r2_v2, 3)
)

print(
    "Test R² V2  :",
    round(test_r2_v2, 3)
)

print(
    "Test MAE V2 :",
    round(mae_v2, 3)
)

print(
    "≈ erreur victoires :",
    round(mae_v2 * 82, 1)
)

Train R² V2 : 0.929
Test R² V2  : 0.926
Test MAE V2 : 0.032
≈ erreur victoires : 2.6

In [378]:
winning_factors_v2 = pd.DataFrame({
    "factor": features_v2,
    "coefficient": model_v2.coef_
})

winning_factors_v2["abs_coefficient"] = (
    winning_factors_v2["coefficient"].abs()
)

winning_factors_v2 = (
    winning_factors_v2
    .sort_values(
        "abs_coefficient",
        ascending=False
    )
)

display(
    winning_factors_v2.round(4)
)

             factor  coefficient  abs_coefficient
0      e_fg_percent       0.0972           0.0972
5  opp_e_fg_percent      -0.0905           0.0905
1       tov_percent      -0.0609           0.0609
6   opp_tov_percent       0.0595           0.0595
2       orb_percent       0.0502           0.0502
3       drb_percent       0.0417           0.0417
7        opp_ft_fga      -0.0345           0.0345
4            ft_fga       0.0284           0.0284

In [379]:
print("Train R² V2 :", round(train_r2_v2, 3))
print("Test R² V2  :", round(test_r2_v2, 3))
print("Test MAE V2 :", round(mae_v2, 3))
print("≈ erreur victoires :", round(mae_v2 * 82, 1))

Train R² V2 : 0.929
Test R² V2  : 0.926
Test MAE V2 : 0.032
≈ erreur victoires : 2.6

In [380]:
team_season_final = team_advanced[
    [
        "season",
        "team_summary",
        "abbreviation",
        "playoffs_summary",

        "w",
        "l",
        "games",
        "win_rate",

        "o_rtg",
        "d_rtg",
        "n_rtg",
        "pace",

        "ts_percent",
        "e_fg_percent",
        "tov_percent",
        "orb_percent",
        "drb_percent",
        "ft_fga",

        "opp_e_fg_percent",
        "opp_tov_percent",
        "opp_ft_fga",

        "pts_per_100_poss",
        "opp_pts_per_100_poss",

        "net_rating_calc"
    ]
].copy()

In [381]:
team_season_final = team_season_final.rename(
    columns={
        "team_summary": "team",
        "playoffs_summary": "playoffs"
    }
)

In [382]:
team_season_final.to_csv(
    "01_team_season.csv",
    index=False
)

print(
    "01_team_season.csv →",
    os.path.exists("01_team_season.csv"),
    "|",
    round(
        os.path.getsize("01_team_season.csv") / 1024,
        2
    ),
    "KB"
)

01_team_season.csv → True | 229.31 KB

In [383]:
factor_labels = {
    "e_fg_percent": "Shooting Efficiency",
    "opp_e_fg_percent": "Opponent Shooting Defense",
    "tov_percent": "Ball Security",
    "opp_tov_percent": "Turnover Creation",
    "orb_percent": "Offensive Rebounding",
    "drb_percent": "Defensive Rebounding",
    "ft_fga": "Free Throw Pressure",
    "opp_ft_fga": "Opponent Free Throw Prevention"
}

factor_categories = {
    "e_fg_percent": "Shooting",
    "opp_e_fg_percent": "Defense",
    "tov_percent": "Possession",
    "opp_tov_percent": "Possession",
    "orb_percent": "Rebounding",
    "drb_percent": "Rebounding",
    "ft_fga": "Free Throws",
    "opp_ft_fga": "Free Throws"
}

winning_factors_final = winning_factors_v2.copy()

winning_factors_final["factor_name"] = (
    winning_factors_final["factor"]
    .map(factor_labels)
)

winning_factors_final["category"] = (
    winning_factors_final["factor"]
    .map(factor_categories)
)

winning_factors_final["direction"] = (
    winning_factors_final["coefficient"]
    .apply(
        lambda x: "Positive"
        if x > 0
        else "Negative"
    )
)

winning_factors_final["importance_rank"] = (
    winning_factors_final["abs_coefficient"]
    .rank(
        ascending=False,
        method="min"
    )
    .astype(int)
)

In [384]:
winning_factors_final["train_r2"] = train_r2_v2
winning_factors_final["test_r2"] = test_r2_v2
winning_factors_final["test_mae"] = mae_v2
winning_factors_final["approx_win_error"] = mae_v2 * 82

In [385]:
winning_factors_final["correlation"] = (
    winning_factors_final["factor"]
    .map(corr_v2.to_dict())
)

In [386]:
winning_factors_final = winning_factors_final[
    [
        "importance_rank",
        "factor",
        "factor_name",
        "category",
        "coefficient",
        "abs_coefficient",
        "correlation",
        "direction",
        "train_r2",
        "test_r2",
        "test_mae",
        "approx_win_error"
    ]
].sort_values(
    "importance_rank"
)

display(
    winning_factors_final.round(4)
)

,importance_rank,factor,factor_name,category,coefficient,abs_coefficient,correlation,direction,train_r2,test_r2,test_mae,approx_win_error
0,1,e_fg_percent,Shooting Efficiency,Shooting,0.0972,0.0972,0.4189,Positive,0.9292,0.9256,0.0321,2.6287
5,2,opp_e_fg_percent,Opponent Shooting Defense,Defense,-0.0905,0.0905,-0.3781,Negative,0.9292,0.9256,0.0321,2.6287
1,3,tov_percent,Ball Security,Possession,-0.0609,0.0609,-0.1977,Negative,0.9292,0.9256,0.0321,2.6287
6,4,opp_tov_percent,Turnover Creation,Possession,0.0595,0.0595,0.0414,Positive,0.9292,0.9256,0.0321,2.6287
2,5,orb_percent,Offensive Rebounding,Rebounding,0.0502,0.0502,0.0538,Positive,0.9292,0.9256,0.0321,2.6287
3,6,drb_percent,Defensive Rebounding,Rebounding,0.0417,0.0417,0.1574,Positive,0.9292,0.9256,0.0321,2.6287
7,7,opp_ft_fga,Opponent Free Throw Prevention,Free Throws,-0.0345,0.0345,-0.2261,Negative,0.9292,0.9256,0.0321,2.6287
4,8,ft_fga,Free Throw Pressure,Free Throws,0.0284,0.0284,0.1837,Positive,0.9292,0.9256,0.0321,2.6287

In [387]:
winning_factors_final.to_csv(
    "02_winning_factors.csv",
    index=False
)

print(
    "02_winning_factors.csv →",
    os.path.exists("02_winning_factors.csv"),
    "|",
    round(
        os.path.getsize("02_winning_factors.csv") / 1024,
        2
    ),
    "KB"
)

02_winning_factors.csv → True | 1.64 KB

In [388]:
files = [
    "01_team_season.csv",
    "02_winning_factors.csv",
    "03_goat_master.csv",
    "04_goat_dimensions.csv",
    "05_goat_scenarios.csv",
    "06_goat_peak.csv",
    "07_goat_player_seasons.csv",
    "08_methodology.csv"
]

audit = []

for file in files:
    df = pd.read_csv(file)

    audit.append({
        "file": file,
        "rows": len(df),
        "columns": len(df.columns),
        "duplicates": df.duplicated().sum(),
        "null_values": int(df.isna().sum().sum()),
        "size_kb": round(os.path.getsize(file) / 1024, 2)
    })

audit_df = pd.DataFrame(audit)

display(audit_df)

                         file  rows  columns  duplicates  null_values  size_kb
0          01_team_season.csv  1433       24           0            0   229.31
1      02_winning_factors.csv     8       12           0            0     1.64
2          03_goat_master.csv     5       20           0            0     0.75
3      04_goat_dimensions.csv     5        7           0            0     0.53
4       05_goat_scenarios.csv     5        6           0            0     0.25
5            06_goat_peak.csv     5        7           0            0     0.45
6  07_goat_player_seasons.csv    79       20           0            0    18.88
7          08_methodology.csv     6        5           0            0     0.85

In [389]:
# TEAM SEASON
df01 = pd.read_csv("01_team_season.csv")

print(
    "01 doublons season/team :",
    df01.duplicated(
        subset=["season", "abbreviation"]
    ).sum()
)

# GOAT MASTER
df03 = pd.read_csv("03_goat_master.csv")

print(
    "03 doublons joueurs :",
    df03["Name"].duplicated().sum()
)

# GOAT DIMENSIONS
df04 = pd.read_csv("04_goat_dimensions.csv")

print(
    "04 doublons joueurs :",
    df04["Name"].duplicated().sum()
)

# PLAYER SEASONS
df07 = pd.read_csv("07_goat_player_seasons.csv")

print(
    "07 doublons joueur/saison :",
    df07.duplicated(
        subset=["PLAYER_ID", "SEASON_ID"]
    ).sum()
)

01 doublons season/team : 0
03 doublons joueurs : 0
04 doublons joueurs : 0
07 doublons joueur/saison : 0

In [390]:
import zipfile
import os

files = [
    "01_team_season.csv",
    "02_winning_factors.csv",
    "03_goat_master.csv",
    "04_goat_dimensions.csv",
    "05_goat_scenarios.csv",
    "06_goat_peak.csv",
    "07_goat_player_seasons.csv",
    "08_methodology.csv"
]

zip_name = "nba_analytics_datamart.zip"

with zipfile.ZipFile(zip_name, "w") as zipf:
    for file in files:
        zipf.write(file)

print("ZIP créé :", os.path.exists(zip_name))
print("Taille :", round(os.path.getsize(zip_name) / 1024, 2), "KB")

ZIP créé : True
Taille : 253.6 KB

In [391]:
from google.colab import files

files.download("nba_analytics_datamart.zip")

In [392]:
print(df_player_season.shape)
print(df_player_season.columns.tolist())

(24599, 33)
['PLAYER_ID', 'Name', 'SEASON_ID', 'TEAM_ID', 'TEAM_ABBREVIATION', 'PLAYER_AGE', 'GP', 'GS', 'MIN', 'FGM', 'FGA', 'FG_PCT', 'FG3M', 'FG3A', 'FG3_PCT', 'FTM', 'FTA', 'FT_PCT', 'OREB', 'DREB', 'REB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS', 'PPG', 'RPG', 'APG', 'SPG', 'BPG', 'MPG']

In [393]:
print(
    sorted(
        df_player_season["SEASON_ID"]
        .dropna()
        .unique()
    )[-10:]
)

['2014-15', '2015-16', '2016-17', '2017-18', '2018-19', '2019-20', '2020-21', '2021-22', '2022-23', '2023-24']

In [394]:
latest_player_season = (
    df_player_season
    .sort_values("SEASON_ID")
    .groupby("PLAYER_ID")
    .tail(1)
    .copy()
)

display(
    latest_player_season[
        [
            "PLAYER_ID",
            "Name",
            "SEASON_ID",
            "PLAYER_AGE",
            "TEAM_ABBREVIATION",
            "GP",
            "PTS",
            "REB",
            "AST"
        ]
    ]
    .sort_values(
        "PLAYER_AGE"
    )
    .head(30)
)

,PLAYER_ID,Name,SEASON_ID,PLAYER_AGE,TEAM_ABBREVIATION,GP,PTS,REB,AST
17898,101258,Corey Williams,1993-94,16.0,MIN,4,11,6.0,6
24480,1631211,Trevor Keels,2022-23,19.0,NYK,3,3,2.0,0
24546,1641713,GG Jackson,2023-24,19.0,MEM,48,699,196.0,59
24559,1641730,Noah Clowney,2023-24,19.0,BKN,23,133,81.0,18
24557,1641727,Dariq Whitehead,2023-24,19.0,BKN,2,3,4.0,3
24560,1641731,Bilal Coulibaly,2023-24,19.0,WAS,63,532,256.0,110
24547,1641715,Cam Whitmore,2023-24,19.0,HOU,47,579,180.0,33
14984,77922,Connie Rea,1953-54,19.0,BAL,20,23,31.0,16
24056,1630221,Josh Hall,2020-21,20.0,OKC,21,86,59.0,28
21933,1626146,Cliff Alexander,2015-16,20.0,POR,8,10,6.0,0
8818,2775,Ha Seung-jin,2005-06,20.0,POR,27,44,49.0,1
23960,1630185,Nico Mannion,2020-21,20.0,GSW,30,123,46.0,70
24416,1631105,Jalen Duren,2023-24,20.0,DET,61,841,709.0,147
24406,1631100,AJ Griffin,2023-24,20.0,ATL,20,48,18.0,5
24379,1630701,Michael Foster Jr.,2022-23,20.0,PHI,1,0,0.0,0
22414,1627757,Stephen Zimmerman,2016-17,20.0,ORL,19,23,35.0,4
24562,1641733,Nick Smith Jr.,2023-24,20.0,CHA,51,302,72.0,59
17464,101117,Yaroslav Korolev,2006-07,20.0,LAC,10,12,3.0,4
24549,1641717,Cason Wallace,2023-24,20.0,OKC,82,561,187.0,120
24548,1641716,Jarace Walker,2023-24,20.0,IND,33,120,63.0,40
24571,1641753,Chris Livingston,2023-24,20.0,MIL,21,26,21.0,5
24545,1641712,Rayan Rupert,2023-24,20.0,POR,39,155,92.0,62
24544,1641711,Gradey Dick,2023-24,20.0,TOR,60,510,132.0,68
24550,1641718,Keyonte George,2023-24,20.0,UTA,75,974,211.0,332
24431,1631113,Kennedy Chandler,2022-23,20.0,MEM,36,78,38.0,58
24563,1641734,Emoni Bates,2023-24,20.0,CLE,15,41,14.0,10
24457,1631159,Leonard Miller,2023-24,20.0,MIN,17,29,20.0,8
6028,1748,Korleone Young,1998-99,20.0,DET,3,13,4.0,1
24382,1630703,Scoot Henderson,2023-24,20.0,POR,62,868,194.0,336
24491,1631219,John Butler Jr.,2022-23,20.0,POR,19,45,17.0,11

In [395]:
future_candidates = latest_player_season[
    (latest_player_season["PLAYER_AGE"] <= 27)
    &
    (latest_player_season["GP"] >= 40)
].copy()

In [396]:
future_candidates["PPG"] = (
    future_candidates["PTS"]
    / future_candidates["GP"]
)

future_candidates["RPG"] = (
    future_candidates["REB"]
    / future_candidates["GP"]
)

future_candidates["APG"] = (
    future_candidates["AST"]
    / future_candidates["GP"]
)

In [397]:
future_candidates["BASIC_PRODUCTION"] = (
    future_candidates["PPG"]
    +
    future_candidates["RPG"]
    +
    future_candidates["APG"]
)

display(
    future_candidates[
        [
            "Name",
            "SEASON_ID",
            "PLAYER_AGE",
            "TEAM_ABBREVIATION",
            "GP",
            "PPG",
            "RPG",
            "APG",
            "BASIC_PRODUCTION"
        ]
    ]
    .sort_values(
        "BASIC_PRODUCTION",
        ascending=False
    )
    .head(25)
    .round(2)
)

,Name,SEASON_ID,PLAYER_AGE,TEAM_ABBREVIATION,GP,PPG,RPG,APG,BASIC_PRODUCTION
23344,Luka Dončić,2023-24,25.0,DAL,70,33.86,9.24,9.80,52.90
23161,Shai Gilgeous-Alexander,2023-24,25.0,OKC,75,30.05,5.53,6.20,41.79
21911,Maurice Stokes,1957-58,25.0,CIN,63,16.92,18.13,6.40,41.44
22705,Jayson Tatum,2023-24,26.0,BOS,74,26.85,8.12,4.92,39.89
23332,Trae Young,2023-24,25.0,ATL,54,25.72,2.76,10.80,39.28
23120,Jalen Brunson,2023-24,27.0,NYK,77,28.73,3.61,6.74,39.08
22042,Devin Booker,2023-24,27.0,PHX,68,27.07,4.53,6.94,38.54
22745,Donovan Mitchell,2023-24,27.0,CLE,55,26.60,5.09,6.05,37.75
22698,De'Aaron Fox,2023-24,26.0,SAC,74,26.57,4.59,5.65,36.81
23875,Anthony Edwards,2023-24,22.0,MIN,79,25.94,5.44,5.13,36.51
24538,Victor Wembanyama,2023-24,20.0,SAS,71,21.44,10.63,3.86,35.93
23937,Tyrese Maxey,2023-24,23.0,PHI,70,25.94,3.69,6.19,35.81
24276,Alperen Sengun,2023-24,21.0,HOU,63,21.13,9.35,4.95,35.43
23902,Tyrese Haliburton,2023-24,24.0,IND,69,20.13,3.93,10.90,34.96
24395,Paolo Banchero,2023-24,21.0,ORL,80,22.55,6.92,5.39,34.86
11736,Alex Groza,1950-51,24.0,INO,66,21.65,10.74,2.36,34.76
24307,Cade Cunningham,2023-24,22.0,DET,62,22.66,4.32,7.48,34.47
22379,Dejounte Murray,2023-24,27.0,ATL,78,22.47,5.33,6.44,34.24
24258,Scottie Barnes,2023-24,22.0,TOR,60,19.85,8.23,6.05,34.13
23563,Zion Williamson,2023-24,23.0,NOP,70,22.87,5.80,5.03,33.70
24049,Desmond Bane,2023-24,26.0,MEM,42,23.74,4.40,5.48,33.62
22807,Bam Adebayo,2023-24,26.0,MIA,71,19.25,10.38,3.92,33.55
22738,Lauri Markkanen,2023-24,27.0,UTA,55,23.24,8.16,2.00,33.40
22425,Jaylen Brown,2023-24,27.0,BOS,70,23.00,5.53,3.56,32.09
22386,Jamal Murray,2023-24,27.0,DEN,59,21.19,4.10,6.51,31.80

In [398]:
future_candidates = latest_player_season[
    (latest_player_season["SEASON_ID"] == "2023-24")
    &
    (latest_player_season["PLAYER_AGE"] <= 27)
    &
    (latest_player_season["GP"] >= 40)
].copy()

In [399]:
future_candidates["PPG"] = (
    future_candidates["PTS"]
    / future_candidates["GP"]
)

future_candidates["RPG"] = (
    future_candidates["REB"]
    / future_candidates["GP"]
)

future_candidates["APG"] = (
    future_candidates["AST"]
    / future_candidates["GP"]
)

future_candidates["BASIC_PRODUCTION"] = (
    future_candidates["PPG"]
    + future_candidates["RPG"]
    + future_candidates["APG"]
)

In [400]:
display(
    future_candidates[
        [
            "Name",
            "SEASON_ID",
            "PLAYER_AGE",
            "TEAM_ABBREVIATION",
            "GP",
            "PPG",
            "RPG",
            "APG",
            "BASIC_PRODUCTION"
        ]
    ]
    .sort_values(
        "BASIC_PRODUCTION",
        ascending=False
    )
    .head(25)
    .round(2)
)

,Name,SEASON_ID,PLAYER_AGE,TEAM_ABBREVIATION,GP,PPG,RPG,APG,BASIC_PRODUCTION
23344,Luka Dončić,2023-24,25.0,DAL,70,33.86,9.24,9.80,52.90
23161,Shai Gilgeous-Alexander,2023-24,25.0,OKC,75,30.05,5.53,6.20,41.79
22705,Jayson Tatum,2023-24,26.0,BOS,74,26.85,8.12,4.92,39.89
23332,Trae Young,2023-24,25.0,ATL,54,25.72,2.76,10.80,39.28
23120,Jalen Brunson,2023-24,27.0,NYK,77,28.73,3.61,6.74,39.08
22042,Devin Booker,2023-24,27.0,PHX,68,27.07,4.53,6.94,38.54
22745,Donovan Mitchell,2023-24,27.0,CLE,55,26.60,5.09,6.05,37.75
22698,De'Aaron Fox,2023-24,26.0,SAC,74,26.57,4.59,5.65,36.81
23875,Anthony Edwards,2023-24,22.0,MIN,79,25.94,5.44,5.13,36.51
24538,Victor Wembanyama,2023-24,20.0,SAS,71,21.44,10.63,3.86,35.93
23937,Tyrese Maxey,2023-24,23.0,PHI,70,25.94,3.69,6.19,35.81
24276,Alperen Sengun,2023-24,21.0,HOU,63,21.13,9.35,4.95,35.43
23902,Tyrese Haliburton,2023-24,24.0,IND,69,20.13,3.93,10.90,34.96
24395,Paolo Banchero,2023-24,21.0,ORL,80,22.55,6.92,5.39,34.86
24307,Cade Cunningham,2023-24,22.0,DET,62,22.66,4.32,7.48,34.47
22379,Dejounte Murray,2023-24,27.0,ATL,78,22.47,5.33,6.44,34.24
24258,Scottie Barnes,2023-24,22.0,TOR,60,19.85,8.23,6.05,34.13
23563,Zion Williamson,2023-24,23.0,NOP,70,22.87,5.80,5.03,33.70
24049,Desmond Bane,2023-24,26.0,MEM,42,23.74,4.40,5.48,33.62
22807,Bam Adebayo,2023-24,26.0,MIA,71,19.25,10.38,3.92,33.55
22738,Lauri Markkanen,2023-24,27.0,UTA,55,23.24,8.16,2.00,33.40
22425,Jaylen Brown,2023-24,27.0,BOS,70,23.00,5.53,3.56,32.09
22386,Jamal Murray,2023-24,27.0,DEN,59,21.19,4.10,6.51,31.80
23282,Anfernee Simons,2023-24,25.0,POR,46,22.59,3.63,5.54,31.76
23102,Miles Bridges,2023-24,26.0,CHA,69,21.00,7.32,3.35,31.67

In [401]:
future_candidates_era = future_candidates[
    [
        "PLAYER_ID",
        "Name",
        "SEASON_ID",
        "PLAYER_AGE",
        "TEAM_ABBREVIATION",
        "GP",
        "PPG",
        "RPG",
        "APG"
    ]
].merge(
    df_era[
        [
            "PLAYER_ID",
            "SEASON_ID",
            "PRODUCTION_Z",
            "PPG_Z",
            "RPG_Z",
            "APG_Z",
            "TS_PLUS",
            "TS_Z"
        ]
    ],
    on=["PLAYER_ID", "SEASON_ID"],
    how="left",
    validate="one_to_one"
)

In [402]:
display(
    future_candidates_era[
        [
            "Name",
            "PLAYER_AGE",
            "PPG",
            "RPG",
            "APG",
            "PRODUCTION_Z",
            "TS_PLUS"
        ]
    ]
    .sort_values(
        "PRODUCTION_Z",
        ascending=False
    )
    .head(20)
    .round(2)
)

,Name,PLAYER_AGE,PPG,RPG,APG,PRODUCTION_Z,TS_PLUS
214,Luka Dončić,25.0,33.86,9.24,9.80,3.25,108.68
211,Trae Young,25.0,25.72,2.76,10.80,2.11,103.00
158,Shai Gilgeous-Alexander,25.0,30.05,5.53,6.20,2.00,111.93
148,Tyrese Haliburton,24.0,20.13,3.93,10.90,1.94,106.51
104,Jayson Tatum,26.0,26.85,8.12,4.92,1.93,106.34
206,Devin Booker,27.0,27.07,4.53,6.94,1.81,107.60
56,Victor Wembanyama,20.0,21.44,10.63,3.86,1.76,99.42
137,Jalen Brunson,27.0,28.73,3.61,6.74,1.76,104.31
185,Alperen Sengun,21.0,21.13,9.35,4.95,1.76,103.05
154,Donovan Mitchell,27.0,26.60,5.09,6.05,1.72,104.79
187,Scottie Barnes,22.0,19.85,8.23,6.05,1.71,99.61
166,Bam Adebayo,26.0,19.25,10.38,3.92,1.61,101.35
19,Cade Cunningham,22.0,22.66,4.32,7.48,1.61,96.05
6,Paolo Banchero,21.0,22.55,6.92,5.39,1.60,96.07
105,De'Aaron Fox,26.0,26.57,4.59,5.65,1.59,99.74
113,Anthony Edwards,22.0,25.94,5.44,5.13,1.58,101.29
116,Dejounte Murray,27.0,22.47,5.33,6.44,1.56,97.77
139,Tyrese Maxey,23.0,25.94,3.69,6.19,1.52,100.83
33,Zion Williamson,23.0,22.87,5.80,5.03,1.43,107.46
95,Desmond Bane,26.0,23.74,4.40,5.48,1.37,103.63

In [403]:
goat_age_history = df_era[
    df_era["Name"].isin(goat_players)
][
    [
        "Name",
        "SEASON_ID",
        "PLAYER_AGE",
        "PRODUCTION_Z",
        "TS_PLUS",
        "PPG",
        "RPG",
        "APG"
    ]
].copy()

In [404]:
goat_age_history["AGE"] = (
    goat_age_history["PLAYER_AGE"]
    .round()
    .astype(int)
)

future_candidates_era["AGE"] = (
    future_candidates_era["PLAYER_AGE"]
    .round()
    .astype(int)
)

In [405]:
goat_age_benchmark = (
    goat_age_history
    .groupby("AGE")
    .agg(
        goat_avg_production=("PRODUCTION_Z", "mean"),
        goat_max_production=("PRODUCTION_Z", "max"),
        goat_avg_ts_plus=("TS_PLUS", "mean"),
        goat_max_ts_plus=("TS_PLUS", "max")
    )
    .reset_index()
)

display(goat_age_benchmark.head(15))

,AGE,goat_avg_production,goat_max_production,goat_avg_ts_plus,goat_max_ts_plus
0,19,1.709776,1.709776,97.033476,97.033476
1,20,2.084134,2.499011,111.932394,116.333060
2,21,2.463919,2.636189,111.036769,112.453492
3,22,2.132083,2.363052,109.777023,112.430348
4,23,2.139632,2.665426,110.264819,116.887696
5,24,2.256739,2.555185,113.349189,126.187254
6,25,2.417269,2.891848,116.093827,124.772710
7,26,2.377944,2.618746,115.043199,120.068290
8,27,2.363785,2.581749,114.025439,117.912966
9,28,2.360441,2.701858,114.568569,122.686912
10,29,2.455965,2.892108,116.089977,123.088842
11,30,2.329261,2.398771,115.504375,121.629591
12,31,2.309883,2.397806,115.913518,119.956529
13,32,2.498151,2.831397,116.654480,118.870860
14,33,2.309754,3.009240,113.069829,123.444739

In [406]:
future_vs_goat = future_candidates_era.merge(
    goat_age_benchmark,
    on="AGE",
    how="left"
)

In [407]:
future_vs_goat["production_gap_vs_goat"] = (
    future_vs_goat["PRODUCTION_Z"]
    - future_vs_goat["goat_avg_production"]
)

future_vs_goat["efficiency_gap_vs_goat"] = (
    future_vs_goat["TS_PLUS"]
    - future_vs_goat["goat_avg_ts_plus"]
)

In [408]:
display(
    future_vs_goat[
        [
            "Name",
            "AGE",
            "PRODUCTION_Z",
            "goat_avg_production",
            "production_gap_vs_goat",
            "TS_PLUS",
            "goat_avg_ts_plus",
            "efficiency_gap_vs_goat"
        ]
    ]
    .sort_values(
        "production_gap_vs_goat",
        ascending=False
    )
    .head(20)
    .round(2)
)

,Name,AGE,PRODUCTION_Z,goat_avg_production,production_gap_vs_goat,TS_PLUS,goat_avg_ts_plus,efficiency_gap_vs_goat
214,Luka Dončić,25,3.25,2.42,0.83,108.68,116.09,-7.41
211,Trae Young,25,2.11,2.42,-0.31,103.00,116.09,-13.10
148,Tyrese Haliburton,24,1.94,2.26,-0.31,106.51,113.35,-6.84
56,Victor Wembanyama,20,1.76,2.08,-0.32,99.42,111.93,-12.51
158,Shai Gilgeous-Alexander,25,2.00,2.42,-0.42,111.93,116.09,-4.16
187,Scottie Barnes,22,1.71,2.13,-0.42,99.61,109.78,-10.17
104,Jayson Tatum,26,1.93,2.38,-0.44,106.34,115.04,-8.70
19,Cade Cunningham,22,1.61,2.13,-0.52,96.05,109.78,-13.73
206,Devin Booker,27,1.81,2.36,-0.55,107.60,114.03,-6.43
113,Anthony Edwards,22,1.58,2.13,-0.56,101.29,109.78,-8.49
137,Jalen Brunson,27,1.76,2.36,-0.60,104.31,114.03,-9.72
139,Tyrese Maxey,23,1.52,2.14,-0.62,100.83,110.26,-9.43
154,Donovan Mitchell,27,1.72,2.36,-0.65,104.79,114.03,-9.24
185,Alperen Sengun,21,1.76,2.46,-0.71,103.05,111.04,-7.98
33,Zion Williamson,23,1.43,2.14,-0.71,107.46,110.26,-2.80
166,Bam Adebayo,26,1.61,2.38,-0.76,101.35,115.04,-13.70
105,De'Aaron Fox,26,1.59,2.38,-0.79,99.74,115.04,-15.31
116,Dejounte Murray,27,1.56,2.36,-0.80,97.77,114.03,-16.26
6,Paolo Banchero,21,1.60,2.46,-0.86,96.07,111.04,-14.97
15,Jalen Duren,20,1.21,2.08,-0.87,115.01,111.93,3.08

In [409]:
def gap_score(series, low=-1.5, high=1.0):
    return (
        (series - low) / (high - low) * 100
    ).clip(0, 100)

future_vs_goat["Production_Trajectory"] = gap_score(
    future_vs_goat["production_gap_vs_goat"],
    low=-1.5,
    high=1.0
)

In [410]:
future_vs_goat["Efficiency_Trajectory"] = gap_score(
    future_vs_goat["efficiency_gap_vs_goat"],
    low=-20,
    high=10
)

In [411]:
display(
    future_vs_goat[
        [
            "Name",
            "AGE",
            "production_gap_vs_goat",
            "Production_Trajectory",
            "efficiency_gap_vs_goat",
            "Efficiency_Trajectory"
        ]
    ]
    .sort_values(
        "Production_Trajectory",
        ascending=False
    )
    .head(20)
    .round(1)
)

,Name,AGE,production_gap_vs_goat,Production_Trajectory,efficiency_gap_vs_goat,Efficiency_Trajectory
214,Luka Dončić,25,0.8,93.2,-7.4,42.0
211,Trae Young,25,-0.3,47.7,-13.1,23.0
148,Tyrese Haliburton,24,-0.3,47.5,-6.8,43.9
56,Victor Wembanyama,20,-0.3,47.2,-12.5,25.0
158,Shai Gilgeous-Alexander,25,-0.4,43.2,-4.2,52.8
187,Scottie Barnes,22,-0.4,43.2,-10.2,32.8
104,Jayson Tatum,26,-0.4,42.2,-8.7,37.7
19,Cade Cunningham,22,-0.5,39.1,-13.7,20.9
206,Devin Booker,27,-0.6,37.9,-6.4,45.2
113,Anthony Edwards,22,-0.6,37.8,-8.5,38.4
137,Jalen Brunson,27,-0.6,35.9,-9.7,34.3
139,Tyrese Maxey,23,-0.6,35.3,-9.4,35.2
154,Donovan Mitchell,27,-0.6,34.1,-9.2,35.9
185,Alperen Sengun,21,-0.7,31.7,-8.0,40.1
33,Zion Williamson,23,-0.7,31.4,-2.8,57.3
166,Bam Adebayo,26,-0.8,29.4,-13.7,21.0
105,De'Aaron Fox,26,-0.8,28.4,-15.3,15.6
116,Dejounte Murray,27,-0.8,27.9,-16.3,12.5
6,Paolo Banchero,21,-0.9,25.6,-15.0,16.8
15,Jalen Duren,20,-0.9,25.1,3.1,76.9

In [412]:
future_names = future_vs_goat["Name"].unique().tolist()

future_mvp = df_mvp[
    df_mvp["player"].isin(future_names)
].copy()

In [413]:
future_mvp_summary = (
    future_mvp
    .groupby("player")
    .agg(
        early_mvp_wins=("winner", "sum"),
        early_mvp_share=("share", "sum")
    )
)

In [414]:
future_eos = df_eos_nba[
    df_eos_nba["player"].isin(future_names)
].copy()

future_eos["ALL_NBA"] = (
    future_eos["type"] == "All-NBA"
).astype(int)

future_eos["ALL_NBA_1ST"] = (
    (future_eos["type"] == "All-NBA")
    &
    (future_eos["number_tm"] == "1st")
).astype(int)

future_allnba_summary = (
    future_eos
    .groupby("player")
    .agg(
        early_all_nba=("ALL_NBA", "sum"),
        early_all_nba_1st=("ALL_NBA_1ST", "sum")
    )
)

In [415]:
future_recognition = (
    future_mvp_summary
    .join(
        future_allnba_summary,
        how="outer"
    )
    .fillna(0)
)

display(future_recognition)

,early_mvp_wins,early_mvp_share,early_all_nba,early_all_nba_1st
player,,,,
Amen Thompson,0.0,0.00,0,0
Anthony Edwards,0.0,0.03,2,0
Ayo Dosunmu,0.0,0.00,0,0
Bam Adebayo,0.0,0.00,0,0
Bennedict Mathurin,0.0,0.00,0,0
...,...,...,...,...
Tyler Herro,0.0,0.00,0,0
Tyrese Haliburton,0.0,0.00,2,0
Victor Wembanyama,0.0,0.00,0,0
Walker Kessler,0.0,0.00,0,0
Zion Williamson,0.0,0.00,0,0

In [418]:
future_model = (
    future_vs_goat
    .merge(
        future_recognition,
        left_on="Name",
        right_index=True,
        how="left"
    )
)

future_model[
    [
        "early_mvp_wins",
        "early_mvp_share",
        "early_all_nba",
        "early_all_nba_1st"
    ]
] = future_model[
    [
        "early_mvp_wins",
        "early_mvp_share",
        "early_all_nba",
        "early_all_nba_1st"
    ]
].fillna(0)

In [420]:
import pandas as pd

dataframes = {
    name: obj
    for name, obj in globals().items()
    if isinstance(obj, pd.DataFrame)
}

for name, df in dataframes.items():
    print(f"{name:30} {df.shape}")

df_game                        (65698, 55)
_5                             (5, 55)
_8                             (55, 3)
home                           (60192, 25)
_15                            (5, 18)
away                           (60192, 25)
_18                            (5, 18)
df_team_games                  (131396, 19)
_19                            (5, 18)
_24                            (10, 3)
df_test                        (724, 20)
_29                            (20, 3)
_32                            (10, 2)
df_animation                   (9, 11)
_38                            (9, 11)
df_player                      (4831, 5)
df_common                      (4171, 33)
tables                         (0, 1)
_66                            (0, 1)
tables_sqlite                  (16, 1)
goat_tables                    (5, 1)
info                           (47, 6)
df_other_sample                (5, 26)
df_game_sample                 (5, 55)
pbp_info                       (34, 6)
player_columns                 (23, 6)
common_info                    (33, 6)
lebron                         (0, 33)
df_matches                     (0, 0)
df_files                       (20, 4)
player_files                   (5, 4)
df_goat                        (29916, 27)
df_test_goat                   (82, 27)
tot_rows                       (2572, 27)
df_player_season               (24599, 33)
career_check                   (5, 7)
goat_seasons                   (82, 33)
peak_ppg                       (25, 33)
peak_5                         (5, 3)
career_stats                   (5, 14)
availability                   (5, 7)
df_era                         (20998, 41)
goat_era                       (79, 41)
best_seasons                   (20, 9)
top5_seasons                   (25, 37)
peak_score                     (5, 4)
top5_efficiency                (25, 41)
peak_efficiency                (5, 3)
df_games                       (65698, 55)
season_check                   (281, 3)
playoffs                       (3842, 57)
last_playoff_games             (67, 58)
champions                      (67, 7)
champions_clean                (67, 2)
df_goat_titles                 (29916, 29)
goat_titles_check              (82, 5)
championship_summary           (5, 1)
jordan_titles_check            (15, 5)
playoffs_1996                  (0, 55)
playoff_quality                (4, 2)
missing_champions              (10, 3)
champions_kaggle               (67, 3)
champions_complete             (77, 3)
df_player_season_titles        (24599, 36)
df_season_info                 (33339, 8)
df_per_game                    (33339, 32)
df                             (6, 5)
df_awards                      (3465, 10)
goat_awards                    (108, 10)
df_eos_teams                   (2222, 7)
df_mvp                         (1057, 11)
goat_mvp                       (74, 13)
mvp_wins                       (5, 1)
mvp_summary                    (5, 4)
mvp_complete                   (5, 6)
df_eos                         (2222, 7)
df_eos_nba                     (2034, 7)
goat_eos                       (101, 14)
eos_summary                    (5, 7)
individual_success             (5, 13)
individual_display             (5, 7)
goat_longevity                 (82, 36)
longevity_basic                (5, 4)
scoring_longevity              (5, 3)
goat_elite                     (79, 44)
elite_longevity                (5, 3)
longevity_complete             (5, 12)
longevity_display              (5, 8)
df_hist                        (28179, 42)
goat_hist                      (136, 42)
goat_playoffs                  (65, 42)
playoff_coverage               (5, 5)
playoff_summary                (5, 8)
goat_hist_all                  (136, 42)
rs                             (71, 10)
po                             (65, 10)
rs_po                          (65, 22)
coverage_rs_po                 (5, 2)
playoff_uplift                 (5, 8)
production_summary             (5, 4)
championships_master           (5, 1)
playoffs_master                (5, 3)
individual_master              (5, 6)
longevity_master               (5, 4)
goat_master                    (5, 19)
goat_scores                    (5, 18)
goat_norm                      (5, 23)
dimension_scores               (5, 6)
production_percentile          (5, 3)
efficiency_v2                  (5, 3)
longevity_v2                   (5, 4)
_279                           (5, 4)
scores_v2_check                (5, 4)
playoffs_v2                    (5, 4)
individual_v2                  (5, 7)
dimension_scores_v2            (5, 6)
goat_final                     (5, 8)
scenario_scores                (5, 5)
scenario_rankings              (5, 5)
scenario_winners               (5, 2)
final_dashboard                (5, 12)
dashboard_long                 (30, 3)
true_peak                      (5, 6)
goat_player_seasons_export     (79, 20)
methodology                    (6, 5)
games_rs                       (60192, 55)
team_games                     (120384, 26)
team_season                    (1519, 27)
X                              (1079, 8)
model_data                     (1079, 9)
X_scaled                       (1079, 8)
winning_factors                (8, 3)
train                          (1369, 27)
test                           (150, 27)
train_model                    (929, 9)
test_model                     (150, 9)
winning_factors_time           (8, 3)
window_results                 (4, 6)
team100                        (1462, 28)
opp100                         (1462, 28)
team_summary                   (1907, 31)
team100_nba                    (1433, 28)
opp100_nba                     (1433, 28)
summary_nba                    (1770, 31)
team_advanced                  (1433, 84)
analysis_v2                    (1403, 84)
train_v2                       (1163, 84)
test_v2                        (240, 84)
train_data_v2                  (1163, 9)
test_data_v2                   (240, 9)
winning_factors_v2             (8, 3)
team_season_final              (1433, 24)
winning_factors_final          (8, 12)
audit_df                       (8, 6)
df01                           (1433, 24)
df03                           (5, 20)
df04                           (5, 7)
df07                           (79, 20)
latest_player_season           (4897, 33)
future_candidates              (219, 34)
future_candidates_era          (219, 16)
goat_age_history               (79, 9)
goat_age_benchmark             (24, 5)
future_vs_goat                 (219, 24)
future_mvp                     (24, 11)
future_mvp_summary             (10, 2)
future_eos                     (112, 9)
future_allnba_summary          (71, 2)
future_recognition             (71, 4)
future_model                   (219, 28)

In [421]:
future_names = future_model["Name"].unique().tolist()

future_playoffs_raw = df_hist[
    (df_hist["name_common"].isin(future_names))
    &
    (df_hist["type"] == "PO")
].copy()

print("Candidats :", len(future_names))
print(
    "Candidats avec données playoffs :",
    future_playoffs_raw["name_common"].nunique()
)

print("\nJoueurs avec données playoffs :")
print(
    sorted(
        future_playoffs_raw["name_common"]
        .dropna()
        .unique()
    )
)

Candidats : 219
Candidats avec données playoffs : 34

Joueurs avec données playoffs :
['Aaron Holiday', 'Amir Coffey', 'Anfernee Simons', 'Bam Adebayo', 'Bol Bol', 'Bruce Brown', 'Dejounte Murray', 'Derrick Jones Jr.', 'Donovan Mitchell', 'Donte DiVincenzo', 'Gary Trent Jr.', 'Grant Williams', 'Isaiah Hartenstein', 'Ivica Zubac', 'Jamal Murray', 'Jarrett Allen', 'Jaylen Brown', 'Jayson Tatum', 'Johnny Davis', 'Jonathan Isaac', 'Landry Shamet', 'Lonnie Walker IV', 'Luguentz Dort', 'Malik Beasley', 'Markelle Fultz', 'Matisse Thybulle', 'Michael Porter Jr.', 'OG Anunoby', 'Shai Gilgeous-Alexander', 'Shake Milton', 'Talen Horton-Tucker', 'Terance Mann', 'Tyler Herro', 'Zach Collins']

In [422]:
future_playoffs = (
    future_playoffs_raw
    .groupby("name_common")
    .agg(
        playoff_seasons=("year_id", "nunique"),
        playoff_games=("G", "sum"),
        playoff_minutes=("Min", "sum"),
        playoff_raptor=("Raptor+/-", "mean"),
        playoff_war=("Raptor WAR", "sum"),
        playoff_ts=("TS%", "mean")
    )
    .reset_index()
    .rename(columns={"name_common": "Name"})
)

display(
    future_playoffs
    .sort_values("playoff_war", ascending=False)
    .head(25)
    .round(2)
)

,Name,playoff_seasons,playoff_games,playoff_minutes,playoff_raptor,playoff_war,playoff_ts
14,Jamal Murray,2,33,1261,5.15,5.59,58.00
17,Jayson Tatum,3,45,1668,2.53,5.16,55.70
16,Jaylen Brown,4,61,1744,-0.15,3.86,57.80
8,Donovan Mitchell,3,23,868,1.57,2.28,54.37
3,Bam Adebayo,2,24,764,-1.55,2.26,51.35
18,Johnny Davis,7,43,1070,1.74,2.05,51.33
26,Michael Porter Jr.,1,19,451,2.80,1.33,60.20
13,Ivica Zubac,2,17,359,3.30,1.30,57.20
27,OG Anunoby,2,21,631,0.95,1.23,63.40
6,Dejounte Murray,2,16,264,5.10,1.15,49.80
28,Shai Gilgeous-Alexander,2,13,452,-0.25,0.73,58.25
32,Tyler Herro,1,21,706,-0.90,0.69,55.70
20,Landry Shamet,2,19,417,0.65,0.56,54.50
11,Grant Williams,1,17,170,2.00,0.43,77.30
22,Luguentz Dort,1,6,175,1.30,0.38,45.40
4,Bol Bol,1,4,21,25.90,0.32,75.90
7,Derrick Jones Jr.,1,15,97,3.60,0.32,57.30
2,Anfernee Simons,2,9,94,-5.20,0.31,34.40
15,Jarrett Allen,2,9,242,-0.85,0.31,66.70
33,Zach Collins,2,20,345,-3.05,0.25,51.65
30,Talen Horton-Tucker,1,2,17,12.90,0.14,58.30
29,Shake Milton,1,4,126,-0.80,0.13,61.60
31,Terance Mann,1,13,27,3.10,0.08,40.00
1,Amir Coffey,1,3,7,19.00,0.08,25.80
10,Gary Trent Jr.,1,5,153,-2.00,0.07,49.90

In [423]:
future_regular_raw = df_hist[
    (df_hist["name_common"].isin(future_names))
    &
    (df_hist["type"] == "RS")
].copy()

future_regular = (
    future_regular_raw
    .groupby("name_common")
    .agg(
        regular_raptor=("Raptor+/-", "mean"),
        regular_ts=("TS%", "mean")
    )
    .reset_index()
    .rename(columns={"name_common": "Name"})
)

In [424]:
future_playoffs = future_playoffs.merge(
    future_regular,
    on="Name",
    how="left"
)

future_playoffs["raptor_uplift"] = (
    future_playoffs["playoff_raptor"]
    - future_playoffs["regular_raptor"]
)

future_playoffs["ts_uplift"] = (
    future_playoffs["playoff_ts"]
    - future_playoffs["regular_ts"]
)

In [425]:
display(
    future_playoffs[
        [
            "Name",
            "playoff_seasons",
            "playoff_games",
            "playoff_raptor",
            "regular_raptor",
            "raptor_uplift",
            "playoff_war",
            "playoff_ts",
            "regular_ts",
            "ts_uplift"
        ]
    ]
    .sort_values("playoff_war", ascending=False)
    .head(25)
    .round(2)
)

,Name,playoff_seasons,playoff_games,playoff_raptor,regular_raptor,raptor_uplift,playoff_war,playoff_ts,regular_ts,ts_uplift
14,Jamal Murray,2,33,5.15,0.90,4.25,5.59,58.00,54.78,3.23
17,Jayson Tatum,3,45,2.53,2.50,0.03,5.16,55.70,56.67,-0.97
16,Jaylen Brown,4,61,-0.15,-0.60,0.45,3.86,57.80,55.78,2.02
8,Donovan Mitchell,3,23,1.57,1.30,0.27,2.28,54.37,54.53,-0.17
3,Bam Adebayo,2,24,-1.55,0.53,-2.08,2.26,51.35,59.70,-8.35
18,Johnny Davis,7,43,1.74,-0.73,2.47,2.05,51.33,51.42,-0.09
26,Michael Porter Jr.,1,19,2.80,1.20,1.60,1.33,60.20,61.70,-1.50
13,Ivica Zubac,2,17,3.30,-0.64,3.94,1.30,57.20,59.24,-2.04
27,OG Anunoby,2,21,0.95,-0.63,1.58,1.23,63.40,57.70,5.70
6,Dejounte Murray,2,16,5.10,-1.67,6.77,1.15,49.80,50.40,-0.60
28,Shai Gilgeous-Alexander,2,13,-0.25,0.05,-0.30,0.73,58.25,56.10,2.15
32,Tyler Herro,1,21,-0.90,-1.80,0.90,0.69,55.70,55.00,0.70
20,Landry Shamet,2,19,0.65,-0.67,1.32,0.56,54.50,59.57,-5.07
11,Grant Williams,1,17,2.00,-1.10,3.10,0.43,77.30,50.50,26.80
22,Luguentz Dort,1,6,1.30,0.80,0.50,0.38,45.40,50.60,-5.20
4,Bol Bol,1,4,25.90,-5.00,30.90,0.32,75.90,61.70,14.20
7,Derrick Jones Jr.,1,15,3.60,1.70,1.90,0.32,57.30,58.36,-1.06
2,Anfernee Simons,2,9,-5.20,-7.45,2.25,0.31,34.40,51.85,-17.45
15,Jarrett Allen,2,9,-0.85,-2.10,1.25,0.31,66.70,64.40,2.30
33,Zach Collins,2,20,-3.05,-2.40,-0.65,0.25,51.65,52.50,-0.85
30,Talen Horton-Tucker,1,2,12.90,-4.60,17.50,0.14,58.30,53.50,4.80
29,Shake Milton,1,4,-0.80,-2.25,1.45,0.13,61.60,55.00,6.60
31,Terance Mann,1,13,3.10,-1.60,4.70,0.08,40.00,54.50,-14.50
1,Amir Coffey,1,3,19.00,-4.10,23.10,0.08,25.80,49.30,-23.50
10,Gary Trent Jr.,1,5,-2.00,-4.00,2.00,0.07,49.90,48.20,1.70

In [426]:
candidate_career_start = (
    df_player_season[
        df_player_season["Name"].isin(future_names)
    ]
    .groupby("Name")
    .agg(
        first_season=("SEASON_ID", "min"),
        last_season=("SEASON_ID", "max")
    )
    .reset_index()
)

candidate_career_start["career_start_year"] = (
    candidate_career_start["first_season"]
    .str[:4]
    .astype(int)
)

display(
    candidate_career_start
    .sort_values("career_start_year")
    .tail(30)
)

                        Name first_season last_season  career_start_year
8          Andre Jackson Jr.      2023-24     2023-24               2023
22        Brandin Podziemski      2023-24     2023-24               2023
58          Dereck Lively II      2023-24     2023-24               2023
127          Julian Phillips      2023-24     2023-24               2023
119           Jordan Hawkins      2023-24     2023-24               2023
102             Jalen Wilson      2023-24     2023-24               2023
93          Jaime Jaquez Jr.      2023-24     2023-24               2023
74               Gradey Dick      2023-24     2023-24               2023
70                GG Jackson      2023-24     2023-24               2023
11             Anthony Black      2023-24     2023-24               2023
13            Ausar Thompson      2023-24     2023-24               2023
24            Brandon Miller      2023-24     2023-24               2023
17              Ben Sheppard      2023-24     2023-24               2023
19           Bilal Coulibaly      2023-24     2023-24               2023
33             Cason Wallace      2023-24     2023-24               2023
43          Craig Porter Jr.      2023-24     2023-24               2023
34             Chet Holmgren      2023-24     2023-24               2023
32              Cam Whitmore      2023-24     2023-24               2023
150            Marcus Sasser      2023-24     2023-24               2023
191          Scoot Henderson      2023-24     2023-24               2023
173  Olivier-Maxence Prosper      2023-24     2023-24               2023
167           Nick Smith Jr.      2023-24     2023-24               2023
135           Keyonte George      2023-24     2023-24               2023
137               Kobe Brown      2023-24     2023-24               2023
138              Kris Murray      2023-24     2023-24               2023
128         Julian Strawther      2023-24     2023-24               2023
197         Taylor Hendricks      2023-24     2023-24               2023
201     Trayce Jackson-Davis      2023-24     2023-24               2023
199           Toumani Camara      2023-24     2023-24               2023
210        Victor Wembanyama      2023-24     2023-24               2023

In [427]:
future_hist_clean = df_hist[
    df_hist["name_common"].isin(future_names)
].copy()

future_hist_clean = future_hist_clean.merge(
    candidate_career_start[
        [
            "Name",
            "career_start_year"
        ]
    ],
    left_on="name_common",
    right_on="Name",
    how="left"
)

In [428]:
future_hist_clean = future_hist_clean[
    future_hist_clean["year_id"]
    >= future_hist_clean["career_start_year"]
].copy()

In [429]:
display(
    future_hist_clean[
        [
            "name_common",
            "year_id",
            "type",
            "age",
            "career_start_year"
        ]
    ]
    .sort_values(
        ["name_common", "year_id"]
    )
)

         name_common  year_id type  age  career_start_year
131    Aaron Holiday     2019   RS   22               2018
132    Aaron Holiday     2019   PO   22               2018
37     Aaron Holiday     2020   RS   23               2018
39     Aaron Holiday     2020   PO   23               2018
43       Amir Coffey     2020   RS   22               2019
..               ...      ...  ...  ...                ...
196     Zach Collins     2018   PO   20               2017
159     Zach Collins     2019   RS   21               2017
162     Zach Collins     2019   PO   21               2017
86      Zach Collins     2020   RS   22               2017
64   Zion Williamson     2020   RS   19               2019

[233 rows x 5 columns]

In [430]:
display(
    future_hist_clean[
        future_hist_clean["name_common"] == "Johnny Davis"
    ]
)

,player_id,name_common,year_id,type,age,team_id,pos,tmRtg,franch_id,G,...,%Pos,DRtg,2P%,3P%,FT%,3PAr,FTAr,Pace +/-,Name,career_start_year
215,davisjo01,Johnny Davis,1986,RS,30,ATL,SG,2.4,ATL,27,...,19.5,109.7,42.9,50.0,86.4,1.9,55.1,-0.3,Johnny Davis,1976
216,davisjo01,Johnny Davis,1986,PO,30,ATL,SG,NaN,ATL,8,...,NaN,NaN,NaN,NaN,NaN,0.0,16.0,-0.3,Johnny Davis,1976
217,davisjo01,Johnny Davis,1986,RS,30,CLE,SG,-2.8,CLE,39,...,20.8,110.8,44.2,18.2,84.8,4.6,33.3,-0.2,Johnny Davis,1976
218,davisjo01,Johnny Davis,1985,RS,29,CLE,PG,-2.7,CLE,76,...,23.0,113.1,43.6,26.1,85.0,5.8,37.9,-0.4,Johnny Davis,1976
219,davisjo01,Johnny Davis,1985,PO,29,CLE,PG,NaN,CLE,3,...,NaN,NaN,NaN,NaN,NaN,6.3,31.3,0.2,Johnny Davis,1976
220,davisjo01,Johnny Davis,1984,RS,28,ATL,PG,-1.3,ATL,75,...,21.8,110.8,44.7,0.0,84.8,1.0,32.0,-0.4,Johnny Davis,1976
221,davisjo01,Johnny Davis,1984,PO,28,ATL,PG,NaN,ATL,5,...,NaN,NaN,NaN,NaN,NaN,0.0,10.9,-0.8,Johnny Davis,1976
222,davisjo01,Johnny Davis,1983,RS,27,ATL,SG,-1.0,ATL,53,...,22.8,106.6,46.1,27.8,79.6,3.2,36.3,-0.5,Johnny Davis,1976
223,davisjo01,Johnny Davis,1983,PO,27,ATL,SG,NaN,ATL,3,...,NaN,NaN,NaN,NaN,NaN,1.9,19.2,-0.9,Johnny Davis,1976
224,davisjo01,Johnny Davis,1982,RS,26,IND,SG,-1.9,IND,82,...,23.3,109.1,47.3,18.5,79.9,2.3,34.2,-0.4,Johnny Davis,1976
225,davisjo01,Johnny Davis,1981,RS,25,IND,PG,1.4,IND,76,...,19.7,108.8,47.7,12.1,79.6,3.6,32.6,-0.3,Johnny Davis,1976
226,davisjo01,Johnny Davis,1981,PO,25,IND,PG,NaN,IND,2,...,NaN,NaN,NaN,NaN,NaN,2.9,37.1,-0.6,Johnny Davis,1976
227,davisjo01,Johnny Davis,1980,RS,24,IND,PG,-0.7,IND,82,...,20.1,110.1,44.0,9.5,86.4,3.6,30.4,-0.4,Johnny Davis,1976
228,davisjo01,Johnny Davis,1979,RS,23,IND,PG,-1.5,IND,79,...,21.3,108.1,45.6,0.0,79.3,0.0,31.9,-0.5,Johnny Davis,1976
229,davisjo01,Johnny Davis,1978,RS,22,POR,SG,5.9,POR,82,...,17.9,101.1,45.4,0.0,82.8,0.0,30.0,-0.2,Johnny Davis,1976
230,davisjo01,Johnny Davis,1978,PO,22,POR,SG,NaN,POR,6,...,NaN,NaN,NaN,NaN,NaN,0.0,30.3,-0.2,Johnny Davis,1976
231,davisjo01,Johnny Davis,1977,RS,21,POR,SG,5.2,POR,79,...,19.2,103.0,44.1,0.0,79.4,0.0,39.4,-0.2,Johnny Davis,1976
232,davisjo01,Johnny Davis,1977,PO,21,POR,SG,NaN,POR,16,...,NaN,NaN,NaN,NaN,NaN,0.0,39.8,0.0,Johnny Davis,1976

In [431]:
print(
    "Première année :",
    df_hist["year_id"].min()
)

print(
    "Dernière année :",
    df_hist["year_id"].max()
)

print(
    df_hist["year_id"]
    .sort_values()
    .unique()[-10:]
)

Première année : 1977
Dernière année : 2020
[2011 2012 2013 2014 2015 2016 2017 2018 2019 2020]

In [432]:
df_hist["year_id"].min()
df_hist["year_id"].max()

2020

In [433]:
recognition_check = (
    future_model[
        [
            "Name",
            "AGE",
            "early_mvp_wins",
            "early_mvp_share",
            "early_all_nba",
            "early_all_nba_1st"
        ]
    ]
    .sort_values(
        ["early_mvp_share", "early_all_nba_1st", "early_all_nba"],
        ascending=False
    )
)

display(recognition_check.head(25))

,Name,AGE,early_mvp_wins,early_mvp_share,early_all_nba,early_all_nba_1st
158,Shai Gilgeous-Alexander,25,1.0,1.605,3.0,3.0
214,Luka Dončić,25,0.0,0.968,5.0,5.0
104,Jayson Tatum,26,0.0,0.722,5.0,4.0
206,Devin Booker,27,0.0,0.216,2.0,1.0
137,Jalen Brunson,27,0.0,0.145,2.0,0.0
154,Donovan Mitchell,27,0.0,0.104,2.0,1.0
113,Anthony Edwards,22,0.0,0.030,2.0,0.0
19,Cade Cunningham,22,0.0,0.012,1.0,0.0
105,De'Aaron Fox,26,0.0,0.002,1.0,0.0
21,Evan Mobley,23,0.0,0.001,1.0,0.0
148,Tyrese Haliburton,24,0.0,0.000,2.0,0.0
76,Jalen Williams,23,0.0,0.000,1.0,0.0
125,Jaylen Brown,27,0.0,0.000,1.0,0.0
211,Trae Young,25,0.0,0.000,1.0,0.0
0,Johnny Davis,22,0.0,0.000,0.0,0.0
1,Aaron Wiggins,25,0.0,0.000,0.0,0.0
2,Keegan Murray,23,0.0,0.000,0.0,0.0
3,Chet Holmgren,22,0.0,0.000,0.0,0.0
4,Nickeil Alexander-Walker,25,0.0,0.000,0.0,0.0
5,Jabari Smith Jr.,21,0.0,0.000,0.0,0.0
6,Paolo Banchero,21,0.0,0.000,0.0,0.0
7,Jaden Ivey,22,0.0,0.000,0.0,0.0
8,Bennedict Mathurin,22,0.0,0.000,0.0,0.0
9,Max Christie,21,0.0,0.000,0.0,0.0
10,Andrew Nembhard,24,0.0,0.000,0.0,0.0

In [434]:
future_model["Recognition_Trajectory"] = (
      future_model["early_mvp_wins"]      * 30
    + future_model["early_mvp_share"]     * 20
    + future_model["early_all_nba_1st"]   * 10
    + future_model["early_all_nba"]       * 5
).clip(0, 100)

In [435]:
display(
    future_model[
        [
            "Name",
            "AGE",
            "early_mvp_wins",
            "early_mvp_share",
            "early_all_nba",
            "early_all_nba_1st",
            "Recognition_Trajectory"
        ]
    ]
    .sort_values(
        "Recognition_Trajectory",
        ascending=False
    )
    .head(25)
    .round(2)
)

,Name,AGE,early_mvp_wins,early_mvp_share,early_all_nba,early_all_nba_1st,Recognition_Trajectory
158,Shai Gilgeous-Alexander,25,1.0,1.60,3.0,3.0,100.00
214,Luka Dončić,25,0.0,0.97,5.0,5.0,94.36
104,Jayson Tatum,26,0.0,0.72,5.0,4.0,79.44
206,Devin Booker,27,0.0,0.22,2.0,1.0,24.32
154,Donovan Mitchell,27,0.0,0.10,2.0,1.0,22.08
137,Jalen Brunson,27,0.0,0.14,2.0,0.0,12.90
113,Anthony Edwards,22,0.0,0.03,2.0,0.0,10.60
148,Tyrese Haliburton,24,0.0,0.00,2.0,0.0,10.00
19,Cade Cunningham,22,0.0,0.01,1.0,0.0,5.24
105,De'Aaron Fox,26,0.0,0.00,1.0,0.0,5.04
21,Evan Mobley,23,0.0,0.00,1.0,0.0,5.02
211,Trae Young,25,0.0,0.00,1.0,0.0,5.00
125,Jaylen Brown,27,0.0,0.00,1.0,0.0,5.00
76,Jalen Williams,23,0.0,0.00,1.0,0.0,5.00
10,Andrew Nembhard,24,0.0,0.00,0.0,0.0,0.00
15,Jalen Duren,20,0.0,0.00,0.0,0.0,0.00
9,Max Christie,21,0.0,0.00,0.0,0.0,0.00
11,Jalen Suggs,23,0.0,0.00,0.0,0.0,0.00
12,Nikola Jović,21,0.0,0.00,0.0,0.0,0.00
3,Chet Holmgren,22,0.0,0.00,0.0,0.0,0.00
4,Nickeil Alexander-Walker,25,0.0,0.00,0.0,0.0,0.00
5,Jabari Smith Jr.,21,0.0,0.00,0.0,0.0,0.00
6,Paolo Banchero,21,0.0,0.00,0.0,0.0,0.00
7,Jaden Ivey,22,0.0,0.00,0.0,0.0,0.00
8,Bennedict Mathurin,22,0.0,0.00,0.0,0.0,0.00

In [436]:
future_model["Production_Trajectory"] = gap_score(
    future_model["production_gap_vs_goat"],
    low=-1.5,
    high=1.0
)

future_model["Efficiency_Trajectory"] = gap_score(
    future_model["efficiency_gap_vs_goat"],
    low=-20,
    high=10
)

In [437]:
display(
    future_model[
        [
            "Name",
            "AGE",
            "Production_Trajectory",
            "Efficiency_Trajectory",
            "Recognition_Trajectory"
        ]
    ]
    .sort_values(
        "Production_Trajectory",
        ascending=False
    )
    .head(20)
    .round(1)
)

,Name,AGE,Production_Trajectory,Efficiency_Trajectory,Recognition_Trajectory
214,Luka Dončić,25,93.2,42.0,94.4
211,Trae Young,25,47.7,23.0,5.0
148,Tyrese Haliburton,24,47.5,43.9,10.0
56,Victor Wembanyama,20,47.2,25.0,0.0
158,Shai Gilgeous-Alexander,25,43.2,52.8,100.0
187,Scottie Barnes,22,43.2,32.8,0.0
104,Jayson Tatum,26,42.2,37.7,79.4
19,Cade Cunningham,22,39.1,20.9,5.2
206,Devin Booker,27,37.9,45.2,24.3
113,Anthony Edwards,22,37.8,38.4,10.6
137,Jalen Brunson,27,35.9,34.3,12.9
139,Tyrese Maxey,23,35.3,35.2,0.0
154,Donovan Mitchell,27,34.1,35.9,22.1
185,Alperen Sengun,21,31.7,40.1,0.0
33,Zion Williamson,23,31.4,57.3,0.0
166,Bam Adebayo,26,29.4,21.0,0.0
105,De'Aaron Fox,26,28.4,15.6,5.0
116,Dejounte Murray,27,27.9,12.5,0.0
6,Paolo Banchero,21,25.6,16.8,0.0
15,Jalen Duren,20,25.1,76.9,0.0

In [438]:
print("Dernière saison MVP :", df_mvp["season"].max())
print("Dernière saison EOS :", df_eos_nba["season"].max())

display(
    df_mvp[
        df_mvp["player"].isin([
            "Shai Gilgeous-Alexander",
            "Luka Dončić",
            "Jayson Tatum"
        ])
    ][
        ["season", "player", "share", "winner"]
    ]
    .sort_values(["player", "season"])
)

Dernière saison MVP : 2025
Dernière saison EOS : 2025

     season                   player  share  winner
367    2020             Jayson Tatum  0.001   False
232    2022             Jayson Tatum  0.043   False
178    2023             Jayson Tatum  0.280   False
114    2024             Jayson Tatum  0.087   False
42     2025             Jayson Tatum  0.311   False
359    2020              Luka Dončić  0.198   False
300    2021              Luka Dončić  0.042   False
231    2022              Luka Dončić  0.146   False
182    2023              Luka Dončić  0.010   False
111    2024              Luka Dončić  0.572   False
179    2023  Shai Gilgeous-Alexander  0.046   False
110    2024  Shai Gilgeous-Alexander  0.646   False
39     2025  Shai Gilgeous-Alexander  0.913    True

In [439]:
print(df_mvp["season"].dropna().unique()[-15:])
print(df_eos_nba["season"].dropna().unique()[-15:])

[1970 1969 1968 1967 1966 1965 1964 1963 1962 1961 1960 1959 1958 1957
 1956]
[1964 1963 1962 1961 1960 1959 1958 1957 1956 1955 1954 1953 1952 1951
 1950]

In [440]:
MVP_CUTOFF = 2024

df_mvp_future = df_mvp[
    df_mvp["season"] <= MVP_CUTOFF
].copy()

df_eos_future = df_eos_nba[
    df_eos_nba["season"] <= MVP_CUTOFF
].copy()

In [441]:
print("Dernière saison MVP :", df_mvp["season"].max())
print("Dernière saison EOS :", df_eos_nba["season"].max())

print(df_mvp["season"].dropna().unique()[-15:])
print(df_eos_nba["season"].dropna().unique()[-15:])

Dernière saison MVP : 2025
Dernière saison EOS : 2025
[1970 1969 1968 1967 1966 1965 1964 1963 1962 1961 1960 1959 1958 1957
 1956]
[1964 1963 1962 1961 1960 1959 1958 1957 1956 1955 1954 1953 1952 1951
 1950]

In [442]:
CUTOFF_YEAR = 2024

df_mvp_cutoff = df_mvp[
    df_mvp["season"] <= CUTOFF_YEAR
].copy()

df_eos_cutoff = df_eos_nba[
    df_eos_nba["season"] <= CUTOFF_YEAR
].copy()

print(
    "MVP :",
    df_mvp_cutoff["season"].min(),
    "→",
    df_mvp_cutoff["season"].max()
)

print(
    "End of Season Teams :",
    df_eos_cutoff["season"].min(),
    "→",
    df_eos_cutoff["season"].max()
)

MVP : 1956 → 2024
End of Season Teams : 1950 → 2024

In [443]:
future_names = future_model["Name"].unique().tolist()

future_mvp = df_mvp_cutoff[
    df_mvp_cutoff["player"].isin(future_names)
].copy()

future_mvp_summary = (
    future_mvp
    .groupby("player")
    .agg(
        early_mvp_wins=("winner", "sum"),
        early_mvp_share=("share", "sum")
    )
)

In [444]:
future_eos = df_eos_cutoff[
    df_eos_cutoff["player"].isin(future_names)
].copy()

future_eos["ALL_NBA"] = (
    future_eos["type"] == "All-NBA"
).astype(int)

future_eos["ALL_NBA_1ST"] = (
    (future_eos["type"] == "All-NBA")
    &
    (future_eos["number_tm"] == "1st")
).astype(int)

future_allnba_summary = (
    future_eos
    .groupby("player")
    .agg(
        early_all_nba=("ALL_NBA", "sum"),
        early_all_nba_1st=("ALL_NBA_1ST", "sum")
    )
)

In [445]:
future_recognition = (
    future_mvp_summary
    .join(
        future_allnba_summary,
        how="outer"
    )
    .fillna(0)
)

display(
    future_recognition
    .sort_values(
        ["early_mvp_share", "early_all_nba_1st"],
        ascending=False
    )
    .head(20)
)

,early_mvp_wins,early_mvp_share,early_all_nba,early_all_nba_1st
player,,,,
Luka Dončić,0.0,0.968,5,5
Shai Gilgeous-Alexander,0.0,0.692,2,2
Jayson Tatum,0.0,0.411,4,3
Devin Booker,0.0,0.216,2,1
Jalen Brunson,0.0,0.144,1,0
Donovan Mitchell,0.0,0.030,1,0
Anthony Edwards,0.0,0.018,1,0
De'Aaron Fox,0.0,0.002,1,0
Amen Thompson,0.0,0.000,0,0
Ayo Dosunmu,0.0,0.000,0,0
Bam Adebayo,0.0,0.000,0,0
Bennedict Mathurin,0.0,0.000,0,0
Brandin Podziemski,0.0,0.000,0,0
Brandon Ingram,0.0,0.000,0,0
Brandon Miller,0.0,0.000,0,0
Cade Cunningham,0.0,0.000,0,0
Cason Wallace,0.0,0.000,0,0
Chet Holmgren,0.0,0.000,0,0
Chris Duarte,0.0,0.000,0,0
Coby White,0.0,0.000,0,0

In [446]:
recognition_cols = [
    "early_mvp_wins",
    "early_mvp_share",
    "early_all_nba",
    "early_all_nba_1st",
    "Recognition_Trajectory"
]

future_model = future_model.drop(
    columns=[
        col for col in recognition_cols
        if col in future_model.columns
    ]
)

future_model = future_model.merge(
    future_recognition,
    left_on="Name",
    right_index=True,
    how="left"
)

In [447]:
cols = [
    "early_mvp_wins",
    "early_mvp_share",
    "early_all_nba",
    "early_all_nba_1st"
]

future_model[cols] = future_model[cols].fillna(0)

In [448]:
future_model["Recognition_Trajectory"] = (
      future_model["early_mvp_wins"] * 30
    + future_model["early_mvp_share"] * 20
    + future_model["early_all_nba_1st"] * 10
    + future_model["early_all_nba"] * 5
).clip(0, 100)

In [449]:
recognition_check = (
    future_model[
        [
            "Name",
            "AGE",
            "early_mvp_wins",
            "early_mvp_share",
            "early_all_nba",
            "early_all_nba_1st",
            "Recognition_Trajectory"
        ]
    ]
    .sort_values(
        "Recognition_Trajectory",
        ascending=False
    )
    .head(20)
    .round(2)
)

display(recognition_check)

,Name,AGE,early_mvp_wins,early_mvp_share,early_all_nba,early_all_nba_1st,Recognition_Trajectory
214,Luka Dončić,25,0.0,0.97,5.0,5.0,94.36
104,Jayson Tatum,26,0.0,0.41,4.0,3.0,58.22
158,Shai Gilgeous-Alexander,25,0.0,0.69,2.0,2.0,43.84
206,Devin Booker,27,0.0,0.22,2.0,1.0,24.32
137,Jalen Brunson,27,0.0,0.14,1.0,0.0,7.88
154,Donovan Mitchell,27,0.0,0.03,1.0,0.0,5.60
113,Anthony Edwards,22,0.0,0.02,1.0,0.0,5.36
105,De'Aaron Fox,26,0.0,0.00,1.0,0.0,5.04
125,Jaylen Brown,27,0.0,0.00,1.0,0.0,5.00
148,Tyrese Haliburton,24,0.0,0.00,1.0,0.0,5.00
211,Trae Young,25,0.0,0.00,1.0,0.0,5.00
11,Jalen Suggs,23,0.0,0.00,0.0,0.0,0.00
12,Nikola Jović,21,0.0,0.00,0.0,0.0,0.00
13,Jalen Wilson,23,0.0,0.00,0.0,0.0,0.00
14,Naz Reid,24,0.0,0.00,0.0,0.0,0.00
15,Jalen Duren,20,0.0,0.00,0.0,0.0,0.00
0,Johnny Davis,22,0.0,0.00,0.0,0.0,0.00
1,Aaron Wiggins,25,0.0,0.00,0.0,0.0,0.00
2,Keegan Murray,23,0.0,0.00,0.0,0.0,0.00
3,Chet Holmgren,22,0.0,0.00,0.0,0.0,0.00

In [450]:
GOATS = [
    "LeBron James",
    "Michael Jordan",
    "Kareem Abdul-Jabbar",
    "Magic Johnson",
    "Larry Bird"
]

goat_trajectory = df_era[
    df_era["Name"].isin(GOATS)
].copy()

goat_trajectory["AGE"] = (
    goat_trajectory["PLAYER_AGE"]
    .round()
    .astype(int)
)

goat_trajectory[
    ["Name", "SEASON_ID", "AGE", "PRODUCTION_Z", "TS_PLUS"]
].head()

                Name SEASON_ID  AGE  PRODUCTION_Z     TS_PLUS
3777  Michael Jordan   1984-85   22      1.848739  111.899423
3779  Michael Jordan   1986-87   24      2.094458  107.788642
3780  Michael Jordan   1987-88   25      2.228892  115.326175
3781  Michael Jordan   1988-89   26      2.618746  118.330280
3782  Michael Jordan   1989-90   27      2.317838  117.277310

In [451]:
def season_end_year(season):
    season = str(season)

    # exemple : 2023-24 -> 2024
    if "-" in season:
        start = int(season[:4])
        return start + 1

    return int(season)

goat_trajectory["season_end"] = (
    goat_trajectory["SEASON_ID"]
    .apply(season_end_year)
)

In [452]:
goat_mvp_age = []

for _, row in goat_trajectory.iterrows():

    player = row["Name"]
    year = row["season_end"]

    awards = df_mvp[
        (df_mvp["player"] == player)
        &
        (df_mvp["season"] <= year)
    ]

    goat_mvp_age.append({
        "Name": player,
        "season_end": year,
        "GOAT_MVP_WINS": awards["winner"].sum(),
        "GOAT_MVP_SHARE": awards["share"].sum()
    })

goat_mvp_age = pd.DataFrame(goat_mvp_age)

In [453]:
goat_allnba_age = []

for _, row in goat_trajectory.iterrows():

    player = row["Name"]
    year = row["season_end"]

    awards = df_eos_nba[
        (df_eos_nba["player"] == player)
        &
        (df_eos_nba["season"] <= year)
        &
        (df_eos_nba["type"] == "All-NBA")
    ]

    goat_allnba_age.append({
        "Name": player,
        "season_end": year,
        "GOAT_ALL_NBA": len(awards),
        "GOAT_ALL_NBA_1ST":
            (awards["number_tm"] == "1st").sum()
    })

goat_allnba_age = pd.DataFrame(goat_allnba_age)

In [454]:
goat_trajectory = (
    goat_trajectory
    .merge(
        goat_mvp_age,
        on=["Name", "season_end"],
        how="left"
    )
    .merge(
        goat_allnba_age,
        on=["Name", "season_end"],
        how="left"
    )
)

In [455]:
goat_trajectory["Recognition_Trajectory"] = (
      goat_trajectory["GOAT_MVP_WINS"] * 30
    + goat_trajectory["GOAT_MVP_SHARE"] * 20
    + goat_trajectory["GOAT_ALL_NBA_1ST"] * 10
    + goat_trajectory["GOAT_ALL_NBA"] * 5
).clip(0, 100)

In [456]:
goat_age_check = (
    goat_trajectory[
        goat_trajectory["AGE"].between(20, 27)
    ][
        [
            "Name",
            "AGE",
            "SEASON_ID",
            "PRODUCTION_Z",
            "TS_PLUS",
            "GOAT_MVP_WINS",
            "GOAT_MVP_SHARE",
            "GOAT_ALL_NBA",
            "GOAT_ALL_NBA_1ST",
            "Recognition_Trajectory"
        ]
    ]
    .sort_values(["AGE", "Name"])
)

display(
    goat_age_check.round(2)
)

,Name,AGE,SEASON_ID,PRODUCTION_Z,TS_PLUS,GOAT_MVP_WINS,GOAT_MVP_SHARE,GOAT_ALL_NBA,GOAT_ALL_NBA_1ST,Recognition_Trajectory
26,LeBron James,20,2004-05,2.50,107.53,0,0.08,1,0,6.64
66,Magic Johnson,20,1979-80,1.67,116.33,0,0.00,0,0,0.00
27,LeBron James,21,2005-06,2.64,109.62,0,0.63,2,1,32.64
67,Magic Johnson,21,1980-81,2.29,112.45,0,0.03,0,0,0.52
28,LeBron James,22,2006-07,2.18,105.00,0,0.77,3,1,40.48
68,Magic Johnson,22,1981-82,2.36,112.43,0,0.12,1,0,7.46
0,Michael Jordan,22,1984-85,1.85,111.90,0,0.17,1,0,8.44
46,Kareem Abdul-Jabbar,23,1969-70,2.02,111.42,0,0.43,1,0,13.64
13,Larry Bird,23,1979-80,1.67,104.01,0,0.07,1,1,16.36
29,LeBron James,23,2007-08,2.67,108.74,0,1.12,4,2,62.44
69,Magic Johnson,23,1982-83,2.20,116.89,0,0.53,2,1,30.58
47,Kareem Abdul-Jabbar,24,1970-71,2.24,126.19,1,1.33,2,1,76.54
14,Larry Bird,24,1980-81,2.00,102.17,0,0.68,2,2,43.62
30,LeBron James,24,2008-09,2.56,111.56,1,2.09,5,3,100.00
70,Magic Johnson,24,1983-84,2.40,119.04,0,0.93,3,2,53.60
1,Michael Jordan,24,1986-87,2.09,107.79,0,0.75,2,1,34.96
48,Kareem Abdul-Jabbar,25,1971-72,2.64,124.77,2,1.97,3,2,100.00
15,Larry Bird,25,1981-82,2.18,106.14,0,1.27,3,3,70.38
31,LeBron James,25,2009-10,2.89,113.80,2,3.07,6,4,100.00
71,Magic Johnson,25,1984-85,2.15,120.44,0,1.27,4,3,75.36
2,Michael Jordan,25,1987-88,2.23,115.33,1,1.58,3,2,96.58
49,Kareem Abdul-Jabbar,26,1972-73,2.43,120.07,2,2.36,4,3,100.00
16,Larry Bird,26,1982-83,2.15,108.75,0,1.75,4,4,95.08
32,LeBron James,26,2010-11,2.50,112.58,2,3.50,7,5,100.00
72,Magic Johnson,26,1985-86,2.19,115.48,0,1.53,5,4,95.62
3,Michael Jordan,26,1988-89,2.62,118.33,1,2.28,4,3,100.00
50,Kareem Abdul-Jabbar,27,1973-74,2.29,114.78,3,2.94,5,4,100.00
17,Larry Bird,27,1983-84,2.18,104.66,1,2.61,5,5,100.00
33,LeBron James,27,2011-12,2.58,117.91,3,4.39,8,6,100.00
73,Magic Johnson,27,1986-87,2.45,115.50,1,2.47,6,5,100.00
4,Michael Jordan,27,1989-90,2.32,117.28,1,2.90,5,4,100.00

In [457]:
from sklearn.preprocessing import StandardScaler
import numpy as np

In [458]:
features = [
    "PRODUCTION_Z",
    "TS_PLUS",
    "Recognition_Trajectory"
]

reference = pd.concat([
    future_model[features],
    goat_trajectory[features]
]).dropna()

scaler_similarity = StandardScaler()

scaler_similarity.fit(reference)

StandardScaler()

In [459]:
similarity_rows = []

for _, candidate in future_model.iterrows():

    age = candidate["AGE"]

    goats_same_age = goat_trajectory[
        goat_trajectory["AGE"] == age
    ]

    if goats_same_age.empty:
        continue

    candidate_vector = scaler_similarity.transform(
        pd.DataFrame(
            [candidate[features].values],
            columns=features
        )
    )[0]

    for _, goat in goats_same_age.iterrows():

        goat_vector = scaler_similarity.transform(
            pd.DataFrame(
                [goat[features].values],
                columns=features
            )
        )[0]

        distance = np.linalg.norm(
            candidate_vector - goat_vector
        )

        similarity = 100 / (1 + distance)

        similarity_rows.append({
            "Name": candidate["Name"],
            "AGE": age,
            "GOAT": goat["Name"],
            "Distance": distance,
            "Similarity": similarity
        })

goat_similarity = pd.DataFrame(similarity_rows)

In [460]:
closest_goat = (
    goat_similarity
    .sort_values(
        ["Name", "Similarity"],
        ascending=[True, False]
    )
    .groupby("Name")
    .first()
    .reset_index()
)

In [461]:
display(
    closest_goat[
        [
            "Name",
            "AGE",
            "GOAT",
            "Similarity",
            "Distance"
        ]
    ]
    .sort_values(
        "Similarity",
        ascending=False
    )
    .head(30)
    .round(2)
)

                        Name  AGE                 GOAT  Similarity  Distance
95               Jalen Duren   20        Magic Johnson       70.70      0.41
209             Tyrese Maxey   23           Larry Bird       65.42      0.53
218          Zion Williamson   23           Larry Bird       63.67      0.57
143              Luka Dončić   25         LeBron James       62.13      0.61
208        Tyrese Haliburton   24       Michael Jordan       56.85      0.76
56               Deni Avdija   23           Larry Bird       56.68      0.76
68               Evan Mobley   23  Kareem Abdul-Jabbar       55.08      0.82
34             Chet Holmgren   22       Michael Jordan       54.52      0.83
62             Devin Vassell   23           Larry Bird       53.73      0.86
193  Shai Gilgeous-Alexander   25           Larry Bird       53.08      0.88
101           Jalen Williams   23           Larry Bird       51.35      0.95
111             Jayson Tatum   26           Larry Bird       51.13      0.96
210        Victor Wembanyama   20         LeBron James       49.10      1.04
5             Alperen Sengun   21        Magic Johnson       48.98      1.04
12           Anthony Edwards   22         LeBron James       48.19      1.08
97             Jalen Johnson   22       Michael Jordan       47.81      1.09
211       Vince Williams Jr.   23           Larry Bird       45.68      1.19
192           Scottie Barnes   22         LeBron James       45.42      1.20
130            Keegan Murray   23           Larry Bird       45.02      1.22
83            Isaiah Stewart   23           Larry Bird       44.11      1.27
69              Franz Wagner   22       Michael Jordan       43.09      1.32
207              Tyler Herro   24           Larry Bird       42.52      1.35
39                Coby White   24           Larry Bird       42.47      1.35
70                GG Jackson   19         LeBron James       42.34      1.36
185               RJ Barrett   24           Larry Bird       41.69      1.40
93          Jaime Jaquez Jr.   23           Larry Bird       41.58      1.40
100              Jalen Suggs   23           Larry Bird       41.42      1.41
28           Cade Cunningham   22         LeBron James       41.26      1.42
47            Darius Garland   24           Larry Bird       41.18      1.43
203                 Tre Mann   23           Larry Bird       40.87      1.45

In [462]:
stars = [
    "Luka Dončić",
    "Shai Gilgeous-Alexander",
    "Jayson Tatum",
    "Anthony Edwards",
    "Victor Wembanyama",
    "Paolo Banchero",
    "Chet Holmgren",
    "Tyrese Haliburton"
]

display(
    goat_similarity[
        goat_similarity["Name"].isin(stars)
    ][
        [
            "Name",
            "AGE",
            "GOAT",
            "Similarity",
            "Distance"
        ]
    ]
    .sort_values(
        ["Name", "Similarity"],
        ascending=[True, False]
    )
    .round(2)
)

                        Name  AGE                 GOAT  Similarity  Distance
420          Anthony Edwards   22         LeBron James       48.19      1.08
419          Anthony Edwards   22       Michael Jordan       48.02      1.08
421          Anthony Edwards   22        Magic Johnson       43.51      1.30
12             Chet Holmgren   22       Michael Jordan       54.52      0.83
14             Chet Holmgren   22        Magic Johnson       44.12      1.27
13             Chet Holmgren   22         LeBron James       38.42      1.60
376             Jayson Tatum   26           Larry Bird       51.13      0.96
377             Jayson Tatum   26         LeBron James       43.55      1.30
379             Jayson Tatum   26        Magic Johnson       43.26      1.31
375             Jayson Tatum   26       Michael Jordan       37.32      1.68
378             Jayson Tatum   26  Kareem Abdul-Jabbar       36.24      1.76
883              Luka Dončić   25         LeBron James       62.13      0.61
881              Luka Dončić   25       Michael Jordan       47.65      1.10
882              Luka Dončić   25           Larry Bird       47.09      1.12
885              Luka Dončić   25        Magic Johnson       38.90      1.57
884              Luka Dončić   25  Kareem Abdul-Jabbar       37.19      1.69
23            Paolo Banchero   21        Magic Johnson       36.60      1.73
22            Paolo Banchero   21         LeBron James       35.69      1.80
631  Shai Gilgeous-Alexander   25           Larry Bird       53.08      0.88
634  Shai Gilgeous-Alexander   25        Magic Johnson       46.41      1.15
630  Shai Gilgeous-Alexander   25       Michael Jordan       42.46      1.36
632  Shai Gilgeous-Alexander   25         LeBron James       38.58      1.59
633  Shai Gilgeous-Alexander   25  Kareem Abdul-Jabbar       33.79      1.96
581        Tyrese Haliburton   24       Michael Jordan       56.85      0.76
582        Tyrese Haliburton   24           Larry Bird       48.91      1.04
585        Tyrese Haliburton   24        Magic Johnson       36.10      1.77
583        Tyrese Haliburton   24         LeBron James       29.01      2.45
584        Tyrese Haliburton   24  Kareem Abdul-Jabbar       27.45      2.64
193        Victor Wembanyama   20         LeBron James       49.10      1.04
194        Victor Wembanyama   20        Magic Johnson       37.29      1.68

In [463]:
closest_goat_score = (
    goat_similarity
    .sort_values(
        ["Name", "Similarity"],
        ascending=[True, False]
    )
    .groupby("Name", as_index=False)
    .first()
    .rename(
        columns={
            "GOAT": "Closest_GOAT",
            "Similarity": "GOAT_Similarity",
            "Distance": "GOAT_Distance"
        }
    )
)

display(
    closest_goat_score[
        [
            "Name",
            "AGE",
            "Closest_GOAT",
            "GOAT_Similarity"
        ]
    ]
    .sort_values("GOAT_Similarity", ascending=False)
    .head(20)
    .round(2)
)

                        Name  AGE         Closest_GOAT  GOAT_Similarity
95               Jalen Duren   20        Magic Johnson            70.70
209             Tyrese Maxey   23           Larry Bird            65.42
218          Zion Williamson   23           Larry Bird            63.67
143              Luka Dončić   25         LeBron James            62.13
208        Tyrese Haliburton   24       Michael Jordan            56.85
56               Deni Avdija   23           Larry Bird            56.68
68               Evan Mobley   23  Kareem Abdul-Jabbar            55.08
34             Chet Holmgren   22       Michael Jordan            54.52
62             Devin Vassell   23           Larry Bird            53.73
193  Shai Gilgeous-Alexander   25           Larry Bird            53.08
101           Jalen Williams   23           Larry Bird            51.35
111             Jayson Tatum   26           Larry Bird            51.13
210        Victor Wembanyama   20         LeBron James            49.10
5             Alperen Sengun   21        Magic Johnson            48.98
12           Anthony Edwards   22         LeBron James            48.19
97             Jalen Johnson   22       Michael Jordan            47.81
211       Vince Williams Jr.   23           Larry Bird            45.68
192           Scottie Barnes   22         LeBron James            45.42
130            Keegan Murray   23           Larry Bird            45.02
83            Isaiah Stewart   23           Larry Bird            44.11

In [464]:
future_goat = future_model.merge(
    closest_goat_score[
        [
            "Name",
            "Closest_GOAT",
            "GOAT_Similarity",
            "GOAT_Distance"
        ]
    ],
    on="Name",
    how="left"
)

In [465]:
print("Lignes :", len(future_goat))
print("Joueurs :", future_goat["Name"].nunique())
print(
    "Similarité manquante :",
    future_goat["GOAT_Similarity"].isna().sum()
)

Lignes : 219
Joueurs : 219
Similarité manquante : 0

In [466]:
future_goat["Future_GOAT_Score"] = (
      future_goat["Production_Trajectory"] * 0.35
    + future_goat["Efficiency_Trajectory"] * 0.25
    + future_goat["Recognition_Trajectory"] * 0.25
    + future_goat["GOAT_Similarity"] * 0.15
)

In [467]:
future_goat["Future_GOAT_Rank"] = (
    future_goat["Future_GOAT_Score"]
    .rank(
        ascending=False,
        method="min"
    )
    .astype("Int64")
)

In [468]:
future_goat_ranking = (
    future_goat[
        [
            "Name",
            "AGE",
            "TEAM_ABBREVIATION",
            "Production_Trajectory",
            "Efficiency_Trajectory",
            "Recognition_Trajectory",
            "Closest_GOAT",
            "GOAT_Similarity",
            "Future_GOAT_Score",
            "Future_GOAT_Rank"
        ]
    ]
    .sort_values("Future_GOAT_Score", ascending=False)
)

display(
    future_goat_ranking
    .head(25)
    .round(1)
)

,Name,AGE,TEAM_ABBREVIATION,Production_Trajectory,Efficiency_Trajectory,Recognition_Trajectory,Closest_GOAT,GOAT_Similarity,Future_GOAT_Score,Future_GOAT_Rank
214,Luka Dončić,25,DAL,93.2,42.0,94.4,LeBron James,62.1,76.0,1
158,Shai Gilgeous-Alexander,25,OKC,43.2,52.8,43.8,Larry Bird,53.1,47.2,2
104,Jayson Tatum,26,BOS,42.2,37.7,58.2,Larry Bird,51.1,46.4,3
15,Jalen Duren,20,DET,25.1,76.9,0.0,Magic Johnson,70.7,38.6,4
148,Tyrese Haliburton,24,IND,47.5,43.9,5.0,Michael Jordan,56.8,37.4,5
206,Devin Booker,27,PHX,37.9,45.2,24.3,Larry Bird,34.4,35.8,6
33,Zion Williamson,23,NOP,31.4,57.3,0.0,Larry Bird,63.7,34.9,7
21,Evan Mobley,23,CLE,21.0,66.3,0.0,Kareem Abdul-Jabbar,55.1,32.2,8
113,Anthony Edwards,22,MIN,37.8,38.4,5.4,LeBron James,48.2,31.4,9
139,Tyrese Maxey,23,PHI,35.3,35.2,0.0,Larry Bird,65.4,31.0,10
52,Dereck Lively II,20,DAL,0.0,100.0,0.0,Magic Johnson,35.9,30.4,11
56,Victor Wembanyama,20,SAS,47.2,25.0,0.0,LeBron James,49.1,30.1,12
187,Scottie Barnes,22,TOR,43.2,32.8,0.0,LeBron James,45.4,30.1,13
3,Chet Holmgren,22,OKC,11.2,71.5,0.0,Michael Jordan,54.5,30.0,14
193,Isaiah Jackson,22,IND,0.0,100.0,0.0,Michael Jordan,31.4,29.7,15
211,Trae Young,25,ATL,47.7,23.0,5.0,Larry Bird,37.9,29.4,16
84,Daniel Gafford,25,TOT,0.0,100.0,0.0,Magic Johnson,28.4,29.3,17
155,Onyeka Okongwu,23,ATL,0.0,94.8,0.0,Kareem Abdul-Jabbar,36.7,29.2,18
106,Nick Richards,26,CHA,0.0,100.0,0.0,Magic Johnson,24.6,28.7,19
22,Jaxson Hayes,24,LAL,0.0,100.0,0.0,Magic Johnson,24.5,28.7,20
39,Bol Bol,24,PHX,0.0,99.4,0.0,Michael Jordan,25.3,28.6,21
185,Alperen Sengun,21,HOU,31.7,40.1,0.0,Magic Johnson,49.0,28.4,22
78,Walker Kessler,22,UTA,0.0,89.5,0.0,Michael Jordan,39.0,28.2,23
168,Jarrett Allen,26,CLE,16.3,72.8,0.0,Magic Johnson,28.7,28.2,24
94,Trayce Jackson-Davis,24,GSW,0.0,95.0,0.0,Michael Jordan,28.3,28.0,25

In [469]:
def future_goat_tier(score):

    if score >= 80:
        return "Generational GOAT trajectory"

    elif score >= 65:
        return "Elite historical trajectory"

    elif score >= 50:
        return "Strong GOAT trajectory"

    elif score >= 35:
        return "Emerging trajectory"

    else:
        return "Developing trajectory"


future_goat["Trajectory_Tier"] = (
    future_goat["Future_GOAT_Score"]
    .apply(future_goat_tier)
)

In [470]:
display(
    future_goat[
        [
            "Future_GOAT_Rank",
            "Name",
            "AGE",
            "Future_GOAT_Score",
            "Trajectory_Tier",
            "Closest_GOAT",
            "GOAT_Similarity"
        ]
    ]
    .sort_values("Future_GOAT_Rank")
    .head(20)
    .round(1)
)

,Future_GOAT_Rank,Name,AGE,Future_GOAT_Score,Trajectory_Tier,Closest_GOAT,GOAT_Similarity
214,1,Luka Dončić,25,76.0,Elite historical trajectory,LeBron James,62.1
158,2,Shai Gilgeous-Alexander,25,47.2,Emerging trajectory,Larry Bird,53.1
104,3,Jayson Tatum,26,46.4,Emerging trajectory,Larry Bird,51.1
15,4,Jalen Duren,20,38.6,Emerging trajectory,Magic Johnson,70.7
148,5,Tyrese Haliburton,24,37.4,Emerging trajectory,Michael Jordan,56.8
206,6,Devin Booker,27,35.8,Emerging trajectory,Larry Bird,34.4
33,7,Zion Williamson,23,34.9,Developing trajectory,Larry Bird,63.7
21,8,Evan Mobley,23,32.2,Developing trajectory,Kareem Abdul-Jabbar,55.1
113,9,Anthony Edwards,22,31.4,Developing trajectory,LeBron James,48.2
139,10,Tyrese Maxey,23,31.0,Developing trajectory,Larry Bird,65.4
52,11,Dereck Lively II,20,30.4,Developing trajectory,Magic Johnson,35.9
56,12,Victor Wembanyama,20,30.1,Developing trajectory,LeBron James,49.1
187,13,Scottie Barnes,22,30.1,Developing trajectory,LeBron James,45.4
3,14,Chet Holmgren,22,30.0,Developing trajectory,Michael Jordan,54.5
193,15,Isaiah Jackson,22,29.7,Developing trajectory,Michael Jordan,31.4
211,16,Trae Young,25,29.4,Developing trajectory,Larry Bird,37.9
84,17,Daniel Gafford,25,29.3,Developing trajectory,Magic Johnson,28.4
155,18,Onyeka Okongwu,23,29.2,Developing trajectory,Kareem Abdul-Jabbar,36.7
106,19,Nick Richards,26,28.7,Developing trajectory,Magic Johnson,24.6
22,20,Jaxson Hayes,24,28.7,Developing trajectory,Magic Johnson,24.5

In [471]:
diagnostic_cols = [
    "Future_GOAT_Rank",
    "Name",
    "AGE",
    "PRODUCTION_Z",
    "production_gap_vs_goat",
    "TS_PLUS",
    "efficiency_gap_vs_goat",
    "Production_Trajectory",
    "Efficiency_Trajectory",
    "Recognition_Trajectory",
    "Closest_GOAT",
    "GOAT_Similarity",
    "Future_GOAT_Score"
]

display(
    future_goat[
        diagnostic_cols
    ]
    .sort_values("Future_GOAT_Rank")
    .head(20)
    .round(2)
)

,Future_GOAT_Rank,Name,AGE,PRODUCTION_Z,production_gap_vs_goat,TS_PLUS,efficiency_gap_vs_goat,Production_Trajectory,Efficiency_Trajectory,Recognition_Trajectory,Closest_GOAT,GOAT_Similarity,Future_GOAT_Score
214,1,Luka Dončić,25,3.25,0.83,108.68,-7.41,93.21,41.96,94.36,LeBron James,62.13,76.02
158,2,Shai Gilgeous-Alexander,25,2.00,-0.42,111.93,-4.16,43.20,52.79,43.84,Larry Bird,53.08,47.24
104,3,Jayson Tatum,26,1.93,-0.44,106.34,-8.70,42.23,37.67,58.22,Larry Bird,51.13,46.42
15,4,Jalen Duren,20,1.21,-0.87,115.01,3.08,25.13,76.94,0.00,Magic Johnson,70.70,38.64
148,5,Tyrese Haliburton,24,1.94,-0.31,106.51,-6.84,47.46,43.88,5.00,Michael Jordan,56.85,37.36
206,6,Devin Booker,27,1.81,-0.55,107.60,-6.43,37.90,45.24,24.32,Larry Bird,34.36,35.81
33,7,Zion Williamson,23,1.43,-0.71,107.46,-2.80,31.42,57.33,0.00,Larry Bird,63.67,34.88
21,8,Evan Mobley,23,1.16,-0.98,110.16,-0.10,20.99,66.32,0.00,Kareem Abdul-Jabbar,55.08,32.19
113,9,Anthony Edwards,22,1.58,-0.56,101.29,-8.49,37.77,38.37,5.36,LeBron James,48.19,31.38
139,10,Tyrese Maxey,23,1.52,-0.62,100.83,-9.43,35.26,35.22,0.00,Larry Bird,65.42,30.96
52,11,Dereck Lively II,20,0.12,-1.97,128.20,16.26,0.00,100.00,0.00,Magic Johnson,35.95,30.39
56,12,Victor Wembanyama,20,1.76,-0.32,99.42,-12.51,47.23,24.97,0.00,LeBron James,49.10,30.14
187,13,Scottie Barnes,22,1.71,-0.42,99.61,-10.17,43.18,32.78,0.00,LeBron James,45.42,30.12
3,14,Chet Holmgren,22,0.91,-1.22,111.22,1.44,11.24,71.47,0.00,Michael Jordan,54.52,29.98
193,15,Isaiah Jackson,22,-0.43,-2.56,121.32,11.54,0.00,100.00,0.00,Michael Jordan,31.43,29.71
211,16,Trae Young,25,2.11,-0.31,103.00,-13.10,47.72,23.01,5.00,Larry Bird,37.89,29.39
84,17,Daniel Gafford,25,0.41,-2.01,128.64,12.54,0.00,100.00,0.00,Magic Johnson,28.41,29.26
155,18,Onyeka Okongwu,23,0.23,-1.90,118.69,8.43,0.00,94.76,0.00,Kareem Abdul-Jabbar,36.67,29.19
106,19,Nick Richards,26,0.27,-2.10,126.20,11.16,0.00,100.00,0.00,Magic Johnson,24.60,28.69
22,20,Jaxson Hayes,24,-0.73,-2.98,126.35,13.01,0.00,100.00,0.00,Magic Johnson,24.50,28.68

In [472]:
Similarity = 100 / (1 + distance)

In [473]:
future_goat["GOAT_Level"] = (
    future_goat[
        [
            "Production_Trajectory",
            "Efficiency_Trajectory",
            "Recognition_Trajectory"
        ]
    ]
    .mean(axis=1)
)

In [474]:
future_goat["Adjusted_GOAT_Similarity"] = (
    future_goat["GOAT_Similarity"]
    *
    (future_goat["GOAT_Level"] / 100)
)

In [475]:
display(
    future_goat[
        [
            "Name",
            "AGE",
            "GOAT_Level",
            "Closest_GOAT",
            "GOAT_Similarity",
            "Adjusted_GOAT_Similarity"
        ]
    ]
    .sort_values(
        "Adjusted_GOAT_Similarity",
        ascending=False
    )
    .head(20)
    .round(1)
)

,Name,AGE,GOAT_Level,Closest_GOAT,GOAT_Similarity,Adjusted_GOAT_Similarity
214,Luka Dončić,25,76.5,LeBron James,62.1,47.5
158,Shai Gilgeous-Alexander,25,46.6,Larry Bird,53.1,24.7
15,Jalen Duren,20,34.0,Magic Johnson,70.7,24.1
104,Jayson Tatum,26,46.0,Larry Bird,51.1,23.5
33,Zion Williamson,23,29.6,Larry Bird,63.7,18.8
148,Tyrese Haliburton,24,32.1,Michael Jordan,56.8,18.3
21,Evan Mobley,23,29.1,Kareem Abdul-Jabbar,55.1,16.0
139,Tyrese Maxey,23,23.5,Larry Bird,65.4,15.4
3,Chet Holmgren,22,27.6,Michael Jordan,54.5,15.0
113,Anthony Edwards,22,27.2,LeBron James,48.2,13.1
76,Jalen Williams,23,24.7,Larry Bird,51.4,12.7
206,Devin Booker,27,35.8,Larry Bird,34.4,12.3
52,Dereck Lively II,20,33.3,Magic Johnson,35.9,12.0
56,Victor Wembanyama,20,24.1,LeBron James,49.1,11.8
185,Alperen Sengun,21,23.9,Magic Johnson,49.0,11.7
78,Walker Kessler,22,29.8,Michael Jordan,39.0,11.6
155,Onyeka Okongwu,23,31.6,Kareem Abdul-Jabbar,36.7,11.6
110,Deni Avdija,23,20.3,Larry Bird,56.7,11.5
187,Scottie Barnes,22,25.3,LeBron James,45.4,11.5
193,Isaiah Jackson,22,33.3,Michael Jordan,31.4,10.5

In [476]:
future_goat["Future_GOAT_Score_V2"] = (
      future_goat["Production_Trajectory"] * 0.35
    + future_goat["Efficiency_Trajectory"] * 0.25
    + future_goat["Recognition_Trajectory"] * 0.25
    + future_goat["Adjusted_GOAT_Similarity"] * 0.15
)

In [477]:
future_goat["Future_GOAT_Rank_V2"] = (
    future_goat["Future_GOAT_Score_V2"]
    .rank(
        ascending=False,
        method="min"
    )
    .astype("Int64")
)

In [478]:
display(
    future_goat[
        [
            "Future_GOAT_Rank_V2",
            "Name",
            "AGE",
            "Production_Trajectory",
            "Efficiency_Trajectory",
            "Recognition_Trajectory",
            "Closest_GOAT",
            "GOAT_Similarity",
            "Adjusted_GOAT_Similarity",
            "Future_GOAT_Score_V2"
        ]
    ]
    .sort_values("Future_GOAT_Rank_V2")
    .head(20)
    .round(1)
)

,Future_GOAT_Rank_V2,Name,AGE,Production_Trajectory,Efficiency_Trajectory,Recognition_Trajectory,Closest_GOAT,GOAT_Similarity,Adjusted_GOAT_Similarity,Future_GOAT_Score_V2
214,1,Luka Dončić,25,93.2,42.0,94.4,LeBron James,62.1,47.5,73.8
158,2,Shai Gilgeous-Alexander,25,43.2,52.8,43.8,Larry Bird,53.1,24.7,43.0
104,3,Jayson Tatum,26,42.2,37.7,58.2,Larry Bird,51.1,23.5,42.3
206,4,Devin Booker,27,37.9,45.2,24.3,Larry Bird,34.4,12.3,32.5
15,5,Jalen Duren,20,25.1,76.9,0.0,Magic Johnson,70.7,24.1,31.6
148,6,Tyrese Haliburton,24,47.5,43.9,5.0,Michael Jordan,56.8,18.3,31.6
33,7,Zion Williamson,23,31.4,57.3,0.0,Larry Bird,63.7,18.8,28.2
52,8,Dereck Lively II,20,0.0,100.0,0.0,Magic Johnson,35.9,12.0,26.8
193,9,Isaiah Jackson,22,0.0,100.0,0.0,Michael Jordan,31.4,10.5,26.6
84,10,Daniel Gafford,25,0.0,100.0,0.0,Magic Johnson,28.4,9.5,26.4
21,11,Evan Mobley,23,21.0,66.3,0.0,Kareem Abdul-Jabbar,55.1,16.0,26.3
106,12,Nick Richards,26,0.0,100.0,0.0,Magic Johnson,24.6,8.2,26.2
22,13,Jaxson Hayes,24,0.0,100.0,0.0,Magic Johnson,24.5,8.2,26.2
113,14,Anthony Edwards,22,37.8,38.4,5.4,LeBron James,48.2,13.1,26.1
39,15,Bol Bol,24,0.0,99.4,0.0,Michael Jordan,25.3,8.4,26.1
155,16,Onyeka Okongwu,23,0.0,94.8,0.0,Kareem Abdul-Jabbar,36.7,11.6,25.4
168,17,Jarrett Allen,26,16.3,72.8,0.0,Magic Johnson,28.7,8.5,25.2
211,18,Trae Young,25,47.7,23.0,5.0,Larry Bird,37.9,9.6,25.1
94,19,Trayce Jackson-Davis,24,0.0,95.0,0.0,Michael Jordan,28.3,9.0,25.1
187,20,Scottie Barnes,22,43.2,32.8,0.0,LeBron James,45.4,11.5,25.0

In [479]:
goat_recognition_benchmark = (
    goat_trajectory[
        goat_trajectory["AGE"].between(20, 27)
    ]
    .groupby("AGE")
    .agg(
        goat_avg_recognition=(
            "Recognition_Trajectory", "mean"
        ),
        goat_max_recognition=(
            "Recognition_Trajectory", "max"
        )
    )
    .reset_index()
)

display(
    goat_recognition_benchmark.round(1)
)

   AGE  goat_avg_recognition  goat_max_recognition
0   20                   3.3                   6.6
1   21                  16.6                  32.6
2   22                  18.8                  40.5
3   23                  30.8                  62.4
4   24                  61.7                 100.0
5   25                  88.5                 100.0
6   26                  98.1                 100.0
7   27                 100.0                 100.0

In [480]:
future_goat = future_goat.merge(
    goat_recognition_benchmark,
    on="AGE",
    how="left"
)

In [481]:
future_goat["recognition_gap_vs_goat"] = (
    future_goat["Recognition_Trajectory"]
    - future_goat["goat_avg_recognition"]
)

In [482]:
future_goat["Recognition_Age_Adjusted"] = gap_score(
    future_goat["recognition_gap_vs_goat"],
    low=-60,
    high=40
)

In [483]:
display(
    future_goat[
        [
            "Name",
            "AGE",
            "Recognition_Trajectory",
            "goat_avg_recognition",
            "recognition_gap_vs_goat",
            "Recognition_Age_Adjusted"
        ]
    ]
    .sort_values(
        "Recognition_Age_Adjusted",
        ascending=False
    )
    .head(25)
    .round(1)
)

,Name,AGE,Recognition_Trajectory,goat_avg_recognition,recognition_gap_vs_goat,Recognition_Age_Adjusted
214,Luka Dončić,25,94.4,88.5,5.9,65.9
15,Jalen Duren,20,0.0,3.3,-3.3,56.7
45,Anthony Black,20,0.0,3.3,-3.3,56.7
49,Cason Wallace,20,0.0,3.3,-3.3,56.7
54,Taylor Hendricks,20,0.0,3.3,-3.3,56.7
56,Victor Wembanyama,20,0.0,3.3,-3.3,56.7
52,Dereck Lively II,20,0.0,3.3,-3.3,56.7
50,Keyonte George,20,0.0,3.3,-3.3,56.7
46,Gradey Dick,20,0.0,3.3,-3.3,56.7
66,Julian Phillips,20,0.0,3.3,-3.3,56.7
62,Nick Smith Jr.,20,0.0,3.3,-3.3,56.7
36,Scoot Henderson,20,0.0,3.3,-3.3,56.7
113,Anthony Edwards,22,5.4,18.8,-13.4,46.6
40,Dyson Daniels,21,0.0,16.6,-16.6,43.4
37,Jaden Hardy,21,0.0,16.6,-16.6,43.4
53,Amen Thompson,21,0.0,16.6,-16.6,43.4
55,Brandon Miller,21,0.0,16.6,-16.6,43.4
6,Paolo Banchero,21,0.0,16.6,-16.6,43.4
9,Max Christie,21,0.0,16.6,-16.6,43.4
5,Jabari Smith Jr.,21,0.0,16.6,-16.6,43.4
16,Blake Wesley,21,0.0,16.6,-16.6,43.4
12,Nikola Jović,21,0.0,16.6,-16.6,43.4
44,Ausar Thompson,21,0.0,16.6,-16.6,43.4
42,Bryce McGowens,21,0.0,16.6,-16.6,43.4
68,Olivier-Maxence Prosper,21,0.0,16.6,-16.6,43.4

In [484]:
future_goat["Production_Volume_Factor"] = (
    future_goat["Production_Trajectory"] / 100
).clip(0, 1)

In [485]:
future_goat["Efficiency_Adjusted"] = (
    future_goat["Efficiency_Trajectory"]
    *
    (
        0.40
        + 0.60 * future_goat["Production_Volume_Factor"]
    )
)

In [486]:
display(
    future_goat[
        [
            "Name",
            "AGE",
            "Production_Trajectory",
            "Efficiency_Trajectory",
            "Efficiency_Adjusted"
        ]
    ]
    .sort_values(
        "Efficiency_Adjusted",
        ascending=False
    )
    .head(25)
    .round(1)
)

,Name,AGE,Production_Trajectory,Efficiency_Trajectory,Efficiency_Adjusted
15,Jalen Duren,20,25.1,76.9,42.4
214,Luka Dončić,25,93.2,42.0,40.2
22,Jaxson Hayes,24,0.0,100.0,40.0
84,Daniel Gafford,25,0.0,100.0,40.0
193,Isaiah Jackson,22,0.0,100.0,40.0
106,Nick Richards,26,0.0,100.0,40.0
52,Dereck Lively II,20,0.0,100.0,40.0
39,Bol Bol,24,0.0,99.4,39.8
94,Trayce Jackson-Davis,24,0.0,95.0,38.0
155,Onyeka Okongwu,23,0.0,94.8,37.9
181,Jericho Sims,25,0.0,91.4,36.6
168,Jarrett Allen,26,16.3,72.8,36.2
78,Walker Kessler,22,0.0,89.5,35.8
133,Jalen Smith,24,0.0,88.9,35.6
21,Evan Mobley,23,21.0,66.3,34.9
158,Shai Gilgeous-Alexander,25,43.2,52.8,34.8
33,Zion Williamson,23,31.4,57.3,33.7
3,Chet Holmgren,22,11.2,71.5,33.4
194,Moritz Wagner,27,0.0,83.4,33.4
119,Obi Toppin,26,0.0,80.2,32.1
98,Ivica Zubac,27,0.0,80.1,32.0
201,Garrison Mathews,27,0.0,76.6,30.7
163,Isaiah Hartenstein,26,0.0,76.6,30.6
148,Tyrese Haliburton,24,47.5,43.9,30.0
76,Jalen Williams,23,10.3,63.8,29.4

In [487]:
future_goat["Future_GOAT_Score_V3"] = (
      future_goat["Production_Trajectory"] * 0.35
    + future_goat["Efficiency_Adjusted"] * 0.25
    + future_goat["Recognition_Age_Adjusted"] * 0.25
    + future_goat["Adjusted_GOAT_Similarity"] * 0.15
)

In [488]:
future_goat["Future_GOAT_Rank_V3"] = (
    future_goat["Future_GOAT_Score_V3"]
    .rank(
        ascending=False,
        method="min"
    )
    .astype("Int64")
)

In [489]:
future_v3 = (
    future_goat[
        [
            "Future_GOAT_Rank_V3",
            "Name",
            "AGE",
            "TEAM_ABBREVIATION",
            "Production_Trajectory",
            "Efficiency_Adjusted",
            "Recognition_Age_Adjusted",
            "Closest_GOAT",
            "GOAT_Similarity",
            "Adjusted_GOAT_Similarity",
            "Future_GOAT_Score_V3"
        ]
    ]
    .sort_values("Future_GOAT_Rank_V3")
)

display(
    future_v3
    .head(25)
    .round(1)
)

,Future_GOAT_Rank_V3,Name,AGE,TEAM_ABBREVIATION,Production_Trajectory,Efficiency_Adjusted,Recognition_Age_Adjusted,Closest_GOAT,GOAT_Similarity,Adjusted_GOAT_Similarity,Future_GOAT_Score_V3
214,1,Luka Dončić,25,DAL,93.2,40.2,65.9,LeBron James,62.1,47.5,66.3
15,2,Jalen Duren,20,DET,25.1,42.4,56.7,Magic Johnson,70.7,24.1,37.2
56,3,Victor Wembanyama,20,SAS,47.2,17.1,56.7,LeBron James,49.1,11.8,36.7
113,4,Anthony Edwards,22,MIN,37.8,24.0,46.6,LeBron James,48.2,13.1,32.8
187,5,Scottie Barnes,22,TOR,43.2,21.6,41.2,LeBron James,45.4,11.5,32.5
158,6,Shai Gilgeous-Alexander,25,OKC,43.2,34.8,15.4,Larry Bird,53.1,24.7,31.4
185,7,Alperen Sengun,21,HOU,31.7,23.6,43.4,Magic Johnson,49.0,11.7,29.6
33,8,Zion Williamson,23,NOP,31.4,33.7,29.2,Larry Bird,63.7,18.8,29.6
104,9,Jayson Tatum,26,BOS,42.2,24.6,20.1,Larry Bird,51.1,23.5,29.5
19,10,Cade Cunningham,22,DET,39.1,13.3,41.2,LeBron James,41.3,8.3,28.5
148,11,Tyrese Haliburton,24,IND,47.5,30.0,3.3,Michael Jordan,56.8,18.3,27.7
139,12,Tyrese Maxey,23,PHI,35.3,21.5,29.2,Larry Bird,65.4,15.4,27.3
52,13,Dereck Lively II,20,DAL,0.0,40.0,56.7,Magic Johnson,35.9,12.0,26.0
21,14,Evan Mobley,23,CLE,21.0,34.9,29.2,Kareem Abdul-Jabbar,55.1,16.0,25.8
178,15,Jalen Johnson,22,ATL,21.4,23.1,41.2,Michael Jordan,47.8,10.4,25.1
3,16,Chet Holmgren,22,OKC,11.2,33.4,41.2,Michael Jordan,54.5,15.0,24.8
6,17,Paolo Banchero,21,ORL,25.6,9.3,43.4,Magic Johnson,36.6,5.2,22.9
206,18,Devin Booker,27,PHX,37.9,28.4,0.0,Larry Bird,34.4,12.3,22.2
211,19,Trae Young,25,ATL,47.7,15.8,0.0,Larry Bird,37.9,9.6,22.1
193,20,Isaiah Jackson,22,IND,0.0,40.0,41.2,Michael Jordan,31.4,10.5,21.9
78,21,Walker Kessler,22,UTA,0.0,35.8,41.2,Michael Jordan,39.0,11.6,21.0
217,22,Franz Wagner,22,ORL,13.7,18.3,41.2,Michael Jordan,43.1,7.4,20.8
49,23,Cason Wallace,20,OKC,0.0,21.1,56.7,Magic Johnson,32.6,5.7,20.3
76,24,Jalen Williams,23,OKC,10.3,29.4,29.2,Larry Bird,51.4,12.7,20.2
137,25,Jalen Brunson,27,NYK,35.9,21.1,0.0,Larry Bird,30.4,7.9,19.0

In [490]:
future_goat_export = (
    future_goat[
        [
            "Future_GOAT_Rank_V2",
            "Name",
            "AGE",
            "TEAM_ABBREVIATION",

            "PRODUCTION_Z",
            "TS_PLUS",

            "Production_Trajectory",
            "Efficiency_Trajectory",
            "Recognition_Trajectory",

            "Closest_GOAT",
            "GOAT_Similarity",
            "Adjusted_GOAT_Similarity",

            "Future_GOAT_Score_V2"
        ]
    ]
    .rename(
        columns={
            "Future_GOAT_Rank_V2": "future_goat_rank",
            "Name": "player",
            "AGE": "age",
            "TEAM_ABBREVIATION": "team",
            "PRODUCTION_Z": "production_z",
            "TS_PLUS": "ts_plus",
            "Production_Trajectory": "production_score",
            "Efficiency_Trajectory": "efficiency_score",
            "Recognition_Trajectory": "recognition_score",
            "Closest_GOAT": "closest_goat",
            "GOAT_Similarity": "goat_similarity",
            "Adjusted_GOAT_Similarity": "adjusted_goat_similarity",
            "Future_GOAT_Score_V2": "future_goat_score"
        }
    )
    .sort_values("future_goat_rank")
    .reset_index(drop=True)
)

display(
    future_goat_export
    .head(20)
    .round(2)
)

,future_goat_rank,player,age,team,production_z,ts_plus,production_score,efficiency_score,recognition_score,closest_goat,goat_similarity,adjusted_goat_similarity,future_goat_score
0,1,Luka Dončić,25,DAL,3.25,108.68,93.21,41.96,94.36,LeBron James,62.13,47.54,73.83
1,2,Shai Gilgeous-Alexander,25,OKC,2.00,111.93,43.20,52.79,43.84,Larry Bird,53.08,24.74,42.99
2,3,Jayson Tatum,26,BOS,1.93,106.34,42.23,37.67,58.22,Larry Bird,51.13,23.54,42.29
3,4,Devin Booker,27,PHX,1.81,107.60,37.90,45.24,24.32,Larry Bird,34.36,12.31,32.50
4,5,Jalen Duren,20,DET,1.21,115.01,25.13,76.94,0.00,Magic Johnson,70.70,24.05,31.64
5,6,Tyrese Haliburton,24,IND,1.94,106.51,47.46,43.88,5.00,Michael Jordan,56.85,18.26,31.57
6,7,Zion Williamson,23,NOP,1.43,107.46,31.42,57.33,0.00,Larry Bird,63.67,18.84,28.16
7,8,Dereck Lively II,20,DAL,0.12,128.20,0.00,100.00,0.00,Magic Johnson,35.95,11.98,26.80
8,9,Isaiah Jackson,22,IND,-0.43,121.32,0.00,100.00,0.00,Michael Jordan,31.43,10.48,26.57
9,10,Daniel Gafford,25,TOT,0.41,128.64,0.00,100.00,0.00,Magic Johnson,28.41,9.47,26.42
10,11,Evan Mobley,23,CLE,1.16,110.16,20.99,66.32,0.00,Kareem Abdul-Jabbar,55.08,16.03,26.33
11,12,Nick Richards,26,CHA,0.27,126.20,0.00,100.00,0.00,Magic Johnson,24.60,8.20,26.23
12,13,Jaxson Hayes,24,LAL,-0.73,126.35,0.00,100.00,0.00,Magic Johnson,24.50,8.17,26.23
13,14,Anthony Edwards,22,MIN,1.58,101.29,37.77,38.37,5.36,LeBron James,48.19,13.09,26.12
14,15,Bol Bol,24,PHX,-0.67,123.17,0.00,99.42,0.00,Michael Jordan,25.30,8.38,26.11
15,16,Onyeka Okongwu,23,ATL,0.23,118.69,0.00,94.76,0.00,Kareem Abdul-Jabbar,36.67,11.58,25.43
16,17,Jarrett Allen,26,CLE,1.29,116.88,16.29,72.80,0.00,Magic Johnson,28.72,8.53,25.18
17,18,Trae Young,25,ATL,2.11,103.00,47.72,23.01,5.00,Larry Bird,37.89,9.56,25.14
18,19,Trayce Jackson-Davis,24,GSW,-0.15,121.85,0.00,95.01,0.00,Michael Jordan,28.31,8.96,25.10
19,20,Scottie Barnes,22,TOR,1.71,99.61,43.18,32.78,0.00,LeBron James,45.42,11.50,25.03

In [491]:
future_goat_export["data_cutoff"] = "2023-24"
future_goat_export["model_version"] = "V2"

In [492]:
def trajectory_label(score):

    if score >= 65:
        return "Elite historical trajectory"

    elif score >= 50:
        return "Strong historical trajectory"

    elif score >= 35:
        return "Emerging trajectory"

    else:
        return "Developing trajectory"


future_goat_export["trajectory_tier"] = (
    future_goat_export["future_goat_score"]
    .apply(trajectory_label)
)

In [493]:
display(
    future_goat_export[
        [
            "future_goat_rank",
            "player",
            "age",
            "team",
            "future_goat_score",
            "trajectory_tier",
            "closest_goat",
            "goat_similarity",
            "data_cutoff",
            "model_version"
        ]
    ]
    .head(20)
    .round(1)
)

,future_goat_rank,player,age,team,future_goat_score,trajectory_tier,closest_goat,goat_similarity,data_cutoff,model_version
0,1,Luka Dončić,25,DAL,73.8,Elite historical trajectory,LeBron James,62.1,2023-24,V2
1,2,Shai Gilgeous-Alexander,25,OKC,43.0,Emerging trajectory,Larry Bird,53.1,2023-24,V2
2,3,Jayson Tatum,26,BOS,42.3,Emerging trajectory,Larry Bird,51.1,2023-24,V2
3,4,Devin Booker,27,PHX,32.5,Developing trajectory,Larry Bird,34.4,2023-24,V2
4,5,Jalen Duren,20,DET,31.6,Developing trajectory,Magic Johnson,70.7,2023-24,V2
5,6,Tyrese Haliburton,24,IND,31.6,Developing trajectory,Michael Jordan,56.8,2023-24,V2
6,7,Zion Williamson,23,NOP,28.2,Developing trajectory,Larry Bird,63.7,2023-24,V2
7,8,Dereck Lively II,20,DAL,26.8,Developing trajectory,Magic Johnson,35.9,2023-24,V2
8,9,Isaiah Jackson,22,IND,26.6,Developing trajectory,Michael Jordan,31.4,2023-24,V2
9,10,Daniel Gafford,25,TOT,26.4,Developing trajectory,Magic Johnson,28.4,2023-24,V2
10,11,Evan Mobley,23,CLE,26.3,Developing trajectory,Kareem Abdul-Jabbar,55.1,2023-24,V2
11,12,Nick Richards,26,CHA,26.2,Developing trajectory,Magic Johnson,24.6,2023-24,V2
12,13,Jaxson Hayes,24,LAL,26.2,Developing trajectory,Magic Johnson,24.5,2023-24,V2
13,14,Anthony Edwards,22,MIN,26.1,Developing trajectory,LeBron James,48.2,2023-24,V2
14,15,Bol Bol,24,PHX,26.1,Developing trajectory,Michael Jordan,25.3,2023-24,V2
15,16,Onyeka Okongwu,23,ATL,25.4,Developing trajectory,Kareem Abdul-Jabbar,36.7,2023-24,V2
16,17,Jarrett Allen,26,CLE,25.2,Developing trajectory,Magic Johnson,28.7,2023-24,V2
17,18,Trae Young,25,ATL,25.1,Developing trajectory,Larry Bird,37.9,2023-24,V2
18,19,Trayce Jackson-Davis,24,GSW,25.1,Developing trajectory,Michael Jordan,28.3,2023-24,V2
19,20,Scottie Barnes,22,TOR,25.0,Developing trajectory,LeBron James,45.4,2023-24,V2

In [496]:
print("Lignes :", len(future_goat_export))
print("Joueurs uniques :", future_goat_export["player"].nunique())

print(
    "Doublons joueurs :",
    future_goat_export["player"].duplicated().sum()
)

print(
    "Scores manquants :",
    future_goat_export["future_goat_score"].isna().sum()
)

print(
    "Rangs manquants :",
    future_goat_export["future_goat_rank"].isna().sum()
)

print(
    "Score min/max :",
    future_goat_export["future_goat_score"].min(),
    "→",
    future_goat_export["future_goat_score"].max()
)

Lignes : 219
Joueurs uniques : 219
Doublons joueurs : 0
Scores manquants : 0
Rangs manquants : 0
Score min/max : 0.0 → 73.83298981615847

In [498]:
import os
import glob

# Rechercher un des fichiers déjà exportés
matches = glob.glob(
    "/content/**/08_methodology.csv",
    recursive=True
)

print("Fichiers trouvés :", matches)

Fichiers trouvés : ['/content/08_methodology.csv']

In [499]:
import os

EXPORT_DIR = "/content"

print("EXPORT_DIR =", EXPORT_DIR)

EXPORT_DIR = /content

In [500]:
for file in sorted(os.listdir(EXPORT_DIR)):
    if file.endswith(".csv"):
        print(file)

01_team_season.csv
02_winning_factors.csv
03_goat_master.csv
04_goat_dimensions.csv
05_goat_scenarios.csv
06_goat_peak.csv
07_goat_player_seasons.csv
08_methodology.csv
nba_team_performance_animation_data.csv

In [501]:
output_path = os.path.join(
    EXPORT_DIR,
    "09_future_goat.csv"
)

future_goat_export.to_csv(
    output_path,
    index=False
)

print(
    "09_future_goat.csv →",
    os.path.exists(output_path)
)

print(
    "Taille :",
    round(os.path.getsize(output_path) / 1024, 2),
    "KB"
)

print(
    "Chemin :",
    output_path
)

09_future_goat.csv → True
Taille : 40.08 KB
Chemin : /content/09_future_goat.csv

In [502]:
check_09 = pd.read_csv(
    "/content/09_future_goat.csv"
)

print("Dimensions :", check_09.shape)
print("Doublons joueurs :", check_09["player"].duplicated().sum())
print("Scores manquants :", check_09["future_goat_score"].isna().sum())

display(
    check_09.head(10).round(2)
)

Dimensions : (219, 16)
Doublons joueurs : 0
Scores manquants : 0

,future_goat_rank,player,age,team,production_z,ts_plus,production_score,efficiency_score,recognition_score,closest_goat,goat_similarity,adjusted_goat_similarity,future_goat_score,data_cutoff,model_version,trajectory_tier
0,1,Luka Dončić,25,DAL,3.25,108.68,93.21,41.96,94.36,LeBron James,62.13,47.54,73.83,2023-24,V2,Elite historical trajectory
1,2,Shai Gilgeous-Alexander,25,OKC,2.00,111.93,43.20,52.79,43.84,Larry Bird,53.08,24.74,42.99,2023-24,V2,Emerging trajectory
2,3,Jayson Tatum,26,BOS,1.93,106.34,42.23,37.67,58.22,Larry Bird,51.13,23.54,42.29,2023-24,V2,Emerging trajectory
3,4,Devin Booker,27,PHX,1.81,107.60,37.90,45.24,24.32,Larry Bird,34.36,12.31,32.50,2023-24,V2,Developing trajectory
4,5,Jalen Duren,20,DET,1.21,115.01,25.13,76.94,0.00,Magic Johnson,70.70,24.05,31.64,2023-24,V2,Developing trajectory
5,6,Tyrese Haliburton,24,IND,1.94,106.51,47.46,43.88,5.00,Michael Jordan,56.85,18.26,31.57,2023-24,V2,Developing trajectory
6,7,Zion Williamson,23,NOP,1.43,107.46,31.42,57.33,0.00,Larry Bird,63.67,18.84,28.16,2023-24,V2,Developing trajectory
7,8,Dereck Lively II,20,DAL,0.12,128.20,0.00,100.00,0.00,Magic Johnson,35.95,11.98,26.80,2023-24,V2,Developing trajectory
8,9,Isaiah Jackson,22,IND,-0.43,121.32,0.00,100.00,0.00,Michael Jordan,31.43,10.48,26.57,2023-24,V2,Developing trajectory
9,10,Daniel Gafford,25,TOT,0.41,128.64,0.00,100.00,0.00,Magic Johnson,28.41,9.47,26.42,2023-24,V2,Developing trajectory

In [503]:
future_similarity_export = (
    goat_similarity[
        [
            "Name",
            "AGE",
            "GOAT",
            "Similarity",
            "Distance"
        ]
    ]
    .rename(
        columns={
            "Name": "player",
            "AGE": "age",
            "GOAT": "goat",
            "Similarity": "similarity",
            "Distance": "distance"
        }
    )
    .sort_values(
        ["player", "similarity"],
        ascending=[True, False]
    )
    .reset_index(drop=True)
)

future_similarity_export["data_cutoff"] = "2023-24"
future_similarity_export["model_version"] = "V2"

In [504]:
print("Dimensions :", future_similarity_export.shape)

print(
    "Doublons player/goat :",
    future_similarity_export
    .duplicated(["player", "goat"])
    .sum()
)

print(
    "Similarités manquantes :",
    future_similarity_export["similarity"]
    .isna()
    .sum()
)

display(
    future_similarity_export[
        future_similarity_export["player"] == "Luka Dončić"
    ].round(2)
)

Dimensions : (899, 7)
Doublons player/goat : 0
Similarités manquantes : 0

,player,age,goat,similarity,distance,data_cutoff,model_version
571,Luka Dončić,25,LeBron James,62.13,0.61,2023-24,V2
572,Luka Dončić,25,Michael Jordan,47.65,1.10,2023-24,V2
573,Luka Dončić,25,Larry Bird,47.09,1.12,2023-24,V2
574,Luka Dončić,25,Magic Johnson,38.90,1.57,2023-24,V2
575,Luka Dončić,25,Kareem Abdul-Jabbar,37.19,1.69,2023-24,V2

In [505]:
similarity_path = os.path.join(
    EXPORT_DIR,
    "10_future_goat_similarity.csv"
)

future_similarity_export.to_csv(
    similarity_path,
    index=False
)

print(
    "10_future_goat_similarity.csv →",
    os.path.exists(similarity_path)
)

print(
    "Taille :",
    round(
        os.path.getsize(similarity_path) / 1024,
        2
    ),
    "KB"
)

10_future_goat_similarity.csv → True
Taille : 70.06 KB

In [506]:
import pandas as pd
import plotly.express as px

future_goat_anim = pd.read_csv(
    "/content/09_future_goat.csv"
)

top10 = (
    future_goat_anim
    .sort_values(
        "future_goat_score",
        ascending=False
    )
    .head(10)
    .copy()
)

display(
    top10[
        [
            "future_goat_rank",
            "player",
            "age",
            "team",
            "future_goat_score",
            "closest_goat",
            "goat_similarity"
        ]
    ]
)

,future_goat_rank,player,age,team,future_goat_score,closest_goat,goat_similarity
0,1,Luka Dončić,25,DAL,73.832990,LeBron James,62.131945
1,2,Shai Gilgeous-Alexander,25,OKC,42.990314,Larry Bird,53.081958
2,3,Jayson Tatum,26,BOS,42.285746,Larry Bird,51.134335
3,4,Devin Booker,27,PHX,32.501819,Larry Bird,34.356049
4,5,Jalen Duren,20,DET,31.637720,Magic Johnson,70.703820
5,6,Tyrese Haliburton,24,IND,31.568237,Michael Jordan,56.848816
6,7,Zion Williamson,23,NOP,28.156548,Larry Bird,63.667885
7,8,Dereck Lively II,20,DAL,26.797487,Magic Johnson,35.949738
8,9,Isaiah Jackson,22,IND,26.571295,Michael Jordan,31.425896
9,10,Daniel Gafford,25,TOT,26.420298,Magic Johnson,28.405969

In [507]:
fig = px.bar(
    top10.sort_values(
        "future_goat_score",
        ascending=True
    ),
    x="future_goat_score",
    y="player",
    orientation="h",
    text="future_goat_score",
    hover_data={
        "age": True,
        "team": True,
        "closest_goat": True,
        "goat_similarity": ":.1f",
        "future_goat_score": ":.1f"
    },
    title="Future GOAT Race — Top 10 Candidates"
)

fig.update_traces(
    texttemplate="%{text:.1f}",
    textposition="outside"
)

fig.update_layout(
    xaxis_title="Future GOAT Score",
    yaxis_title="",
    xaxis_range=[0, 100],
    height=650
)

fig.show()

In [508]:
html_path = "/content/future-goat-race.html"

fig.write_html(
    html_path,
    include_plotlyjs="cdn",
    full_html=True
)

print(
    "HTML créé :",
    html_path
)

HTML créé : /content/future-goat-race.html

In [509]:
# Candidats actuels
current_players = [
    "Luka Dončić",
    "Shai Gilgeous-Alexander",
    "Jayson Tatum",
    "Anthony Edwards",
    "Victor Wembanyama",
    "Tyrese Haliburton"
]

future_anim = future_goat[
    future_goat["Name"].isin(current_players)
][
    [
        "Name",
        "AGE",
        "Production_Trajectory",
        "Efficiency_Trajectory",
        "Recognition_Trajectory",
        "Future_GOAT_Score_V2"
    ]
].copy()

future_anim["group"] = "Current Candidate"

In [510]:
goat_anim = goat_trajectory[
    goat_trajectory["Name"].isin(GOATS)
][
    [
        "Name",
        "AGE",
        "PRODUCTION_Z",
        "TS_PLUS",
        "Recognition_Trajectory"
    ]
].copy()

In [511]:
goat_prod_anim = goat_anim[
    ["Name", "AGE", "PRODUCTION_Z"]
].rename(
    columns={"PRODUCTION_Z": "score"}
)

goat_prod_anim["group"] = "Historical GOAT"

future_prod_anim = future_anim[
    ["Name", "AGE", "Production_Trajectory"]
].rename(
    columns={"Production_Trajectory": "score"}
)

future_prod_anim["group"] = "Current Candidate"

In [512]:
future_prod_anim = future_goat[
    future_goat["Name"].isin(current_players)
][
    ["Name", "AGE", "PRODUCTION_Z"]
].rename(
    columns={"PRODUCTION_Z": "score"}
)

future_prod_anim["group"] = "Current Candidate"

In [513]:
animation_df = pd.concat(
    [
        goat_prod_anim,
        future_prod_anim
    ],
    ignore_index=True
)

animation_df = animation_df[
    animation_df["AGE"].between(20, 30)
].copy()

In [514]:
fig_age = px.scatter(
    animation_df,
    x="AGE",
    y="score",
    color="Name",
    symbol="group",
    hover_name="Name",
    hover_data={
        "AGE": True,
        "score": ":.2f",
        "group": True
    },
    title="GOAT Trajectory by Age — Production vs Era",
    labels={
        "AGE": "Age",
        "score": "Production Z"
    }
)

fig_age.update_traces(
    marker=dict(size=14)
)

fig_age.update_layout(
    height=650,
    xaxis=dict(
        dtick=1,
        range=[19, 31]
    )
)

fig_age.show()

In [515]:
frames = []

ages = sorted(
    animation_df["AGE"]
    .dropna()
    .unique()
)

for age in ages:

    temp = animation_df[
        animation_df["AGE"] <= age
    ].copy()

    temp["animation_age"] = age

    frames.append(temp)

animation_history = pd.concat(
    frames,
    ignore_index=True
)

In [516]:
fig_age_anim = px.scatter(
    animation_history,
    x="AGE",
    y="score",
    color="Name",
    symbol="group",
    animation_frame="animation_age",
    hover_name="Name",
    title="Future GOAT Race — Career Trajectory by Age",
    labels={
        "AGE": "Age",
        "score": "Era-adjusted Production Z",
        "animation_age": "Age reached"
    },
    range_x=[19, 31],
    range_y=[
        animation_history["score"].min() - 0.5,
        animation_history["score"].max() + 0.5
    ]
)

fig_age_anim.update_traces(
    marker=dict(size=14)
)

fig_age_anim.update_layout(
    height=700
)

fig_age_anim.show()

In [517]:
print(
    animation_df[
        animation_df["group"] == "Current Candidate"
    ][["Name", "AGE", "score"]]
    .sort_values("AGE")
)

                       Name  AGE     score
79        Victor Wembanyama   20  1.764780
81          Anthony Edwards   22  1.576303
82        Tyrese Haliburton   24  1.943185
83  Shai Gilgeous-Alexander   25  1.997385
84              Luka Dončić   25  3.247527
80             Jayson Tatum   26  1.933807

In [518]:
frames = []

ages = range(20, 31)

for current_age in ages:

    temp = animation_df[
        animation_df["AGE"] <= current_age
    ].copy()

    temp["animation_age"] = current_age

    frames.append(temp)

animation_history = pd.concat(
    frames,
    ignore_index=True
)

print("Lignes :", len(animation_history))
print("Joueurs :", animation_history["Name"].nunique())

Lignes : 285
Joueurs : 11

In [519]:
check_age30 = (
    animation_history[
        animation_history["animation_age"] == 30
    ]
    [["Name", "group"]]
    .drop_duplicates()
)

display(check_age30)

                        Name              group
233           Michael Jordan    Historical GOAT
241               Larry Bird    Historical GOAT
249             LeBron James    Historical GOAT
260      Kareem Abdul-Jabbar    Historical GOAT
268            Magic Johnson    Historical GOAT
279        Victor Wembanyama  Current Candidate
280             Jayson Tatum  Current Candidate
281          Anthony Edwards  Current Candidate
282        Tyrese Haliburton  Current Candidate
283  Shai Gilgeous-Alexander  Current Candidate
284              Luka Dončić  Current Candidate

In [520]:
race_frames = []

for current_age in range(20, 31):

    temp = animation_df[
        animation_df["AGE"] <= current_age
    ].copy()

    # Dernière observation disponible de chaque joueur
    temp = (
        temp
        .sort_values("AGE")
        .groupby("Name", as_index=False)
        .tail(1)
    )

    temp["animation_age"] = current_age

    race_frames.append(temp)

race_df = pd.concat(
    race_frames,
    ignore_index=True
)

In [521]:
display(
    race_df[
        race_df["animation_age"] == 30
    ][
        ["Name", "AGE", "score", "group"]
    ]
    .sort_values(
        "score",
        ascending=False
    )
)

                       Name  AGE     score              group
84              Luka Dončić   25  3.247527  Current Candidate
87             LeBron James   30  2.398771    Historical GOAT
88               Larry Bird   30  2.389386    Historical GOAT
89            Magic Johnson   30  2.293977    Historical GOAT
90      Kareem Abdul-Jabbar   30  2.293533    Historical GOAT
86           Michael Jordan   30  2.270639    Historical GOAT
83  Shai Gilgeous-Alexander   25  1.997385  Current Candidate
82        Tyrese Haliburton   24  1.943185  Current Candidate
85             Jayson Tatum   26  1.933807  Current Candidate
80        Victor Wembanyama   20  1.764780  Current Candidate
81          Anthony Edwards   22  1.576303  Current Candidate

In [522]:
fig_race = px.scatter(
    race_df,
    x="AGE",
    y="score",
    color="Name",
    symbol="group",
    animation_frame="animation_age",
    hover_name="Name",

    hover_data={
        "AGE": True,
        "score": ":.2f",
        "group": True,
        "animation_age": False
    },

    title="Future GOAT Race — Career Trajectory by Age",

    labels={
        "AGE": "Age",
        "score": "Era-adjusted Production Z",
        "animation_age": "Age reached"
    },

    range_x=[19, 31],

    range_y=[
        race_df["score"].min() - 0.5,
        race_df["score"].max() + 0.5
    ]
)

fig_race.update_traces(
    marker=dict(size=16)
)

fig_race.update_layout(
    height=700
)

fig_race.show()

In [523]:
candidates = [
    "Luka Dončić",
    "Shai Gilgeous-Alexander",
    "Jayson Tatum",
    "Anthony Edwards",
    "Victor Wembanyama",
    "Tyrese Haliburton"
]

print("Colonnes disponibles :")
print(df_era.columns.tolist())

print("\n--- Candidats trouvés ---")

candidate_check = (
    df_era[df_era["Name"].isin(candidates)]
    .groupby("Name")
    .agg(
        seasons=("SEASON_ID", "nunique"),
        first_age=("PLAYER_AGE", "min"),
        last_age=("PLAYER_AGE", "max"),
        first_season=("SEASON_ID", "min"),
        last_season=("SEASON_ID", "max")
    )
    .sort_values("last_age")
)

display(candidate_check)

Colonnes disponibles :
['PLAYER_ID', 'Name', 'SEASON_ID', 'TEAM_ID', 'TEAM_ABBREVIATION', 'PLAYER_AGE', 'GP', 'GS', 'MIN', 'FGM', 'FGA', 'FG_PCT', 'FG3M', 'FG3A', 'FG3_PCT', 'FTM', 'FTA', 'FT_PCT', 'OREB', 'DREB', 'REB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS', 'PPG', 'RPG', 'APG', 'SPG', 'BPG', 'MPG', 'PPG_Z', 'RPG_Z', 'APG_Z', 'PRODUCTION_Z', 'TS_PCT', 'LEAGUE_TS', 'TS_PLUS', 'TS_Z']

--- Candidats trouvés ---

                         seasons  first_age  last_age first_season last_season
Name
Victor Wembanyama              1       20.0      20.0      2023-24     2023-24
Anthony Edwards                4       19.0      22.0      2020-21     2023-24
Tyrese Haliburton              4       21.0      24.0      2020-21     2023-24
Luka Dončić                    6       20.0      25.0      2018-19     2023-24
Shai Gilgeous-Alexander        6       20.0      25.0      2018-19     2023-24
Jayson Tatum                   7       20.0      26.0      2017-18     2023-24

In [524]:
candidate_trajectory = (
    df_era[
        df_era["Name"].isin(candidates)
    ][
        [
            "PLAYER_ID",
            "Name",
            "SEASON_ID",
            "PLAYER_AGE",
            "TEAM_ABBREVIATION",
            "GP",
            "PPG",
            "RPG",
            "APG",
            "PRODUCTION_Z",
            "TS_PLUS"
        ]
    ]
    .copy()
)

candidate_trajectory = (
    candidate_trajectory
    .sort_values(
        ["Name", "PLAYER_AGE"]
    )
    .reset_index(drop=True)
)

candidate_trajectory["group"] = "Future GOAT Candidate"

display(
    candidate_trajectory[
        [
            "Name",
            "SEASON_ID",
            "PLAYER_AGE",
            "TEAM_ABBREVIATION",
            "PRODUCTION_Z",
            "TS_PLUS"
        ]
    ]
)

,Name,SEASON_ID,PLAYER_AGE,TEAM_ABBREVIATION,PRODUCTION_Z,TS_PLUS
0,Anthony Edwards,2020-21,19.0,MIN,0.763539,93.068741
1,Anthony Edwards,2021-22,20.0,MIN,1.062333,100.089562
2,Anthony Edwards,2022-23,21.0,MIN,1.403328,98.213838
3,Anthony Edwards,2023-24,22.0,MIN,1.576303,101.288916
4,Jayson Tatum,2017-18,20.0,BOS,0.345896,106.700556
5,Jayson Tatum,2018-19,21.0,BOS,0.611879,99.339614
6,Jayson Tatum,2019-20,22.0,BOS,1.319925,101.436466
7,Jayson Tatum,2020-21,23.0,BOS,1.765774,102.572488
8,Jayson Tatum,2021-22,24.0,BOS,1.929420,103.238161
9,Jayson Tatum,2022-23,25.0,BOS,2.131414,105.799857
10,Jayson Tatum,2023-24,26.0,BOS,1.933807,106.343891
11,Luka Dončić,2018-19,20.0,DAL,1.820113,99.029515
12,Luka Dončić,2019-20,21.0,DAL,2.915636,104.699344
13,Luka Dončić,2020-21,22.0,DAL,2.593363,104.485247
14,Luka Dončić,2021-22,23.0,DAL,2.857233,101.962776
15,Luka Dončić,2022-23,24.0,DAL,2.773224,106.201510
16,Luka Dončić,2023-24,25.0,DAL,3.247527,108.680541
17,Shai Gilgeous-Alexander,2018-19,20.0,LAC,0.089767,100.690315
18,Shai Gilgeous-Alexander,2019-20,21.0,OKC,0.950046,101.542957
19,Shai Gilgeous-Alexander,2020-21,22.0,OKC,1.514174,110.917131
20,Shai Gilgeous-Alexander,2021-22,23.0,OKC,1.625003,99.553825
21,Shai Gilgeous-Alexander,2022-23,24.0,OKC,1.834774,109.048534
22,Shai Gilgeous-Alexander,2023-24,25.0,OKC,1.997385,111.930658
23,Tyrese Haliburton,2020-21,21.0,SAC,0.529510,104.085488
24,Tyrese Haliburton,2021-22,22.0,TOT,1.276994,106.284968
25,Tyrese Haliburton,2022-23,23.0,IND,1.830930,108.762288
26,Tyrese Haliburton,2023-24,24.0,IND,1.943185,106.512811
27,Victor Wembanyama,2023-24,20.0,SAS,1.764780,99.423355

In [525]:
print(
    "Nombre de lignes :",
    len(candidate_trajectory)
)

print(
    "Nombre de joueurs :",
    candidate_trajectory["Name"].nunique()
)

print(
    "Doublons joueur/saison :",
    candidate_trajectory
    .duplicated(
        ["Name", "SEASON_ID"]
    )
    .sum()
)

print(
    "PRODUCTION_Z manquants :",
    candidate_trajectory["PRODUCTION_Z"]
    .isna()
    .sum()
)

Nombre de lignes : 28
Nombre de joueurs : 6
Doublons joueur/saison : 0
PRODUCTION_Z manquants : 0

In [526]:
display(
    candidate_trajectory[
        candidate_trajectory["Name"] == "Luka Dončić"
    ][
        [
            "SEASON_ID",
            "PLAYER_AGE",
            "TEAM_ABBREVIATION",
            "GP",
            "PPG",
            "RPG",
            "APG",
            "PRODUCTION_Z",
            "TS_PLUS"
        ]
    ]
    .round(2)
)

,SEASON_ID,PLAYER_AGE,TEAM_ABBREVIATION,GP,PPG,RPG,APG,PRODUCTION_Z,TS_PLUS
11,2018-19,20.0,DAL,72,21.19,7.82,5.96,1.82,99.03
12,2019-20,21.0,DAL,61,28.84,9.39,8.82,2.92,104.70
13,2020-21,22.0,DAL,66,27.73,7.98,8.59,2.59,104.49
14,2021-22,23.0,DAL,65,28.42,9.12,8.74,2.86,101.96
15,2022-23,24.0,DAL,66,32.39,8.62,8.02,2.77,106.20
16,2023-24,25.0,DAL,70,33.86,9.24,9.80,3.25,108.68

In [527]:
historical_goats = [
    "LeBron James",
    "Michael Jordan",
    "Kareem Abdul-Jabbar",
    "Magic Johnson",
    "Larry Bird"
]

goat_trajectory_anim = (
    df_era[
        df_era["Name"].isin(historical_goats)
    ][
        [
            "PLAYER_ID",
            "Name",
            "SEASON_ID",
            "PLAYER_AGE",
            "TEAM_ABBREVIATION",
            "GP",
            "PPG",
            "RPG",
            "APG",
            "PRODUCTION_Z",
            "TS_PLUS"
        ]
    ]
    .copy()
)

goat_trajectory_anim["group"] = "Historical GOAT"

goat_trajectory_anim = (
    goat_trajectory_anim
    .sort_values(["Name", "PLAYER_AGE"])
    .reset_index(drop=True)
)

display(
    goat_trajectory_anim[
        [
            "Name",
            "SEASON_ID",
            "PLAYER_AGE",
            "PRODUCTION_Z",
            "TS_PLUS"
        ]
    ].head(30)
)

                   Name SEASON_ID  PLAYER_AGE  PRODUCTION_Z     TS_PLUS
0   Kareem Abdul-Jabbar   1969-70        23.0      2.016141  111.420902
1   Kareem Abdul-Jabbar   1970-71        24.0      2.238034  126.187254
2   Kareem Abdul-Jabbar   1971-72        25.0      2.635896  124.772710
3   Kareem Abdul-Jabbar   1972-73        26.0      2.426467  120.068290
4   Kareem Abdul-Jabbar   1973-74        27.0      2.286279  114.776690
5   Kareem Abdul-Jabbar   1974-75        28.0      2.483473  112.050405
6   Kareem Abdul-Jabbar   1975-76        29.0      2.892108  114.980908
7   Kareem Abdul-Jabbar   1976-77        30.0      2.293533  121.629591
8   Kareem Abdul-Jabbar   1977-78        31.0      2.153167  116.970973
9   Kareem Abdul-Jabbar   1978-79        32.0      2.164906  118.870860
10  Kareem Abdul-Jabbar   1979-80        33.0      1.948985  123.444739
11  Kareem Abdul-Jabbar   1980-81        34.0      1.889171  119.140642
12  Kareem Abdul-Jabbar   1981-82        35.0      1.534936  115.851837
13  Kareem Abdul-Jabbar   1982-83        36.0      1.124740  120.040558
14  Kareem Abdul-Jabbar   1983-84        37.0      1.130057  115.258857
15  Kareem Abdul-Jabbar   1984-85        38.0      1.243168  118.734390
16  Kareem Abdul-Jabbar   1985-86        39.0      1.240197  114.032446
17  Kareem Abdul-Jabbar   1986-87        40.0      0.766045  114.564098
18  Kareem Abdul-Jabbar   1987-88        41.0      0.416558  108.997206
19  Kareem Abdul-Jabbar   1988-89        42.0     -0.089391   98.510270
20           Larry Bird   1979-80        23.0      1.674838  104.013564
21           Larry Bird   1980-81        24.0      1.997490  102.168019
22           Larry Bird   1981-82        25.0      2.175789  106.135875
23           Larry Bird   1982-83        26.0      2.147247  108.754657
24           Larry Bird   1983-84        27.0      2.178203  104.656812
25           Larry Bird   1984-85        28.0      2.434891  110.584740
26           Larry Bird   1985-86        29.0      2.267323  109.765262
27           Larry Bird   1986-87        30.0      2.389386  117.351277
28           Larry Bird   1987-88        31.0      2.363977  116.172043
29           Larry Bird   1989-90        33.0      2.198449  105.591307

In [528]:
goat_coverage = (
    goat_trajectory_anim
    .groupby("Name")
    .agg(
        seasons=("SEASON_ID", "nunique"),
        first_age=("PLAYER_AGE", "min"),
        last_age=("PLAYER_AGE", "max"),
        min_production=("PRODUCTION_Z", "min"),
        max_production=("PRODUCTION_Z", "max")
    )
    .round(2)
)

display(goat_coverage)

,seasons,first_age,last_age,min_production,max_production
Name,,,,,
Kareem Abdul-Jabbar,20,23.0,42.0,-0.09,2.89
Larry Bird,12,23.0,35.0,1.67,2.43
LeBron James,21,19.0,39.0,1.71,3.01
Magic Johnson,13,20.0,36.0,1.29,2.62
Michael Jordan,13,22.0,40.0,1.31,2.62

In [529]:
goat_trajectory_20_30 = goat_trajectory_anim[
    goat_trajectory_anim["PLAYER_AGE"].between(20, 30)
].copy()

candidate_trajectory_20_30 = candidate_trajectory[
    candidate_trajectory["PLAYER_AGE"].between(20, 30)
].copy()

In [530]:
career_trajectory = pd.concat(
    [
        goat_trajectory_20_30,
        candidate_trajectory_20_30
    ],
    ignore_index=True
)

career_trajectory = (
    career_trajectory
    .sort_values(
        ["PLAYER_AGE", "group", "Name"]
    )
    .reset_index(drop=True)
)

In [531]:
print(
    "Lignes :", len(career_trajectory)
)

print(
    "Joueurs :", career_trajectory["Name"].nunique()
)

print("\nRépartition :")
display(
    career_trajectory
    .groupby("group")["Name"]
    .nunique()
)

print("\nCouverture complète :")
display(
    career_trajectory
    .groupby(["group", "Name"])
    .agg(
        seasons=("SEASON_ID", "nunique"),
        first_age=("PLAYER_AGE", "min"),
        last_age=("PLAYER_AGE", "max")
    )
)

Lignes : 73
Joueurs : 11

Répartition :

group
Future GOAT Candidate    6
Historical GOAT          5
Name: Name, dtype: int64

Couverture complète :

                                               seasons  first_age  last_age
group                 Name
Future GOAT Candidate Anthony Edwards                3       20.0      22.0
                      Jayson Tatum                   7       20.0      26.0
                      Luka Dončić                    6       20.0      25.0
                      Shai Gilgeous-Alexander        6       20.0      25.0
                      Tyrese Haliburton              4       21.0      24.0
                      Victor Wembanyama              1       20.0      20.0
Historical GOAT       Kareem Abdul-Jabbar            8       23.0      30.0
                      Larry Bird                     8       23.0      30.0
                      LeBron James                  11       20.0      30.0
                      Magic Johnson                 11       20.0      30.0
                      Michael Jordan                 8       22.0      30.0

In [532]:
frames = []

for current_age in range(20, 31):

    temp = career_trajectory[
        career_trajectory["PLAYER_AGE"] <= current_age
    ].copy()

    temp["animation_age"] = current_age

    frames.append(temp)

career_animation = pd.concat(
    frames,
    ignore_index=True
)

print("Dimensions :", career_animation.shape)

print(
    "Joueurs dans la dernière frame :",
    career_animation[
        career_animation["animation_age"] == 30
    ]["Name"].nunique()
)

Dimensions : (474, 13)
Joueurs dans la dernière frame : 11

In [533]:
import plotly.express as px

fig_trajectory = px.line(
    career_animation,

    x="PLAYER_AGE",
    y="PRODUCTION_Z",

    color="Name",
    line_dash="group",

    animation_frame="animation_age",

    markers=True,

    hover_name="Name",

    hover_data={
        "SEASON_ID": True,
        "TEAM_ABBREVIATION": True,
        "PLAYER_AGE": True,
        "PPG": ":.1f",
        "RPG": ":.1f",
        "APG": ":.1f",
        "PRODUCTION_Z": ":.2f",
        "TS_PLUS": ":.1f",
        "group": True,
        "animation_age": False
    },

    labels={
        "PLAYER_AGE": "Age",
        "PRODUCTION_Z": "Era-adjusted Production Z",
        "SEASON_ID": "Season",
        "TEAM_ABBREVIATION": "Team",
        "PPG": "PPG",
        "RPG": "RPG",
        "APG": "APG",
        "TS_PLUS": "TS+",
        "group": "Player Type",
        "animation_age": "Age reached"
    },

    title="Future GOAT Race — Career Trajectory vs NBA Legends",

    range_x=[19.5, 30.5],

    range_y=[
        career_trajectory["PRODUCTION_Z"].min() - 0.5,
        career_trajectory["PRODUCTION_Z"].max() + 0.5
    ]
)

fig_trajectory.update_traces(
    line=dict(width=3),
    marker=dict(size=9)
)

fig_trajectory.update_layout(
    height=720,

    xaxis=dict(
        dtick=1
    ),

    legend_title_text="Player",

    hovermode="closest"
)

fig_trajectory.show()

In [534]:
final_frame = career_animation[
    career_animation["animation_age"] == 30
]

display(
    final_frame
    .groupby(["group", "Name"])
    .agg(
        first_age=("PLAYER_AGE", "min"),
        current_age=("PLAYER_AGE", "max"),
        observations=("SEASON_ID", "nunique"),
        latest_production_z=("PRODUCTION_Z", "last")
    )
    .round(2)
)

                                               first_age  current_age  \
group                 Name
Future GOAT Candidate Anthony Edwards               20.0         22.0
                      Jayson Tatum                  20.0         26.0
                      Luka Dončić                   20.0         25.0
                      Shai Gilgeous-Alexander       20.0         25.0
                      Tyrese Haliburton             21.0         24.0
                      Victor Wembanyama             20.0         20.0
Historical GOAT       Kareem Abdul-Jabbar           23.0         30.0
                      Larry Bird                    23.0         30.0
                      LeBron James                  20.0         30.0
                      Magic Johnson                 20.0         30.0
                      Michael Jordan                22.0         30.0

                                               observations  \
group                 Name
Future GOAT Candidate Anthony Edwards                     3
                      Jayson Tatum                        7
                      Luka Dončić                         6
                      Shai Gilgeous-Alexander             6
                      Tyrese Haliburton                   4
                      Victor Wembanyama                   1
Historical GOAT       Kareem Abdul-Jabbar                 8
                      Larry Bird                          8
                      LeBron James                       11
                      Magic Johnson                      11
                      Michael Jordan                      8

                                               latest_production_z
group                 Name
Future GOAT Candidate Anthony Edwards                         1.58
                      Jayson Tatum                            1.93
                      Luka Dončić                             3.25
                      Shai Gilgeous-Alexander                 2.00
                      Tyrese Haliburton                       1.94
                      Victor Wembanyama                       1.76
Historical GOAT       Kareem Abdul-Jabbar                     2.29
                      Larry Bird                              2.39
                      LeBron James                            2.40
                      Magic Johnson                           2.29
                      Michael Jordan                          2.27

In [535]:
career_animation["player_type"] = career_animation["group"].map({
    "Historical GOAT": "NBA Legend",
    "Future GOAT Candidate": "Future GOAT Candidate"
})

In [536]:
import plotly.express as px

fig_final = px.line(
    career_animation,

    x="PLAYER_AGE",
    y="PRODUCTION_Z",

    color="Name",
    line_dash="player_type",

    animation_frame="animation_age",

    markers=True,

    hover_name="Name",

    hover_data={
        "SEASON_ID": True,
        "TEAM_ABBREVIATION": True,
        "PLAYER_AGE": True,
        "PPG": ":.1f",
        "RPG": ":.1f",
        "APG": ":.1f",
        "TS_PLUS": ":.1f",
        "PRODUCTION_Z": ":.2f",
        "player_type": True,
        "animation_age": False
    },

    title=(
        "<b>FUTURE GOAT RACE</b>"
        "<br>"
        "<sup>"
        "How today's stars compare with NBA legends "
        "at the same age"
        "</sup>"
    ),

    labels={
        "PLAYER_AGE": "Age",
        "PRODUCTION_Z": "Era-Adjusted Production (Z-Score)",
        "SEASON_ID": "Season",
        "TEAM_ABBREVIATION": "Team",
        "PPG": "Points / Game",
        "RPG": "Rebounds / Game",
        "APG": "Assists / Game",
        "TS_PLUS": "TS+",
        "player_type": "Profile",
        "animation_age": "Age reached"
    },

    range_x=[19.5, 30.5],

    range_y=[
        career_trajectory["PRODUCTION_Z"].min() - 0.4,
        career_trajectory["PRODUCTION_Z"].max() + 0.5
    ]
)

fig_final.update_traces(
    line=dict(width=3),
    marker=dict(size=9)
)

fig_final.update_layout(
    height=760,

    title=dict(
        x=0.03,
        xanchor="left",
        font=dict(size=25)
    ),

    xaxis=dict(
        dtick=1,
        title="PLAYER AGE"
    ),

    yaxis=dict(
        title="ERA-ADJUSTED PRODUCTION"
    ),

    legend=dict(
        title="PLAYER",
        orientation="v",
        x=1.02,
        y=1
    ),

    margin=dict(
        l=80,
        r=230,
        t=110,
        b=80
    ),

    hovermode="closest"
)

fig_final.show()

In [537]:
age_compare = 25

comparison_25 = (
    career_trajectory[
        career_trajectory["PLAYER_AGE"] == age_compare
    ][
        [
            "Name",
            "group",
            "SEASON_ID",
            "PPG",
            "RPG",
            "APG",
            "PRODUCTION_Z",
            "TS_PLUS"
        ]
    ]
    .sort_values(
        "PRODUCTION_Z",
        ascending=False
    )
)

display(comparison_25.round(2))

,Name,group,SEASON_ID,PPG,RPG,APG,PRODUCTION_Z,TS_PLUS
40,Luka Dončić,Future GOAT Candidate,2023-24,33.86,9.24,9.80,3.25,108.68
44,LeBron James,Historical GOAT,2009-10,29.71,7.29,8.57,2.89,113.80
42,Kareem Abdul-Jabbar,Historical GOAT,1971-72,34.84,16.62,4.57,2.64,124.77
46,Michael Jordan,Historical GOAT,1987-88,34.98,5.48,5.91,2.23,115.33
43,Larry Bird,Historical GOAT,1981-82,22.87,10.87,5.81,2.18,106.14
45,Magic Johnson,Historical GOAT,1984-85,18.26,6.18,12.57,2.15,120.44
39,Jayson Tatum,Future GOAT Candidate,2022-23,30.07,8.77,4.62,2.13,105.80
41,Shai Gilgeous-Alexander,Future GOAT Candidate,2023-24,30.05,5.53,6.20,2.00,111.93

In [538]:
premium_html = "/content/future-goat-trajectory-premium.html"

fig_final.write_html(
    premium_html,
    include_plotlyjs="cdn",
    full_html=True,
    config={
        "displayModeBar": False,
        "responsive": True
    }
)

print("HTML créé :", premium_html)

print(
    "Taille :",
    round(
        os.path.getsize(premium_html) / 1024,
        2
    ),
    "KB"
)

HTML créé : /content/future-goat-trajectory-premium.html
Taille : 180.5 KB

In [539]:
import os

premium_html = "/content/future-goat-trajectory-premium.html"

fig_final.write_html(
    premium_html,
    include_plotlyjs="cdn",
    full_html=True,
    config={
        "displayModeBar": False,
        "responsive": True
    }
)

print(
    "future-goat-trajectory-premium.html →",
    os.path.exists(premium_html)
)

print(
    "Taille :",
    round(os.path.getsize(premium_html) / 1024, 2),
    "KB"
)

print("Chemin :", premium_html)

future-goat-trajectory-premium.html → True
Taille : 180.5 KB
Chemin : /content/future-goat-trajectory-premium.html

In [540]:
from google.colab import files

files.download(
    "/content/future-goat-trajectory-premium.html"
)

In [541]:
import os
import glob

csv_files = sorted(glob.glob("/content/*.csv"))

for file in csv_files:
    print(
        os.path.basename(file),
        "→",
        round(os.path.getsize(file) / 1024, 2),
        "KB"
    )

01_team_season.csv → 229.31 KB
02_winning_factors.csv → 1.64 KB
03_goat_master.csv → 0.75 KB
04_goat_dimensions.csv → 0.53 KB
05_goat_scenarios.csv → 0.25 KB
06_goat_peak.csv → 0.45 KB
07_goat_player_seasons.csv → 18.88 KB
08_methodology.csv → 0.85 KB
09_future_goat.csv → 40.08 KB
10_future_goat_similarity.csv → 70.06 KB
nba_team_performance_animation_data.csv → 1.38 KB

In [542]:
import os
import zipfile

files_to_export = [
    "01_team_season.csv",
    "02_winning_factors.csv",
    "03_goat_master.csv",
    "04_goat_dimensions.csv",
    "05_goat_scenarios.csv",
    "06_goat_peak.csv",
    "07_goat_player_seasons.csv",
    "08_methodology.csv",
    "09_future_goat.csv",
    "10_future_goat_similarity.csv"
]

zip_path = "/content/nba-winning-formula-data.zip"

with zipfile.ZipFile(zip_path, "w") as zipf:
    for filename in files_to_export:
        path = f"/content/{filename}"

        if os.path.exists(path):
            zipf.write(path, arcname=filename)
            print("✓", filename)
        else:
            print("✗ MANQUANT :", filename)

print("\nZIP créé :", zip_path)

✓ 01_team_season.csv
✓ 02_winning_factors.csv
✓ 03_goat_master.csv
✓ 04_goat_dimensions.csv
✓ 05_goat_scenarios.csv
✓ 06_goat_peak.csv
✓ 07_goat_player_seasons.csv
✓ 08_methodology.csv
✓ 09_future_goat.csv
✓ 10_future_goat_similarity.csv

ZIP créé : /content/nba-winning-formula-data.zip

In [543]:
from google.colab import files

files.download("/content/nba-winning-formula-data.zip")